### ISSUE TITLE
Loading content from multiple root directory trees

### ISSUE THREAD

**Issue by kmjbyrne** [nuxt/content#1004]
I have somewhat (possibly) bizarre use case that lends itself to the same feature set as `components` where I may have `content` folders in a `modules` folder or a package installed in node_modules. 

With `components` you simply define a `nuxt.js` instruction function like:

```
import { join } from 'path';

export default function () {
    const { nuxt } = this;

    // Make sure components is enabled
    if (!nuxt.options.components) {
        throw new Error('please set `components: true` inside `nuxt.config` and ensure using `nuxt >= 2.13.0`');
    }

    this.nuxt.hook('components:dirs', (dirs) => {
        dirs.push({
            path: join(__dirname, './components'),
            prefix: 'Access',
        });
    });
}
```

Having read through some of the existing questions I think people have encountered the need for a similar use case but more leaning towards fetching .md files over APIs. 

For example: 

https://github.com/nuxt/content/issues/872
https://github.com/nuxt/content/issues/265

But in my use case (for now) the files are local, just not in the same relative directory tree to the nuxt.config.js srcDir.

If I maintain a separate repo with its own content that may be contributed to as part of a smaller suite of docs. Git sub module approach is OK but it is a crutch to something that is a pretty reasonable feature.

I have tried:

A) clone $content and tried to jury rig this object, overwriting the `dir` property but I am afraid I am fundamentally blocked here. Will need more time to explore how Nuxt binds `content: {}` from nuxt.config.js and figure out how to replicate the same options. Effectively trying to rebuild the entire $content object and reconfigure for a unique path. Then assign this to a temporary $_content. Some magic awful logic can take care of figuring out which to use based on options to that specific module.

B) create a module that copies the module's own ./content directory to the srcDir content path. Something like:

module/index.js

```js
import path from 'path';
import fse from 'fs-extra';
import { sortRoutes } from '@nuxt/utils';

export default async function DocsModule(moduleOptions) {
    // load up routes, since the module can have its own mechanism for display the content (isolated dev server for example or specific pages to provide to owner app
    this.extendRoutes((routes) => {
        routes.push({
            // module specific pages for rendering module's own content style, layout etc...
        });
        sortRoutes(routes);
    });
    
    // load up the components for this module
    this.nuxt.hook('components:dirs', (dirs) => {
        dirs.push({
            path: path.join(__dirname, 'components'),
        });
    });

    fse.copy(path.resolve(__dirname, 'src/content'), path.resolve(moduleOptions.srcDir, 'content'));
}
```

nuxt.config.js (in core Nuxt app)

```js
const srcDir = 'src';

module.exports = {
    srcDir,
    // ...
    buildModules: [
        '@some-docs-module', { srcDir }],
    ],
};
```

This works as a hacky workaround for me for now but I would love to be able to see something like:

nuxt.config.js

```js
module.exports = {
    // ...
    content: {
        paths: ['~/content', '@some-docs-module'],
    },
};
```

One could .gitignore a specific path that was copied to prevent accidental VC but I am sure I am missing some fundamental understanding of Nuxt modules / contexts that could be better put to use.

Is it possible to do the same with nuxt/content?

**Comment by Tahul** [comment]
Hello!

This is now a feature of @nuxt/content v2, via the following configuration:

```ts
export default defineNuxtConfig({
  content: {
    sources: [
      'content'
      {
        name: '@some-docs-module',
        prefix: '/some-docs-module', // All contents inside this source will be prefixed with `/fa`
        driver: 'fs',
        driverOptions: {
          base: resolve(__dirname, './node_modules/@some-docs-module/docs') // Absolute path for source directory
        }
      }
    ]
  }
})
```

I am closing this as we are moving priority support to @nuxt/content v2 and this is supported there!

Feel free to re-open with an PR targeted at `v1` branch if you want this to be fixed in v1.
