### ISSUE TITLE
Can @nuxt/content be used without Nuxt?

### ISSUE THREAD

**Issue by mbrain-io** [nuxt/content#1015]
Hi guys, awesome project! I would like to use it in many projects, even the ones that are not Nuxt, can that be done? Tnx

**Comment by NozomuIkuta** [comment]
No, you can't.
Nuxt Content is a Nuxt module, which is supposed to be used within Nuxt application.

If you do want to achieve the same features, you have to find another solution or dig into Nuxt Content's code, especially parts of parsing files and storing them into [LokiJS](https://github.com/techfort/LokiJS) to extract them.

**Comment by mbrain-io** [comment]
@NozomuIkuta  Got it tnx! No plans on making it more universal maybe?

**Comment by NozomuIkuta** [comment]
@mbrain-io 

There is no such plan as far as I know.

You might want to ask in Discord of the community, whose link is in the official site.
