### ISSUE TITLE
Add a table of contents - The problem of toc links with other languages

### ISSUE THREAD

**Issue by faresdjefaflia** [nuxt/content#1019]
welcome

I read an article about creating a blog and tried to apply it.
But I faced a problem, I am creating a blog for her content in Arabic.

Everything was fine but when I got to this part of the article I discovered that it does not work properly with Arabic letters.

Part: https://nuxtjs.org/tutorials/creating-blog-with-nuxt-content#add-a-table-of-contents

I tried to apply it and indeed the links were created automatically and all the sections of the article were shown, but the problem is that the links are encrypted or different, and when I click on the link, it does not take me to the desired part within the article

**Comment by NozomuIkuta** [comment]
@faresdjefaflia 

It seems to be same as or related to #867.
It's also worth checking #835, which is about a URL encoding bug.
