### ISSUE TITLE
How to clean integrate latex equation inside markdown files ?

### ISSUE THREAD

**Issue by mathieunicolas** [nuxt/content#102]
Hello !

I'm not quite used to the nuxt/content module, and I've never integrated latex in nuxt before, so I prefer asking you !
I'd like to write latex equations un mardown files, fetch the files thanks to the nuxt/content module, and display each articles with their equations.
At the end, I'd like to `nuxt generate` and serve the website with netlify.

I tried integrating through npm, and by including mathjax script in the `nuxt.config.js` head, but none of this worked, and I'd like to know the "best practice" to make a clean website.

Thanks !

edit : I forgot to say, I checked the remark plugin `remark-html-katex` and I thought installing it with `npm` and adding it to the markdown.plugins section of `nuxt.config.js` would have been a success, but it seems nothing happens when I write an equation in a markdown file.

**Comment by Atinux** [comment]
Similar to #45 and will be resolved with https://github.com/nuxt/content/pull/65

**Comment by benjamincanac** [comment]
Hey @mathieunicolas,

First of all, to make a clean website, I'd start by using [create-nuxt-app](https://github.com/nuxt/create-nuxt-app):

```bash
npx create-nuxt-app my-project
```

Then add the `content` module:

```bash
yarn add @nuxt/content
```

and register it inside `nuxt.config.js`:

```js
export default {
  modules: [
    '@nuxt/content'
  ]
}
```

Then to support math equations you will need to use [remark-math and rehype-katex](https://github.com/remarkjs/remark-math) (`yarn add remark-math rehype-katex`).

However, a PR is actually ongoing to extend rehype plugins in the content module, so until it's merged and released you can set the @nuxt/content dependency to the PR inside your `package.json`:

```json
"dependencies": {
  "@nuxt/content": "nuxt/content#feat\/rehype-plugins"
}
```
 
Then in your `nuxt.config.js`, you can register the two plugins:

```js
export default {
  content: {
    markdown: {
      remarkPlugins: [
        'remark-math'
      ],
      rehypePlugins: [
        'rehype-katex'
      ]
    }
  }
}
```

At this point it should be working, you can then write a markdown file with LaTex inside the `content` folder and fetch it in your pages:

```vue
<template>
  <nuxt-content :document="document" />
</template>

<script>
export default {
  async asyncData ({ $content }) {
    const document = await $content('math').fetch()

    return {
      document
    }
  }
}
</script>
```

I've made you an example here: https://github.com/benjamincanac/nuxt-content-latex

**Comment by mathieunicolas** [comment]
Thank you very much !! It works like a charm.
Example repo much appreciated !

**Comment by NebelNidas** [comment]
@benjamincanac I can't get your example to run anymore, any updates on how to accomplish this as of now?

**Comment by saumyasinghal747** [comment]
How can I specify options for the Katex? For example, I'd like it to output HTML instead of MathML as Chrome no longer supports it.
https://katex.org/docs/next/options.html
Thank you!

**Comment by anthonyarusso** [comment]
@saumyasinghal747 A bit late but I figured out how to pass in Katex options. As per [Rehype Documentation](https://github.com/unifiedjs/unified-engine/blob/HEAD/doc/configure.md#plugins) you can specify plugin options in your configuration file (`nuxt.config.js`) by passing a "plugin–options tuple". In my case this looks like:
```javascript
content: {
    markdown: {
      prism: {
        theme: 'prism-themes/prism-coldark-dark.css'
      },
      remarkPlugins: [
        'remark-math'
      ],
      rehypePlugins: [
	      ['rehype-katex', { output: 'html' }]
      ]
    }
  },
```
Just be sure to not forget the stylesheet line in your head.link object! `{ rel: 'stylesheet', href: 'https://cdn.jsdelivr.net/npm/katex@0.11.0/dist/katex.min.css' }`. Let me know if this helps.
