### ISSUE TITLE
Excerpt does not work

### ISSUE THREAD

**Issue by Atinux** [nuxt/content#1035]
### Version
@nuxt/content: v2
nuxt: v3

### Steps to reproduce

Add `<!--more-->` into a markdown file in `playground/` and run `yarn dev`

### What is Expected?

To work and add a `excerpt` key in the document.

### What is actually happening?

![Screenshot 2022-05-06 at 18.37.36@2x.png](https://volta.s3.fr-par.scw.cloud/Screenshot_2022_05_06_at_18_37_36_2x_b1de2b8e02.png)

### Note

How would we use the excerpt in Markdown, shall we have an option for the `<Content/>` component?

**Comment by Tahul** [comment]
As a reference @farnabaz : https://content.nuxtjs.org/writing#excerpt
