### ISSUE TITLE
Parser plugin interface

### ISSUE THREAD

**Issue by jbnv** [nuxt/content#104]
### Is your feature request related to a problem? Please describe.

A few days ago I submitted a request (#67) for a parser for .txt files. I've also been pondering a parser for SVG files to solve a problem with avatars. 

Today I started studying the [parser code](https://github.com/nuxt/content/tree/master/lib/parsers). I see that the CSV and YAML parsers are both very simple: a class definition with a `toJSON` method, with modules handling the heavy work. 

### Describe the solution you'd like

A configuration point in `nuxt.config.js` for custom parsers. It could be as simple as an array of patterns and resolution functions:
```
[
    {
        'pattern': /^\.txt$/,
        'parse': function (file) {
            return file.split('\n');
        }
    }
]
```

### Describe alternatives you've considered

I don't know that there is any real alternative to this at this point. I've searched both the documentation and the code for information about custom parsers and haven't found any information.

**Comment by mathe42** [comment]
@jbnv Created a PR: #256 with option to add custom parsers.
