### ISSUE TITLE
How do we configure markdown plugins?

### ISSUE THREAD

**Issue by davestewart** [nuxt/content#105]
How does one configure markdown plugins?

I want to tweak the behaviour of the autolink-headings plugin, but could not see how to do that in the docs.

**Comment by benjamincanac** [comment]
Hey @davestewart,

You can configure remark plugins using its name in camelCase, so for `remark-autolink-headings`:

```js
{
  content: {
    markdown: {
      autolinkHeadings: {
        // https://github.com/remarkjs/remark-autolink-headings#options
      }
    }
  }
}
```

Here is the link to the [documentation](https://content.nuxtjs.org/configuration#markdown).

**Comment by davestewart** [comment]
Thanks for the speedy help!

That's really ticked away! I'd recommend making that WAY more obvious, perhaps its own section:

![image](https://user-images.githubusercontent.com/132681/83884590-fea00e00-a73c-11ea-95b6-7cc738e47929.png)

**Comment by benjamincanac** [comment]
@davestewart A PR is actually ongoing that will support rehype plugins and change how to configure them. Stay tuned!
