### ISSUE TITLE
V2: Add new query `SortByNatural`

### ISSUE THREAD

**Issue by ManasMadrecha** [nuxt/content#1074]
### Is your feature request related to a problem? Please describe
Currently (even in V1), we can only fetch and sort using normal `SortBy`, but it sorts files like this... 1-name, 10-name, 2-name, 3-name, etc. 

### Describe the solution you'd like
1. To be able to sort the files naturally like this... 1-name, 2-name, 3-name, 10-name
2. So, in addition to the `SortBy` option, kindly add one more option of `SortByNatural` using `Intl.collator`
    https://github.com/nuxt/content/blob/1968257881db58634bdf4448bd85d7b059f88e4c/src/runtime/query/query.ts#L35

This way we can directly naturally sort while fetching itself and then properly use `limit`, etc. options. 

### Describe alternatives you've considered
Fetch thousands of posts without any sort, and then use `Intl.collator` to sort them, and then filter out only first n posts. But it's not performant if there are so many posts. 

### Additional context
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator

**Comment by Atinux** [comment]
Seems like a good solution to order by default, what do you think @farnabaz ?

**Comment by farnabaz** [comment]
Indeed, natural order should be default order.

**Comment by farnabaz** [comment]
Instead of having `sortByNatural` I'm proposing a change in `sortBy` and create mongo like sorting util which is more powerful and fix multiple issues in sorting, like case insensitive sorting, or natural sorting.

```ts
queryContent().sort({
  title: 1, // title ascending
  description: 0, // descending
  $numeric: 1, // natural sort
  $sensitivity: 'case' // define case sensitivity
})
```

**Comment by ManasMadrecha** [comment]
@farnabaz Yes, this seems intuitive to understand as well.

**Comment by Atinux** [comment]
Looks good to me @farnabaz
