### ISSUE TITLE
<QueryContent> component

### ISSUE THREAD

**Issue by clemcode** [nuxt/content#1081]
### Describe the solution you'd like
The `queryContent()` composable provides a way to make programmatic queries in the `content/` directory. The `<QueryContent>` component could act as a wrapper around the composable and accept props to create the queryBuilder and render the content.

### Usage

```vue
<template>
  <QueryContent path="articles" :only="['title']" :where="{author: 'Ada Lovelace'}" />
</template>
```

### Minus
The potential downside would be having to maintain both the composable and the component in case of API changes.

**Comment by Atinux** [comment]
What about calling it `ContentQuery` instead?

**Comment by clemcode** [comment]
That would be even simpler to use. Don't you worry it would prevent `useAsyncData()` and `queryContent()` to be tree-shaken from any Content project though? (I might be wrong or maybe the cost is negligible)

**Comment by Tahul** [comment]
Since latest changes `<Content />` ships `useAsyncData` and `queryContent` anyways.

**Comment by clemcode** [comment]
Would it be better to have:

```vue
<template>
  <Content path="articles" :only="['title']" :where="{author: 'Ada Lovelace'}" />
</template>
```

or

```vue
<template>
  <Content path="articles" :only="['title']" :where="{author: 'Ada Lovelace'}" v-slot={ document }>
    <h1>{{ document.title }}</h1>
  </Content>
</template>
```

**Comment by Tahul** [comment]
We can definitely support both. 😄

**Comment by Tahul** [comment]
Closing this as we have implemented it via content components. 😄
