### ISSUE TITLE
Optional content validation

### ISSUE THREAD

**Issue by dtmzr** [nuxt/content#109]
### Is your feature request related to a problem? Please describe.

This is a feature request which could improve the experience of adding or editing content.
Especially in cases when people migrate to this module or have a bulk of data to insert, an additional validation would help to ensure that the content is entered correctly.

### Describe the solution you'd like

I would really like to be able to add something like a `validate.js` into my content directory and each file in the same directory would be validated with the configuration I provided there.

```js
// content/posts/validate.js
import { validateOrReject, Contains, Length } from "class-validator";

class Post {
    @Length(10, 20)
    title: string;

    @Contains("hello")
    text: string;
}

export default (fileContent) => {
  const post = new Post(fileContent);
  return validateOrReject(post);
}
```

If the validation fails, a warning or error should be thrown.

I think it would be pretty cool if people could opt-in their favorite validator for this.
In this case, a hook or external module might be enough to provide this experience without bloating this module itself?

### Describe alternatives you've considered

For cases like static page generation, strict component API's could solve this problem too. Although I assume this could get really fast really messy.

### Additional context

I would be really happy to help to provide this feature or module - due to my missing knowledge about the implementation of nuxt and nuxt-content, some hints would be really appreciated :pray:

**Comment by benjamincanac** [comment]
Hey @dtmzr,

I think this feature is a bit too specific to be implemented in the core on the content module.

However you could call your validation inside the `content:file:beforeInsert` hook.

You could even create a `nuxt-content-validation` module that reads a `validate.js` file and registers the hook to call the validate method with the document.

**Comment by dtmzr** [comment]
@benjamincanac thanks for your response and pointing out some paths! 🙏 

I'll try to fiddle around with this on the weekend.
