### ISSUE TITLE
'About' page from fresh project does not render

### ISSUE THREAD

**Issue by christophermiles** [nuxt/content#1113]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.0.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/content@2.0.0-27554036.302ad9b`

### Reproduction

As per the instructions on the Content v2 'Get started':

```
npx nuxi init content-app -t content-v2

cd content-app

yarn install

yarn dev
```

### Describe the bug

The content for the `index.md` is displayed at `localhost:3000`

<img width="571" alt="Screen Shot 2022-05-23 at 3 54 46 pm" src="https://user-images.githubusercontent.com/1767439/169752715-2be49976-4599-4578-be9a-0ede014b20e1.png">

Clicking `/about` loads a blank screen and the following console warning:

```
[Warning] [Vue warn]: Component inside <Transition> renders non-element root node that cannot be animated. (38) (vue.js, line 1266)
"
"
" at <Anonymous"
"path=\"/\""
"find=\"one\""
">"
"
"
" at <Anonymous>"
"
"
" at <[...slug]"
"onVnodeUnmounted=fn<onVnodeUnmounted>"
"ref=Ref<"
undefined
">"
"key=\"/\""
">"
"
"
" at <BaseTransition"
"mode=\"out-in\""
"appear=false"
"persisted=false"
" ..."
">"
"
"
" at <Transition"
"name=\"page\""
"mode=\"out-in\""
">"
"
"
" at <RouterView"
">"
"
"
" at <NuxtPage>"
"
"
" at <App"
"key=1"
">"
"
"
" at <NuxtRoot>"
```

instead of the content of the `about.md` file.

Using the 'Back' button in the browser returns to `localhost:3000` but the the screen remains blank.

---

I am also very confused about which version of the Content module I am supposed to be using if I want to use Nuxt 3.

**Comment by Atinux** [comment]
Hi @christophermiles 

You can wrap the `<ContentDoc>` with a `<div>` to remove the warning, see my fix on https://github.com/nuxt/starter/commit/8b30d317f167a28d90e5af3ef0d434a39c1f6640

> I am also very confused about which version of the Content module I am supposed to be using if I want to use Nuxt 3.

You need to use @nuxt/content version 2 but it is not public yet, it is planned for tomorrow (24th May).
