### ISSUE TITLE
API for a array of objects, unclear documentation on API

### ISSUE THREAD

**Issue by fayazara** [nuxt/content#112]
I have a array objects like this 
```
[
    {
      "id": 1,
      "name": "Abc Def",
      "semester": 1,
      "fees": "Paid"
    },
    {
      "id": 2,
      "name": "Qwe Rty",
      "semester": 3,
      "fees": "Pending"
    },
    {
      "id": 3,
      "name": "Qwe Rty",
      "semester": 3,
      "fees": "Pending"
    }
  ]
```

When I try to use it as a api, it auto converts it to a object and adds a key to each object. How do I even read this? 

My students.json array is converted to a object with keys(numbers increamented).

![response](https://user-images.githubusercontent.com/15716057/83950639-eff34d00-a849-11ea-96f5-3aec2939a20c.png)

What do I do to get the array instead of a object, how do I access a specific object say `student 2 or object 2` from my array. 

How do I query this data, like `only` or `where` and `sortBy`, is it also possible to paginate the data (my array of students, eventually it will be crossing 200 students with each object containing more details)

I tried adding querying with `only` like this `http://localhost:3000/api/students?only=title` it responds with empty object
![image](https://user-images.githubusercontent.com/15716057/83951156-2b434b00-a84d-11ea-92c0-922671ad3cda.png)

I might be trying to use it the wrong way, but this would solve me a lot of problems, like instead of using a Headless CMS via its api, everything will be handled locally

**Comment by dtmzr** [comment]
Hey there 👋 

Do you have a specific reason to not store your students inside another directory?
Like `/content/students/1.json`, `/content/students/2.json` and so on and so forth.

The `students` directory would then represent something like a collection and each json file a document. From your question, I would assume that's what you want.

Here's a very well example - maybe this could help you :) 
https://github.com/nuxt/content/tree/master/example

**Comment by fayazara** [comment]
This collection was exported from a MongoDB and in stores everything in a array and not as seperate files.

Having an array is easier, imagine having to add a new field to our existing collections and you try doing it programmatically with node, can be done quickly, or say you want to import it back to mongodb, or convert your data to a csv.

**Comment by dtmzr** [comment]
I guess getting the array back won't work as you might expect it, the docs say:
`path can be a file or a directory. If path is a file, fetch() will return an Object, if it's a directory it will return an Array.`

What you might work for you, is to add a top-level property in the `json` file, then you'll have a nested array which you could iterate over.
```json
{
  "allstudents": [{
    "id": 1,
    "name": "Abc Def",
    "semester": 1,
    "fees": "Paid"
  }]
}
```

So you would at least have your data easily iterable. You might be able to access a single student object by fetching like this:
```js
const firstStudent = await this.$content('students').select('allstudents[0]').fetch()
```
(I don't know if this actually works but will try out and give you some feedback. :) 

Sadly I assume you won't be able to use `limit()` and `skip()` with this data structure, these could've taken the heavy lifting for integrating pagination for you. Thus, for pagination you might have to pull the whole object with all students, in this case, pagination would be senseless I guess?

**Comment by fayazara** [comment]
That wont work, importing the file locally would be better than what you suggested, but I will miss out on all the features of the module.

**Comment by fayazara** [comment]
I guess I'll have to break it down into files using something like jq

**Comment by mathieunicolas** [comment]
Hello there ! 
I don't know if it can help, but I've had the same issue few months ago with firebase requests returning objects instead of json. I can't verifiy the code right now, but here's how you could do :

```
module.exports = (data) => {
  let keys = Object.keys(data).filter(key => typeof(key) === 'number')
  let arr = []

  keys.forEach((key) => {
    array.push(data[key])
  })

  return array
}
```

**Comment by dtmzr** [comment]
Hi @mathieunicolas this would work but would mean that you'll always have to pull the whole data set of all students.

In addition to you code, someone would have to filter out these properties which this module adds to each file by default `dir`, `path`, `slug`, `extension`, `createdAt` and `update`.

**Comment by dtmzr** [comment]
@mathieunicolas yep, this could work but may need a few tweaks since this module adds some additional fields by default. :)

**Comment by mathieunicolas** [comment]
> @mathieunicolas yep, this could work but may need a few tweaks since this module adds some additional fields by default. :)

The filter does that, doesn’t it ?

**Comment by dtmzr** [comment]
@mathieunicolas  sorry my fault, I missed the truthy check for `data[key].id` in your second example. :)

**Comment by monsieurnebo** [comment]
I'm encountering the same issue with multiple "mono JSON files" containing an array of objects.

Create one file per entry is not always the right solution. In my case, that's a lot of small objects and it would be way overkill to split them into distinct files.

It would be great to support this type of files in `nuxt/content` in order to use its great features such as queries.
