### ISSUE TITLE
Content v2, preserving white space with `flatUnwrap`

### ISSUE THREAD

**Issue by Laurensvdmaas** [nuxt/content#1126]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.2.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.9.0`
- Builder:          `vite`
- User Config:      `components`, `runtimeConfig`, `vue`, `app`, `css`, `vite`, `modules`, `algolia`
- Runtime Modules:  `@pinia/nuxt@0.1.9`, `@nuxtjs/tailwindcss@5.0.4`, `@nuxtjs/algolia@0.9.2`, `@nuxt/content-edge@2.0.0-27554973.ff1492e`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-wpxzjy?file=content/index.md

### Describe the bug

I'm trying to create a code editor and i would like to preserve the whitespace in the slot content, whenever i `flatUnwrap` the slot it seems to remove the whitespace.

**Comment by Laurensvdmaas** [comment]
I see, thanks for your answer! My code-block component takes some extra props like a heading etc. I guess the only way around this is to write a wrapper component?

**Comment by farnabaz** [comment]
Yes you can create a wrapper component and wrap code inside it.

**Comment by Laurensvdmaas** [comment]
Thank you!
