### ISSUE TITLE
Invalidate cache when changing Shiki theme

### ISSUE THREAD

**Issue by Atinux** [nuxt/content#1128]
See the video that explain better:

https://user-images.githubusercontent.com/904724/170025630-689c1c15-2d4f-44b5-a406-2eb41d521a25.mp4

I think we could use the cache key to also add the current highlight config (and maybe parsers), WDYT @farnabaz ?

**Comment by farnabaz** [comment]
I agree, we should generate a cache key based on markdown options, highlight options and locales
