### ISSUE TITLE
markdown files queries broken on Windows

### ISSUE THREAD

**Issue by prazdevs** [nuxt/content#1137]
### Environment

```
- Operating System: `Windows_NT` OR `Darwin`
- Node Version:     `v18.2.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `pnpm@7.1.0`
- Builder:          `vite`
- User Config:      `modules`, `css`, `experimental`, `unocss`, `colorMode`
- Runtime Modules:  `@nuxt/content@2.0.0`, `@nuxtjs/color-mode@3.0.3`, `@unocss/nuxt@0.34.1`, `@vueuse/nuxt@8.5.0`
- Build Modules:    `-`
```

### Reproduction

https://github.com/prazdevs/praz-nuxt

### Describe the bug

While querying for `content/posts` as in `pages/posts/index.vue`, everything works fine and displays properly, but on Windows, everything is broken. The frontmatter isnt parsed properly.

Seems like some format/encoding/parsing issue causing my markdowns to be misread or something.

### Additional context

It works perfectly fine under MacOS or when run through Netlify serverless functions.
Not sure if linked, but the <ContentQuery> component is breaking as well when not querying for one (`find="one"`).

After investigating a bit, I found out that the [ `content.startsWith("---\n"`](https://github.com/nuxt/content/blob/main/src/runtime/markdown-parser/frontmatter.ts#L25) doesnt return true when it should on Windows.

**Comment by pavlexander** [comment]
Good find. If you change `End Of Line`  conversion from `Windows` to `Unix` then parsing works as expected:

![image](https://user-images.githubusercontent.com/20644772/170541623-8cdf0116-ba47-402a-aa8f-52064ef35086.png)

This issue should probably be fixed with: https://github.com/nuxt/content/issues/1140
