### ISSUE TITLE
createAt/updateAt is of different types for CSR and SSR

### ISSUE THREAD

**Issue by odanado** [nuxt/content#114]
### Version
@nuxt/content: 1.3.1
nuxt: 2.12.2

### Reproduction Link
https://github.com/odan-sandbox/nuxtjs-content-date-hydration-reproduction

### Steps to reproduce
1. yarn
2. yarn dev
3. open localhost:3000
4. change a mode from `spa` to `universal` in `nuxt.config.js`
4. open localhost:3000

### What is Expected?
I get the same display.

### What is actually happening?
I got a different display.

- When `universal` mode
  - `Sun Jun 07 2020 03:37:06 GMT+0900 (日本標準時) object`
- When `spa` mode
  - `2020-06-06T18:37:06.335Z string`

**Comment by odanado** [comment]
In addition, the same bug occurs for custom properties of date types.
e.g. `publishedAt`
ref: https://github.com/odan-sandbox/nuxtjs-content-date-hydration-reproduction/blob/4b3f99217bc63b4bcacad8b84bf86b1895249a24/pages/index.vue#L11

**Comment by dwfee** [comment]
same here
