### ISSUE TITLE
Issue parsing Front-matter

### ISSUE THREAD

**Issue by mctweb** [nuxt/content#1140]
### Environment

Nuxt CLI v3.0.0-rc.3                                                                                          11:06:16
RootDir: C:\Users\Fraser\Websites\content-wind                                             11:06:17
Nuxt project info:                                                                                            11:06:17

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.11`
- Builder:          `vite`
- User Config:      `modules`, `colorMode`, `content`
- Runtime Modules:  `@nuxt/content@2.0.0-27556335.6403e35`, `@nuxtjs/tailwindcss@5.1.2`, `@nuxtjs/color-mode@3.0.3`
- Build Modules:    `-`

### Reproduction

https://github.com/Atinux/content-wind

### Describe the bug

![issues](https://user-images.githubusercontent.com/25713548/170238163-cec9d0ac-dfe7-4cf6-bba7-4befce79fe24.png)

Front matter is not getting displayed correctly. See image

**Comment by pavlexander** [comment]
Same problem. With both the `<ContentDoc />` and `<ContentRenderer :value="post" />` the front-matter is rendered "as-is" with the rest of the content.

![image](https://user-images.githubusercontent.com/20644772/170443359-5b06d2ac-2ac6-4091-9a0c-9b1c8b64638e.png)

```md
---
title: 'Title of the page'
description: 'meta description of the page'
date: "2015-05-28T22:40:32.169Z"
id: 1
createdAt: "2015-05-28T22:40:32.169Z"
---

# HW1
```

**Comment by ram-you** [comment]
Hi, I'm on Linux and have the same issue even with native parameters. 
Nuxt version:  "^3.0.0-rc.3"
@nuxt/content version:   "^2.0.0"

**Comment by pavlexander** [comment]
just found a temporary workaround if you are interested: https://github.com/nuxt/content/issues/1137#issuecomment-1138821912

working for me on Windows. @ram-you could you test if you have the same problem on Linux as well?

**Comment by ram-you** [comment]
Hi @pavlexander.
Well found.
I changed the End of File Sequence to Unix/LF (on Linux) and it works.
It's really strange.
I wish @Atinux will put a definitive solution for this problem.
Thank you.

**Comment by mctweb** [comment]
That is correct for me as well. It is the End of File Sequence on the markdown files that seems to make a difference. My editor is set up to use LF as standard. The .editorconfig on this repo is also set up as LF.
