### ISSUE TITLE
Auto generated slug property for each document based on file name or title

### ISSUE THREAD

**Issue by NukeJS** [nuxt/content#1153]
It would be nice to have auto generated slugs like we did back in Content V1.

**Comment by farnabaz** [comment]
Content v2 have same auto generated meta for each file.
You can use `_path` which is same as V1 `slug` and generates from file path

**Comment by NukeJS** [comment]
> Content v2 have same auto generated meta for each file. (names are changes though, and auto generated fields prefixed with `_` to prevent from possible conflict with non-generated content meta) You can use `_path` which is same as V1 `slug` and generates from file path

But what if I want to put my content files in let's say `content/blog` and have the blog posts at `pages/[slug].vue`.

**Comment by farnabaz** [comment]
You can use path prefix to search for your contents:

Checkout [ContentList docs](https://content.nuxtjs.org/api/components/content-list)
```vue
<ContentList path="/blog">...</ContentList/>
```

or using composable:

```ts
queryContent('/blog')
```

**Comment by NukeJS** [comment]
> You can use path prefix to search for your contents:
> 
> Checkout [ContentList docs](https://content.nuxtjs.org/api/components/content-list)
> 
> ```
> <ContentList path="/blog">...</ContentList/>
> ```
> 
> or using composable:
> 
> ```ts
> queryContent('/blog')
> ```

But if I do it like that, e.g.

`pages/blog.vue`
```vue
<template>
  <div v-for="post in posts" :key="post._id">
    <NuxtLink :to="post._path">
      {{ post.title }}
    </NuxtLink>
  </div>
</template>

<script setup lang="ts">
const { data: posts } = useAsyncData('blog', () =>
  queryContent('/blog').where({ _draft: false }).find()
);
</script>
```

And my content blog files are located at `content/blog` but I want my posts located at `pages/[slug].vue`, the NuxtLink will still go to `/blog/some-page` instead of having a slug that's just the file name (or title) to go to `/some-page`. This wouldn't work.
