### ISSUE TITLE
Invalid template name: content

### ISSUE THREAD

**Issue by LukaHarambasic** [nuxt/content#1155]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `0.0.0`
- Package Manager:  `unknown`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Execute the following command from [Get started](https://content.nuxtjs.org/get-started):

```
npx nuxi init content-app -t content
```

### Describe the bug

Directly these error message occurs and the execution stops.

```
ERROR  Invalid template name: content
```

**Comment by Atinux** [comment]
Make sure to upgrade nuxi

```
npx nuxi@latest init content-app -t content
```

**Comment by LukaHarambasic** [comment]
Thanks a lot, that was the first step to the solution. The other problem was related to my Mac update, but thanks to the helpful error message from nuxi I stumbled upon this [SO question](https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa).

<img width="495" alt="image" src="https://user-images.githubusercontent.com/22857823/170458789-347f74b1-862a-41cc-a5ee-9407bb9ec909.png">

Solution:
- use latest nuxi version
- install xcode
- tada

Thanks :)
