### ISSUE TITLE
Sort by date doesn't work

### ISSUE THREAD

**Issue by cawa-93** [nuxt/content#1167]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `modules`, `css`, `content`
- Runtime Modules:  `@nuxt/content@2.0.0`
- Build Modules:    `-`
------------------------------

### Reproduction

1. Clone https://github.com/ua-tech-hub/tech-hub.in.ua `feat/articles` branch
2. Start dev server and go to http://localhost:3000/articles

### Describe the bug

Articles should by sorted by date desc. 
https://github.com/ua-tech-hub/tech-hub.in.ua/blob/d91ab2aba44d520ab7f574515bc57286a3757118/pages/articles/index.vue#L12-L15

But actually it doesn't
![зображення](https://user-images.githubusercontent.com/1662812/170841784-b74c02ad-01ba-45de-b8c7-e0fad4f2b301.png)

**Comment by cawa-93** [comment]
Surprisingly, there is no such problem in the production (netlify). This applies either to the development mode or the Windows os. Unfortunately, I can not test the development mode on another OS.

**Comment by iBobik** [comment]
This is also on Nuxt 2, but it is broken also on production build.

**Comment by DRD161** [comment]
I am experiencing a similar issue and can't seem top figure it out.

`
const { data } = await useAsyncData("posts", () => queryContent("posts").sort({ date: -1 }).limit(limit.value).find())
`

<img width="567" alt="Screen Shot 2022-12-17 at 9 45 45 PM" src="https://user-images.githubusercontent.com/29187448/208278881-ca5601b2-2e40-4b79-8b76-ed1e8f451030.png">

**Nuxt version:** 3.0
**Nuxt Content version:** 2.2.2
**Node version:** 14.16.0
**OS:** macOS Monterey 12.6
**Builder:** Vite

**Comment by brunodeangelis** [comment]
I'm having the same issue, using Nuxt 3 and it's also broken on production build.

**Comment by dxphilo** [comment]
Migrated a blog from Nuxt 2 to Nuxt 3 with nuxt-content, unfortunately I am experiencing the same issue.

**Comment by jjaimealeman** [comment]
Same here 👎 Fails to render at all.

```
const { data: blogPostList } = useAsyncData("blogPostList", () => {
  return queryContent("/blog").sort("dates.published").find();
});
```
I tried `sortby` as per the Docs 
https://content.nuxtjs.org/v1/getting-started/fetching/#sortbykey-direction but that throws an error.

![image](https://user-images.githubusercontent.com/1428292/231047493-54e5d550-f464-4e0e-989a-136a20d5f735.png)

```
    "@nuxt/content": "^2.5.2",
    "nuxt": "^3.3.2",
```
```
OS: Linux (EndeavourOS)
yarn: 1.22.19
npm: 8.19.2
nodejs: 16.18.0
```

**Comment by hecktarzuli** [comment]
@jjaimealeman I made this same mistake.  sortBy is only available for $content.  You are using the `queryContent` composable, so you should be using `sort` with an object. https://content.nuxtjs.org/api/composables/query-content#sortoptions
