### ISSUE TITLE
Front-matter doesn't parsed if file use CRLF

### ISSUE THREAD

**Issue by cawa-93** [nuxt/content#1168]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-rc.3-27550969.a4a3cff`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/content@2.0.0-27555126.58f2d50`, `@nuxt/ui@0.1.1-27555426.2ead323`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/trusting-shtern-zboubf?file=/content/index.md
https://codesandbox.io/s/strange-tree-ksgig6?file=/content/index.md

### Describe the bug

If file use `CRLF` as EOL then Front-matter doesn't parsed correctly

**Comment by farnabaz** [comment]
This is fixed in https://github.com/nuxt/content/pull/1161. Try again by upgrading module version in your sandbox.

```
yarn upgrade @nuxt/content
```

Note: changes does not release under `@nuxt/content` package, until release you can use `@nuxt/content-edge`
