### ISSUE TITLE
How to sort an array?

### ISSUE THREAD

**Issue by webcoderkz** [nuxt/content#118]
I have the following code:

```
async fetch() {
  const data: { items: Item[] } = await this.$content('portfolio')
    .only('items')
    .sortBy('order', 'desc')
    .fetch()
  this.items = data.items
},
```

And corresponding JSON file:

```
{
  "items": [
    {
      "name": "John",
      "description": "asd",
      "order": 1
    },
    {
      "name": "Arnold",
      "description": "asd",
      "order": 2
    },
    {
      "name": "Jason",
      "description": "asd",
      "order": 3
    },

  ]
}

```

How can i sort these items by `order` field? Above code has no effect on sorting.

**Comment by benjamincanac** [comment]
Hey @webcoderkz,

To sort an array you can use the `.sort()` JavaScript method, you don't need `$content` for that.

The `.sortBy` method of `$content()` is used to sort the files.

**Comment by webcoderkz** [comment]
@benjamincanac 

There's an example:

![image](https://user-images.githubusercontent.com/5739191/84009428-0ce86700-a995-11ea-95cb-9003b1c41f7a.png)

Looking at this, first thing that comes to mind, is that articles is an articles.json file, which contains an array of articles, then i could sort them by a title. What do you mean by "sort the files"?

Also if i `sort()` on the client, wouldn't it give inconsistent DOM state, because on the backend site it would have a different order?

**Comment by benjamincanac** [comment]
@webcoderkz You can't put an array in a json file, however you could put a key inside this json which will contain an array.

You can check #62, it's the same question but with CSV.

You won't have any problem with inconsistent state, arrays will be in the same order on both sides.

**Comment by webcoderkz** [comment]
@benjamincanac it's obvious, that i can't put an array inside json, i meant a key which contains an array of course.

I guess i just misunderstood from content documentation sort's purpose. You meant to use markdown files, like:

- articles
-- article 1
-- article 2
-- article 3

every article has frontmatter fields, then i can use `sortBy()` on these fields, am i correct?
