### ISSUE TITLE
Render function with markdown children: TypeError: Cannot read properties of null (reading 'namespaceURI')

### ISSUE THREAD

**Issue by Laurensvdmaas** [nuxt/content#1184]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.2.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.9.0`
- Builder:          `vite`
- User Config:      `components`, `runtimeConfig`, `vue`, `app`, `css`, `vite`, `modules`, `content`, `algolia`
- Runtime Modules:  `@pinia/nuxt@0.1.9`, `@nuxtjs/tailwindcss@5.1.2`, `@nuxtjs/algolia@0.9.2`, `@nuxt/content@2.0.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-mszmvg-6tdtyy?file=components/content/TestSection.vue

### Describe the bug

I'm trying to create a category switcher based on props given to a component (`Test.vue`) inside this component (`TestSection.vue`). So in this section i have a render function that renders a category switcher and based on what is selected in here i show the relevant items.

The problem:
Whenever i switch category and go back to the previous selected category, the slot children get lost and i get the error: `TypeError: Cannot read properties of null (reading 'namespaceURI')`, i tried it with normal slot content and there seems to be no problem, passing the markdown content is where it goes wrong.

**Comment by farnabaz** [comment]
This is not related to content module. You are trying to manipulate virtual DOM and dynamically add/remove some nodes to/from it (the Nodes that was part of vDOM). You definitely should not do that. You can remove nodes from vDOM once but dynamic manipulation is dangerous.

I suggest wrapping you slots in a dummy `<div>` and show/hide based on category, using css (for example with `display: none`)

**Comment by Laurensvdmaas** [comment]
Alright, thanks!
