### ISSUE TITLE
Nuxt3 content v2 with Front matter is not picking up title and description

### ISSUE THREAD

**Issue by zarub2k** [nuxt/content#1187]
### Environment

Nuxt CLI v3.0.0-rc.3                                                                                          23:22:41
RootDir: C:\work\personal\repos\nuxt3content                                                                  23:22:44
Nuxt project info:                                                                                            23:22:44

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v17.4.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.10.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/content@2.0.0`
- Build Modules:    `-`
------------------------------

### Reproduction

The source code is available under https://github.com/zarub2k/nuxt3content

I have stored all the markdown under content/articles and similarly I have a page to render /articles

### Describe the bug

<script setup>
// const { data: articles } = await useAsyncData('articles', () => queryContent('/articles').only(['title', 'description']).find())
const articles = await queryContent('articles').only(['title', 'description']).find()
console.log('here: ' + JSON.stringify(articles))
</script>

<template>
  <section>
    <div>Articles page</div>
    <div>
      <div v-for="article in articles" :key="article._path">
        <h2>{{ article.title }}</h2>
        <p>{{ article.description }}</p>
        
      </div>
    </div>
  </section>
</template>

The title and description is not picking up from the frontmatter syntax. description is always empty and title is always the file name. I have no idea what am I missing here.

Can you help me on this?

**Comment by farnabaz** [comment]
Updating to `content@v2.0.1` should solve the issue

**Comment by zarub2k** [comment]
Thanks for the hint. Now it is working fine after upgrading the content module version
