### ISSUE TITLE
index.md doesn't get loaded when using <ContentDoc> with dynamic routing.

### ISSUE THREAD

**Issue by dankcatlord** [nuxt/content#1189]
### Environment

```
Nuxt CLI v3.0.0-rc.3
RootDir: /home/projects/nuxt-starter-jx8vzt
Nuxt project info:

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/content@2.0.1`
- Build Modules:    `-`
------------------------------
```

### Reproduction

I reproduced the issue in stackblitz.
https://stackblitz.com/edit/nuxt-starter-jx8vzt

### Describe the bug

When using dynamic routing, rather than loading the `index.md` file inside the directory pointed to by `$route.path`, the page loaded is the first one found alphabetically inside the directory pointed to by `$route.path`.

### Additional context

As far as I know, this bug isn't in 2.0.0.

**Comment by Atinux** [comment]
I think we shall for the path to be equal and not starting by when using ContentDoc @farnabaz

**Comment by itshizhan** [comment]
the same questions

**Comment by qin-guan** [comment]
The issue appears to be caused by this PR: https://github.com/nuxt/content/pull/1143

**Comment by qin-guan** [comment]
@Atinux From some rough experimenting, updating 

https://github.com/nuxt/content/blob/main/src/runtime/composables/query.ts#L44
```diff
export function queryContent<T = ParsedContent> (query?: string | QueryBuilderParams, ...pathParts: string[]) {
  if (typeof query === 'string') {
    let path = withLeadingSlash(withoutTrailingSlash(joinURL(query, ...pathParts)))
    // escape regex special chars
-   path = path.replace(/[-[\]{}()*+.,^$\s]/g, '\\$&')
+   path = path.replace(/[-[\]{}()*+.,^$\s/]/g, '\\$&')

-   return createQuery<T>(queryFetch).where({ _path: new RegExp(`^${path}`) })
+   return createQuery<T>(queryFetch).where({ _path: new RegExp(`^${path}$`) })
  }

  return createQuery<T>(queryFetch, query)
}
```

to include `/` in path and `$` in regex query fixes the issue. I am not sure of any unintended side effects this might cause, please advise if the changes are alright 😄 !
