### ISSUE TITLE
Cannot read properties of undefined (reading 'props') - which makes it unable to load from content directory

### ISSUE THREAD

**Issue by tcampbPPU** [nuxt/content#1194]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `meta`, `css`, `components`, `modules`, `runtimeConfig`, `windicss`, `content`
- Runtime Modules:  `@nuxt/content@2.0.1`, `@vueuse/nuxt@8.6.0`, `nuxt-windicss@2.4.1`
- Build Modules:    `-`

### Reproduction

For a link to the repo to reproduce you can visit [https://github.com/tcampbPPU/anma/tree/nuxt-content-2](https://github.com/tcampbPPU/anma/tree/nuxt-content-2)

> **Note**
> Make sure you are on `nuxt-content-2` branch

To install 
1. `yarn install`
2. `yarn dev`

When server is done you can visit `http://localhost:3000/` upon there are 2  `useAsyncData` call to fetch static JSON data, which now no longer works.

### Describe the bug

Unable to fetch content using `useAsyncData`, the content is not found for some reason, and my console is getting the following message
![image](https://user-images.githubusercontent.com/25044744/171448801-ae0aa548-6842-4ec4-9d71-212eef6bfb41.png)

### Logs

```shell
[nuxt] [request error] Cannot read properties of undefined (reading 'props')
  at ./.nuxt/dev/index.mjs:298:33  
  at assertion (./node_modules/unist-util-is/index.js:244:26)  
  at visit (./node_modules/unist-util-visit-parents/index.js:103:24)  
  at visitParents (./node_modules/unist-util-visit-parents/index.js:61:30)  
  at visit (./node_modules/unist-util-visit/index.js:42:7)  
  at ./.nuxt/dev/index.mjs:298:5
```
```

**Comment by harlan-zw** [comment]
Hey @tcampbPPU 

I couldn't access your repo but it looks like this may have been a Windi issue. Seems like you have a node in your markdown graph which is null, which I haven't come across.

I've pushed up version 2.4.2 will solve this if it is in fact the issue

**Comment by tcampbPPU** [comment]
Thanks! It also might of been some node_module issues I retried it later on and was working fine this time.
