### ISSUE TITLE
Truly inline components

### ISSUE THREAD

**Issue by NickSto** [nuxt/content#1195]
### Is your feature request related to a problem? Please describe
I'm evaluating Nuxt for our site, and one feature we'd really like to gain is the ability to insert components inline, in the middle of text. This could be useful for, say, citations, badges, auto-generated text, etc. But I can't tell from the current documentation if this is already possible.

### Describe the solution you'd like
I've tried syntax like this in the [Playground](https://content.nuxtjs.org/playground):
`This is some text :alert{type="success"}: in which I'd like to insert a component`
That was my best guess as I tried to see if the feature already exists. I don't care much what the syntax is, though.

### Describe alternatives you've considered
I guess you could try inserting a component the normal way, then use some kind of CSS to display it as an `inline-block`. But that's pretty kludgy.

### Additional context
Other static site generators which use more traditional template languages are able to do this. For instance, Jekyll's [scholar](https://www.rubydoc.info/gems/jekyll-scholar/0.4.0) plugin gives you a `{% cite %}` tag you can insert into your text. Gridsome's [vue-remark](https://gridsome.org/plugins/@gridsome/vue-remark) plugin even lets you do this with Vue components.

**Comment by NickSto** [comment]
Ohhh cool, that's great news! Then I guess this is a documentation request instead?

**Comment by leipert** [comment]
@harlan-zw There might a related bug. I think inline components should work if they are trailed by non-whitespace characters like the colon (`:`). Filed: https://github.com/nuxt/content/issues/1217
