### ISSUE TITLE
`content.nuxtjs.org/examples/essentials/hello-world` keeps loading about.md as default site. You can't reach index.md...

### ISSUE THREAD

**Issue by DannyEndert** [nuxt/content#1207]
### Reproduction

https://content.nuxtjs.org/examples/essentials/hello-world

### Describe the bug

I was wondering why my `./content/index.md` file is not displayed and went to the Hello World example of Content v2.... the problem exists there too. For some reason the `./content/index.md` is not accessible.

**Comment by WayNian** [comment]
Maybe the first file is displayed in file order

**Comment by Atinux** [comment]
Duplicates of #1189

**Comment by nberlette** [comment]
If I rename the file to `1.index.md` it immediately recognizes the file as the home page...  without the order number, it behaves as if the page simply does not exist.
