### ISSUE TITLE
Non functional buttons in mobile dropdown

### ISSUE THREAD

**Issue by heychazza** [nuxt/content#1209]
There is a bug with the docs where the buttons aren’t functional. I’m assuming this is a bug with Docus? As I believe that’s what the docs use.

![1D5F0D80-A12B-41AA-BD57-59EB5588DB34](https://user-images.githubusercontent.com/47271716/171907374-d7d60646-a748-4f8e-8c4c-27339c098ad1.jpeg)

You cannot click the Twitter or GitHub button.

Related code:
https://github.com/nuxt/content/blob/main/docs/content/_theme.yml#L6-L12

**Comment by farnabaz** [comment]
This is fixed in the latest deployment 🙂
