### ISSUE TITLE
icons dont see 

### ISSUE THREAD

**Issue by productdevbook** [nuxt/content#1215]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `extends`, `vite`, `modules`, `tailwindcss`, `content`, `colorMode`, `theme`, `github`, `admin`
- Runtime Modules:  `@nuxthq/admin@0.0.1-27556623.cee307a`, `@docus/github@1.2.6-a0efb08`, `@nuxt/content@2.0.1-27571156.c18a99d`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/productdevbook/productdevbook.com

### Describe the bug

![image](https://user-images.githubusercontent.com/38668796/172048740-4fd3b22b-0d60-475e-affe-d856af0f3f2e.png)

**Comment by Atinux** [comment]
Sorry but this is the repo for Nuxt Content, you are trying to use the docs theme from Docus and we did not open source it yet.
