### ISSUE TITLE
the highlighter not support scss language,and caused the crash

### ISSUE THREAD

**Issue by flik1337** [nuxt/content#1225]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `modules`, `styleResources`, `css`, `content`, `colorMode`
- Runtime Modules:  `@nuxt/content@2.0.1`, `@nuxtjs/color-mode@3.1.3`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-eqvgm9?file=content%2Findex.md

### Describe the bug

`Scss` language is supported by shiki, however it is not supported by content module.

In the given reproduction, it is not working when highlight the `scss` code blcok . It works after changing `scss` to `css`.

I think it is caused by the **shiki** version ,which needs to be upgraded from 0.10.0 to 0.10.1.

**Not matter what language is not supported , it should't caused the crash.**

### Logs

```shell
[request error] No grammar provided for <source.css.scss>
  at Registry.e._collectDependenciesForDep (./node_modules/shiki-es/dist/shiki.mjs:34:24999)  
  at Registry.eval (./node_modules/shiki-es/dist/shiki.mjs:34:25495)  
  at eval (./node_modules/shiki-es/dist/shiki.mjs:34:23016)  
  at Object.eval [as next] (./node_modules/shiki-es/dist/shiki.mjs:34:23125)  
  at s (./node_modules/shiki-es/dist/shiki.mjs:34:21828)
```

**Comment by farnabaz** [comment]
This is an upstream issue https://github.com/shikijs/shiki/issues/257

Meanwhile, you can preload `scss` and other languages that you wish to use, using `content.highlight.preload` in `nuxt.config`

```ts
defineNuxtConfig({
  content: {
    highlight: {
      preload: ['css', 'scss', 'js', 'ts']
    }
  }
})
```

**Comment by flik1337** [comment]
Thank you so much @farnabaz 
I have viewed this  issue when this error encountered, but that issue seems not to be fixed.
The `content.highlight.preload` is  still not working for me after I try some times.
I have changed the highlight plugin from shiki to highlight.js and I am waiting for this issue to be fixed.
Thank you again for your time.
