### ISSUE TITLE
Unsuccessful OptionsAPI queries because of docs

### ISSUE THREAD

**Issue by R0N1n-dev** [nuxt/content#1233]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `content`, `build`
- Runtime Modules:  `@nuxt/content@2.0.0`
- Build Modules:    `-`

### Reproduction
```<template>
    <div class="container">
      <ul>
        <li v-for="{ _path: slug, title } in posts" :key="slug">
          <NuxtLink :to="slug">
            {{ title }}
          </NuxtLink>
        </li>
      </ul>
    </div>
  </template>
  
  <script>
  export default {
    data: () => ({
      posts: null
    }),
    async mounted() {
      const data = await queryContent("/posts")
        .sort({ date: -1 })
        .where({ _partial: false })
        .find();
        this.posts = data;
    },
  };
  </script>```
Trying to follow this link: 
https://dev.to/mokkapps/create-a-blog-with-nuxt-content-v2-1i4d

No results. 
renders Fallback template from [...slug].vue

### Describe the bug

Can't query successfully blog posts in content/posts and render the list of posts.
Docs assume everybody is using Comp API

### Additional context

Documentation is only in Composition API terms. 
Not considerable to us "the options API dinosaurs" since options API is still viable in Vue.
Frustrating.

### Logs

_No response_

**Comment by farnabaz** [comment]
It seems to work fine, check out https://stackblitz.com/edit/nuxt-content-v2-starter-w5qptg?file=pages%2F[...slug].vue
Feel free to fork it and provide a reproduction if anything goes wrong

**Comment by farnabaz** [comment]
Do you mind forking this and providing a reproduction?
[https://stackblitz.com/edit/nuxt-content-v2-starter-w5qptg](https://stackblitz.com/edit/nuxt-content-v2-starter-w5qptg?file=pages%2F%5B...slug%5D.vue)

**Comment by R0N1n-dev** [comment]
Forked that thing and now, my single post render cannot render. Posts are listed but on clicking on one, the blog page just refreshes and shows the posts. Cannot show  a single posts.

So not useful. This is useless. Nothing but more errors.

**Comment by farnabaz** [comment]
Could you share it? we can sort it out and fix possible bugs 🙂

**Comment by R0N1n-dev** [comment]
https://github.com/R0N1n-dev/nuxt3blog.git.
There it is

**Comment by farnabaz** [comment]
> Posts are listed but on clicking on one, the blog page just refreshes and shows the posts. Cannot show a single posts.

Ok as I see in your repo, you did not render post contents, and it has nothing to do with Options API.
- Rename `pages/blog/[...slug].vue` into `pages/blog/index.vue`
- Create `pages/blog/[...slug].vue` with following content

```vue
<template>
  <div class="container">
    <ContentDoc />
  </div>
</template>
```

Start the project and you will see the contents

**Comment by R0N1n-dev** [comment]
I swear I dont know if am being messed with OR i really have bad luck OR you really are a wizard,
but you advice is really not working for me.


Even manged to get a new error thrown up in the text editor console on this most recent advice on running the server the first time after making the suggested changes.

 ERROR  [h3] write EPIPE

  at afterWriteDispatched (node:internal/stream_base_commons:164:15)
  at writeGeneric (node:internal/stream_base_commons:155:3)
  at Socket._writeGeneric (node:net:795:11)
  at Socket.connect (node:net:777:12)
  at Object.onceWrapper (node:events:509:28)
  at Socket.emit (node:events:402:35)
  at Socket.emit (node:domain:475:12)
  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1147:10) .

I get youre trying to be helpful but this is becoming really infuriating and resource wasting.
WTF??????


AM completely lost

**Comment by R0N1n-dev** [comment]
Have even pushed your suggested changes to the repository. 
If your'e telling me that the code in my repo is working(with your chnages) , then something is very wrong on this earth

**Comment by R0N1n-dev** [comment]
Successfully failed
