### ISSUE TITLE
Generate static build with app.baseUrl

### ISSUE THREAD

**Issue by stafyniaksacha** [nuxt/content#1252]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `colorMode`, `content`
- Runtime Modules:  `@nuxt/content@2.0.1`, `@nuxtjs/tailwindcss@5.1.2`, `@nuxtjs/color-mode@3.0.3`
- Build Modules:    `-`
------------------------------

### Reproduction

1. git clone https://github.com/Atinux/content-wind
2. cd content-wind
3. yarn
4. NUXT_APP_BASE_URL=/sub/ yarn generate

### Describe the bug

During prerender, it seems that the `/api` path does not contains the `app.baseUrl` provided by nuxt (neither env or configuration in `nuxt.config`)

### Logs

```shell
ℹ Prerendering 2 initial routes with crawler                                                    nitro 17:51:21
  ├─ / (751ms)                                                                                  nitro 17:51:21
  ├─ /api/_content/cache (9ms)                                                                  nitro 17:51:21
  ├─ /api/_content/navigation (5ms)                                                             nitro 17:51:21
  ├─ /api/_content/query/1354861641 (3ms)                                                       nitro 17:51:21
  ├─ /sub/ (17ms)                                                                               nitro 17:51:21
  ├─ /sub/about (16ms)                                                                          nitro 17:51:21
  ├─ /sub/test (21ms)                                                                           nitro 17:51:21
  ├─ /api/_content/query/4205208744 (3ms) (Error: [404] Document not found!)                    nitro 17:51:21
  ├─ /api/_content/query/896285848 (3ms) (Error: [404] Document not found!)                     nitro 17:51:21
  ├─ /api/_content/query/1501933505 (3ms) (Error: [404] Document not found!)                    nitro 17:51:21
```
```

**Comment by danielroe** [comment]
`useRoute().path` should not include the baseURL - if it does that's a bug that needs to be addressed.

**Comment by danielroe** [comment]
I think the issue here is that the baseURL isn't being used in Nuxt Content - it appears to be returning the correct value in `useRoute()` in the Vue part of the app.

**Comment by farnabaz** [comment]
Seems that during generation process `useRotue().path` have `/sub` prefix. 
I might doing something wrong here, try running `NUXT_APP_BASE_URL=/sub/ yarn generate` command on this reproduction: https://stackblitz.com/edit/atinux-content-wind-wyhmyl?file=pages%2F[...slug].vue

You'll see routes logged in the console

**Comment by danielroe** [comment]
Thanks for the reproduction. It's an issue with Nitro following the links with `/sub` prefixed. (Not an issue with `useRoute()`.) PR incoming.
