### ISSUE TITLE
Content from first .md file in a partial directory overrides the content of 1.index.md

### ISSUE THREAD

**Issue by JDN89** [nuxt/content#1257]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.2.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/content@2.0.1`
- Build Modules:    `-`
------------------------------

### Reproduction

Reproduction on StackBlitz:

https://stackblitz.com/github/JDN89/possible-bug-nuxt-content-v2?file=content/1.index.md

### Describe the bug

Content from _1.first-post.md_ located int the __posts_ directory overwrites the content of _1.index.md_.

![folder-structure](https://user-images.githubusercontent.com/68808655/173713201-c7d0d9b9-2249-4b95-b402-6ed57129ffff.png)

I noticed this issue when I upgraded one of my current projects to the above-mentioned environment.

Is the new behavior the intended behavior? 

Project works when I roll back to this environment:
------------------------------
- Operating System: `Linux`
- Node Version:     `v18.2.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `colorMode`, `content`
- Runtime Modules:  `@nuxt/content@2.0.0`, `@nuxtjs/tailwindcss@5.1.2`, `@nuxtjs/color-mode@3.0.3`
- Build Modules:    `-`
------------------------------

**Comment by farnabaz** [comment]
This is fixed in the edge version and soon will release in version `2.1.0`. Checkout this comment https://github.com/nuxt/content/issues/1237#issuecomment-1152131314

close in favor of https://github.com/nuxt/content/issues/1237
