### ISSUE TITLE
Support more code type

### ISSUE THREAD

**Issue by Benbinbin** [nuxt/content#1265]
### Is your feature request related to a problem? Please describe
When I write code block which type rarely seen in markdown file, like `diff`, the console throw an error in dev mode 

```bash
[nuxt] [request error] No grammar provided for <source.[the name of the rarely seen code type]>
```

### Describe the solution you'd like
It seems this error throw from shiki, how to config it to ignore the rarely code type instead of throw an error

### Additional context
the markdown wrting code block as fellow, its type is `diff`, github and VS Code built-in markdown editor preview mode can render this type

![Snipaste_2022-06-16_17-25-33](https://user-images.githubusercontent.com/40909550/174039108-44c88d44-5e3d-4878-975a-0c61ae13ddf3.png)

but the Nuxt console throw an request error and then a `500 Internal Server Error`

![Snipaste_2022-06-16_17-22-03](https://user-images.githubusercontent.com/40909550/174038313-a5a34285-4ac5-4e47-885b-6291b769849c.png)

and the page cannot render correct 

![Snipaste_2022-06-16_17-24-32](https://user-images.githubusercontent.com/40909550/174039139-8bd1cb19-a8f1-432a-95cc-02be6df5b204.png)

**Comment by farnabaz** [comment]
This issue comes from Shiki itself. check upstream issue https://github.com/shikijs/shiki/issues/257

Meanwhile, you can use `highlight.preload` to preload all required language. Check my comment https://github.com/nuxt/content/issues/1225#issuecomment-1148786924

**Comment by Benbinbin** [comment]
> This issue comes from Shiki itself. check upstream issue [shikijs/shiki#257](https://github.com/shikijs/shiki/issues/257)
> 
> Meanwhile, you can use `highlight.preload` to preload all required language. Check my comment [#1225 (comment)](https://github.com/nuxt/content/issues/1225#issuecomment-1148786924)

just add `'diff'` in `content.highlight.preload` is still not working, the console throw another error `[nuxt] [request error] No grammar provided for <source.ts>` 

Maybe it needs more setting

**Comment by farnabaz** [comment]
When you use `preload` config, you need to define list of languages you are using in your contents.

```ts
defineNuxtConfig({
  content: {
    highlight: {
      preload: ['diff', 'ts', 'js', 'css', ...]
    }
  }
})
```

**Comment by farnabaz** [comment]
I just create a PR(#1278) to prevent this bad behavior, in next release you will not need to add `ts` or `js` into `preload` options.
