### ISSUE TITLE
New section in docs with community examples

### ISSUE THREAD

**Issue by jualoppaz** [nuxt/content#127]
### Describe the solution you'd like
It would be nice if a section with **community examples** is present in **nuxt/content** docs.

### Describe alternatives you've considered
A clean page with a list of repositories with **nuxt/content** projects and **deployed examples** if possible

### Additional context
I am developing a **nuxt/content blog** in the repo: https://github.com/jualoppaz/blog and it is deployed in http://blog.juanmanuellopezpazos.es/

**Comment by TheLearneer** [comment]
Would be nice to have, but not sure if it is necessary :thinking:

**Comment by jualoppaz** [comment]
**nuxt/content** docs are very well redacted by the moment, but there are some use cases like using **$content** calls inside **vuex store** modules instead of use them directly in **asyncData** or **fetch** lifecycle methods.

I applied that strategy in my blog and I think having a little section with a few examples could be interesting.

**Comment by jameshhood** [comment]
I personally use $content calls in layouts which have no examples. I think there should be layout, page, and component level examples at the very minimum.

**Comment by benjamincanac** [comment]
The documentation has been updated, you will a find a new "Examples" section: https://content.nuxtjs.org/examples.

Feel free to make PRs to add new ones 🙂
