### ISSUE TITLE
ContentDoc "not-found" slot: "Codegen node is missing for element/if/for node. Apply appropriate transforms first."

### ISSUE THREAD

**Issue by Mokkapps** [nuxt/content#1287]
### Environment

Nuxt CLI v3.0.0-rc.4
RootDir: /home/projects/github-sxpe79
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/content@2.0.1`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

https://stackblitz.com/edit/github-sxpe79?file=pages/[...slug].vue

### Describe the bug

If I try to use the "not-found" slot inside ContentDoc using v-slot I receive the following error:

```
[plugin:vite:vue] Codegen node is missing for element/if/for node. Apply appropriate transforms first.
/home/projects/github-sxpe79/pages/[...slug].vue
```

My `pages/[...slug].vue` template code: 

```vue
<template>
  <main>
    <ContentDoc v-slot="{ doc }" :path="$route.path">
      <h1>{{ doc.title }}</h1>
      <ContentRenderer :value="doc" />
      <template #not-found> <h1>Document not found</h1> </template>
    </ContentDoc>
  </main>
</template>
```

Am I using the slots in a wrong way or is this a bug?

**Comment by farnabaz** [comment]
Change your `[...slug].vue` to
```vue
<ContentDoc :path="$route.path">
  <template v-slot="{ doc }">  
      <h1>{{ doc.title }}</h1>
      <ContentRenderer :value="doc" />
  </template>
  <template #not-found> <h1>Document not found</h1> </template>
</ContentDoc>
```

The reason here is that you want to use two slots, and you should define both of them with `template`

**Comment by Mokkapps** [comment]
Thanks @farnabaz , that works like expected!
