### ISSUE TITLE
Error render when using variable in markdown block

### ISSUE THREAD

**Issue by boojack** [nuxt/content#1289]
### Environment

https://content.nuxtjs.org/playground

### Reproduction

Move variable block `{{ $doc.title }}` into markdown block, then the render result will be unwanted.

### Describe the bug

<img width="1668" alt="image" src="https://user-images.githubusercontent.com/24653555/175812674-51ded12a-cde1-4902-898e-198e17dd693d.png">

**Comment by farnabaz** [comment]
Thanks for reporting the issue, note that:
- It is not possible to have space characters in markdown links. This is the default behavior of markdown parsers.
- For now, it is only possible to use variable blocks inside text flow and not in links

```
# {{ $doc.title}}

{{ $doc.title}}

> {{ $doc.title}}

- {{ $doc.title}}

[{{ $doc.title }}]

[{{ $doc.title}}](/link)
```

**Comment by farnabaz** [comment]
The content module does not replace variables, it evaluates them at render time. With this approach, let's say you can use the `$route` variable in your markdown, which will change based on the URL you are visiting.

```
Your are visiting: {{ $route.path }}
```

**Comment by boojack** [comment]
Got that, thanks for your reply.

**Comment by ManasMadrecha** [comment]
@farnabaz These `$route.path` or `$doc.xx` variables don't work while using them as props for Vue components in markdown, even when prop is written as `:prop`. 

Any workaround?

**Comment by ManasMadrecha** [comment]
Found it https://github.com/nuxt/content/pull/1266#issuecomment-1223989222
