### ISSUE TITLE
the H5 and H6 in toc don't have the depth information

### ISSUE THREAD

**Issue by Benbinbin** [nuxt/content#1292]
### Is your feature request related to a problem? Please describe
I can get the more depth heading by setting the `nuxt.config.ts`

```ts
export default defineNuxtConfig({
  content: {
    markdown: {
      toc: {
        depth: 5,
        searchDepth: 5
      }
    }
  }
})
```

but the toc for h5 and h6 not the same as h1~h4, they don't has the depth information

![Snipaste_2022-06-27_19-52-12](https://user-images.githubusercontent.com/40909550/175935668-ebd62298-002b-4b05-af82-24d3d1c350a0.png)

### Describe the solution you'd like
maybe I can tell the level of the H5 or H6 depend on their parent level, 

### Describe alternatives you've considered
but I think also add the `depth`  field for H5 and H6 can be more convenience for developers.

### Additional context
the [ProseH1](https://github.com/nuxt/content/blob/main/src/runtime/components/Prose/ProseH1.vue), [ProseH5](https://github.com/nuxt/content/blob/main/src/runtime/components/Prose/ProseH5.vue) and [ProseH6](https://github.com/nuxt/content/blob/main/src/runtime/components/Prose/ProseH6.vue) also different, they don't wrap the `<NuxtLink>` component, for example the `ProseH5.vue` is

```vue
<template>
  <h5><slot /></h5>
</template>
```

but the [ProseH2](https://github.com/nuxt/content/blob/main/src/runtime/components/Prose/ProseH2.vue) ~ [ProseH4](https://github.com/nuxt/content/blob/main/src/runtime/components/Prose/ProseH4.vue) components can provide an anchor link, for example the `ProseH2.vue` is

```vue
<template>
  <h2 :id="id">
    <NuxtLink :href="`#${id}`">
      <slot />
    </NuxtLink>
  </h2>
</template>

<script setup lang="ts">
defineProps<{ id: string }>()
</script>
```

Sometimes a long blog post has the H5 or H6 level heading, but it can't provide the anchor link like other headings to click and navigate, it maybe confuse readers.

Although I can [custom](https://content.nuxtjs.org/guide/writing/markdown#customizing) the Prose components for H5 and H6, but I think wrapping the `<NuxtLink>` component inside all the Heading Prose components maybe better.

**Comment by farnabaz** [comment]
Hey @Benbinbin,
I agree that h5 and h6 should have depth fields in their nodes. But note that the depth field does not depend on the position of the header in the document. Depth of and `h5` will be `5` no matter where it is placed.
