### ISSUE TITLE
content navigation fails with azure preset

### ISSUE THREAD

**Issue by sig9** [nuxt/content#1299]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.4-27605536.8c2c80e`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `colorMode`, `content`
- Runtime Modules:  `@nuxt/content@2.0.1-27605779.105f690`, `@nuxtjs/tailwindcss@5.1.3`, `@nuxtjs/color-mode@3.1.4`
- Build Modules:    `-`
------------------------------

### Reproduction

I was unable to reproduce this in stackblitz, the environment does not have `ps` which is called by either @azure/static-web-apps-cli or azure-functions-core-tools.

Instead I created a repo https://github.com/sig9/content-wind-swa-navigation to demonstrate the issue.

I created a repo from the  [Atinux/content-wind](https://github.com/Atinux/content-wind) template.

Added just one commit with changes to package.json to bring in azure-functions-core-tools and @azure/static-web-apps-cli

Then added a package.json script called runbuildwithswa.  

``` sh
git clone  https://github.com/sig9/content-wind-swa-navigation
cd content-wind-swa-navigation
yarn
yarn runbuildwithswa
```

### Describe the bug

When I first navigate to the / route, it renders nicely.

Clicking on the **About** nav link yields 

![image](https://user-images.githubusercontent.com/2271605/176087807-18242668-51a0-4c5c-b579-c2a0f56a7510.png)

Notice that the url does not show /about after clicking on the link.

Now if I add /about to the url and load that page it renders nicely.

At this point I can open an incognito window and navigate to / and /about and they both render properly. This suggests there is something cached on the server side.

The same behavior exists if I deploy to azure static websites.

An earlier version of contentwind would show /about in the url bar after clicking the About nav link and we only needed to reload, now we need to know the route path in order to do a full reload.

I realize we are running nuxt3@latest and @nuxt/content-edge@latest here. Thanks for having a look. 

Thanks @danielroe for suggesting that I open the issue here instead of with content-wind

**Comment by farnabaz** [comment]
Thank you for reporting the issue, This is related to Azure deployment in Nuxt3. Keep an eye on https://github.com/unjs/nitro/pull/318
