### ISSUE TITLE
Surround documentation link is invalid

### ISSUE THREAD

**Issue by saschwarz** [nuxt/content#1318]
### Environment

I'm new to `nuxt/content` and was reading: https://content.nuxtjs.org/v1/community/snippets/#prev-and-next and I didn't understand what the `surround` method does. IOW, what is being "surrounded" by this query method? 

To learn more I clicked the link: `Check out the [surround documentation](https://content.nuxtjs.org/fetching#surroundslug-options)` and it didn't take me to the description

It looks like that link should be: `Check out the [surround documentation](https://content.nuxtjs.org/fetching#surroundslugorpath-options)`

So I learned that `surround == getPrevNextNodes` 😄 

### Reproduction

Go to: https://content.nuxtjs.org/v1/community/snippets/#prev-and-next 

### Describe the bug

The anchor in the link is outdated.

**Comment by Atinux** [comment]
Do you mind opening a PR ? :)
