### ISSUE TITLE
Error in invocation of contentFilterPrivate.isURLBlocked (Opera GX only)

### ISSUE THREAD

**Issue by OrbisK** [nuxt/content#1325]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/content@2.0.1`
- Build Modules:    `-`
------------------------------

### Reproduction

```bash
npx nuxi init content-app -t content
cd content-app
npm install
npm run dev
```

or use:
https://stackblitz.com/github/nuxt/starter/tree/content

### Describe the bug

![image](https://user-images.githubusercontent.com/37191683/177006434-12623a1d-3c6c-4c4b-90d9-4c0bd6e6e6e4.png)

See image.

### Logs

```shell
[vite] connecting...
client.ts:53 
[vite] connected.
filter_content.js:202 Uncaught (in promise) TypeError: Error in invocation of contentFilterPrivate.isURLBlocked(string url, contentFilterPrivate.ElementType type, string sitekey): No matching signature.
    at FilterContent.isUrlFiltered_ (filter_content.js:202:44)
    at FilterContent.filterAssetsIfNeeded_ (filter_content.js:85:16)
    at FilterContent.filter_ (filter_content.js:78:10)
    at FilterContent.initialize_ (filter_content.js:181:10)
    at filter_content.js:30:46
isUrlFiltered_ @ filter_content.js:202
filterAssetsIfNeeded_ @ filter_content.js:85
filter_ @ filter_content.js:78
initialize_ @ filter_content.js:181
(anonym) @ filter_content.js:30
Promise.then (async)
(anonym) @ filter_content.js:30
runtime-core.esm-bundler.js:1331 <Suspense> is an experimental feature and its API will likely change.
```

**Comment by OrbisK** [comment]
Seems that this is not an issue in Chrome or Edge.

I am using OperaGX LVL4 (core: 88.0.4412.65).

**Comment by thuliumsystems** [comment]
same here... maybe it is a opera issue only...

**Comment by qusay-and** [comment]
another opera gx here

**Comment by dmchinenov** [comment]
The same problem in opera, happens in any applications and does not disappear anywhere

**Comment by flechajm** [comment]
I'm using OperaGX too. Maybe it's just an issue, I'll hope they can fix it.

**Comment by halibal** [comment]
Have the same issue with Opera GX. Does this have anything to do with the code or hinder it?

**Comment by szygendaborys** [comment]
Opera GX issue as well

**Comment by thestatic7** [comment]
I thought this was an issue on my website but yea seems that it's opera

**Comment by zkgz** [comment]
I'm also having this issue (using Opera GX)

**Comment by topex-psy** [comment]
I have this issue in Opera browser as well (I don't use Opera GX). Also mine is happen when running Flutter web app, not Nuxt app.
So it's not an issue of our framework, but Opera's.

**Comment by dreki9** [comment]
i have the same problem and i am using Opera 88.0.4412.53

**Comment by paweleq1994** [comment]
Older version of opera don't have this error (tried on 83.0.4254.27)

**Comment by MarBGamer** [comment]
It is caused by a fault in the Opera GX tracking blocker. You can fix this by disabling the tracking blocker until Opera releases a fix.

**Comment by david-abell** [comment]
> It is caused by a fault in the Opera GX tracking blocker. You can fix this by disabling the tracking blocker until Opera releases a fix.

Definitely a problem with Opera. Also a fault in Opera for desktop's tracking blocker. 

I came here after encountering this issue in a create react app dev server after importing a react-query custom data fetch hook when I had not yet declared state from the hook. ie:

Error encountered when useForecasts imported into App...
```
function useForecasts({ lat, long }) {
const fetchForecasts = async () => {
    ...
    try ...fetch(someData
    ...return data
  };
const { isLoading, error, data, isFetching } = useQuery(
    "forecasts",
    fetchForecasts
  );
return {
    forecasts: data ?? [],
    isForecastLoading: isLoading,
    error,
    isFetching,
  };
}
```
Error not encountered when below code is also included in App
```
  const { forecasts, isForecastLoading } = useForecasts(
   geoLocation.coordinates
  );

```

**Comment by Gosmacx** [comment]
same error i am using opera gx too

**Comment by nepa** [comment]
I've reported this bug to the developers at **Opera Software** a couple of days ago already:

https://opera.atlassian.net/servicedesk/customer/portals

Unfortunately, I cannot link to the issue, since their bugtracker is not public.

**Comment by codcodea** [comment]
> unction useForecasts({ lat, long }) {

+1

**Comment by f22j** [comment]
I solved it by disabling "Block ads" and "Block Trackers" under Settings>Privacy Protection

**Comment by Phantomat0** [comment]
Using NextJS with Opera and am receiving this error

**Comment by nepa** [comment]
Issue is now fixed with Opera 89.0.4447.38.

**Comment by devbraz** [comment]
Disable privacy protection on localhost page, it's works normally.

**Comment by kevstar0** [comment]
> opera://settings/privacyProtection
> 
> disable block ads and block trackers and error disapppears

but here is the thing my website does not have ads in them just a customized user activity monitoring system
