### ISSUE TITLE
Latex inside markdown

### ISSUE THREAD

**Issue by anandkumar89** [nuxt/content#133]
### Is your feature request related to a problem? Please describe.
I wanted an entirely new feature useful to whole new class of people. I want to write math equations in markdown. Being able to write latex will be useful feature for people in academic domain.

### Describe the solution you'd like
There exists couple of modules - `markdown-it-latex`  or `markdown-it-texmath` which can be used along with `markdown-it` to parse latex inside markdown. Similar feature of being able to extend `@nuxt/content` to use said plugins will be useful in short term. 
Alternatively, above said plugins use katex to render math inside. It'd be great solution to extend plugin to use katex to render math.

### Describe alternatives you've considered
Currently I'm using `markdown-it` along with `markdown-it-texmath` and it works perfect for rendering math. But this combination lacks the other great features `@nuxt/content` has to offer.

### Additional context
Mathjax is also used to render math equations and latex on web. But Katex is said to be fast and light. Before proceeding along this line, it'd be better to weigh the alternatives.

**Comment by mathieunicolas** [comment]
I've posted a similar issue few weeks ago : https://github.com/nuxt/content/issues/102

**Comment by anandkumar89** [comment]
Awesome and thanks for super quick reply! Closing this issue.

**Comment by anandkumar89** [comment]
Does this still work. 

`
Command failed: git checkout feat/rehype-plugins
`

npm can't find feature branch. Has this been merged into master now ? Can't get it working with latest `@nuxt/content` install.

**Comment by heeteshalwani** [comment]
> Does this still work.
> 
> `Command failed: git checkout feat/rehype-plugins`
> 
> npm can't find feature branch. Has this been merged into master now ? Can't get it working with latest `@nuxt/content` install.

Hi, I managed to get it working with these dependencies
"dependencies": {
    "@nuxt/content": "^1.14.0",
    "nuxt": "^2.0.0",
    "rehype-katex": "^5.0.0",
    "remark-math": "^4.0.0"
}
Hope it helps.

**Comment by anandkumar89** [comment]
Thanks. Worked.
