### ISSUE TITLE
Route name is cropped when it contains `index` in it

### ISSUE THREAD

**Issue by Baroshem** [nuxt/content#1332]
### Environment

production

### Reproduction

Access website here -> https://algolia.nuxtjs.org/advanced/er

The name of the file and the route is `indexer.md`. A screenshot shows the folder 2.advanced and 3.indexer.md

![image](https://user-images.githubusercontent.com/37120330/177315852-9a2cb8db-9b56-4837-a6bd-e86a2a16470d.png)

### Describe the bug

Not sure if a bug is related to NuxtContent, Docus, or the Nuxt 3 so I decided to report it here. Can be transfered if needed :)

When naming a .md page in the documentation powered by Docus 3 with a name consisting of the keyword `index` will result in the route cropped.

In my case the file is called `3.indexer.md` and the route created from it is `er` -> Like indexer without index

**Comment by Tahul** [comment]
Hey Baroshem!

Thanks for reporting the issue, I suspect this line to be the culprit: https://github.com/nuxt/content/blob/3fbcd22a17eee6bb1c8224b2cfb436539cda0a6b/src/runtime/server/transformers/path-meta.ts#L93-L94

I guess we should maybe use a regex here instead.

**Comment by Baroshem** [comment]
Hi @Tahul 

Thanks for the fast reply! It is not a big issue for me. Just reporting because one of the community members reached to me with it.

It should not break any place and it is a rather minor bug.

Happy coding!
