### ISSUE TITLE
Cannot start nuxt | Cannot add package to an existing Nuxt3 project using yarn

### ISSUE THREAD

**Issue by MoodyBones** [nuxt/content#1337]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.1-27520426.ab3971d`
- Package Manager:  `yarn@1.17.3`
- Builder:          `vite`
- User Config:      `buildModules`, `modules`, `css`, `build`, `vite`, `content`, `strapi`, `intlify`, `telemetry`
- Runtime Modules:  `@nuxt/content@2.0.1`, `@intlify/nuxt3@0.2.2`, `@formkit/nuxt@1.0.0-beta.6`, `@nuxtjs/strapi@1.3.2-27565120.a6bd24b`
- Build Modules:    `@vueuse/nuxt@8.3.1`

### Reproduction

I first got this error 2 weeks ago when I couldn't replicate it in stackblitz I removed the package. Today I tried to add the package again and got the same error which is why I am reporting it here. 

In the stackblitz link provided `nuxt/content` is already installed. But I get an error when I **try to add nuxt/content** to an existing nuxt3 project. I will try again to replicate it and provide a link. 

### Describe the bug

Cannot add nuxt/content to our existing Nuxt3 project using yarn 

`$ yarn add -D @nuxt/content`
`$ yarn dev`
```
Nuxt CLI v3.0.0-rc.1-27520426.ab3971d                                                                         15:09:13
                                                                                                              15:09:13
  > Local:    http://localhost:3000/ 
  > Network:  ******
  > Network:  ******

Server Started ∹ http://localhost:3001
✔ Using ~/components/content for components in Markdown                                         @nuxt/content 15:09:22

 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'watch')                             15:09:22

  at node_modules/@nuxt/content/dist/module.mjs:287:27
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async initNitro (node_modules/nuxt/dist/index.mjs:1162:3)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1323:3)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6734:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6777:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:46:20)
```
From following the log what I understand is that nitro is undefined. When I run `yarn why nitropack` and I get:
```
Found "nitropack@0.3.8"
info Reasons this module exists
   - "nuxt" depends on it
   - Hoisted from "nuxt#nitropack"
info Disk size without dependencies: "1.45MB"
info Disk size with unique dependencies: "23.45MB"
info Disk size with transitive dependencies: "73.11MB"
info Number of shared dependencies: 199
```
If I add `nitropack` as a dev dependency I get the same error

### Additional context

I also tried the following:
- `rm -rf node_module`
- `yarn cache clean`
- `yarn install`
- `yarn dev`

I get the same `ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'watch')                             15:09:22  at node_modules/@nuxt/content/dist/module.mjs:287:27`

What else could I try? Thanks all <3

**Comment by farnabaz** [comment]
Content module requires `nuxt@3.0.0-rc.4` but you are using `nuzt@3.0.0-rc.1`. Consider updating Nuxt version and it will be good 🙂

**Comment by MoodyBones** [comment]
Thanks for the quick response. You are correct It was the version - thanks for spotting that :D

I had the version in my package.json set to `"nuxt": "npm:nuxt3@latest"` which I now changed to `nuxt@3.0.0-rc.4`. I thought that by defining it as `npm:nuxt3@latest` it would install the latest - my bad.

Thanks again for the help and for getting nuxt/content working with nuxt3! amazing work 💯
