### ISSUE TITLE
query prop is inconsistent between ContentList and ContentNavigation

### ISSUE THREAD

**Issue by sudoLife** [nuxt/content#1344]
### Environment

```
- Operating System: `Linux`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `target`, `head`, `modules`, `components`
- Runtime Modules:  `@nuxt/content@2.0.1`, `@nuxtjs/tailwindcss@5.1.3`, `@nuxtjs/eslint-module@3.1.0`
- Build Modules:    `-`
```

### Reproduction

No reproduction is needed in this case.

### Describe the bug

According to the documentation, for `ContentNavigation`, it's 

- `query`: A query to be passed to `fetchContentNavigation()`.
  - Type: `QueryBuilderParams | QueryBuilder`
  - Default: `undefined`

For `ContentList` it's different:
- `query`: A query to be passed to `queryContent()`.
  - Type: `QueryBuilderParams`
  - Default: `undefined`

It's quite confusing. Also, in the case of `ContentList`, the query is not passed to `queryContent()`, it's passed to `ContentQuery`, so either the docs or the code has to be changed.

My two cents is that it'd be great to have the same API in these two cases as it'd be much more intuitive.

Thanks to @tomaszal for helping to pinpoint the issue.

**Comment by itpropro** [comment]
I also have this issue, it's confusing and makes the creation helper functions e.g. to share queries hard to implement.
