### ISSUE TITLE
Using nuxt/content in test file without Nuxt instance

### ISSUE THREAD

**Issue by ipatate** [nuxt/content#1350]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.9.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `modules`, `experimental`, `components`, `colorMode`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.1.3`, `@nuxt/content@2.0.1`, `@vueuse/nuxt@8.9.1`, `@pinia/nuxt@0.1.9`, `@nuxtjs/color-mode@3.1.4`
- Build Modules:    `-`
------------------------------

### Reproduction

i want replace this method with nuxt/content find()
https://github.com/double-slash-podcast/website/blob/efd97318601f47a4379509780c8ddfcce76bd03b/__tests__/guid-episodes.test.ts#L42

### Describe the bug

I can't use nuxt/content in my test file.
When i import content, it's mendatory to init content with all options and one instance of nuxt app.
But i haven't nuxt app in my test.
My question is : it's possible to use nuxt/content outiside nuxt app ?

### Additional context

```
import Content from '@nuxt/content'

const content  = Content({...lot of options}, nuxt instance);
```

**Comment by farnabaz** [comment]
It is not possible to use Nuxt Content outside of Nuxt context. in order to use content utils and APIs you need to start nuxt server.

You can simply do it using [`@nuxt/test-utils`](https://github.com/nuxt/framework/tree/main/packages/test-utils).

Check out module tests as an example of using test utils. https://github.com/nuxt/content/blob/main/test/basic.test.ts#L23-L26

**Comment by farnabaz** [comment]
Ok since you have the server,  you need to use `$fetch` function from test utils and call the `query` API. 

```ts
import { $fetch } from '@nuxt/test-utils'

...

test('...', async () => {
  const list = await $fetch('/api/_content/query?_params={}')

})

**Comment by ipatate** [comment]
yeah thanks, it's better. It's difficult to find the good params for query but it works. 👍🏼 
https://github.com/double-slash-podcast/website/blob/7ce57b088ece8cb1dc9ae14319765dc4d9433a12/__tests__/guid-episodes.test.ts#L44

**Comment by farnabaz** [comment]
I'm closing this one. Feel free to open a new issue if you encounter an issue or have a question.
