### ISSUE TITLE
Multiple calls with find() later gives error: nuxt instance unavailable

### ISSUE THREAD

**Issue by kirtan403** [nuxt/content#1368]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.6-27638947.92269dd`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/content@2.1.0-27639343.b832f24`, `@nuxt/ui@0.2.0-27638810.adb0eb6`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-4fmlha?file=app.vue

### Describe the bug

when there are multiple calls to the `queryContent()` and later both calls to `find()`. The first instance works and the second instance gives error: `nuxt instance unavailable`. 

It is a very straightforward usage, written in the reproduction link in the `app.vue` file.

### Additional context

```
<script setup>
const { data: posts } = await useAsyncData('equal', async () => {
  const posts1 = queryContent('/posts/');
  const posts2 = queryContent('/posts/');

 // first call succeed
  try {
    await posts1.find();
  } catch (e) {
    console.log("error from 1st call")
    console.log(e)
  }

  // second call gives error
  try {
    const posts =  await posts2.find();
    return posts
  } catch(e) {
    console.log("error from 2nd call")
    console.log(e)
  }
});
</script>
```

Simple usage of query content fails.

### Logs

```shell
Error: nuxt instance unavailable
    at useNuxtApp (file:///home/projects/github-4fmlha/.nuxt/dist/server/server.mjs:488:13)
    at Module.useRuntimeConfig (file:///home/projects/github-4fmlha/.nuxt/dist/server/server.mjs:496:10)
    at Module.withContentBase (file:///home/projects/github-4fmlha/.nuxt/dist/server/server.mjs:10843:102)
    at eval (file:///home/projects/github-4fmlha/.nuxt/dist/server/server.mjs:10624:41)
    at Object.find (file:///home/projects/github-4fmlha/.nuxt/dist/server/server.mjs:10687:17)
    at eval (file:///home/projects/github-4fmlha/.nuxt/dist/server/server.mjs:16449:33)
    at async setup (file:///home/projects/github-4fmlha/.nuxt/dist/server/server.mjs:16456:12
```

**Comment by farnabaz** [comment]
This is a known behavior of Nuxt, If you wish to use multiple fetch/find inside asyncData, you need to await for all of them at once.

```ts
const { data: posts } = await useAsyncData('equal', async () => {
  const posts1 = queryContent('/posts/');
  const posts2 = queryContent('/posts/');
  const [res1, res2] = await Promise.all([
    posts1.find()
    posts2.find()
  ])
});
```

**Comment by kirtan403** [comment]
@farnabaz  Thanks for providing details. But it only exists with the async setup function? (Based on the docs)


I've created another problem with the composable. I want to retrieve the data from 2 collections one after the other. For example, based on posts, I want to retrieve authors. That can only happen once the posts have been retrieved. Now this was something that was working for me on nuxt 2. I'm not sure why it is not in nuxt3. Do you know why this happens even when I'm not in `asyncData` or using `script setup` or when using `composables` ?

Example with composables: https://stackblitz.com/edit/github-4fmlha-98vt5s?file=app.vue,composables%2FgetContent.js

**Comment by farnabaz** [comment]
You use two consequent queries directly in `script setup` but not in a custom composable. Check: https://stackblitz.com/edit/github-4fmlha-w9eyhs?file=app.vue

The reason is Nuxt internally does some magic in the setup function to make this happen, but it is not possible in custom composable

**Comment by kirtan403** [comment]
I've previously made 2 await calls in a composable, and it worked fine (multiple fetch calls). So I guess if you are making await calls which involve the nuxt / vue content, then it's an issue, otherwise there should not be any problem. Am I correct?

**Comment by farnabaz** [comment]
> So I guess if you are making await calls which involve the nuxt / vue context, then it's an issue

Exactly, this limitation implies only if your async operations want to access Nuxt context (`useNuxtApp` or other composables). Query fetch function requires Nuxt context to operate correctly and that's why you can't use the consequent calls in your custom composable

**Comment by kirtan403** [comment]
Thanks for explaining this. I appreciate it. Closing this issue.

**Comment by luksak** [comment]
I just came across this and had a similar but not exactly the same issue. This is how I solved mine:

```
const { data: content1 } = await useAsyncData('content1', () => queryContent('/content1').findOne())
const { data: content2 } = await useAsyncData('content2', () => queryContent('/content2').findOne())
```

**Comment by davestewart** [comment]
Hey there,

Just been tripped up by this and said some very hurtful things to my computer in the process!

@farnabaz, you mention:

> This is a known behavior of Nuxt, If you wish to use multiple fetch/find inside asyncData, you need to await for all of them at once.

I am somewhat of a fairweather Nuxter; that is, I really don't think I "know" Nuxt; it always trips me up, for example, things like this.

How is this a "known behaviour"? Can I find this in the Nuxt or Content docs somewhere?

There is always something with Nuxt. It's frustrating. Help appreciated!

**Comment by luksak** [comment]
@davestewart well, this is just how asynchronous Javascript and this API works. So this i by design and this is the way you should use it.

**Comment by davestewart** [comment]
Hey @luksak, 

Perhaps I should be more explicit.

In vanilla JS, the following hypothetical code would most likely work fine:

```js
// normal async js: works
const data = await getAsyncData(async () => {
  const foo = await getFoo()
  const bar = await getBar()
  return { foo, bar }
})
```

But in Nuxt, for some reason, the almost exact same setup only works works with a `Promise.all()`:

```js
// nuxt: needs Promise.all()
const data = await useAsyncData('some-key', async () => {
  const [foo, bar] = await Promise.all([
    getFoo(),
    getBar(),
  ])
  return { foo, bar }
}
```

So my question is, why is this so?

It's all very well saying "it's by design" but for a framework whose slogan is "the intuitive framework" this is about as far away from intuitive as you can get. 

At the very least, Nuxt should ship with a linter rule which tells you you can't do this, because of some internal gymnastics.

So, do we know why this is so? Or is it just &lt;waves hands magically&gt; "the way it is" ?

**Comment by luksak** [comment]
Well regarding "this is the way it is": I think that there should be documentation about this. That is what we could provide.

As of why this is the case, I can't really provide more information. Just one sidenote: Our case here is different from your example. There is a callback function inside the `await`. The code is:

```
const { data: content1 } = await useAsyncData('content1', () => queryContent('/content1').findOne())
```

But not according to your example:

```
const { data: content1 } = await useAsyncData('content1')
```

Maybe that's the reason for this issue?

> It's all very well saying "it's by design" but for a framework whose slogan is "the intuitive framework" this is about as far away from intuitive as you can get.
I think nuxt is quite intuitive in general compared to others. But this is kind of off-topic here.

> At the very least, Nuxt should ship with a linter rule which tells you you can't do this, because of some internal gymnastics.
Feel free to contribute that!

**Comment by davestewart** [comment]
> But not according to your example:

Actually, both examples do call a callback. Maybe I'm not understanding you?

As for writing a linter, that actually sounds like fun, but certainly updating the docs would be a quicker win here. Though I still think it's essential to understand the mechanics behind this one.

FWIW every time I've seen `Promise.all()` mentioned in the same breath as `useAsyncData()` it's attributed to _performance_, but in my most-basic, prototyping code I add two calls, and it simply breaks, with no errors or feedback of any kind. Worse still, I had an erroneous page setup before that meant it worked some of the time, but not the rest!

Anyway, I really appreciate you coming back with responses for me. Thank you :)

**Comment by davestewart** [comment]
> No, they don't. getFoo() and getBar() don't have a callback function as an argument in your example.

Sure, but neither does:

```js
queryContent(path).find()
```

> Have you tried what I suggested here:

I didn't because a `Promise.all()` is a faster parallel call.
