### ISSUE TITLE
Allow extending Shiki

### ISSUE THREAD

**Issue by heychazza** [nuxt/content#1371]
### Is your feature request related to a problem? Please describe

I want to extend Shikis highlighting to support code diffs, which isn't currently a Shiki native feature.

### Describe the solution you'd like

The ability to specify a callback within our `nuxt.config.js` file to add these tweaks. My main reason is the following code:
https://github.com/kylebutts/shiki-vue/blob/main/src/components/Shiki.vue#L43-L59

This adds support for this, which would need to be added after
https://github.com/nuxt/content/blob/772f48f277bbd116be7e4d630407c5b2321df903/src/runtime/server/api/highlight.ts#L116-L123

### Describe alternatives you've considered

n/a
### Additional context

<img width="261" alt="CleanShot 2022-07-21 at 12 57 48@2x" src="https://user-images.githubusercontent.com/47271716/180208309-14a49447-0fd9-49e1-9c21-656cafc5d697.png">

**Comment by heychazza** [comment]
> Try using the edge version of Nuxt content, it supports diff syntax by default. https://content.nuxtjs.org/guide/migration/edge-channel

How does the diff syntax work? I've tried
```diff-yaml
++ test
-- blah
```

**Comment by farnabaz** [comment]
Simply use `diff` language.
Also if you want to use `diff-yaml` language, you can add it into `content.highlight.preload` in `nuxt.config.ts`

```ts
export default defineNuxtConfig({
  content: {
    highlight: {
      preload: ['diff-yaml']
    }
  }
})
```

**Comment by heychazza** [comment]
> farnabaz

Woah, this is fantastic:
```
[nuxt] [request error] Cannot read property 'id' of undefined
  at Resolver.addLanguage (./node_modules/shiki-es/dist/shiki.mjs:1792:28)  
  at Registry.loadLanguages (./node_modules/shiki-es/dist/shiki.mjs:2037:28)  
  at getHighlighter (./node_modules/shiki-es/dist/shiki.mjs:2082:21)  
  at async ./.nuxt/dev/index.mjs:2285:23
```

I added `diff-yaml`

**Comment by farnabaz** [comment]
@heychazza My bad, no there is no such language in shiki.

**Comment by heychazza** [comment]
> @heychazza My bad, no there is no such language in shiki.

Aw damn, I wasn't sure if shiki had a way to highlight code but keep diffs. The code I linked in my original post has a way to do it.

Perhaps if it could be possible to integrate that with Nuxt.

**Comment by farnabaz** [comment]
Also, it is not possible to support a callback function is nuxt.config file.

However, if you want to use `shiki-vue` to achieve your goal, you can disable the content's default highlighter and overwrite `ProseCode` component, and do highlighting with shiki-vue.

Check Prose components: https://content.nuxtjs.org/api/components/prose

**Comment by heychazza** [comment]
> Also, it is not possible to support a callback function is nuxt.config file.
> 
> However, if you want to use `shiki-vue` to achieve your goal, you can disable the content's default highlighter and overwrite `ProseCode` component, and do highlighting with shiki-vue.
> 
> Check Prose components: https://content.nuxtjs.org/api/components/prose

Oh thats fantastic, thanks for linking this! A feature requesr (but I can make a new issue for this) is to prevent the `+` and `-` being included in the copied code. Only because when you copy code it shows beside it.

Thanks for all your help

**Comment by farnabaz** [comment]
I'm closing this one. Feel free to open a new issue about the copy button so we can discuss about it.
