### ISSUE TITLE
How to get only the content of a json file?

### ISSUE THREAD

**Issue by Rednas83** [nuxt/content#138]
**Tried**
`return await this.$content('settings').fetch()`
**Result**
![image](https://user-images.githubusercontent.com/25219229/84590889-6f7caf80-ae3a-11ea-858d-07b5166010db.png)
**Expected only the content of the file and not the meta information**
![image](https://user-images.githubusercontent.com/25219229/84590956-e74ada00-ae3a-11ea-8958-c72c9b95cb3d.png)

**Comment by mathieunicolas** [comment]
Hi there !
I've seen nothing about this in the docs. A workaround could be using a function to make this automatic with `delete` operator ?

```
    const test = await $content("/", "test").fetch();
    delete test.createdAt;
    delete test.dir;
    delete test.extension;
    delete test.path;
    delete test.slug;
    delete test.updatedAt;
```

**Comment by Rednas83** [comment]
Only delete and require worked for me to get the content.
```
        // return await this.$content('settings').fetch() // => Returns content and meta information
        // return await this.$content('settings').only('items').fetch() // => returns Object (empty)
        // return await this.$content('settings').only(['items']).fetch() // => returns Object (empty)
        return await require('../content/settings.json') // => Returns content
        // eslint-disable-next-line no-var
        // return await this.$content('settings').fetch()
        // delete result.createdAt
        // delete result.dir
        // delete result.extension
        // delete result.path
        // delete result.slug
        // delete result.updatedAt
        // return result
```

**Comment by benjamincanac** [comment]
@Rednas83 

As @mathieunicolas mentioned you can use `only` to select a subset of fields: https://content.nuxtjs.org/fetching#onlykeys.
