### ISSUE TITLE
Non-English filenames cannot generate routes

### ISSUE THREAD

**Issue by NEOTSO** [nuxt/content#1383]
### Environment

```
    "@nuxt/content": "^2.0.0",
    "nuxt": "^3.0.0-rc.4"
```

### Reproduction

https://codesandbox.io/s/language-test-sr1mov?file=/content/%E4%B8%AD%E6%96%87.md

### Describe the bug

When using a non-English filename, no corresponding routing link is generated.
for example:
- content
  * 中文.md
  * chinese.md

https://sr1mov.sse.codesandbox.io/中文
Document not found, overwrite this content with #not-found slot in <ContentDoc>.

https://sr1mov.sse.codesandbox.io/chinese
it works.

**Comment by nobkd** [comment]
Thats probably because of the Regular Expressions used to find the files

**Comment by farnabaz** [comment]
The module uses [`slugify`](https://www.npmjs.com/package/slugify) to generate URL paths based on file names.  Slugify removes Chinese characters and that's why the generated path for your content is not the same as the file name.
The path for the `中文.md` files will be `/`.

However, you can set a custom path for your content using front-matter

```
---
_path: /中文
---

# 中文

测试
```

**Comment by NEOTSO** [comment]
You are awesome!
It works, thanks.

**Comment by Jimi1126** [comment]
> The module uses [`slugify`](https://www.npmjs.com/package/slugify) to generate URL paths based on file names. Slugify removes Chinese characters and that's why the generated path for your content is not the same as the file name. The path for the `中文.md` files will be `/`.该模块用于根据文件名生成URL路径。Slugify删除了中文字符，这就是为什么生成的内容路径和文件名不一样。文件的路径将是。
> 
> However, you can set a custom path for your content using front-matter但是，您可以使用front-matter为您的内容设置自定义路径
> 
> ```
> ---
> _path: /中文
> ---
> 
> # 中文
> 
> 测试
> ```

What do I need to do if I want to keep the level? When I have many subdirectories, or when I need to migrate content, it is difficult to set up files one by one. : )

**Comment by Jimi1126** [comment]
> > The module uses [`slugify`](https://www.npmjs.com/package/slugify) to generate URL paths based on file names. Slugify removes Chinese characters and that's why the generated path for your content is not the same as the file name. The path for the `中文.md` files will be `/`.该模块用于根据文件名生成URL路径。Slugify删除了中文字符，这就是为什么生成的内容路径和文件名不一样。文件的路径将是。
> > However, you can set a custom path for your content using front-matter但是，您可以使用front-matter为您的内容设置自定义路径
> > ```
> > ---
> > _path: /中文
> > ---
> > 
> > # 中文
> > 
> > 测试
> > ```
> 
> What do I need to do if I want to keep the level? When I have many subdirectories, or when I need to migrate content, it is difficult to set up files one by one. : )


I have found a solution that may serve as a reference, Automatically set the '_path' through the 'content: file: beforeParse' hook

```
//@ts-nocheck

export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('content:file:beforeParse', (file) => {
    if (!/---[\s\S]*_path[\s\S]*---/.test(file.body)) {
      file.body = file.body.replace(
        /---/,
        '---'
          .concat('\n')
          .concat('_path: ')
          .concat(file._id.replace('content', '').split(':').join('/'))
      );
    }
  });
});
```
