### ISSUE TITLE
Generate parsed content during module boot in production

### ISSUE THREAD

**Issue by Atinux** [nuxt/content#1387]
Instead of adding the `/api/_content/cache` route in pre-render.

This way, Tailwind JIT (and others) will work.

**Comment by farnabaz** [comment]
AFAIK there is two way to achieve this goal:

1. Create a secondary build of Nuxt, generate parsed contents by calling nitro APIs, and move the caches to the main build.
  - I am not sure how we can do this, I tried to create a secondary build inside the module but couldn't make it. From my understanding Nuxt can only have one live context at the time and calling `kit.loadNuxt` inside the module will fail. Maybe @danielroe and @pi0 could help us on this

3.  Simulate parsing inside the module, resolve transformers, remark/rehype plugins ... and parse and store contents in the cache directory.
  - This way content hooks will not work (`beforeParse`, `afterParse`) and the generated parsed content will be wrong in these cases. (Nuxt Windicss uses these hooks)

WDYT @Atinux @pi0

**Comment by Atinux** [comment]
Can we at least, load all the raw files from the sources and store them? This way we can link to this directory for both dev and production, this is fine and faster as boot time and solve the CSS parsing issue for production for TailwindCSS

**Comment by pi0** [comment]
Can you please explain more specifically what information from raw sources is needed? I think in order for tailwind styles to be discovered, we need raw content sources (accessible from the build-context storage instance) and a simpler parser that can parse/extract a **list of components** and **used classes** from markdown files to be provided to jits such as tailwind..

**Comment by Atinux** [comment]
Basically we need the content from sources for TailwindCSS to analyse: https://github.com/nuxt/content/blob/main/src/module.ts#L548

The issue here is that the parsed content is available after the `nuxi build`

**Comment by pi0** [comment]
I see but I think unparsed markdowns pulled from storage sources should be also enough for a tailwind to match class usages right?

**Comment by farnabaz** [comment]
I think tailwind has some issues with extracting classes from markdown files.

/cc @Tahul

**Comment by Atinux** [comment]
Not it is working in dev, it's only because we don't have the content in production that is fails.

**Comment by farnabaz** [comment]
As I checked tailwind build happens before nitro create/init, therefore we can't use `nitro.storage` to fetch remote contents.

The solution is to create a storage instance in `before:build` hook, mount drivers, and fetch all contents and store them in cache dir.
