### ISSUE TITLE
`fetchContentNavigation()` composable with queryBuilder argument not work

### ISSUE THREAD

**Issue by Benbinbin** [nuxt/content#1399]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/content@2.1.0-27652015.55e99e4`
- Build Modules:    `-`

### Reproduction

https://github.com/Benbinbin/nuxt-content-fetchContentNavigation

### Describe the bug

After update to the Nuxt Content v2 module to latest edge version `@nuxt/content@2.1.0-27652015.55e99e4` the `fetchContentNavigation()` composable don't work for exectation with the queryBuilder arguments.

In [the minimal reporduction repo](https://github.com/Benbinbin/nuxt-content-fetchContentNavigation), I want to fetch the tree structure for the `sub-folder` and show it at home page with `<pre>` tag, **but it always show the tree structure for the `content`** 

```vue
<script setup lang="ts">
const queryBuilder = queryContent('sub-folder')
const { data: tree } = await useAsyncData('tree', () => fetchContentNavigation(queryBuilder))
console.log(tree)
</script>

<template>
  <main>
    <ContentDoc />
  </main>
  <pre>{{ tree }}</pre>
</template>
```

### Additional context

the `fetchContentNavigation()` composable just works fine [at `@nuxt/content@2.1.0`](https://github.com/Benbinbin/nuxt-content-fetchContentNavigation/tree/4470af354e4b8bdeb48a0e4e47a2cfa951579392) with queryBuilder arguments.

**Comment by Benbinbin** [comment]
maybe you can using the `where` to make it work

```js
const queryBuilder = queryContent().where({ _path: { $contains: '/article' } })
const { data: tree } = await useAsyncData('tree', () => fetchContentNavigation(queryBuilder))
console.log(tree)
```

**Comment by drusellers** [comment]
I'm currently running into this same issue. Oddly the addition of the where clause does assist in the matter.

Nuxt v3
Nuxt Content v2
node 16.13
