### ISSUE TITLE
ERROR  Rollup error:  Unexpected token (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by ktx-drashti** [nuxt/content#1422]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.6-27661960.60656df`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `nuxt-full-static@0.1.1`, `@nuxt/content@2.0.1`
- Build Modules:    `-`

### Reproduction

Repo - https://stackblitz.com/edit/github-p1mkc1?file=package.json

### Describe the bug

`@nuxt/content` not working with the latest version of `nuxt/framework` `3.0.0-rc.6-27664440.41d6f37`.

The error I am getting is:

```
ERROR  Rollup error:  Unexpected token (Note that you need plugins to import files that are not JavaScript)
 at error (node_modules/rollup/dist/es/shared/rollup.js:1888:30)
 at Module.error (node_modules/rollup/dist/es/shared/rollup.js:12442:16)
 at Module.tryParse (node_modules/rollup/dist/es/shared/rollup.js:12819:25)
 at Module.setSource (node_modules/rollup/dist/es/shared/rollup.js:12724:24)
 at ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/rollup.js:22166:20)
```

Reference Issue [#6](https://github.com/danielroe/nuxt-full-static/issues/6#issuecomment-1207813854)

**Comment by ktx-drashti** [comment]
How to use the latest version comment that includes the PR? As the new version is not released yet after the PR is merged.

**Comment by farnabaz** [comment]
You can find it here https://content.nuxtjs.org/guide/migration/edge-channel
