### ISSUE TITLE
Excerpt displaying

### ISSUE THREAD

**Issue by ipatate** [nuxt/content#1426]
Hello, i don't find how to display the excerpt on a list of articles.
```
 <div v-for="article in articles" :key="article._path">
      <h2>{{ article.title }}</h2>
      <ContentRenderer :value="article" :excerpt="true" />
    </div>
```
this code display all the content of page : 
<img width="648" alt="Screenshot 2022-08-08 at 15 35 31" src="https://user-images.githubusercontent.com/46760/183430726-3338290e-a471-442e-85aa-10f82e49214e.png">

Thanks for help 👍🏼

**Comment by Atinux** [comment]
Hey @ipatate 

Are you using `<!--more-->` in your content to create the excerpt?

If so we may have a bug @farnabaz

**Comment by ipatate** [comment]
More ? No.
where i should use  ?

I don't find things about "more" in doc.

PS : I talk about v2.

**Comment by farnabaz** [comment]
`<!--mode-->` is a delimiter that is used to determine excerpt paragraphs. You can simply add `<!--more-->` in any line of your content and by doing it above paragraphs will become part of the excerpt.

```
# title

First paragraph

Second paragraph

<!--more-->

Third paragraph. (not included in excerpt)
```

**Comment by ipatate** [comment]
Ah ok ! Thanks @farnabaz 
I understand now.

**Comment by ipatate** [comment]
It works, but i have always the H1 title. Maybe i can remove this tag with filter

**Comment by farnabaz** [comment]
If you don't want to have H1 tag, you can remove `# title` from your markdown and define content title in front matter

```
---
title: YOUR TITLE
---

First paragraph

Second paragraph

<!--more-->

Third paragraph. (not included in excerpt)
```

**Comment by ipatate** [comment]
ok thanks.
And so for get title in Layout, i try this but i think is not clean.
<img width="777" alt="Screenshot 2022-08-09 at 15 03 46" src="https://user-images.githubusercontent.com/46760/183654111-e9bda763-d183-4b99-9bd9-2f8da14f106e.png">

**Comment by ipatate** [comment]
You think it's possible to implement in a future a system for generate excerpt. A system with tags cleaning (H1, img,..) and keep only text ? with param number for length

**Comment by farnabaz** [comment]
It is possible to do this extraction. The module supports creating custom transformers to manipulate parsed contents. Unfortunately, transformers are not documented yet.

I'll ping in this issue once the documentation is updated 🙂

**Comment by ipatate** [comment]
yeah good news for the transformer ! thanks 🙏

**Comment by farnabaz** [comment]
Here are the docs:
- Excerpt: https://content.nuxtjs.org/guide/writing/markdown#excerpt
- Transformers: https://content.nuxtjs.org/api/advanced#transformers

**Comment by ipatate** [comment]
Nice ! thanks @farnabaz
