### ISSUE TITLE
Display 500 Cannot read properties of undefined (reading 'startsWith') message

### ISSUE THREAD

**Issue by prabeshmagar** [nuxt/content#1428]
### Environment

browser

### Reproduction

Visit doc url: 

https://content.nuxtjs.org/configuration/#markdown

### Describe the bug

500 error msg displayed 
![image](https://user-images.githubusercontent.com/53116461/183712678-56aaccbd-4c68-45df-b050-f3dacca05ec7.png)

**Comment by farnabaz** [comment]
This is fixed in the latest deploy 🙂
