### ISSUE TITLE
Rename `<Markdown>` to `<RichSlot>`

### ISSUE THREAD

**Issue by Atinux** [nuxt/content#1434]
### Is your feature request related to a problem? Please describe

Markdown is too confusing when creating a components library to be used in MDC but also outside in other Vue files.

### Describe the solution you'd like

- Renaming `<Markdown>` to `<RichSlot>`
- Creating `<Markdown>` as an alias of `<RichSlot>` + warning (or see with TS warning) about deprecation

**Comment by pi0** [comment]
By renaming, please also consider adding `Content` prefix to component names as `<ContentRichSlot>`, following module best practices.
