### ISSUE TITLE
Nested attributes are ignored

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt/content#1452]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `alias`, `nitro`, `ssr`, `meta`, `css`, `modules`, `watch`, `runtimeConfig`, `serverHandlers`, `storybook`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.1`, `@pinia/nuxt@0.4.0`, `./modules/storybook`, `./modules/graphql`, `nuxt3-runtime-compiler-module@1.0.4`, `@nuxt/content@2.0.1`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-fxpgdf?file=content/index.md

### Describe the bug

Given the following markdown content
```md
![Nuxt](https://nuxtjs.org/design-kit/colored-logo.svg){.h-6}
[![Nuxt](https://nuxtjs.org/design-kit/colored-logo.svg){.h-6}](https:test)
```
in the rendered html, the first image the class `h-6` is present, in the second not.

**Comment by ManasMadrecha** [comment]
The issue is you are using `a` inside `a` which is not allowed. 

----------

Nested attributes work properly. For example, this

```markdown
[[Hooray]{.text-red-100}]{.bg-pink-50}
```

gives this ast (as per https://content.nuxtjs.org/playground)

```json
{
        "type": "element",
        "tag": "p",
        "props": {},
        "children": [
          {
            "type": "element",
            "tag": "span",
            "props": {
              "class": "bg-pink-50"
            },
            "children": [
              {
                "type": "element",
                "tag": "span",
                "props": {
                  "class": "text-red-100"
                },
                "children": [
                  {
                    "type": "text",
                    "value": "Hooray"
                  }
                ]
              }
            ]
          }
        ]
      },
```
