### ISSUE TITLE
Content 2 and SSG - Problem with ContentList or wrong configuration?

### ISSUE THREAD

**Issue by kjanusz** [nuxt/content#1454]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `ssr`, `target`, `modules`, `content`
- Runtime Modules:  `@nuxt/content@2.1.0-27677352.6aad636`
- Build Modules:    `-`

### Reproduction

https://github.com/kjanusz/nuxt3-content2

### Describe the bug

I'm trying to build a new project with Nuxt Content 2 and SSG. 
According to documentation ([https://content.nuxtjs.org/guide/deploy/static-hosting#static-hosting](https://content.nuxtjs.org/guide/deploy/static-hosting#static-hosting)), this is possible (**prerendering**).

```ts
export default defineNuxtConfig({
  // static HTML generation (SSG)
  ssr: true,
  target: "static",
  modules: ['@nuxt/content'],
  content: {
    // https://content.nuxtjs.org/api/configuration
  },
})
```
After the run generate and preview, there is an endless loop (ContentList) on the overview page "/blog".
 
```sh
npm run generate
npm run preview
```
There are no problems at dev Build.

```sh
npm run dev
```
My index.vue

```vue
<template>
    <main>
        <ContentList path="/blog" v-slot="{ list }">
            <div v-for="post in list" :key="post._path">
                <h2>{{ post.title }}</h2>
                <p>{{ post.description }}</p>
                <nuxt-link :to="post._path">{{ post.title }}</nuxt-link>
                <pre>{{ path }}</pre>
            </div>
        </ContentList>
    </main>
</template>

<script setup lang="ts">
const { path } = useRoute();
</script>
```

Is my SSG configuration in nuxt.config.ts wrong? Or do I make a mistake in this regard (generate/preview)? Or bug?

### Additional context

Use of Edge Chanel for Content 2 has not brought any changes.

**Comment by farnabaz** [comment]
- Consider using edge channel to use lots of features and bug fixes
- There is a known issue with [`npx preview`](https://github.com/nuxt/content/issues/1281#issuecomment-1164579970), use `npx serve .output/public`

**Comment by kjanusz** [comment]
@farnabaz -  thanks 👍, I just tried the edge channel again and worked now (yesterday the bug was not fixed with the Edge channel)

After the error is fixed, I tested a little more. In the case of browser refresh (on /blog page after nuxt run preview), a following error/warning occurs in the browser console (the data is displayed):

```sh
Hydration completed but contains mismatches.
c @ entry.c7a9fd7c.js:1
mount @ entry.c7a9fd7c.js:1
t.mount @ entry.c7a9fd7c.js:1
Pl @ entry.c7a9fd7c.js:7
await in Pl (async)
(anonym) @ entry.c7a9fd7c.js:7
```
An idea where this comes from?
