### ISSUE TITLE
Cannot pass array as prop with MDC inline style

### ISSUE THREAD

**Issue by dylanmcgowan** [nuxt/content#1494]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.20.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.0`
- Package Manager:  `npm@8.19.0`
- Builder:          `vite`
- User Config:      `css`, `modules`, `content`, `vite`
- Runtime Modules:  `@nuxt/content@2.0.1`
- Build Modules:    `-`
------------------------------

### Reproduction

`/content/myfile.md`
```md
::my-component{arrayprop="['okey', 'dokey']"} 
```

### Describe the bug

Arrays cannot be passed as MDC inline props, they are received as strings to the component instead. It works as expected when using the verbose YAML syntax.

Is this behavior intended?

**Comment by farnabaz** [comment]
You need to add `:` before the prop name in order to evaluate it as JSON object.

```
::prop-inspector{:prop='["okey", "dokey"]'} 
::
```


[Demo](https://content.nuxtjs.org/playground/?content=::prop-inspector{:prop=%27[%22okey%22,+%22dokey%22]%27}+%0A::)
