### ISSUE TITLE
h2 and below tags getting converted into <a> links

### ISSUE THREAD

**Issue by RonaldLat** [nuxt/content#1506]
### Environment

npx nuxi

### Reproduction

 ---
    1 description: Why A Domain name matters more in 2021 than ever
      .
    2 img: dynamic.webp
    3 alt: web page illustration                                       4 tags:
    5   - web
    6   - digital-marketing
    7 ---                                                              8
    9 # Seven Reasons To Buy A Domain Name In 2021                    10 ## Seven Reasons To Buy A Domain Name In 2021                   11 # Seven Reasons To Buy A Domain Name In 2021                    12 # Seven Reasons To Buy A Domain Name In 2021
   13 # Seven Reasons To Buy A Domain Name In 2021
   
   19 ### 1. Increases brand awareness
   20
   21 ### 2. Search engine positioning
  
   
~

### Describe the bug

when I write any .md heading other than it gets converted into link, pre or code. 
On #h1/ heading 1 is working correctly.

**Comment by nobkd** [comment]
H2 to H4 automatically generate anchor links. You can override that behavior by using your own prose components.
See #1248 for context.

Example hX override file (replace X with 2 to 4):
```vue
<!--~/components/content/ProseHX.vue-->

<template>
  <hX><slot /></hX>
</template>
```

**Comment by NozomuIkuta** [comment]
#1495 is also worth checking to know another way to achieve your goal.

Refs:

- https://content.nuxtjs.org/api/components/prose
- https://content.nuxtjs.org/api/configuration/#tags

**Comment by RonaldLat** [comment]
Thanks for your help.

ronaldoti.com

**Comment by nobkd** [comment]
You can also set it through the anchorLinks option in the nuxt config: https://content.nuxtjs.org/api/configuration#anchorlinks
