### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'children')

### ISSUE THREAD

**Issue by ArthurDanjou** [nuxt/content#1509]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.11.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `srcDir`, `router`, `modules`, `css`, `components`, `content`, `colorMode`, `vite`
- Runtime Modules:  `@pinia/nuxt@0.4.2`, `nuxt-windicss@2.5.1`, `@nuxtjs/color-mode@3.1.4`, `@vueuse/nuxt@9.2.0`, `@nuxt/content@2.1.0`, `nuxt-icon@0.1.5`
- Build Modules:    `-`

### Reproduction

I think I don't understand how to fetch my page. For example, I want to write my uses page in markdown and import the page with nuxt content. The <ContentDoc path="uses" /> return an error in the console (see Log part)
  
  You can find the content page here : https://github.com/ArthurDanjou/artdanj-website-v2/blob/feature_content/src/content/uses.md 
  and the vue page which fetch the page : https://github.com/ArthurDanjou/artdanj-website-v2/blob/feature_content/src/pages/uses.vue

### Describe the bug

When I go to the uses page, the page isn't fetched and I can see the error written in log part in my console.

### Logs

```shell
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'children')
  at visit (./node_modules/unist-util-visit-parents/index.js:116:20)
  at visitParents (./node_modules/unist-util-visit-parents/index.js:65:30)
  at visit (./node_modules/unist-util-visit/index.js:44:7)
  at ./.nuxt/dev/index.mjs:342:5
```

**Comment by lucpotage** [comment]
I'm stuck with the same error and find it very cryptic. 😐

**Comment by lucpotage** [comment]
I have the same config as you and after removing and reintroducing  `nuxt-windicss` module, it worked again…

**Comment by ArthurDanjou** [comment]
> I have the same config as you and after removing and reintroducing `nuxt-windicss` module, it worked again…

I try the same method, and it works for me ! Thank you :)

**Comment by xrayian** [comment]
> > I have the same config as you and after removing and reintroducing `nuxt-windicss` module, it worked again…
> 
> I try the same method, and it works for me ! Thank you :)

Is this the proper solution ?
