### ISSUE TITLE
bug: support MDC in nested html elements

### ISSUE THREAD

**Issue by Lexpeartha** [nuxt/content#1511]
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `target`, `modules`, `colorMode`, `css`, `content`, `nitro`
- Runtime Modules:  `@nuxt/content@2.1.0`, `@nuxtjs/tailwindcss@5.3.3`, `@nuxtjs/color-mode@3.1.4`, `@vueuse/nuxt@9.1.1`, `nuxt-icon@0.1.5`
- Build Modules:    `-`
------------------------------
```

### Reproduction

Any markdown

### Describe the bug

Currently using document-driven mode, and when I have the following code:
```md
::AppButton{type="cta" icon="cib:linkedin" class="h-10"}
LinkedIn
::
::AppButton{type="cta" icon="cib:upwork" class="h-10"}
Upwork
::
```
it works fine

![working example](https://user-images.githubusercontent.com/43365376/189208313-273ba822-e884-4fe4-8620-b7365d2b05cf.png)

However after wrapping it in a div to apply more specific styling
```md
<div>
::AppButton{type="cta" icon="cib:linkedin" class="h-10"}
LinkedIn
::
::AppButton{type="cta" icon="cib:upwork" class="h-10"}
Upwork
::
</div>
```

Suddenly MDC doesn't recognize them as components

![broken example](https://user-images.githubusercontent.com/43365376/189208686-02579bf6-dbdb-4fcf-9635-f01eb7b939be.png)

### Additional context

I've come across this issue trying to add more specific way to style something. I know I can make a separate component for that in the `components/content` but I'm wondering if there's a better way to style something specific in MDC, since using `[]{.flex` around that cotnet seemed to break even more things.

Also not sure if MDC not working was supposed behavior, hence I opened this issue

**Comment by farnabaz** [comment]
You need to add an extra empty line before and after your HTML tags, this is the limitation of the remark HTML parser and it has nothing to do with MDC parser.

Just like this:
```
<div>

::AppButton{type="cta" icon="cib:linkedin" class="h-10"}
LinkedIn
::
::AppButton{type="cta" icon="cib:upwork" class="h-10"}
Upwork
::

</div>
```

Or you can use MDC syntax to create `div`

```
::div
::AppButton{type="cta" icon="cib:linkedin" class="h-10"}
LinkedIn
::
::AppButton{type="cta" icon="cib:upwork" class="h-10"}
Upwork
::
::
```
