### ISSUE TITLE
PRISM configuration does not exist

### ISSUE THREAD

**Issue by BroJenuel** [nuxt/content#1536]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Go to This page.
https://content.nuxtjs.org/configuration#markdownprismtheme
![image](https://user-images.githubusercontent.com/31676163/190901067-0f8669fc-47fd-484d-8866-8583e4b73eea.png)

### Describe the bug

it seems no Idea how to setup prism JS.

**Comment by farnabaz** [comment]
Prisms js is supported in Content V1 and you can find documentation here: https://content.nuxtjs.org/v1/getting-started/configuration#markdownprismtheme
If you use Content V2, Prism is no more supported and you can enable Shiki : https://content.nuxtjs.org/api/configuration#highlight

**Comment by BroJenuel** [comment]
I was able to understand this, here is the answer of a discussion https://github.com/nuxt/content/discussions/1534
