### ISSUE TITLE
Website is blinking

### ISSUE THREAD

**Issue by lucpotage** [nuxt/content#1544]
### Environment

Firefox 104.0.2

### Reproduction

https://user-images.githubusercontent.com/7230764/191355765-e3604af3-b403-4088-97c3-7fa01ae15d34.mp4

### Describe the bug

The website is blinking.

**Comment by farnabaz** [comment]
Does it happen in other browsers, or even in an incognito window? I've tested with the same version of firefox and it seems ok.

**Comment by lucpotage** [comment]
I cannot reproduce the issue anymore so I close it. 🤷‍♂️
