### ISSUE TITLE
Static Generation does not Work / does not crawl [...slug].vue pages

### ISSUE THREAD

**Issue by davidbernegger** [nuxt/content#1551]
### Environment

Nuxi 3.0.0-rc.11
RootDir: /home/projects/github-qfx8ch
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`, `ssr`
- Runtime Modules:  `@nuxt/content@2.1.1`
- Build Modules:    `-`
------------------------------

### Reproduction

Repo: https://stackblitz.com/edit/github-qfx8ch?file=dist 

### Describe the bug

Static Generation does not crawl [...slug].vue pages

- Open the [Stackblitz](https://stackblitz.com/github/nuxt/starter/tree/content) template or try it locally with the `npx nuxi init content-app -t content` template
- set ssr: true in nuxt.config.ts
- generate the website with "npm run generate"
- the index.vue gets rendered, but the about vue does not 

<img width="711" alt="image" src="https://user-images.githubusercontent.com/16232537/191945667-f533ad5c-5e9e-471e-b173-3fa01e5ba449.png">

If I build this, and upload it on any platform it generates this:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/16232537/191974783-677734b1-08a1-486b-9e4d-1a179216d4fe.png">

## Additional context

I was working on a personal page with this structure
![image](https://user-images.githubusercontent.com/16232537/191947013-177359a6-05f8-45d7-b0f7-448e63b814d0.png)

and would expect "blogpost1.md" and "blogpost2.md" to be generated with the crawler, but they are missing:
![image](https://user-images.githubusercontent.com/16232537/191947414-b6fc81dc-2964-4641-a184-d7a29cd1cea0.png)

even manually prerendering routes with `nitro.prerender.routes` would not render them correctly

**Comment by michaelvcolianna** [comment]
@davidbernegger If I change `ssr` to `true` or remove `ssr` from the config on the StackBlitz version, the `/about` is generated:

![Terminal output showing expected results of generation](https://user-images.githubusercontent.com/12972792/192160144-ea456a26-106a-4a27-9980-fd0787eae1c4.png)

The directory has the expected `index.html` and `_payload.js` file.

Is the repo for the personal page available?

**Comment by ManasMadrecha** [comment]
The crawler automatically picks up random links scattered anywhere only if they are actually used in the app somewhere. So, check whether some page (e.g., home) shows a list of all the linked posts, or else ensure each post is linked somehow to some page, or else create a sidebar navigation with list of all posts. Basically, ensure that each post's link is seen somewhere in the app.

**Comment by davidbernegger** [comment]
@michaelvcolianna, thanks for the answer! maybe it's my limited knowledge of the internal crawler, but why would the prerendering (npx nuxi generate) crawl different routes than the client-side only rendering (with ssr: true) - great to hear it works with the latter option tho :)

@ManasMadrecha - Thanks! I solved it now with a sitemap listing all the posts, appreciate it!  👍🏼 

closing this now as there is a workaround to this use case.

**Comment by nomadoda** [comment]
Possible workaround https://github.com/nuxt/nuxt/issues/13949#issuecomment-1438408078

**Comment by nomadoda** [comment]
> @michaelvcolianna, thanks for the answer! maybe it's my limited knowledge of the internal crawler, but why would the prerendering (npx nuxi generate) crawl different routes than the client-side only rendering (with ssr: true) - great to hear it works with the latter option tho :)
> 
> @ManasMadrecha - Thanks! I solved it now with a sitemap listing all the posts, appreciate it! 👍🏼
> 
> closing this now as there is a workaround to this use case.

I'm curious how you solved it using a sitemap. Do you mean a `sitemap.xml` file or was it added to the template?

**Comment by ManasMadrecha** [comment]
@nomadoda he must have meant a sitemap as in a simple page showing list of all the articles; not sitemap.xml.

**Comment by davidbernegger** [comment]
> I'm curious how you solved it using a sitemap. Do you mean a `sitemap.xml` file or was it added to the template?

Yeah @nomadoda, exactly how @ManasMadrecha described, but if you don't want to use a sitemap and want to prerender them via `generate` I have used this method to generate these routes explicitly: 

```js
// in nuxt.config.ts
import { globSync } from "glob" // using glob here but any package you are comfortable with works
const routes = globSync('./content/**/*.md')
    .map(path => path.slice(7, -3))
    
/* 
- the globSync function with the specified glob argument returns an array of all .md files
[  
    'content/index.md',
    'content/projects/pro2.md',
    'content/projects/pro1.md',
    'content/blog/post1.md',
    'content/blog/post2.md' 
]  
- we need to slice these routes a bit (remove the content / remove the .md ending) so we get this:
[                                                                                                         
  '/index',
  '/projects/pro2',
  '/projects/pro1',
  '/blog/sherg',
  '/blog/berg'
]
- now you either spread these routes into your existing prerender array or define it. 
*/

export default defineNuxtConfig({
    nitro: {
        prerender: {
            routes: ['/sitemap.xml', '/rss.xml', ...routes]
        }
    }
})
```

**Comment by vampirefan** [comment]
Thanks a lot for the solution!! @davidbernegger  
Here's a little improvement for generating the routes:
```
import { globSync } from "glob" 
const routes = globSync('./content/**/*.md')
    .map(path => path.slice(7, -3).replace(/\d+\./g, '').replace(/\\/g, '/')
```

**Comment by mathijsfr** [comment]
Unfortunately this doesn't work with yarn build. I have a website with a dashboard. Preferably I use ssr: false for my dashboard and prerender all the landing pages and the blogs. For example:

```
export default defineNuxtConfig({
    components: true,
    ssr: false,
    content: {
        experimental: {
            clientDb: true
        }
    },
    nitro: {
        prerender: {
            routes: ['/sitemap.xml', ...landingPageRoutes, ...blogPageRoutes]
        }
    }

})
```

The above nuxt config doesn't work with yarn build. The blog pages can't be found after deploying. It can be found on a local production build for some reason. I hardcoded all the blog and landing page routes at the moment for testing purposes.

Using route rules like so also doesn't work: 

```
routeRules: {
    '/**': { ssr: false },
    '/blog/**': { ssr: true },
    '/blogs/**': { ssr: true }
}
```

According to the documentation, yarn generate doesn't work when hybrid rendering. https://nuxt.com/docs/guide/concepts/rendering

**Comment by ingmarcur** [comment]
adding 
ssr:false,
target:static

to nuxt.config.ts worked for me
