### ISSUE TITLE
ContentNavigation doesn't seem to use the :query ?

### ISSUE THREAD

**Issue by mathieunicolas** [nuxt/content#1558]
### Environment

Nuxi 3.0.0-rc.11                                                      01:01:15
RootDir: /Users/mathieu/nsinuxt                                       01:01:15
Nuxt project info: (copied to clipboard)                              01:01:15

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.9.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

in pages/[...slug].vue : 

```
<template>
  <div>
    <ContentNavigation v-slot="{ navigation }" :query="querpath">
      <NuxtLayout :navigation="navigation">
        <div class="basis-1/2 shrink grow"><ContentDoc /></div>
      </NuxtLayout>
    </ContentNavigation>
  </div>
</template>

<script setup>
const querpath = queryContent('snt');
</script>
```

### Describe the bug

I want to generate a nav sidebar where I only load the files which are in the same folder as the current page. For this example, I hardcoded "snt" but first I used useRoute() to get the path, then split & concat to get only the first element of the path (in the content folder, there's two folders : snt and nsi)
So I get this ContentNavigation from the catch-all route, then I pass it to the layout, and the layout passes it to the nav sidebar component.

It looks like the ContentNavigation component returns in the navigation variable the tree from the root of the content folder, without taking my "snt" query param.

Maybe my call to ContentNavigation from the catch-all route is not a good practice ?

### Additional context

<img width="292" alt="Screenshot 2022-09-27 at 01 06 25" src="https://user-images.githubusercontent.com/65437872/192396139-70397a5e-e624-4511-9b14-eb460c3b4b89.png">

^ From the "localhost:3000/snt" URL ^

I tried the same code directly in the nav sidebar component, and I get the same result : navigation from the root of the content folder.

**Comment by farnabaz** [comment]
Could you provide your example in a simple reproduction using https://stackblitz.com/github/nuxt/starter/tree/content?

**Comment by farnabaz** [comment]
I see, this happens because the argument of `queryContent` affects only when you use `find/findeOne`.

To use query builder for navigation you can manually use where 
```ts
queryContent().where({ _path: /^\/snt/ })
```

**Comment by mathieunicolas** [comment]
Okaaaay it works ! Thanks A LOT, I'm so happy thanks to you I understand how it works now !!

**Comment by mathieunicolas** [comment]
I reopen to ask you one more thing : is it better to use only one ContentNavigation in my app, and process the data to use it in one component or in another, or is it ok to use more than one ContentNavigation ?

For example, in my header, I'd like to get all the root folders.
In the navbar, I'd like to get the files in the current folder.
Maybe in another component, I'd like to get all the files matching one specific criteria.

Is it, or not, a good practice to call three different ContentNavigation with different parameters, all loaded in my Nuxt app ?

**Comment by farnabaz** [comment]
Calling ContentNavigation with different params result three different API calls and more CPU consume in server-side, If you are building static(pre-rendered) website all of these API calls will be pre-rendered and stored as a JSON file in the `dist` directory. The only overheead in pre-render mode is multiple http call for receiving these files.

Based on this details, if you want to reduce http requests you can use single API call and filter them in your components. If you don't care about couple of more http requests feel free to use ContentNavigation as you like.
