### ISSUE TITLE
How to $content(route.path) in asyncData ?

### ISSUE THREAD

**Issue by ApolloNet** [nuxt/content#156]
Hi Nuxt commuity,

I am trying to load some content from a markdown file at `/content/events/an-event.md` through a template file at `/pages/events/_slug.vue` that has the code below:

```
<template>
  <div>
    <h1>{{ content.title }}</h1>
    <nuxt-content :document="content" />
  </div>
</template>

<script>
export default {
  async asyncData({ route, $content }) {
    return {
      content: await $content(route.path).fetch()
    }
  }
}
</script>
```

When I load the URL through a `<nuxt-link>`, I got an **"Error: not found"** :-/  
But no problem when I load the page from the URL.

It seems that `route` is not available in `$content(route.path).fetch()`...  
If a replace that code with `$content('/events/an-event').fetch()`, everything is fine.

Nuxt is configured with the mode Universal and here is the `generate` entry:

```
generate: {
    async routes() {
      const { $content } = require('@nuxt/content')
      const files = await $content('', { deep: true }).fetch()
      return files.map((file) => (file.path === '/index' ? '/' : file.path))
    }
  }
```

What am I doing wrong ?

**Comment by benjamincanac** [comment]
Hey @ApolloNet,

You could use the `slug` to get your content as your pages and content tree are not related:

```vue
<script>
export default {
  async asyncData({ params, $content }) {
    return {
      content: await $content('events', params.slug).fetch()
    }
  }
}
</script>
```

**Comment by ApolloNet** [comment]
I don't understand why but it works!

Many thanks @benjamincanac
