### ISSUE TITLE
<ContentList> path prop overrides query

### ISSUE THREAD

**Issue by xSuffix** [nuxt/content#1570]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `pnpm@7.3.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-uk9ctc?file=app.vue

### Describe the bug

\<ContentList\> has two props: `path` and `query`. The [documentation](https://content.nuxtjs.org/api/components/content-list) suggests that both can be used individually to set the path.

Using `path`:
```vue
<template>
  <ContentList path="/articles" v-slot="{ list }">
    <!-- ... -->
  </ContentList>
</template>
``` 

Using `query`:
```vue
<script setup lang="ts">
import type { QueryBuilderParams } from '@nuxt/content/dist/runtime/types'
const query: QueryBuilderParams = { path: '/articles', limit: 5 }
</script>

<template>
  <ContentList :query="query" v-slot="{ list }">
    <!-- ... -->
  </ContentList>
</template>
```

Both examples can be found in the documentation in similar form. However, the example using `query` doesn't work because `path` has a default value of '/' and overrides `query` as seen in the [source code](https://github.com/nuxt/content/blob/main/src/runtime/components/ContentList.vue):

```typescript
// Merge local `path` props and apply `findOne` query default.
const contentQueryProps = Object.assign(query || {}, { path })
```

I see multiple solutions to this:
1. Make it clear that this doesn't work in the documentation by adding an additional `path` prop in the second example.
2. Override `path` using `query` by swapping the order of the values. This will lead to `query` having a higher priority when both props are set:
```typescript
const contentQueryProps = Object.assign({ path }, query || {})
```
3. Give `path` a default value of undefined and only if neither `path` nor `query` is set, change it to '/' in the script. This way the `path` prop can have a higher priority while not overriding `query` if it is not set. However, the implementation might be slightly less clean / more complicated than the second solution.

I'm happy to make a PR if you agree that this is an issue and decide for one of the solutions.

**Comment by Jursdotme** [comment]
Giving query higher priority would be an obvious fix, but it seems strange from a specificity perspective. But giving query priority unless path is explicitly declared would be prefered i think.
