### ISSUE TITLE
How am I supposed to pass multiple props to a MDC component ?

### ISSUE THREAD

**Issue by mathieunicolas** [nuxt/content#1573]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.9.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.19.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

const props = defineProps({
  type: {
    type: String,
    default: '',
  },

});

### Describe the bug

My `admo.vue` in `components/content/` contains this script field :

```
<script setup lang="ts">
const props = defineProps({
  type: {
    type: String,
    default: '',
  },
  titre: {
    type: String,
    default: '',
  },
});
</script>
```

I can't understand how I'm supposed to call it.

::admo{ type="test", titre="coucou" }
blablabla
::

This example is simply not parsed by the parser. These 3 lines are displayed as-is (in a single line) in the rendered page.
I've spent hours today trying everything, looking for examples I didn't found. I tried to look in the Prose components but nothing, I even tried to reverse engineer the MDC Visual Code extension since it's the only thing that comes up when using a search engine.

### Additional context

I think the examples and doc could be more explicit, this MDC syntax looks like something new in this world. I would be glad to add examples to the doc when I understand how it works :smile: 

Thanks !

**Comment by mathieunicolas** [comment]
I really spent hours on this one. Like, getting mad and everything.
5 minutes after finally posting this issue, I try deleting the comma between my props, and it worked like a charm.

I can't believe I lost so much time on this...

**Comment by Atinux** [comment]
How can we improve the DX of this @farnabaz ?

**Comment by mathieunicolas** [comment]
> How can we improve the DX of this @farnabaz ?

I must admit, once I know how it works it's pretty clear. 
It could be inspired by the code blocks syntax, but since the length of the props list can be anything between 0 and many it's not handy. 

I think I was confused because I was switching between the javascript JSON style and the HTML attributes written between { }
