### ISSUE TITLE
Latest version conflicts with documentation (remark plugins)

### ISSUE THREAD

**Issue by jhull** [nuxt/content#158]
Running 1.3.2 and tried forever to get this to work:

```
  content: {
    markdown: {
      remarkPlugins: ['remark-container']
    }
  }
```

but then noticed the `V2.0.0` in the docs...

switched to this:

```
  content: {
    markdown: {
      plugins: ['remark-container']
    }
  }
```
and plugin works...

**Comment by benjamincanac** [comment]
Hey @jhull,

Indeed I published the docs before the v2.0.0 release, my bad!

**Comment by wemod123** [comment]
I got same issue, very confused on how to config the plugins

@benjamincanac  when will be next release as your estimation?

**Comment by mathe42** [comment]
You can use the new Features by installing this repro to your dependencies:


`yarn add https://github.com/nuxt/content.git`
