### ISSUE TITLE
Navigation is null on pages

### ISSUE THREAD

**Issue by oripka** [nuxt/content#1585]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.9.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@3.2.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I am using partially document driven mode but also want to include some `pages/` with the same layout. When navigating to a document driven page the navigation is available via useContent.

Code in `Nav.vue`

```
const { navigation } = useContent()
const hasNavigation = computed(() => navigation.value)
```

The navigation is fine for pages that a generated by document driven mode. However, when navigating to a page like this one `pages/test.vue` `navigation.value` is undefined.

```
[...]
<script setup>
definePageMeta({
  documentDriven: false,
  middleware: 'auth'
})
[...]
```
Looking at the code and documentation I found that I can call directly `fetchContentNavigation`. Changing the `Navbar.vue` code to following works also for `pages`.

```
const { data: navigation } = await useAsyncData('navigation', () => fetchContentNavigation())
const hasNavigation = computed(() => navigation?.value)
```

### Describe the bug

I am not sure if this is desired behavior. Looking at the nuxt3/content docs repositories I can't find any example where somebody uses `content` and `pages` with a shared navigation. Any hints?

**Comment by farnabaz** [comment]
If you want to use navigation in your custom pages, you  should not disable document driven entirely. Instead you can disable `page` and `surround`  fetching in document driven and keep navigation enabled. See: https://content.nuxtjs.org/guide/writing/document-driven#disable-or-control-the-page-data


```html
<script setup lang="ts">
definePageMeta({
  documentDriven: {
    page: false, // disable page fetching
    surround: false, // disable surround fetching
    
    navigation: true // keep navigation enabled,  NOTE: this is default value, you can omit this line
  }
})
</script>
```

**Comment by oripka** [comment]
Thanks, this works!
