### ISSUE TITLE
require('@nuxt/content') dependencies not found

### ISSUE THREAD

**Issue by jbnv** [nuxt/content#159]
I'm not sure if this is an actual bug, which is why I'm reporting it as a question instead of a bug. 

[Advanced > Programmatic Usage](https://content.nuxtjs.org/advanced#programmatic-usage) gives the impression that `require('@nuxt/content')` can be used to supply `$content` in arbitrary contexts (i.e. outside of a component's `this` context).

I want to write refactor certain functionality into functions that can hit the content and return extended content on various items. Here is a practical example:

```
import * as R from 'ramda';

export const expand = R.pipe(
	taxons => {
		if (taxons === null || taxons === undefined) return [];
		if (taxons.constructor === String || taxons instanceof String) return [[taxons]];
		// &c
	},
	R.assoc('pairs', R.__, {}),
	o => R.assoc('keys', o.map(R.prop(1)), o),
	o => {
		return require('@nuxt/content').$content('taxons').where({ title: { $in: o.keys }}).fetch();
	},
);
```

However, with this implemented in my project, it throws an error on compile:

```
These dependencies were not found:
* fs in ./node_modules/@nuxt/content/lib/index.js, ./node_modules/@nuxt/content/node_modules/mkdirp/lib/opts-arg.js and 4 others
* net in ./node_modules/node-req/index.js  
```

So, is this a bug that needs to be fixed, or am I using `require('@nuxt/content')` incorrectly? If this is not a bug, is there a way that I can access `$content` outside of a component context?

**Comment by jbnv** [comment]
Additional information: This is still causing my compilation to fail, but now it's a failure to parse `fsevents.node`. Here's the stack trace:
```
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

 @ ./node_modules/fsevents/fsevents.js 13:15-41
 @ ./node_modules/chokidar/lib/fsevents-handler.js
 @ ./node_modules/chokidar/index.js
 @ ./node_modules/@nuxt/content/lib/database.js
 @ ./node_modules/@nuxt/content/lib/index.js
 @ ./api/characters.js // the code that calls require('@nuxt/content')
```

**Comment by jbnv** [comment]
Update: I realized that I might be able to resolve this one myself by adding `node-loader` and a Webpack rule for `/\.node$/`. That did in fact overcome the problem. But I shouldn't have to add dependencies to my project to fix something that should already be working. I would appreciate an explanation of how this is something I need to resolve myself.

**Comment by benjamincanac** [comment]
@jbnv You seem to use `@nuxt/content` outside of a Nuxt.js application which is not possible, the module needs to be loaded before doing the `const { $content } = require('@nuxt/content')` otherwise `$content` won't exist, see the [documentation](https://content.nuxtjs.org/advanced#programmatic-usage).

However, what you can try to do is access the Database class from `@nuxt/content` and instantiate yourself so you can use the query builder. You will have to specify the options yourself.

```js
const { Database } = require('@nuxt/content')

const database = new Database(options)

await database.query()...
```

You can check the `database.js` file to see the options required: https://github.com/nuxt/content/blob/dev/lib/database.js#L20.

**Comment by jbnv** [comment]
What makes you think I'm using @nuxt/content ourside of a Nuxt.js application?

**Comment by benjamincanac** [comment]
@jbnv Could you provide a reproduction link so I can understand better?

**Comment by luksak** [comment]
I am trying to use this in a vuex store and I get those errors. How could I access data from @nuxt/content in vuex?
