### ISSUE TITLE
Extend MongoDB "where" syntax to support custom function

### ISSUE THREAD

**Issue by fanckush** [nuxt/content#1592]
I have no idea if this possible to implement but here goes.

simply said, instead of doing this
``` ts
const articles = await queryContent('articles').where({ age: { $gt: 18 } }).find()
```
I want to be able to do
``` ts
const articles = await queryContent('articles').where({ age: (v) => v > 18 }).find()

```

## why?
because
1. I have to memorize `$gt` and `$contains` (since I don't use mongo)
2. more importantly, `$gt` is not type safe, I don't get intellisense 
3. a function checker makes it way more flexible to do crazy checks like `age: checkIsEven`  

### Additional context
This is not a major issue, the alternative is to either use the current MongoDB syntax or to manually filter the results with standard js if the `where` behaviour is complex.
If this behaviour goes against some standard that nuxt content is trying to follow (namely: strictly following mongoDB syntax) then we can close this issue

**Comment by Atinux** [comment]
Well the hard part here it that the function has to be serialised to be given to the API in order to be executed, this is why we don't support functions in the query object.
