### ISSUE TITLE
nuxt v3's SSG & ContentDoc with slot

### ISSUE THREAD

**Issue by fabon-f** [nuxt/content#1594]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/content@2.1.1`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-zqhzee

`pages/[...slug].vue` is the sample code of [ContentDoc official document](https://content.nuxtjs.org/api/components/content-doc#slots).

Run `npm run generate && npm run preview`, then access `/about` directly in browser.

### Describe the bug

The page shows like this, but the content of `about.md` is only `About Content v2` and `back home`, and the content of `index.md` pollutes the page.

![screenshot 2022-10-11 9 56 25](https://user-images.githubusercontent.com/8928378/194974351-25b59ad7-24eb-4557-846f-2ac9df99eeb3.png)

**Comment by farnabaz** [comment]
Seems that this happens because you have multiple root element within slot.
Try adding a wrapper `div` around slots and test

```html
<ContentDoc v-slot="{ doc }">
      <article>
        <h1>{{ doc.title }}</h1>
        <ContentRenderer :value="doc" />
      </article>
    </ContentDoc>
```

**Comment by gustawdaniel** [comment]
was ContentDoc removed from @nuxt/content v3?

https://content.nuxt.com/api/components/content-doc#slots

**Comment by gustawdaniel** [comment]
I found:

> All content should be rendered using <ContentRenderer> component. <ContentDoc>, <ContentList>, <ContentNavigation> and <ContentQuery> components are dropped in v3.

https://content.nuxt.com/docs/getting-started/migration
