### ISSUE TITLE
Allow adding new languages to shiki

### ISSUE THREAD

**Issue by Demivan** [nuxt/content#1595]
### Is your feature request related to a problem? Please describe
I was trying to add support syntax highlighting for custom language. I have `tmLanguage.json` file but no way to configure `lang` option for shiki properly. `preload` option almost works but:
https://github.com/nuxt/content/blob/5d29a377e9710343bb1770282a577b4fd6e35d3b/src/runtime/server/api/highlight.ts#L16-L17
only checks for built-in languages.

### Describe the solution you'd like
Either allow custom languages in `resolveLang` function or allow to replace `getHighlighter` function.

### Describe alternatives you've considered
No real alternative for this except reimplementing `server/api/highlight.ts`

**Comment by Atinux** [comment]
What about if we expose a hook for the shiki `content:shiki:resolveLang`, would that work @farnabaz ?

**Comment by Demivan** [comment]
The most flexible way would be to allow replacing the highlighter. Nuxt 2 Content had `getHighlighter` exposed.

**Comment by farnabaz** [comment]
@atinux We can expose this hook, but it will be available in nitro context inside a nitro plugin.

**Comment by farnabaz** [comment]
@Demivan what does happen when you add your custom language to `preload` options? We can update `resolveLang` to support custom languages.

**Comment by Demivan** [comment]
@farnabaz Nothing happens because of this check: 
https://github.com/nuxt/content/blob/5d29a377e9710343bb1770282a577b4fd6e35d3b/src/runtime/server/api/highlight.ts#L93-L96
For my case it is enough for `resolveLang` to support custom languages.

**Comment by jonko0493** [comment]
Just leaving a +1 to this issue; being able to resolve custom languages would help me out a lot (trying to highlight ARM & PowerPC assembly while `asm` is for x86_64 asm).
