### ISSUE TITLE
'/api/' path should be configurable

### ISSUE THREAD

**Issue by rikzwarthoff** [nuxt/content#1596]
### The problem
In my case i'm already running an API at the` /api/'`path so this conflicts. Currently the config only allows for editing the base path` /api/${options.base}/`

### Solution
I would make `options.base`include the '/api/', so the default would be ` /api/_content/`. This should also function in combination with the `options.sources `

### Other solution
Other options would be to have a separate config option for the `/api/` part.

**Comment by Atinux** [comment]
What do you mean you are having an API on `/api` ? You are leveraging a proxy?

**Comment by rikzwarthoff** [comment]
> What do you mean you are having an API on `/api` ? You are leveraging a proxy?

No on the domain where the app will be hosted there is an API running at `/api/`, different application entirely. This means that `/api/_content` is unreachable for the Nuxt app. So I want to move the content api to something like `/content-api/`.

I'm using static by the way

**Comment by Atinux** [comment]
What do you think about this @farnabaz ?

**Comment by manniL** [comment]
I second this idea. Especially when using proxy + target rewrites, `api` is a very common path. Rewriting the calls to Nuxt content unintentionally leads to issues.

**Comment by farnabaz** [comment]
We can deprecate [`base`](https://github.com/nuxt/content/blob/558add0cf6739bcab737e90a9f80fad254157274/src/module.ts#L44-L49) option and introduce new option.

**Comment by Atinux** [comment]
I would anyway recommend to proxy on another route than `/api` as best practices since Nuxt `server/api/` is already matching to `/api`.

But happy to chance the base option.

**Comment by rikzwarthoff** [comment]
I agree, i would rather proxy elsewhere, but we may not always have that choice
