### ISSUE TITLE
FATAL ERROR: Error: EMFILE: too many open files, open 'C:\dev\delme\nuxt01\content\post\entry8369.md'  

### ISSUE THREAD

**Issue by soongsta** [nuxt/content#160]
### Version
@nuxt/content: 1.3.2
nuxt: 2.13.0

### Reproduction Link

https://github.com/soongsta/nuxt-maxed-out

### Steps to reproduce

git clone repo

or

1. npx create-nuxt-app nuxt01
2. cd nuxt01
3. create 10,000 dummy MD files in content/post folder
4. npm run dev

### What is Expected?

Project should run without opening all the files

### What is actually happening?

Error: EMFILE: too many open files, open 'C:\dev\delme\nuxt01\content\post\entry8369.md'

**Comment by benjamincanac** [comment]
Hey @soongsta,

Are you on Windows?

I can't reproduce this error on Mac OS.

**Comment by soongsta** [comment]
@benjamincanac I tried on my macbook air laptop with 8GB, same issue. I actually had to delete about 4000 posts to make it work. So I am wondering if this is a limitation based on available RAM
