### ISSUE TITLE
Some css bind to <nuxt-content> do not work

### ISSUE THREAD

**Issue by amotarao** [nuxt/content#161]
### Version
@nuxt/content: v1.3.2
nuxt: v2.13.0

### Reproduction Link

https://codesandbox.io/s/nuxtcontent-demo-6vkd2?file=/pages/_slug.vue

### Steps to reproduce
- go to https://codesandbox.io/s/nuxtcontent-demo-6vkd2?file=/pages/_slug.vue
- view browser

#### :smile: string
```vue
<nuxt-content class="large"/>
↓
<div class="large nuxt-content">
```

#### :pleading_face: array
```vue
<nuxt-content :class="['large', 'red']"/>
↓
<div class="0 1 nuxt-content">
```

#### :pleading_face: css modules
```vue
<nuxt-content :class="$style.underline"/>
↓
<div class="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 nuxt-content">
```

#### :smile: object
```vue
<nuxt-content :class="{ [$style.underline]: true }"/>
↓
<div class="nuxt-content underline_3Zble">
```

### What is actually happening?

All css bind can work.

**Comment by benjamincanac** [comment]
Hey @amotarao,

This bug has been fixed, you can check it out by using @nuxt/content from GitHub directly in your package.json:

```json
{
  "dependencies": {
    "@nuxt/content": "nuxt/content"
  }
}
```

It should be available when we release the next version.

**Comment by amotarao** [comment]
@benjamincanac 
I confirmed it was fixed.
Thank you very much!
