### ISSUE TITLE
Nuxt content doesn't display images located in the /assets directory

### ISSUE THREAD

**Issue by remiconnesson** [nuxt/content#1610]
### Environment

The environment is the one provided by the doc here : https://codesandbox.io/s/github/nuxt/starter/tree/content

### Reproduction

https://codesandbox.io/s/new-glitter-3ngl2g?file=/content/index.md

### Describe the bug

Nuxt content doesn't display images located in the `/assets` directory as it should based on the [nuxt3 documentation.](https://v3.nuxtjs.org/getting-started/assets/)

It does display images located in the `/public` though.

**Comment by Atinux** [comment]
It's because Nuxt Content does not go through Vite or Webpack.

You have to put your images in the `public/` directory.
