### ISSUE TITLE
Add `_dir` field

### ISSUE THREAD

**Issue by Atinux** [nuxt/content#1611]
This is quite useful to know in which directory this file is in and I believe we had it in Nuxt Content v1.

This could be done with a Nitro plugin so far:

```ts
export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('content:file:afterParse', (file) => {
    if (file._id.endsWith('.md')) {
      file._dir = file._path.split('/').slice(-2)[0]
    }
  })
})
```

What do you think @farnabaz ?

**Comment by farnabaz** [comment]
Sounds good to me to have `_dir` field in parsed contents.
Instead of having separate hook for it we can add it directly into `path-meta` transformer https://github.com/nuxt/content/blob/main/src/runtime/transformers/path-meta.ts

**Comment by Atinux** [comment]
You have my green light to add it before next release
