### ISSUE TITLE
Timeout error when passing twitter card validator

### ISSUE THREAD

**Issue by jualoppaz** [nuxt/content#162]
### Version
@nuxt/content: ^1.3.2
nuxt: ^2.12.X

### Environment
node/npm:
- 10.15.3 / 6.4.1
- 12.18.1 / 6.14.5

cloud system: Heroku

### Config
mode: 'universal'

### Steps to reproduce

1. Go to **https://cards-dev.twitter.com/validator**
2. Type a nuxt application web url
3. Click **preview card** button

### What is Expected?

Card preview is displayed with detected info as possible.

First example with an own application with nuxt
![1 - twitter validation SUCCESS - empty](https://user-images.githubusercontent.com/5088244/85162380-8f103f80-b261-11ea-8f1c-9841df0bc230.JPG)

http://www.anhqv-stats.es
https://github.com/jualoppaz/anhqv-stats-front

Second example with a simple autogenerated nuxt application without @nuxt/content
![2 - twitter validation SUCCESS - with data](https://user-images.githubusercontent.com/5088244/85162383-8fa8d600-b261-11ea-8b44-9539ee7f0419.JPG)

http://nuxt-demo-jmlp.herokuapp.com/
https://github.com/jualoppaz/nuxt-demo-jmlp

### What is actually happening?

Twitter validator is returning a timeout error.

Third example with a nuxt application with @nuxt/content
![3 - twitter validation ERROR](https://user-images.githubusercontent.com/5088244/85162635-fe862f00-b261-11ea-8dba-02e89f9d9ac2.JPG)

http://blog.juanmanuellopezpazos.es/
https://github.com/jualoppaz/blog

As this error appears, the twitter card will never work.

**IMPORTANT**

- I also tried to add @nuxt/content to http://nuxt-demo-jmlp.herokuapp.com/ and then the timeout error appeared.
- Googlebot or Facebook crawler can access to previous web applications in all cases. I suppose that Twitter card validator performs  the request in different way like others

**Comment by benjamincanac** [comment]
@jualoppaz This doesn't seem to be a bug related to @nuxt/content but with your application.

If however it is really a bug, please provide a reproduction with the source of the problem.

**Comment by jualoppaz** [comment]
Hi @benjamincanac !

I supposed also that could be an error in my nuxt app. However, I created a new app with ```npx create-nuxt-app```` command and I deployed it to Heroku.

You can get this app working here:

- http://nuxt-demo-jmlp.herokuapp.com
- https://github.com/jualoppaz/nuxt-demo-jmlp

For better comprehension I have just deployed another boilerplate app with @nuxt/content configured:

- http://nuxt-demo-jmlp-with-content.herokuapp.com/
- https://github.com/jualoppaz/nuxt-demo-jmlp-with-content

If you try twitter card validator with the first web application you'll see that Twitter bot could access to the page but didn't found  any meta tag info.

![1 - twitter validation SUCCESS - empty](https://user-images.githubusercontent.com/5088244/85862519-2aedfe00-b7c2-11ea-8af7-704f80b74959.JPG)

However, if you try do the same with the last app you'll get the mentioned error with time out.

![4 - twitter validation ERROR nuxt-content](https://user-images.githubusercontent.com/5088244/85862522-2b869480-b7c2-11ea-9ed3-499f8c86f40d.JPG)

After that, we can guess that this error is not caused by a code error. This error is produced only with adding @nuxt/content module in nuxt.config.js file.

I though debugging @nuxt/content with messages in the server as it seems to Twitter card validator requests to be not resolved in @nuxt/content middleware or similar stage.

I'm trying to load @nuxt/content as a project module for debug middleware in a production environment. If I guess something I'll report here.

Thank you for your time.

**Comment by benjamincanac** [comment]
@jualoppaz Okay so just adding @nuxt/content as a module seems to cause this error.

I'll reopen this issue and investigate asap. If you find any lead don't mind posting it here!

**Comment by Tahul** [comment]
I'm pretty sure this won't be an issue in @nuxt/content v2.

If anyone wants to investigate further for v1, please feel free to re-open?
