### ISSUE TITLE
[Error] WebSocket connection to 'ws://[::]:4000/ws' failed

### ISSUE THREAD

**Issue by ahoiroman** [nuxt/content#1622]
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `experimental`, `build`, `buildModules`, `modules`, `publicRuntimeConfig`, `privateRuntimeConfig`, `globalName`, `app`, `intlify`, `http`, `proxy`, `auth`, `tailwindcss`, `googleFonts`, `content`
- Runtime Modules:  `@nuxtjs-alt/auth@2.0.20`, `@nuxtjs-alt/http@1.3.18`, `@nuxtjs-alt/proxy@1.3.5`, `@nuxt/content@2.2.0`, `@nuxtjs/tailwindcss@5.3.5`, `@nuxtjs/google-fonts@3.0.0-0`, `@intlify/nuxt3@0.2.4`, `@pinia/nuxt@0.4.3`
- Build Modules:    `@intlify/nuxt3@0.2.4`
```

### Reproduction

Install Nuxt with nuxt/content on macOS using watcher.

### Describe the bug

After upgrading to https://github.com/nuxt/content/releases/tag/v2.2.0 I mentioned errors in dev mode on my Mac:

```
[Error] WebSocket connection to 'ws://[::]:4000/ws' failed: The Internet connection appears to be offline.
```

<img width="674" alt="Bildschirmfoto 2022-10-19 um 23 Uhr 16 Minuten und 41 Sekunden@2x" src="https://user-images.githubusercontent.com/23051150/196807363-6d85f5c8-4fea-4317-a1a6-71d5bac2ba41.png">

At first I thought it was about the recent update to Nuxt3-rc12 (https://github.com/nuxt/framework/issues/8330), but it turned out that if I disable content watcher like this:

```
    content: {
        base: '/_content',
        watch: false
    }
```

the problem does no longer appear.

### Additional context

The port itself seems open:

```
nmap -6 ::1 -Pn -p 4000
Starting Nmap 7.93 ( https://nmap.org ) at 2022-10-19 23:21 CEST
Nmap scan report for localhost (::1)
Host is up (0.00027s latency).

PORT     STATE SERVICE
4000/tcp open  remoteanything
```

And there is listening something on that port:

```
lsof -i tcp:4000
COMMAND   PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node    18648 ahoiroman   44u  IPv6 0x2fa1d5696f4b9643      0t0  TCP *:terabase (LISTEN)
```

**Comment by ahoiroman** [comment]
Update: Seems to affect Safari on macOS only. Using Brave or Firefox this issue is gone. The issue does appear on two different Macs, so caching etc. shouldn't be the problem.

**Comment by ahoiroman** [comment]
```
    content: {
        watch: {
            ws: {
                hostname: 'localhost'
            }
        }
    }
```

seems to be a workaround, which fixes the problem in Safari. But it would still be nice to have a better solution.

**Comment by OTTIN-T** [comment]
> 

Same error here but with nuxt version 3.0.0-rc.11. It's the transition to version 2.2 of the nuxt/content that seems to be the origin (no problem under version 2.1.1).
The workaround works for me too.

**Comment by Suniron** [comment]
Same error since i switched from Nuxt 3 `RC 10` to `RC 12` yesterday.

**Comment by Minecraftschurli** [comment]
Also affects OperaGX on Windows

**Comment by TheScree** [comment]
Not to bring this back up, but I'm seeing this issue resurfaced in 3.3.2... Any idea why this is happening still?

**Comment by kogratte** [comment]
I'm having the same issue

>
