### ISSUE TITLE
Embedding video not possible?

### ISSUE THREAD

**Issue by jhull** [nuxt/content#163]
Looking over the list of remark and rehype plugins, there isn't anything resembling `markdown-it-video`, my previous method for embedding Vimeo videos into Markdown content.

I found this `[remark-oembed](https://github.com/agentofuser/remark-oembed)` which looked semi-interesting, but ended up not working for my use case and super-hacky.

Is there another way to do this with the new Content module? If not, how hard is it/where should one start when trying to port over another implementation?

**Comment by Atinux** [comment]
Hi @jhull 

You can use the HTML5 `<video>` tag for it, see how we do on https://raw.githubusercontent.com/nuxt/content/master/docs/content/en/index.md
