### ISSUE TITLE
Nuxt Content Alert, Code, Code Syntax Highlighting not working in Nuxt documentation

### ISSUE THREAD

**Issue by HyunseungLee-Travis** [nuxt/content#1635]
### Environment

Nuxi 3.0.0-rc.12                                                                                                                    14:47:26
RootDir: /workspace/framework                                                                                                       14:47:26
Nuxt project info:                                                                                                                  14:47:26

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `pnpm@7.13.4`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

This issue can been seen on Nuxt Documentation repo.

https://v3.nuxtjs.org/getting-started/data-fetching/

### Describe the bug

Note: This bug seems to happen occasionally. When reloading the page or transition through page.

Overall, I could not find any difference between the code from `/data-fetching` and the code from other files, which seems to be fine.
Maybe (?) this is nuxt/content issue.
It appears both in build and development.

Seems like [Data Fetching](https://github.com/nuxt/framework/blob/main/docs/content/1.getting-started/6.data-fetching.md) directory has some problems.

## Alert Not Working (1)
![alert](https://user-images.githubusercontent.com/78584173/197398910-db60cbcd-fa3b-4634-b1c5-f9b26025b46a.png)

But then, while profiling...

![alert fixed](https://user-images.githubusercontent.com/78584173/197399466-2653a8d1-1cba-4ea4-a8d0-b43342304789.png)

As you can see, this might be an issue from Nuxt content.

## Code Not Working (2)
![code1](https://user-images.githubusercontent.com/78584173/197399011-cd2d885c-9aae-48d3-b563-c6f93285c2bd.png)
![code2](https://user-images.githubusercontent.com/78584173/197399012-a1a41700-6437-4a5c-8403-5bb69c684ed4.png)

## Code Syntax Coloring Working Weirdly (3)
![syntax1](https://user-images.githubusercontent.com/78584173/197399079-6e4c3123-2370-4289-9705-f4dcd6d68dcc.png)
![syntax2](https://user-images.githubusercontent.com/78584173/197399081-45f95344-84e9-4f60-a587-35d6db0309f5.png)
![syntax3](https://user-images.githubusercontent.com/78584173/197399084-736e6c70-0ef3-481f-b199-6a3fa498af87.png)

**Comment by Atinux** [comment]
Can you check @farnabaz ?
