### ISSUE TITLE
Named export 'u' not found. module 'unist-builder'

### ISSUE THREAD

**Issue by karis** [nuxt/content#1649]
hai i need your help.. :)

### Environment

- Operating System: `Darwin`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `buildModules`, `build`, `modules`, `strapi`, `i18n`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.2`, `@nuxt/content@2.2.1`, `@pinia/nuxt@0.4.3`, `nuxt-icon@0.1.7`, `@nuxtjs/i18n@8.0.0-alpha.1`
- Build Modules:    `@vueuse/nuxt@9.4.0`, `@nuxtjs/strapi@1.6.1`

### Reproduction

After adding nuxt/content to my project and including it in the nuxt.config.ts, then 
i run 
`yarn dev`

### Describe the bug

 **ERROR**  [worker reload] [worker init] Named export 'u' not found. The requested module 'unist-builder' is a CommonJS module, which may not support all module.exports as named exports.

i already add in nuxt.config.ts file
`transpile: ['unist-builder']`

but it doesnt work.

### Logs

```shell
ERROR  [worker reload] [worker init] Named export 'u' not found. The requested module 'unist-builder' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'unist-builder';
const { u } = pkg;


  import { u } from 'unist-builder';
  ^
  SyntaxError: Named export 'u' not found. The requested module 'unist-builder' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from 'unist-builder';
  const { u } = pkg;
  
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
  at async loadESM (node:internal/process/esm_loader:91:5)
  at async handleMainPromise (node:internal/modules/run_main:65:12)
```

**Comment by farnabaz** [comment]
This likely happens because one of you dependencies uses older version of `unist-builder` and it creates conflict in packages.
Try to clean install your deps, by removing `package-lock.jcon`. This should fix the issue

**Comment by karis** [comment]
thanks @farnabaz ,

it can be solved temporary by 
rename file to index.mjs
and 
change fix the code with type script style.
