### ISSUE TITLE
Style overwriting with prose by WindiCSS

### ISSUE THREAD

**Issue by ArthurDanjou** [nuxt/content#1661]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.11.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `srcDir`, `app`, `modules`, `css`, `components`, `content`, `colorMode`
- Runtime Modules:  `nuxt-windicss@2.5.3`, `@nuxtjs/color-mode@3.1.8`, `@vueuse/nuxt@9.4.0`, `@nuxt/content@2.1.0`, `nuxt-icon@0.1.7`, `@nuxtjs/supabase@0.1.28`
- Build Modules:    `-`

### Reproduction

https://github.com/ArthurDanjou/artdanj-website-v2

### Describe the bug

I am following the [documentation](https://content.nuxtjs.org/api/components/prose) to create my own blog style with Nuxt Content by overwriting the prose component.

You can find an example with the ProseA component in the [components/content](https://github.com/ArthurDanjou/artdanj-website-v2/blob/main/src/components/content/ProseA.vue) directory. In a [test article](https://github.com/ArthurDanjou/artdanj-website-v2/blob/main/src/content/posts/test.md), my style is well imported but there is an additional style by the .prose class by windicss (an additional underline below the text).

**Comment by Atinux** [comment]
Well if you want to overwrite the prose component, it is tricky with plugins like Tailwind or Windi typography. I think you need to directly overwrite it via their configuration 🤔

**Comment by ArthurDanjou** [comment]
Can I just recreate all the Prose component and overwrite with my theme so that I can remove the windicss' typography plugin ?

**Comment by Atinux** [comment]
Yes you can @ArthurDanjou 

We are working on an upcoming theme to help customize the prose components easily if you want to give a try: https://typography.nuxt.space

**Comment by ArthurDanjou** [comment]
Thank you for the tips ! I think the repository is still private but I will try to import the dependency
