### ISSUE TITLE
Fresh install, can't even start the local server

### ISSUE THREAD

**Issue by Dominik-Giroux** [nuxt/content#1667]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/content@2.2.1`
- Build Modules:    `-`

### Reproduction

Followed the Get Started - New project guide from https://content.nuxtjs.org/get-started/ and the nuxt server won't start.

### Describe the bug

I get a warning "[get-port] Unable to find an available port (tried 4000). Using alternative port: 3000" when running npm run dev, nitro does build the project, but then I have nothing on my localhost:3000

### Additional context

I'm using a M1 iMac, could that be part of the issue?

**Comment by Dominik-Giroux** [comment]
Turns out I only needed to update node to v18.12.1 and it worked

**Comment by spyesx** [comment]
Actually this issue still exists. Unless now we can't change the port. It want port `3000` even though another one is set. The thing is Nuxt uses this port already.

```bash
$ node -v
v18.12.1
```

```bash
[get-port] Unable to find an available port (tried 3000). Using alternative port: 3001
```

My configuration

```js
{
watch: {
    ws: {
      port: 3010,
      showUrl: true
    }
  }
}
```
