### ISSUE TITLE
Deployment with @nuxtjs/now-builder?

### ISSUE THREAD

**Issue by paolomolo** [nuxt/content#168]
I have a content project working great locally however nuxt-content is not displayed when deploying to Vercel with [@nuxtjs/now-builder](https://github.com/nuxt/now-builder).

Has anyone worked out a way to get content to work with the now-builder module?
Is there a easy config for the now.json? Or am I looking at it the wrong way?

I'm using the default now.json config at the moment:

```json
{
  "version": 2,
  "builds": [
    {
      "src": "nuxt.config.js",
      "use": "@nuxtjs/now-builder",
      "config": {
        "serverFiles": ["package.json"]
      }
    }
  ]
}
```

Thanks

**Comment by hunterliu1003** [comment]
Please try this: 

```
{
  "version": 2,
  "builds": [
    {
      "src": "nuxt.config.js",
      "use": "@nuxtjs/now-builder",
      "config": {
        "serverFiles": [
          "content/**"
        ]
      }
    }
  ]
}

```

**Comment by paolomolo** [comment]
Works like a charm! Thanks @hunterliu1003
