### ISSUE TITLE
Can't import queryContent

### ISSUE THREAD

**Issue by talhabw** [nuxt/content#1690]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `googleFonts`, `build`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/supabase@0.2.4`, `@nuxtjs/google-fonts@3.0.0-1`, `@nuxt/content@2.2.2`
- Build Modules:    `-`

### Reproduction

It is the same with every Nuxt 3 stable release and content project. So no need a reproduction as it's not a specific case.

### Describe the bug

Can't use Nuxt Content with Nuxt 3 stable release. I get this error when building, and can't use the `queryContent` in any file.

```
 ERROR  [unimport] failed to find "queryContent" imported from "#imports"
```

### Logs

```shell
Nuxt 3.0.0 with Nitro 1.0.0                                                              10:43:24  
                                                                                         10:43:25  
  > Local:    http://localhost:3000/
  > Network:  http://172.25.16.1:3000/
  > Network:  http://192.168.0.227:3000/

i Using Tailwind CSS from ~/assets/css/tailwind.css                     nuxt:tailwindcss 10:43:25  
i Please create ~/components/content and restart the Nuxt server to use components in Markdown     
i Tailwind Viewer: http://localhost:3000/_tailwind/                     nuxt:tailwindcss 10:43:27  

 ERROR  [unimport] failed to find "queryContent" imported from "#imports"                10:43:29  


 ERROR  [unimport] failed to find "useUnwrap" imported from "#imports"                   10:43:31  

i Vite client warmed up in 3968ms                                                        10:43:33  
√ Nitro built in 1467 ms
```

**Comment by farnabaz** [comment]
Could you try to clean install your project by removing `yarn.lock` and `node_modules`?

**Comment by talhabw** [comment]
Yeah, that seems to fix the issue. Thanks.
