### ISSUE TITLE
Nuxt content not working with nuxt 3

### ISSUE THREAD

**Issue by R0N1n-dev** [nuxt/content#1710]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `ssr`, `modules`, `buildModules`, `content`
- Runtime Modules:  `@nuxt/content@2.2.2`, `nuxt-windicss@2.5.1`
- Build Modules:    `-`

### Reproduction

https://github.com/R0N1n-dev/nuxt-daisy-blog

### Describe the bug

on attempting to start development server, error is presented as below,
![Uploading Screenshot_2022-11-28_08-40-02.png…]()

### Additional context

It was working fine before updating to nuxt RC13 and nuxt 3 stable.
( nuxt RC 12 worked )

**Comment by R0N1n-dev** [comment]
![Screenshot_2022-11-28_08-40-02](https://user-images.githubusercontent.com/83344872/204203724-8f419de8-464e-4c70-aed8-4c97b5b0d5df.png)

Screenshot of error

**Comment by Tahul** [comment]
Hey :)

https://github.com/windicss/nuxt-windicss

@harlan-zw seem to have release 2.6.0 of WindiCSS which seem to be causing your issue.

Could you try this version?

🙏

**Comment by R0N1n-dev** [comment]
Yes, updated nuxt-windicss and it worked. Thank you
