### ISSUE TITLE
npx command missing template

### ISSUE THREAD

**Issue by acidjazz** [nuxt/content#1714]
### Environment

Nuxt CLI v3.0.0-27254511.41ff3b8                                                                                             13:00:35
RootDir: /Users/k/tmp/content                                                                                                13:00:35
Nuxt project info:                                                                                                           13:00:35

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `0.0.0`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

<img width="480" alt="image" src="https://user-images.githubusercontent.com/967369/204621662-7a799fe1-ddf8-4731-a04c-bc747e6fff62.png">

<img width="480" alt="image" src="https://user-images.githubusercontent.com/967369/204621696-7720c37c-f806-462d-bd07-fbf7bed1a354.png">

### Describe the bug

Invalid template name

**Comment by Atinux** [comment]
Can you try with `npx nuxi@latest`
