### ISSUE TITLE
Can't find GroupCode component 

### ISSUE THREAD

**Issue by Croodo** [nuxt/content#1719]
Can anyone please share the CodeGroup component? I need the code for editing. 
In the prose section, only the ProseCode component is available.
CodeGroup Code from nuxt content v1 is not working on v2.

Before Nuxt3 and Nuxt Content v2 
This mounted function was used to access slots property on the theme doc.
`  mounted() {
    this.tabs = this.$slots.default
      .filter((slot) => Boolean(slot.componentOptions))
      .map((slot) => {
        return {
          label: slot.componentOptions.propsData.label,
          elm: slot.elm,
        };
      });
  },`

`this.$slots.default` was accessible. can anyone tell me how can I access the slots property in Nuxt3?

**Comment by farnabaz** [comment]
CodeGroup was part of content-docs-theme which is replaced by Docus.
You need to migrate to Docus or build your own theme.

Here is docs for [Docus CodeGroup](https://docus.dev/api/components#codegroup-)

**Comment by Mokkapps** [comment]
I created a [StackBlitz that demonstrates a CodeGroup content component](https://stackblitz.com/edit/nuxt-content-code-group?file=components%2Fcontent%2FCodeGroup.vue) inspired by the [Docus CodeGroup](https://github.com/nuxt-themes/docus/blob/e210d3a830ba69e778f0bd5745a2801f3f81a79b/components/content/CodeGroup.vue) component:

**Comment by leosin** [comment]
> I created a [StackBlitz that demonstrates a CodeGroup content component](https://stackblitz.com/edit/nuxt-content-code-group?file=components%2Fcontent%2FCodeGroup.vue) inspired by the [Docus CodeGroup](https://github.com/nuxt-themes/docus/blob/e210d3a830ba69e778f0bd5745a2801f3f81a79b/components/content/CodeGroup.vue) component
> 
> Hope that helps anybody who is looking for such a component in Nuxt Content!

Thanks for the code, but in Nuxt 3.8 and content 2.9.0 not working,
the highlight not work,
the tabs disappear,
If you have time, can you check it out? Is it caused by an upstream upgrade?

**Comment by Mokkapps** [comment]
> > I created a [StackBlitz that demonstrates a CodeGroup content component](https://stackblitz.com/edit/nuxt-content-code-group?file=components%2Fcontent%2FCodeGroup.vue) inspired by the [Docus CodeGroup](https://github.com/nuxt-themes/docus/blob/e210d3a830ba69e778f0bd5745a2801f3f81a79b/components/content/CodeGroup.vue) component
> > Hope that helps anybody who is looking for such a component in Nuxt Content!
> 
> Thanks for the code, but in Nuxt 3.8 and content 2.9.0 not working, the highlight not work, the tabs disappear, If you have time, can you check it out? Is it caused by an upstream upgrade?

I plan to upgrade my portfolio website to Nuxt 3.8 during Christmas holidays, I will check this soon

**Comment by Mokkapps** [comment]
@leosin I fixed it: https://stackblitz.com/edit/nuxt-content-code-group-qrvays?file=components%2Fcontent%2FCodeGroup.vue

**Comment by leosin** [comment]
> @leosin I fixed it: https://stackblitz.com/edit/nuxt-content-code-group-qrvays?file=components%2Fcontent%2FCodeGroup.vue

it works thank you very much :) ☕️
