### ISSUE TITLE
Exclude fields from fetch request

### ISSUE THREAD

**Issue by andre-brdoch** [nuxt/content#172]
### Is your feature request related to a problem? Please describe.
We have big pieces of content, where we want to fetch all fields, with the exception of a few ones.

### Describe the solution you'd like
```js
// returns all fields, but not 'summary'
const content = await this.$content('article-1').exclude(['summary']).fetch()
```

**Comment by Atinux** [comment]
Hi @andre-brdoch 

We have the only(fields) method to return the requested fields. It is more explicit so you knows the field returned directly.

Does that work for you?

**Comment by andre-brdoch** [comment]
Hi Atinux! 

I agree that for content with few fields being explicit is better. However, we often deal with JSON files that have a few dozen props, where listing all of them manually would be very tedious, when we just want a few removed 😃

**Comment by benjamincanac** [comment]
Hey @andre-brdoch,

Your feature request has been implemented, you can check it by using `@nuxt/content` from GitHub directly in your `package.json`:

```json
{
  "dependencies": {
    "@nuxt/content": "nuxt/content"
  }
}
```

It should be available when we release the next version.

**Comment by andre-brdoch** [comment]
@benjamincanac awesome, thank you very much for putting in the work! 😄
