### ISSUE TITLE
[Docs] Nested code block is wrongly highlighted

### ISSUE THREAD

**Issue by Zerro97** [nuxt/content#1723]
### Environment

N/A

### Reproduction

N/A

### Describe the bug

Nested code block within alert component is wrongly highlighted

![Screen Shot 2022-12-02 at 5 50 34 PM](https://user-images.githubusercontent.com/34781112/205255057-8d673655-b7cd-4437-b0bb-7039471156f6.png)

**Comment by bdrtsky** [comment]
This should be already fixed.
