### ISSUE TITLE
Please remove the message "Please create ~/components/content and restart the Nuxt server to use components in Markdown"

### ISSUE THREAD

**Issue by cavatron** [nuxt/content#1732]
### Is your feature request related to a problem? Please describe
The existence of the `components` folder causes the message `Please create ~/components/content and restart the Nuxt server to use components in Markdown` to appear. You can easily reproduce by using [the starter template](https://stackblitz.com/github/nuxt/starter/tree/content) and creating a `components` folder with nothing in it.

I don't think it's a helpful message especially since mdc is optional

### Describe the solution you'd like
Some options:

1. Enable it only when `content.markdown.mdc` is `true` in `nuxt.config.ts`. 
2. Completely remove it. Seems like something that should just be a part of the docs, and not show up in the console.

Also remove  [the other message](https://github.com/nuxt/content/blob/ae138a879e11def0919dd2fa90e2b6d24164e7c7/src/module.ts#L428). It's just telling me what the directory structure of the project is. Seems to be no more valuable than 

>Your `nuxt.config.ts` is at the root of your Nuxt project! :->

### Describe alternatives you've considered
Blindfolds, masking tape, reluctant acceptance

### Additional context
![Screen Shot 2022-12-07 at 4 35 51 PM](https://user-images.githubusercontent.com/24627271/206311811-935e4b50-d3a1-4c7a-b136-2a253ce5fa0b.png)

**Comment by Tahul** [comment]
Hey @cavatron ; I tend to think the same as you do

Here is a PR, I'll let @Atinux and @farnabaz take a decision:
https://github.com/nuxt/content/pull/1733

**Comment by farnabaz** [comment]
Released is v2.3
