### ISSUE TITLE
Mobile navigation not responsive

### ISSUE THREAD

**Issue by oripka** [nuxt/content#1739]
### Environment

Browsing to the docs on an iPhone does not have responsive navigation 

### Reproduction

https://content.nuxtjs.org/blog/announcing-v2/

### Describe the bug

See screenshot 
![FE9FBF1F-7061-48F8-BA55-0B7ED66A11FD](https://user-images.githubusercontent.com/227032/206896645-41d20303-62b4-4248-b4da-c8caf6668e10.jpeg)

**Comment by Tahul** [comment]
@bdrtsky could you look into this?

**Comment by Tahul** [comment]
@Atinux ; how do you think we should wrap navigation in that case?

**Comment by bdrtsky** [comment]
seems like a bug, since on latest Docus header nav is hidden on mobile

**Comment by farnabaz** [comment]
Thank you for reporting, this is fixed in latest version of Docus.

**Comment by oripka** [comment]
Seems better, but not quite right.

![D753462C-9CBE-47E7-9ED7-3B0D33EBDE36](https://user-images.githubusercontent.com/227032/207901722-635755d7-2ed9-45f1-b953-9b24b8e8476f.jpeg)
