### ISSUE TITLE
Triggered date fields from draft/publish states?

### ISSUE THREAD

**Issue by thely** [nuxt/content#174]
### Is your feature request related to a problem? Please describe.

I'm migrating over from Wordpress to @nuxt/content, which by and large has been fairly painless. But one feature of WP that I haven't yet figured out a pleasant solution for is having a programmatic draft/publish date. In WP, the moment you set a post from "draft" to "publish," the post gets a specific publish date as a timestamp, which it keeps as long as the post remains in the "publish" state and isn't sent back to "draft."

In @nuxt/content, I can give a .md file a `status: publish` line in its front matter, which I can use to generate a timestamp in `content:file:beforeInsert`. However, that timestamp isn't permanent - it will regenerate every time the file's saved.

### Describe the solution you'd like

I'm not certain how this could be solved in @nuxt/content without nuxt being able to alter the original .md file somehow. `createdAt` and `updatedAt` are also time-based, but they have to do with actual file properties, not Markdown front matter.

### Describe alternatives you've considered

I'm using git hooks to update my site on the remote server, so I could potentially use the `createdAt` property that's generated the moment a new .md file is pushed to `live`.

**Comment by benjamincanac** [comment]
Hey @thely,

Could #252 solve your issue?

**Comment by thely** [comment]
Hmm. Not totally, because it doesn't automatically generate the date, but I'm not sure my original request was feasible with how nuxt/content is set up anyway. It's close enough!
