### ISSUE TITLE
.search() for query (nuxt-content v2)

### ISSUE THREAD

**Issue by gitFoxCode** [nuxt/content#1758]
### Is your feature request related to a problem? Please describe

In nuxt-content v1 there was the possibility to search, for example, articles using `.search()`, there is no such thing in v2

### Describe the solution you'd like

```javascript
const search = "javascript"
const articles= await queryContent('/articles/').search(search).only(['title', 'description',' date').find()
```
or if the developer doesn't want to search by the entire contents of the file 
```javascript
const articles= await queryContent('/articles/').search(search, ['title','description']).only(['title', 'description',' date').find()
```

### Describe alternatives you've considered

I am currently using something like this (there is no mention of regex in the documentation, but it works). The problem is that I would like to search not only by title but also, for example, by description or even by the contents of the .md file itself.
```javascript
.where({title: { $regex: `/${search}/ig` }})
```

**Comment by ManasMadrecha** [comment]
Try this using `$or` to search in multiple keys.

```js
.where({
  $or: [title: { $regex: `/${search}/ig` }, description: { $regex: `/${search}/ig` }]
})
```

-----

And to search in entire contents of the file, add a key containing raw contents of the body. You can add this in [content:file:afterParse](https://content.nuxtjs.org/api/advanced#contentfileafterparse). E.g., `file._full = file.body`. Then, you can use `where` to search in `_full` too.

**Comment by alfosforo** [comment]
> Try this using `$or` to search in multiple keys.
> 
> ```js
> .where({
>   $or: [title: { $regex: `/${search}/ig` }, description: { $regex: `/${search}/ig` }]
> })
> ```
> 
> And to search in entire contents of the file, add a key containing raw contents of the body. You can add this in [content:file:afterParse](https://content.nuxtjs.org/api/advanced#contentfileafterparse). E.g., `file._full = file.body`. Then, you can use `where` to search in `_full` too.

It would be great if this was in the documentation.
