### ISSUE TITLE
SPA Configuration

### ISSUE THREAD

**Issue by jameshhood** [nuxt/content#176]
I've commented on an existing "closed" issue. I've tried asking for help on discord. I just need some straight answers or some guidance in the right direction.

### My Needs
I have a nuxt app that requires authenticated users and needs to be able to be built for a cordova app which means I'm stuck with SPA. Now I have multiple customers that will want tweaks here and there for some common areas of the app I'm building and I was hoping to use MD files with vue in them to be able to manage the differences between customers.

### Question
What do I need to do to get this to work with SPA? Static and SSR are not an option.

### What I've tried
Anyone who has tried just installing the content module and run your nuxt app in development mode probably havent found any problems, however, once you publish your dist directory to your web server, you will get 400/500s out the wazoo. 
- So what I did to fix this was deploy my content directory to _content (default folder) and the errors go away. However, I quickly noticed that vue was no longer working and more than likely because it has to be compiled. 
- This led me to look into a vue runtime compiler component which just takes a string of a vue template. 
- I started looking into the body of the object coming back from fetch() and it truly reads it as an object so I couldn't just stringify it and pass it to the vue compiler.
- I noticed that there was an option to return the MD file as in a "text" version of it and thought my problems had been solved to quickly realize that it's not coming until 2.0. 

So I'm kind of stuck between a rock and a hard place. Vue doesn't make "dynamic" content very easy to generate and I was hoping I could use this module to do it because I love the idea of using MD files to do it. None of the documentation is very clear on setting up SPA or if it's completely unsupported ect.

**Comment by benjamincanac** [comment]
Hey @jameshhood,

This bug should be fixed, you can check it out by using @nuxt/content from GitHub directly in your package.json:

{
  "dependencies": {
    "@nuxt/content": "nuxt/content"
  }
}

It should be available when we release the next version.

**Comment by giovannilaperna** [comment]
Can you confirm this is now working with `ssr: false, target: 'server'`?
I run `nuxt build` not `nuxt generate`

**Comment by giovannilaperna** [comment]
This is not working yet in spa mode with `nuxt build` and `nuxt run`
