### ISSUE TITLE
Add property 'name' in generate meta tag

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/content#1766]
Actually, generated meta tag looks like this:

```html
<meta property="og:image" content="/images/...">
```

But some website, like LinkedIn, needs to have the property `name`:

```html
<meta name="image" property="og:image" content="/images/...">
```

**Comment by Barbapapazes** [comment]
I think it's here?

https://github.com/nuxt/content/blob/main/src/runtime/composables/head.ts#L48

**Comment by farnabaz** [comment]
I've made a quick search and this is what I found from LinkedIn https://www.linkedin.com/help/linkedin/answer/a521928/make-your-website-shareable-on-linkedin?lang=en

Do you mind providing some docs or articles about `image` attribute?  I didn't see this use case before

**Comment by Barbapapazes** [comment]
Yes, here what I found

**Comment by Barbapapazes** [comment]
And the weird thing is that LinkedIn doesn't find social image but I don't understand why.

**Comment by farnabaz** [comment]
> Nuxt have a social image but LinkedIn doesn't display
> ![](https://user-images.githubusercontent.com/45267552/208899544-835d5166-0bf9-4cde-8cb8-2944729849e0.png)

From what I see in your image, the meta tag is invalid indeed. It should be `<meta property="og:image"`, but it is `<meta name="og:image"`.

> But maybe, it's not related to this module.

I believe so. As you have seen in the module source, it uses `<meta property="og:image"`.

**Comment by Barbapapazes** [comment]
> > Nuxt have a social image but LinkedIn doesn't display
> > ![](https://user-images.githubusercontent.com/45267552/208899544-835d5166-0bf9-4cde-8cb8-2944729849e0.png)
> 
> From what I see in your image, the meta tag is invalid indeed. It should be `<meta property="og:image"`, but it is `<meta name="og:image"`.
> 
> > But maybe, it's not related to this module.
> 
> I believe so. As you have seen in the module source, it uses `<meta property="og:image"`.

Ok, fine to me. I close as not planned this issue.

**Comment by Barbapapazes** [comment]
@farnabaz I understand the issue thanks to @harlan-zw !

Reading this,https://github.com/harlan-zw/nuxt-og-image#add-your-host-name, the URL need to contain the host name. After some real life checking, it seems to be confirmed.

So when Content generated `og:image` link the full link need to be added. But I don't know it this is the responsibility of the content writer or of this module.
