### ISSUE TITLE
The composable web-socket is in production

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/content#1767]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@3.3.1`
- Builder:          `vite`
- User Config:      `schemaOrg`, `app`, `runtimeConfig`, `modules`, `robots`, `content`, `routeRules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `@nuxt/content@2.3.0`, `@vueuse/nuxt@9.6.0`, `nuxt-icon@0.1.8`, `nuxt-schema-org@2.0.2`, `@nuxtjs/fontaine@0.2.3`, `nuxt-simple-robots@0.1.3`
- Build Modules:    `-`
------------------------------

### Reproduction

Create a new project with `nuxt/content`
Build it using `npm run build`
Check dist files and you will `web-socket.js`

![image](https://user-images.githubusercontent.com/45267552/208883502-75868b29-37b0-4827-b05b-560a88e03374.png)

Or you can find him here: https://le-classement.fr/_nuxt/web-socket.47cdec99.js

### Describe the bug

I think this file must not go in production. It create a useless request.

**Comment by Atinux** [comment]
It should not be there indeed, cc @farnabaz
