### ISSUE TITLE
How to use Component in markdown file (component with some logic)

### ISSUE THREAD

**Issue by MuhammadKhizar7** [nuxt/content#1773]
### Discussed in https://github.com/nuxt/content/discussions/1771

<div type='discussions-op-text'>

<sup>Originally posted by **MuhammadKhizar7** December 23, 2022</sup>
I am using components with little bit of logic or extra text besides slot text inside components, for example  FAQ questions or blog post with reference links in bottom I want to use show hide button so if user want see reference click button and see reference but did not show initially.
Question is to you can do that with way mention in docs, and I am not able to do it with ``` :ComponentName ``` or
```
::componentName 
text
::
```
</div>
or there is any other way to do that from Markdown

**Comment by farnabaz** [comment]
Did you defined your component inside `components/content` directory?  If you do you should be able to use it in the markddown with pascal case to kebab case naming

```
::component-name
Text
::

::ComponentName
Text
::
```

If you already created it inside `components/content`, please provide a simple reproduction  to dig into the problem. You can use https://stackblitz.com/github/nuxt/starter/tree/content to create reproduction

**Comment by MuhammadKhizar7** [comment]
Thanks, @farnabaz,  for replying. I already use it, but problem is it shows only slot text not other elements like buttons above slot or any hide and show logic of slot text. Like FAQ to show initial question and click to show the answer

**Comment by MuhammadKhizar7** [comment]
Thanks, @farnabaz,  It's working but only problem which I was actually facing is on Windows. It needs to be restarted and also .nuxt folder must be deleted before it will work.
