### ISSUE TITLE
Download of files from `/public` folder does not work

### ISSUE THREAD

**Issue by chamaoskurumi** [nuxt/content#1783]
### Environment

```
# package.json

{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "@nuxt/content": "^2.2.2",
    "nuxt": "^3.0.0"
  }
}

# npx nuxi info
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/content@2.3.0`
- Build Modules:    `-`
------------------------------
```

### Reproduction

**Stackblitz**
https://stackblitz.com/edit/github-snyd9q?file=content/index.md

**Github**
https://github.com/chamaoskurumi/nuxt3content_example

### Describe the bug

I should be able to link a download in an `..md` file that points to a `.pdf` that lives in the `/public` folder easily by

`<a href="/my_pdf_file.pdf" download>Download</a>`

or maybe even

`[Download](/my_pdf_file.pdf`

But unfortunately it doesn't work.

Any ideas how to solve this?

### Additional context

I also asked this question on [StackOverflow](https://stackoverflow.com/questions/74928277/how-to-add-a-link-to-download-a-file-in-a-md-file-using-nuxt3-nuxt-content).

**Comment by farnabaz** [comment]
There is no simple way to detect whether the link is a file in the public directory, or it is a path to a content. And since content module uses `NuxtLink` under the hood, all internal links are treated as pages.

You can add `_target="blank"` to your link to ensure that they will be handled by server and retrieve as real files.

With MDC attributes syntax
```
[Download](/my_pdf_file.pdf){target="_blank" download="awesome.pdf"}
```

With HTML syntax

```
<a href="/my_pdf_file.pdf" target="_blank" download="awesome.pdf">Download</a>
```

**Comment by kissu** [comment]
Both syntaxes are working super well, thanks @farnabaz! ❤️

**Comment by chamaoskurumi** [comment]
Works like a charm :bow: thx!

**Comment by paolieri** [comment]
To open in the same browser tab, `target="_top"` worked for me.
