### ISSUE TITLE
Changelog page empty

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/content#1796]
### Environment

Documentation website

### Reproduction

https://content.nuxtjs.org/changelog

### Describe the bug

The documentation page of Nuxt-content v2 is empty but Algolia Search still return results for this page.
When you click on the Algolia result, you end up on this empty page and can't find what you are looking for.

**Comment by mrleblanc101** [comment]
![Capture d’écran, le 2023-01-05 à 22 52 48](https://user-images.githubusercontent.com/17392251/210926660-1e541f12-4bdf-43af-8c83-9faedae12002.png)

**Comment by Atinux** [comment]
I think we could update the component to leverage directly an API call to https://ungh.cc/repos/nuxt/content/releases form our server and parse it.

But anyway we plan to move the docs to the main nuxt.com website very soon.

Thank you for reporting the bug @mrleblanc101

**Comment by nobkd** [comment]
Related: #1729

**Comment by nobkd** [comment]
Works for me now, probably since nuxtlabs/github-module#42 was merged.
So I think this issue can be closed.
