### ISSUE TITLE
Layout duplicated in document driven mode

### ISSUE THREAD

**Issue by ceceliacreates** [nuxt/content#1807]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `modules`, `content`, `css`
- Runtime Modules:  `@nuxt/content@2.2.2`, `@nuxt/image-edge@1.0.0-27809804.194d2d6`
- Build Modules:    `-`

### Reproduction

Minimal reproduction:
https://content.nuxtjs.org/examples/essentials/document-driven

Also seeing it in my own project:
https://github.com/ceceliacreates/nuxt-content-v2-doc-driven

### Describe the bug

On the about page in the example for document driven mode in the docs, the 

```
<div class="pb-4 border-b border-gray-500">
      Article layout
    </div>
```
Above the `<slot />` appears twice when navigating to the page. 

![Screenshot 2023-01-07 at 4 39 05 PM](https://user-images.githubusercontent.com/40367173/211171257-0bec8ff9-1137-4edd-a585-6e373b136d2c.png)

This is happening for my project as well. Components around the `<slot />` appear twice when navigating to the page with the `blog.vue` layout. On refresh, the duplicate components disappear and the page renders correctly.

**Comment by nobkd** [comment]
You have to remove the `<NuxtLayout>` tag from your `app.vue`.

I'll do a quick PR to fix the example.

**Comment by ceceliacreates** [comment]
> You have to remove the `<NuxtLayout>` tag from your `app.vue`.
> 
> I'll do a quick PR to fix the example.

Thank you!! That worked.
