### ISSUE TITLE
Overriding a single default plugin

### ISSUE THREAD

**Issue by jhull** [nuxt/content#181]
How does one go about overriding a single default plugin? The documentation is not entirely clear about this.

`remark-footnotes` is insufficient for my needs (and likely many others, see [this issue](https://github.com/remarkjs/remark-footnotes/issues/3#event-3476113819)) and I'd like to swap it out for [`remark-numbered-footnote-labels`](https://github.com/jackfletch/remark-numbered-footnote-labels) while maintaining the other defaults.

**Comment by benjamincanac** [comment]
@jhull You can't override a single plugin, in this version you can override the `basePlugins` array to remove `remark-footnotes` add and your own in `plugins`.

In the next version `basePlugins` and `plugins` will disappear and you will have to override `remarkPlugins` with a function:

```js
export default {
  content: {
    markdown: {
      remarkPlugins: () => ['remark-squeeze-paragraphs', 'remark-slug', 'remark-autolink-headings', 'remark-external-links', 'remark-numbered-footnote-labels']
    }
  }
}
```

**Comment by jhull** [comment]
Hmmm...I did as suggested, but the labels are still there...do I bug you or the repo for `footnotes-label`?

my config:

```
  content: {
    markdown: {
      remarkPlugins: () => ['remark-squeeze-paragraphs', 'remark-slug', 'remark-autolink-headings', 'remark-external-links', 'remark-numbered-footnote-labels'],
      plugins: ['remark-container']
    }
  },
```
