### ISSUE TITLE
queryContent does not work as expected on Vercel

### ISSUE THREAD

**Issue by shoma-mano** [nuxt/content#1825]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.4.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `content`
- Runtime Modules:  `@nuxt/content@2.3.0`
- Build Modules:    `-`

### Reproduction

This is app url deployed on Vercel, and this doesn't work as the same as app deployed on StackBlitz. 
[https://nuxt-content-reproduction.vercel.app/](https://nuxt-content-reproduction.vercel.app/)

This is StackBlitz ver, and works as expected.
[https://stackblitz.com/github/shoma-mano/nuxt-content-reproduction](https://stackblitz.com/github/shoma-mano/nuxt-content-reproduction)

### Describe the bug

I have content directory like this.
```
content
├── city
│   └── NewYorkCity.json
└── state
    └── NewYork.json
```

```
// NewYorkCity.json
{
  "id": 1,
  "name": "New York City"
}

// NewYork.json
{
  "id": 1,
  "name": "New York"
}
```

and **app.vue** is
```app.vue
<script setup lang="ts">
const { data: cityInfo } = await useAsyncData('city',() => queryContent('city').where({id:1}).findOne());
const { data: stateInfo } = await useAsyncData('state',() => queryContent('state').where({id:1}).findOne());
</script>

<template>
  <main>
    <p>
      data fetched by queryContent('city').where({id:1}).findOne()
    </p>
    <p>
       {{cityInfo}}
    </p>
    <p>
      data fetched by queryContent('state').where({id:1}).findOne()
    </p>
    <p>
      {{stateInfo}}
    </p>
  </main>
</template>
```
This works as expected on local, but doesn't on Vercel.

**Comment by Atinux** [comment]
Could you try with nuxt-edge @shoma-mano ?

https://content.nuxtjs.org/guide/migration/edge-channel

**Comment by shoma-mano** [comment]
Thanks for your advice! But, It still doesn't work as expected.
[https://nuxt-content-reproduxtion-edge-channel.vercel.app/](https://nuxt-content-reproduxtion-edge-channel.vercel.app)

Repository is here.
[https://github.com/shoma-mano/nuxt-content-reproduxtion-edge-channel](https://github.com/shoma-mano/nuxt-content-reproduxtion-edge-channel)

**Comment by farnabaz** [comment]
I've tried deploying your repository to Vercel and it seems to work as expected. https://nuxt-content-reproduxtion-edge-channel-sigma.vercel.app/

**Comment by shoma-mano** [comment]
@farnabaz
The reason why my deployment didn't work well was my Edge Runtime did not support $fetch.

I didn't know the reason, I couldn't confirm function logs appeared on Vercel's Dashboard before, but Dashboard works well now and I can confirm logs like below.
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/65682253/214202272-1055d37a-5903-4600-9465-dfb69c98e27c.png">

I didn't change node version setting, and it was default v18. So I'm not sure why this error happened.

But I overrode

**Comment by shoma-mano** [comment]
@farnabaz
The reason why my deployment didn't work well was my Edge Runtime did not support $fetch.

I didn't know the reason, I couldn't confirm function logs appeared on Vercel's Dashboard before, but Dashboard works well now and I can confirm logs like below.
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/65682253/214202272-1055d37a-5903-4600-9465-dfb69c98e27c.png">

I didn't change node version setting, and it was default v18. So I'm not sure why this error happened.

But I overrode build command  to  ```nuxt generate && node -v``` to confirm node version, queryContent worked as expected suddenly.It seems overriding some setting is trigger that refresh edge runtime.

Anyway, this problem is not due to this library, so it's ok to close this issue.Thanks for supporting.
