### ISSUE TITLE
H2 headers get rendered as links

### ISSUE THREAD

**Issue by garyo** [nuxt/content#1834]
### Environment

Latest starter on Stackblitz: https://stackblitz.com/github/nuxt/starter/tree/content

### Reproduction

Use the starter on Stackblitz, and add one line to `index.md`:

```
## This is an h2 heading
```

### Describe the bug

You will see the h2 heading gets rendered as a link, and in fact it has an `<a>` element.

![image](https://user-images.githubusercontent.com/139975/213772740-1a352e09-2001-4e9e-af13-f4a11c3d45e6.png)

I realize this is because `content.markdown.anchorLinks` defaults to true, but just turning the whole header into an `a` seems like a poor default. It took me a long time to figure out why some of my headings were ending up as links.

Maybe it should default to false, but when nuxt/content is used with a system that renders the links in a "nice" way (with a chain that appears on hover for instance) that system could turn on `anchorLinks`?

**Comment by Barbapapazes** [comment]
Hello,

Not sure why this is a poor default?

**Comment by garyo** [comment]
It just seems surprising and odd that all headings should be blue-underlined links, except H1. I don't think that's what people expect when writing Markdown (well, it wasn't what I expected anyway).

**Comment by Barbapapazes** [comment]
Yes, can understand that. In fact, because we can use reset css to avoid this, it was not an unexpected behavior.

Maybe a better documentation could help?

**Comment by alfosforo** [comment]
I think it is useful for anchor links, but maybe better documentation (and how to avoid it) could help.

In my case I've applied this styles in App.vue:

```scss
h2,
h3,
h4,
h5,
h6 {
  a {
    color: black;
      &:hover {
        text-decoration: none;
      }
    }
  }
```

**Comment by ElyseGiroux** [comment]
Having this issue as well, I do not wish for my headers to be anchor links

**Comment by Barbapapazes** [comment]
Hello, you can disable anchor generation via settings. https://content.nuxtjs.org/api/configuration#anchorlinks

**Comment by ElyseGiroux** [comment]
> Hello, you can disable anchor generation via settings. https://content.nuxtjs.org/api/configuration#anchorlinks

Thank you! I missed that one when reading the docs, works like a charm

**Comment by dosstx** [comment]
Thank you! I had this "problem" too and the suggested solution works.

**Comment by kalnode** [comment]
**nuxt.config.ts**

```
export default defineNuxtConfig({
    // ...

    content: {
        renderer: {
            anchorLinks: { h2: false, h3: false, h4: false }
        }
    }

    // ...
}
```

**Comment by prof2k** [comment]
This works and is simpler:

`nuxt.config.ts`
```
export default defineNuxtConfig({
    // ...

    content: {
        renderer: {
            anchorLinks: false
        }
    }

    // ...
}
```

**Comment by MickL** [comment]
Regarding this the docs are quite confusing. I expected to do:

```ts
export default defineNuxtConfig({
    mdc: {
        headings: {
            anchorLinks: false
        }
    }
}
```
But it had no effect. The docs say:

> In addition to configuring via content.markdown, you can use Markdown Components (MDC) to customize the rendering of Markdown elements with mdc property.

So I tried:

```ts
export default defineNuxtConfig({
    content: {
        mdc: {
            headings: {
                anchorLinks: false
            }
       }
    }
}
```

Which wasnt working too. In the end the solution is quite simple but docs were confusing:

```ts
export default defineNuxtConfig({
    content: {
        renderer: {
            anchorLinks: false
        }
    }
}
```

Maybe even DX is confusing here? Because `Nuxt Content` is using `mdc`, so mdc config should be done explicit as mdc config -> One of the two ways I tried above

**Comment by farnabaz** [comment]
@MickL, which parts of the docs are confusing? If you’d like, feel free to open a PR to improve them—contributions are always welcome 🙂

**Comment by MickL** [comment]
I think the DX should be to config either by `content.mdc` or `mdc` as I showed above. The confusing part was:

> In addition to configuring via content.markdown, you can use Markdown Components (MDC) to customize the rendering of Markdown elements with mdc property.

It says to use "mdc property" to configure mdc.
