### ISSUE TITLE
Module registration is important?

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/content#1846]
### Environment

RootDir: C:/Users/esoubiran/dev/sandbox/content-tailwind
Nuxt project info:

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.2.0`, `@nuxt/content@2.3.0`
- Build Modules:    `-`
------------------------------

### Reproduction

/

### Describe the bug

I discover this code in the module:

```ts
  nuxt.hook("tailwindcss:config", (tailwindConfig) => {
    tailwindConfig.content = tailwindConfig.content ?? [];
    tailwindConfig.content.push(resolve(nuxt.options.buildDir, "content-cache", "parsed/**/*.md"));
  });
```

But, after some research, this can work only it the content module is declared after the tailwind one.

this works:
```ts
modules: [
  '@nuxtjs/tailwindcss',
  '@nuxt/content',
]
```

results:

```
content: [
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/components/**/*.{vue,js,ts}',
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/layouts/**/*.vue',
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/pages/**/*.vue',
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/composables/**/*.{js,ts}',
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/plugins/**/*.{js,ts}',
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/App.{js,ts,vue}',
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/app.{js,ts,vue}',
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/Error.{js,ts,vue}',
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/error.{js,ts,vue}',
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/.nuxt/content-cache/parsed/**/*.md'
]
```

this **not** works:

```ts
modules: [
  '@nuxtjs/tailwindcss',
  '@nuxt/content',
]
```

results:
```ts
content: [
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/components/**/*.{vue,js,ts}',
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/layouts/**/*.vue',
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/pages/**/*.vue',
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/composables/**/*.{js,ts}',
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/plugins/**/*.{js,ts}',
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/App.{js,ts,vue}',
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/app.{js,ts,vue}',
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/Error.{js,ts,vue}',
  'C:/Users/esoubiran/dev/sandbox/content-tailwind/error.{js,ts,vue}'
]
```

So, it there a way to do this works no matter the order or do we need to update docs to explains this?

**Comment by farnabaz** [comment]
Indeed module orders are matter here, because of Content module tries to inject data to tailwind config, therefore it should register hook before raising it by tailwind module. So You should register content module before tailwind.

I'm afraid there is no other workaround for now, this is something might resolve in Nuxt framework.

I'm closing this, because it's not actually a bug, actually this is modules behaviour in Nuxt eco-system
