### ISSUE TITLE
List type in markdown meta data

### ISSUE THREAD

**Issue by bayssmekanique** [nuxt/content#185]
A common use case for the meta data section of a markdown file is to include a list of tags.  Unless I'm missing something, there is no way to do a search on these tags other than using something like `tags: { $contains: params.tag }` which will return any tags with matching text.  This might be an intended use case so that a search of `dev` would return `dev` and `web-dev`, but there are also several cases where unrelated topics share a string segment within their tags.

The ideal solution would be to get elements like `tags` returned as an array from the `fetch()` call, and able to search and sort using these arrays from the `$content` chain.

**Comment by jbnv** [comment]
This sounds like something you can do after you fetch the content. `fetch()` returns a promise for the content and you can `.then()` run whatever function you want on the content. How is this something that needs to be added to the `$content` chain?

**Comment by mathe42** [comment]
@jbnv Yes you can do that after fetch but then the complete content is send to the client and this is a waste of bandwith (think about 1000 Articles where you only want the articles with a spezified tag) so it might be a good idea to implement such filter methods.

**Comment by bayssmekanique** [comment]
@jbnv, what @mathe42 said is basically the issue I'm foresee.  The more I think on it, the more I'm convinced this might actually be something that is solved by a plugin in the markdown parser.

I'm trying to avoid having to do the filtering after the `fetch` if I can avoid it.

**Comment by benjamincanac** [comment]
Hey @bayssmekanique,

You can actually perform a search on arrays by using regex:

```js
await $content('articles')
  .where({
    tags: {
      $regex: param.tag
    }
  })
  .fetch()
```

**Comment by bayssmekanique** [comment]
That works well, thank you for the tip @benjamincanac!

**Comment by ManasMadrecha** [comment]
@benjamincanac Great tip on using $regex. 😃 But it doesn't work on array of objects. Is there any query method available inside Loki to filter through such array of objects?

Related to #800
