### ISSUE TITLE
Type error in prose components

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt/content#1856]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v19.4.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `yarn@3.3.0`
- Builder:          `vite`
- User Config:      `alias`, `experimental`, `nitro`, `app`, `css`, `modules`, `runtimeConfig`, `routeRules`, `tailwindcss`, `graphqlServer`, `content`, `naiveUI`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.2.0`, `@huntersofbook/naive-ui-nuxt@0.5.1`, `@pinia/nuxt@0.4.6`, `./modules/storybook`, `nuxt-graphql-server@1.1.5`, `nuxt-runtime-compiler@1.1.3`, `@nuxt/content@2.4.2`
- Build Modules:    `-`

### Reproduction

Run `nuxi typecheck` in a project using nuxt/content.

### Describe the bug

Reports the error:
```
node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH2.vue:15:65 - error TS2339: Property 'exclude' does not exist on type 'boolean'.

15 const generate = anchorLinks?.depth >= heading && !anchorLinks?.exclude.includes(heading)        
```
and similarly for the other prose components.

**Comment by nobkd** [comment]
Should be fixed with https://github.com/nuxt/content/releases/tag/v2.5.0

**Comment by tobiasdiez** [comment]
I still have this with v2.5.2:
```
node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH1.vue:15:31 - error TS2339: Property 'depth' does not exist on type 'boolean'.

15 const generate = anchorLinks?.depth >= heading && !anchorLinks?.exclude.includes(heading)
                                 ~~~~~

node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH1.vue:15:65 - error TS2339: Property 'exclude' does not exist on type 'boolean'.

15 const generate = anchorLinks?.depth >= heading && !anchorLinks?.exclude.includes(heading)
```

**Comment by botmaster** [comment]
Hello.
I still have this issue with v2.6.0. 

![CleanShot 2023-05-04 at 15 17 01](https://user-images.githubusercontent.com/488208/236216171-27ca2899-cd47-47ff-b947-999dead00426.png)

@nobkd did you find a workaround ?

**Comment by nobkd** [comment]
Is anyone able to provide a reproduction for this?
I'm really unable to get this error on `typecheck`... 🤷

**Comment by tobiasdiez** [comment]
It's sadly not a minimal reproduction, but you can checkout https://github.com/JabRef/JabRefOnline/pull/2070 to see the error with `yarn typecheck`.

**Comment by nobkd** [comment]
Thanks. I can reproduce it locally too when I check out pr `#2070`.

**Comment by nobkd** [comment]
I can see, that your PR was closed, as it was *done*. I'm happy to see this :+1:

Was this just the result of upgrading Nuxt Content?
If yes, maybe because the `h1`-`h6` part was extracted and rewritten with #2187 (and https://github.com/nuxt-modules/mdc/commit/e5770b3e57ed4058dd08fc89bd5cfc738ca3b5b2 and some later commits)...

**Comment by tobiasdiez** [comment]
Not sure what fixed it in the end. But I'm also happy its working now.
