### ISSUE TITLE
`queryContent` empty result on where query

### ISSUE THREAD

**Issue by farnabaz** [nuxt/content#1857]
Querying with `_path` condition results empty list

```ts
const { data: _articles } = await useAsyncData('articles', async () => await queryContent(props.path).sort({ date: -1 }).where({ _dir: { $ne: `/${props.path}` } }).find())
```

**Comment by mctweb** [comment]
This is a regression with the newest release ( 2.4.2 ). 
I believe it is related to this: https://github.com/nuxt/content/commit/f6a429dc0ec2c935e9713b55b7ee043522255863
