### ISSUE TITLE
Turining off "rehype-slug" adds undefiend anchor link

### ISSUE THREAD

**Issue by melnikovdv** [nuxt/content#1864]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `build`, `vite`, `typescript`, `modules`, `app`, `googleFonts`, `content`, `yandexMetrika`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.3.0`, `@nuxtjs/google-fonts@3.0.0-1`, `@nuxt/content@2.4.2`, `yandex-metrika-module-nuxt3@1.5.1`
- Build Modules:    `-`

### Reproduction

Any nuxt3 project with content module

### Describe the bug

If I turn off rehype-slug plugin, it still adds `undefined` link to headers.

```
content: {
    markdown: {
      rehypePlugins: {   
        "rehype-slug": false
      }
    }
  },
```

What I then get in html:

```
<a href="#undefined"><!--[-->My test header<!--]--></a>
```

**Comment by nobkd** [comment]
If you just want to disable anchor link generation on headings, you can do so by setting [`anchorLinks` option](https://content.nuxtjs.org/api/configuration#anchorlinks) in the `nuxt.config.ts` to `false`.

But you also have a point, that it should automatically be disabled, if `href` is `undefined`.

**Comment by melnikovdv** [comment]
Thank you, I haven't noticed this option. Now it works as expected with the `anchorLinks` turned off.

**Comment by nobkd** [comment]
Should be fixed with https://github.com/nuxt/content/releases/tag/v2.5.0
