### ISSUE TITLE
Question about nestedProperties json structure and $containsAny

### ISSUE THREAD

**Issue by ibdf** [nuxt/content#187]
Hello,

I am using the option nestedProperties, and it works, but  the json structure seems redundant when comparing multiple values.

My where query:
```{ 'categories.cat': { $contains: [ 'Cat1', 'Cat2' ]}}```

Right now I have to write my items this way:
```
{
  "name": "Item1",
  "categories": [
    {
      "cat": "Cat1"
    },
   {
      "cat": "Cat2"
    },
  ]
}
```

But wouldn't it make more sense to write it this way?

```
{
  "name": "Item1",
  "categories": [
    {
      "cat": ["Cat1", "Cat2"]
    },
  ]
}
```
The above would also allow me to pass different "types" of categories if you will:
```
{
  "name": "Item1",
  "categories": [
    {
      "colors": ["Yellow", "Blue"],
      "sizes": ["1", "2"]
    },
  ]
}
```
Then I could search: { 'categories.colors': { $contains: [ 'Yellow' ]}}

I was looking at the LokiJS documentation and it says I should use $containsAny when comparing 2 arrays, but it doesn't seem to work when using nestedProperties. 

On another related note, I was also confused when I found out about $containsAny because right now in my queries (not nested) I use just $contains to compare 2 arrays and that has been working just fine. I also noticed that LokiJS uses "find' and not "where", which then makes me wonder what else is different in your implementation of LokiJS.

**Comment by benjamincanac** [comment]
Hey @ibdf, have you tried setting the `nestedProperties` option to enable dot-notation? https://content.nuxtjs.org/configuration#nestedproperties

**Comment by ibdf** [comment]
> Hey @ibdf, have you tried setting the `nestedProperties` option to enable dot-notation? https://content.nuxtjs.org/configuration#nestedproperties

This answer is frustrating at best. Of course I have, that's what prompted the question. 

"I was looking at the LokiJS documentation and it says I should use $containsAny when comparing 2 arrays, but it doesn't seem to work when using nestedProperties."

**Comment by benjamincanac** [comment]
By using objects inside your `colors` array:

```json
{
  "categories": [
    {
      "colors": [
        {
          "name": "Yellow"
        },
        {
          "name": "Blue"
        }
      ]
    }
  ]
}
```

and by setting your `nestedProperties` to:

```
content: {
    nestedProperties: [
      'categories.colors.name'
    ]
  }
```

you can query like this:

```js
// Contains
const products = await $content('products')
      .where({ 'categories.colors.name': { $contains: 'Yellow' } })
      .fetch()

// ContainsAny
const products = await $content('products')
      .where({ 'categories.colors.name': { $containsAny: ['Yellow', 'Blue'] } })
      .fetch()
```
