### ISSUE TITLE
`WARN` Export "useNitroApp" will produce a circular dependency between chunks

### ISSUE THREAD

**Issue by hopkins385** [nuxt/content#1880]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.5.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`, `imports`, `vite`, `content`, `app`, `tailwindcss`, `googleFonts`
- Runtime Modules:  `nuxt-csurf@1.0.1`, `@nuxt/content@2.4.3`, `@nuxtjs/tailwindcss@6.3.1`, `@pinia/nuxt@0.4.6`, `@vueuse/nuxt@9.12.0`, `nuxt-icon@0.2.10`, `nuxt-headlessui@1.1.1`, `@nuxtjs/google-fonts@3.0.0-1`
- Build Modules:    `-`

### Reproduction

1. `yarn install`
2. `yarn add -D @nuxt/content`
3.  Edit nuxt.config
4.  `yarn build`

https://stackblitz.com/edit/usenitroapp-warn

### Describe the bug

Hi guys,

after installing nuxt-content the following warning is thrown. See stackblitz example.

`WARN`  Export "useNitroApp" of module "node_modules/nitropack/dist/runtime/app.mjs" was reexported through module "node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/nuxt/dist/core/runtime/nitro/renderer.mjs" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.

**Comment by sandercoffee** [comment]
Same error for me
![image](https://user-images.githubusercontent.com/60913938/216785082-5785a89d-f16a-4644-80d7-0559f6c0e6da.png)

**Comment by Zerro97** [comment]
I got the same error too. My deployment to Cloudflare pages started failing few days back, even though I haven't quite changed my source code.

**Comment by Zerro97** [comment]
Posting 3 related logs here for the sake of readability:

```
WARN  Export "useNitroApp" of module "node_modules/nitropack/dist/runtime/app.mjs" was reexported 
through module "node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies 
of each other and will end up in different chunks by current Rollup settings. This scenario is not well 
supported at the moment as it will produce a circular dependency between chunks and will likely lead 
to broken execution order.
```

```
Either change the import in "node_modules/nuxt/dist/core/runtime/nitro/renderer.mjs" to point directly 
to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the 
same chunk.
```

For cloudflare pages, using `nuxt generate` with Nuxt 3.1.2 with Nitro 2.1.2 and yarn:
```
Failed: build output directory contains links to files that can't be accessed
```

**Comment by manniL** [comment]
Closing in favor of https://github.com/nuxt/nuxt/issues/18789#issuecomment-1420047699
