### ISSUE TITLE
'content' does not exist in type 'NuxtConfig'

### ISSUE THREAD

**Issue by mcrapts** [nuxt/content#1884]
### Environment

Nuxi 3.1.2

RootDir: /home/projects/xoriopayy.github
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`, `content`
- Runtime Modules:  `@nuxt/content@2.4.3`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-7ywwnd?file=nuxt.config.ts

### Describe the bug

Modifying the configuration according to the [documentation](https://content.nuxtjs.org/get-started/#add-to-a-project) results in a type error.

```
Argument of type '{ modules: string[]; content: { locales: string[]; }; }' is not assignable to parameter of type 'NuxtConfig'.
  Object literal may only specify known properties, and 'content' does not exist in type 'NuxtConfig'.(2345)
```

**Comment by mcrapts** [comment]
Still happening with Nuxt 3.2.0. Is this a Nuxt issue or Nuxt Content issue? @danielroe What do you think?

**Comment by danielroe** [comment]
This should be resolved in the [Nuxt edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and we can reopen.

**Comment by mcrapts** [comment]
Thank you for looking into this!

I tried Edge channel and indeed the error is gone on Edge channel. However, the types from the module for extending the configuration are not recognized. For example, there is no autocomplete or documentation on hover available.

IntelliSense with 3.1.1:
![image](https://user-images.githubusercontent.com/16231555/218793969-80e09f74-1589-463e-adee-b62dce266446.png)
![image](https://user-images.githubusercontent.com/16231555/218794380-933a97ad-5b33-4d59-ad3c-354966dcc35b.png)

IntelliSense with Edge:
![image](https://user-images.githubusercontent.com/16231555/218794140-22936211-dc99-4ce6-905a-5d926a7a1e42.png)
![image](https://user-images.githubusercontent.com/16231555/218794516-9e90f7e1-dfbb-419b-aff0-0ca2e7582b3e.png)

**Comment by danielroe** [comment]
Hm. I wouldn't consider that resolved. Let's reopen.

**Comment by lustremedia** [comment]
I face the same issue with nuxtIcon ...

```
Argument of type '{ modules: string[]; colorMode: { classSuffix: string; }; nuxtIcon: { size: string; class: string; }; i18n: { defaultLocale: string; strategy: "prefix"; locales: ({ code: string; iso: string; name: string; } | { ...; })[]; detectBrowserLanguage: { ...; }; vueI18n: { ...; }; }; }' is not assignable to parameter of type 'NuxtConfig'.
  Object literal may only specify known properties, and 'nuxtIcon' does not exist in type 'NuxtConfig'
```

**Comment by denissteinhorst** [comment]
...same issue for **content: {}** here, I'm using: **"nuxt": "^3.3.3"** 

`Argument of type '{ ssr: true; experimental: { externalVue: false; inlineSSRStyles: true; }; dev: boolean; devServer: { host: string; port: number; }; app: { head: { charset: string; viewport: string; }; }; modules: string[]; content: { ...; }; }' is not assignable to parameter of type 'NuxtConfig'.
  Object literal may only specify known properties, and 'content' does not exist in type 'NuxtConfig'.ts(2345)`

**Comment by Sleggi** [comment]
Actually i manage to solve this issue by simple   
`import { defineNuxtConfig } from 'nuxt/config'`

**Comment by OlenDavis** [comment]
Inside `@nuxt/content/dist/types.d.ts`, it extends `NuxtConfig` and `NuxtOptions` via the `@nuxt/schema` module like so:
```ts
import { ModuleOptions, ModuleHooks } from './module'

declare module '@nuxt/schema' {
  interface NuxtConfig { ['content']?: Partial<ModuleOptions> }
  interface NuxtOptions { ['content']?: ModuleOptions }
  interface NuxtHooks extends ModuleHooks {}
}


export { ModuleHooks, ModuleOptions, MountOptions, default } from './module'
```

But if `declare module '@nuxt/schema' {` were changed to `declare module 'nuxt/schema' {`, then the typings for `content: { /* ... */ }` on the config passed to `defineNuxtConfig` work properly.

Thoughts on how to update the package bundler for `@nuxt/content` to make that change @danielroe? I can't see where/how that change could be made.

**Comment by danielroe** [comment]
~> https://github.com/nuxt/module-builder/commit/796d6ab161f753b3cce66ebf182f1f46b22f2a7c

**Comment by mcrapts** [comment]
The issue is resolved for me indeed. If no others experience this issue anymore it can be closed.
