### ISSUE TITLE
Fallback to 'content/*' from 'pages/*' if no page found

### ISSUE THREAD

**Issue by JPustkuchen** [nuxt/content#1888]
### Is your feature request related to a problem? Please describe
Hopefully I wasn't just too dumb to find an existing solution or documentation to this, but is there a way to fall back to `content/*.md`  if there's not a `pages/*.vue` implementation?

### Describe the solution you'd like
Calling https://www.example.com/imprint
should fall back to
`content/imprint.md` (or .yml etc.)
if
`pages.imprint.vue`
does not exist.

If both do not exist, a 404 should be returned.

That way, you could easily use `pages` for complex routes with dynamic content, while using `content` for simple static contents.

I think a login or frontpage are good examples for `pages` while imprint, about us, ... are examples for static content?

Thank you in advance for your help! :)

**Comment by JPustkuchen** [comment]
Sorry, playing around I found
```
content: {
    // https://content.nuxtjs.org/api/configuration
    documentDriven: true,
},
```
in nuxt.config.ts
to be what I was looking for. Am I right?

**Comment by farnabaz** [comment]
Indeed, DocumentDriven is a way to create pages without having a Vue file in the pages directory.
You can read more about it in docs: https://content.nuxtjs.org/guide/writing/document-driven
