### ISSUE TITLE
Add filter by tag/category feature

### ISSUE THREAD

**Issue by faiyaz26** [nuxt/content#19]
### Is your feature request related to a problem? Please describe.
I need to show a list of articles which contain `featured` tag. Currently, if I understand correctly there is no way to filter articles by tag. This can be category as well. I prefer tags for this certain problem.

### Describe the solution you'd like
One should be able to able to query for some tags like this:
```
const articles = await this.$content('articles').where({ tag: { $in: ['feature', 'announcements'] } }).fetch()
```

### Describe alternatives you've considered
I don't see any alternative way of doing this on @nuxtjs/content

**Comment by faiyaz26** [comment]
I can work on it if this feature request is approved.

**Comment by benjamincanac** [comment]
Hey @faiyaz26,

You can already do this by using $containsAny.

Assuming `tags` is an array:

```js
const articles = await this.$content('articles')
    .where({ tags: { $containsAny: ['feature', 'announcements'] } })
    .fetch()
```

Let me know if this solves your problem!
