### ISSUE TITLE
Parsing Markdown inside YAML section of FrontMatter

### ISSUE THREAD

**Issue by santicros** [nuxt/content#191]
Is it possible to also parse markdown in other parts that are not the "body" of a Markdown file.
I'm doing some tests with NetlifyCMS and I have different sections in one page, and some have markdown inside. They get saved to a markdown format inside the YAML part of the .md, like:

```markdown
---
hero:
  title: This will be the hero text
services:
  - title: This is a title of the first service
    description: Description of this service
    explanation: >-

      * **First** item text

      * **Second** item text

      * **Second** item text
  - title: This is a title of the second service
    description: Description of this service
    explanation: >-

      * **First** item text

      * **Second** item text

      * **Second** item text
---

# Here I have some more text of the body

```

I would like Nuxt Content to also parse the explanation ul list :)

Thanks so much for your great job!

**Comment by benjamincanac** [comment]
Hey @santicros,

Unfortunately this is not possible at the moment, we're depending on [gray-matter](https://github.com/jonschlinkert/gray-matter) to parse the front-matter which doesn't seem to support this.

Maybe you can ask them if they plan to support it?

**Comment by violoncelloCH** [comment]
hey @benjamincanac 
I'm interested in this as well and thought about asking gray-matter, however after having taken a little closer look at the gray-matter I don't really get what they would need to add support for this. Could you elaborate a little bit on this?
from what I read in the documentation `matter()` returns `data` and `content` with all the frontmatter objects being in `data` - so wouldn't it be possible to access data.services[key].explanation (for the example above) and process it the same way as `content`?

**Comment by mathe42** [comment]
Just create your own custom markdown parser (based on the existing one) and add it like here: https://content.nuxtjs.org/configuration#extendparser

**Comment by violoncelloCH** [comment]
Thanks for the hint @mathe42 ! I'll take a closer look at how those parsers work...
However I'm still wondering if this is not a quite common use-case so it would be worth to have this in the core parser. Would a corresponding PR possibly be accepted?

**Comment by violoncelloCH** [comment]
hmm, I'm looking for a way to pass a parameter (containing the field(s) to be treated as markdown) from `$content(path, options.tomarkdown)` to the markdown parsers `toJSON()` function, but I didn't find a way to do this so far.
