### ISSUE TITLE
Is there an option to add inline JavaScript into markdown files?

### ISSUE THREAD

**Issue by jepster** [nuxt/content#1911]
Hi,

I would like to use an inline JavaScript from Matomo in my markdown generated page:

```
<div>
    <div id="matomo-opt-out"></div>
    <script src="https://mysite.matomo.cloud/index.php?module=CoreAdminHome&action=optOutJS&divId=matomo-opt-out&language=auto&showIntro=1"></script>
</div>
```

The script tag is always rendered and not processed as usual JavaScript. How can I enable inline JavaScript via writing markdown files?

**Comment by Atinux** [comment]
We avoid this for a security issue inside the content, if you have a custom Vue component to inject or using the document driven mode, you should be able to use `head.script` to inject a custom script.

See an example: https://stackblitz.com/edit/github-u3dxb2?file=public%2Fhello.js,content%2Findex.md
