### ISSUE TITLE
/articles not found

### ISSUE THREAD

**Issue by alenieto97** [nuxt/content#193]
Hello! I've incorporated nuxt content to my webpage and I absolutely love it. It works fine on development but on production it is throwing the following error.

`[GET] /blog
07:36:06:28
 ERROR  /articles not found
  at QueryBuilder.fetch (node_modules/@nuxt/content/lib/query-builder.js:190:13)`

My articles are at content/articles and my code is 

```  async asyncData ({ $content }) {
    const articles = await $content('articles').sortBy('date', 'desc').fetch()
```
What could be going wrong?

**Comment by benjamincanac** [comment]
Hey @alenieto97, could you provide a reproduction link? Thanks!

**Comment by alenieto97** [comment]
> Hey @alenieto97, could you provide a reproduction link? Thanks!

Sure! Would a trimmed bitbucket repro and instructions for vercel deployment suffice? Since It works fine on development I don't think it would throw the error on a codepen

**Comment by alenieto97** [comment]
Cool! So I commited a minimal repro repository to bitbucket and sent you an invitation so you can check it out, if you clone it and npm run dev you can see it works fine on localhost. Then I deployed it to vercel teams and made you a team member, there you can see the webpage here https://twitch-toc-3-howfweoj2.vercel.app/ , check that the source code is identical here https://vercel.com/myttteam/twitch-toc-3/howfweoj2/source and check the error msg here https://vercel.com/myttteam/twitch-toc-3/howfweoj2/functions cicking on the errors tab. I'm working on running the built app on localhost to check it has nothing to do with vercel

**Comment by alenieto97** [comment]
Oh and here is the full working site with the but https://twitch-toc.now.sh

**Comment by alenieto97** [comment]
Okay so the built version works on localohst, seems like a problem with vercel integration. This thread should be closed.

**Comment by JessicaSachs** [comment]
I'm getting this same issue with Debbie's Nuxt Content blog example [here](https://nuxtjs.org/blog/creating-blog-with-nuxt-content) when I deploy it on a basic Netlify site.

Everything works fine locally and `yarn export` works fine locally. On Netlify, I get the following stacktrace.

Node v12.16.3

```
8:53:20 PM: Error: /articles not found
8:53:20 PM:     at QueryBuilder.fetch (/opt/build/repo/node_modules/@nuxt/content/lib/query-builder.js:236:13)
8:53:20 PM:     at asyncData (pages/index.vue:33:0)
8:53:20 PM:     at promisify (node_modules/.cache/nuxt/utils.js:259:0)
8:53:20 PM:     at server.js:29027:23
8:53:20 PM:     at Array.map (<anonymous>)
8:53:20 PM:     at module.exports.__webpack_exports__.default (node_modules/.cache/nuxt/server.js:227:0)
8:53:20 PM: [error] /articles not found
8:53:20 PM:   at QueryBuilder.fetch (node_modules/@nuxt/content/lib/query-builder.js:236:13)
8:53:20 PM:   at asyncData (pages/index.vue:33:0)
8:53:20 PM:   at promisify (node_modules/.cache/nuxt/utils.js:259:0)
8:53:20 PM:   at server.js:29027:23
8:53:20 PM:   at Array.map (<anonymous>)
8:53:20 PM:   at module.exports.__webpack_exports__.default (node_modules/.cache/nuxt/server.js:227:0)
8:53:21 PM: Done in 7.52s.
```

@alenieto97 what did you end up changing?
