### ISSUE TITLE
[Website] Blank Changelog page

### ISSUE THREAD

**Issue by phenomen** [nuxt/content#1975]
### Environment

Google Chrome (V111)

### Reproduction

1. Open https://content.nuxtjs.org/
2. Click Changelog in the top navigation

### Describe the bug

When you open Changelog page from the top navigation, it opens a blank page.
If you reload the page, the content will render correctly.
What I've noticed, initially it opens `/changelog` path but when you reload it adds a trailing slash (`/changelog/`) and only then page is loaded correctly.

**Comment by nobkd** [comment]
Duplicate of #1729  and #1796

**Comment by phenomen** [comment]
Closed as duplicate
