### ISSUE TITLE
[DOC] Broken URL for "@nuxt/content theme docs"

### ISSUE THREAD

**Issue by Neilblaze** [nuxt/content#1987]
### Environment

The URL redirecting to `@nuxt/content theme docs` i.e. `https://content.nuxtjs.org/themes-docs` is broken & returns 404. Even tried with an alternate URL (`https://content.nuxtjs.org/en/v1/examples/docs-theme`), it also returns the same.

### Reproduction

Visit [`https://content.nuxtjs.org/themes-docs`](https://content.nuxtjs.org/themes-docs) or [`https://content.nuxtjs.org/en/v1/examples/docs-theme`](https://content.nuxtjs.org/en/v1/examples/docs-theme) to inspect.

### Describe the bug

URL is broken & returns 404 for [`en`](https://content.nuxtjs.org/en/v1/examples/docs-theme) or [main](https://content.nuxtjs.org/themes-docs), while the [`ja`](https://content.nuxtjs.org/ja/v1/examples/docs-theme) returns the page.

**Comment by farnabaz** [comment]
Hey,
Sorry for the late response, for English language Content v1 docs you can drop `/en`. You can visit https://content.nuxtjs.org/v1/examples/docs-theme

**Comment by Neilblaze** [comment]
> Hey, Sorry for the late response, for English language Content v1 docs you can drop `/en`. You can visit https://content.nuxtjs.org/v1/examples/docs-theme

@farnabaz seems like the link is a broken one 😓

**Comment by farnabaz** [comment]
Ah, seems that SSR is broken. Will fix the website meanwhile you can visit this page https://content.nuxtjs.org/v1/getting-started/introduction
On the left navigation bar goto bottom under `v1 -> Examples -> Docs Theme` you can navigate to page.
