### ISSUE TITLE
Are you even able to use script in a md file? How did document driven mode become a thought when it can't be dynamic?

### ISSUE THREAD

**Issue by VividLemon** [nuxt/content#1997]
Nuxt Content allows you to render markdown files. Okay, cool. Then they came out with Document driven mode. Which is nice, make everything in an md file and render it on Nuxt. Okay, so this begs the question, how do I make any md files dynamic in document driven mode? If everything is a md file, besides perhaps the layout, how do I use it? If the answer is you don't, what in the world would be the point of using Nuxt Content? The point of Vue & Nuxt is to be dynamic. The point of JS is to make things dynamic... So why would I want to kneecap myself by using Nuxt Content? If I was just going to write some md files and render only some md files, why would I just not write some md files? 

So, this begs the question, is the only way to render any sort of dynamic content to wrap every piece of dynamic item in a component, then render it in an mdc? Well that's dumb. Defeats the purpose of using document driven if you're just going to be forced to wrap everything in a vue file. 

So, it begs the question, if this is the case... As shown in the docs, as there is never a reference to script in a md file, how is this better than just using Vitepress?

**Comment by ManasMadrecha** [comment]
Nuxt Content is better than Vitepress because
- We get to use `.md` files instead of `.mdx` files. This helps in using the files in other software too, like Obsidian
- With Nuxt Content, we get MongoDB-like filtering options. So, your entire markdown posts gets turned into full-fledged database automatically
- For JS in markdown, many people don't need that. Some really need just the content. And in case one needs to use JS in markdown, then we can get one-off components for that purpose.

**Comment by VividLemon** [comment]
If you're counter to requiring js in markdown is that "people don't need it". Then you could argue that people don't need to use Nuxt at all to do a simple compilation. 

I for one don't enjoy kneecapping my Vue applications. If I'm going to make a Vue app, there's probably a reason for it. If I want to make some MD files, there's probably a reason for it.

All of this shows glaring problems with document driven mode. As the entire point is to write exclusively MD files, and as such, you're not able to use the power of Vue or Nuxt, literally at all. So, what in the world is the point of having it?

**Comment by ManasMadrecha** [comment]
You can always use JS in markdown by creating components and passing props from the md file itself. 

Yes, in Vitepress, you can simply type JS in mdx file itself, but in Nuxt Content, you need to create separate component file for that. But, still, you can use JS in markdown that way then. 

And document-driven mode is anyway optional, particularly suited for content heavy websites like blog or documentation. You can use Nuxt Content module without document-drive mode as well (which is my preferred way).

**Comment by VividLemon** [comment]
Yes but if you want to do anything complex, it would be impossible in nuct content.

```ts
<button @click=show>

# some markdown content

<show v-if=shown>
```

It simply would not be possible. And wrapping everything dynamic in a component defeats the purpose of nuxt content, as every simple little thing now requires another wrapper component. Building a component library documentation should be super simple in document driven mode. Everything is mostly markdown, with just some example sprinkled around. But its not, simply because nuxt content disallows it.

If you are actually allowed to use Vue in vitepress, with the same  functionality for writing MD, what practical purpose does Nuxt content have? The Nuxt ecosystem? Sure, it would be great to use Nuxt plugins & modules, but again, you're not allowed to do to limitations

**Comment by ManasMadrecha** [comment]
Yes, dynamic stuff won't work without wrapping in another component. However, for me having a database of my markdown files where I can filter my notes on my site is more important than having dynamic JS stuff in notes. So, that depends case to case.

Also, Nuxt Content uses `remark` library for markdown, which is very easy to customize based on our own markdown syntax (e.g., wikilinks or callouts), unlike in Vite, where the difficult `markdown-it` is used.

Also, using Nuxt has its benefits: we can still use many Nuxt stuff out of the box in the md files themselves, like Nuxt Image or Nuxt Icon.

**Comment by VividLemon** [comment]
Regardless on the use of it, what harm does allowing Vue in Nuxt Content do? What drawbacks does it have? It would combine the power and dynamicness of Vue & the ease of use of MD
