### ISSUE TITLE
Vue in Markdown

### ISSUE THREAD

**Issue by VividLemon** [nuxt/content#1998]
### Is your feature request related to a problem? Please describe

Markdown is almost completely unusable as you can't interpolate values or scripts in md files. It makes document driven mode a unusable feature, as the only way to sufficiently add any sort of dynamic essence to a component is to further wrap it in another component, then render in mdc. This is significantly worse than just using plain Nuxt. 

Take for example the following scenario:

1. You are using Document driven mode
2. You have a component, say a modal, that you would like to use on a button click
3. In order to make this work, you would need to make a wrapper component that handles the ref state for the modal, and keep everything inside that component
This has the obvious drawback on, what if the toggler (a button) wants to exist in a different location, and not be coupled to wherever the modal is rendered. You can't put a button that opens a modal at the top, add some content in between, then render the modal at the bottom
So this makes document driven mode a complete waste of time. If you want any sort of dynamic essence to your Nuxt-content document-driven app, you will need to wrap everything in a above component. Alternatively, you could just use Nuxt without content. If you wanted to forgo anything dynamic, then there's no use of using Nuxt in the first place. You'd be better off just writing md files and compiling them to html or something.

### Describe the solution you'd like

A Vue in Markdown solution like https://vitepress.dev/guide/using-vue#using-vue-in-markdown or Vuepress equivalent is required to make this stack feasible. I like the mdc syntax, simply because it's "novel"... Though, rendering Vue in md could allow for the mdc syntax to be simplified to just writing any other Vue component -- a much easier skill curve for sure.  

### Describe alternatives you've considered

Wrap everything in another component -- worse than using Nuxt
Forgo Nuxt content -- It's alright ig, but writing in md is a nice to have
Use an alternative like VitePress -- it's also alright, but you then lose the elements that make Nuxt great. 

### Additional context

I think this should be top priority. Without it, I don't see any reason to ever use Nuxt Content. I understand that there isn't many developers working on this right now, and it's a true shame, as I could consider it so close to being done. Minus improving the abysmal docs (Do the docs even tell you how to use queryContent? the "querying page" says wrap it in a 'useAsyncData', but the queryContent api doesn't need it?)  & fixing various features (Say for example, https://content.nuxtjs.org/guide/displaying/typescript#type-augmentation & the whole TS system, or Static hosting)

**Comment by helltraitor** [comment]
It sounds strange for me. Recently I have used vue in markdown too, but is it problem at all since `@nuxt/content` supports [Markdown Components](https://content.nuxtjs.org/guide/writing/mdc "MDC")?

**Comment by VividLemon** [comment]
> It sounds strange for me. Recently I have used vue in markdown too, but is it problem at all since `@nuxt/content` supports [Markdown Components](https://content.nuxtjs.org/guide/writing/mdc)?

Using MDC, if you have a component at the top of the page, say if it has a dynamic background color.

You then want to put a button on the bottom of the page that controls the color 

How would you toggle the color of the top component, using the bottom button using MD and MDC syntax? 

The answer is since you can't use Vue in a MD file, you must build the entire page in a component. And since you need to have everything in a Vue component, why would you ever need Nuxt content? The answer is, you don't. 

The idea of nuxt content is too limiting in comparison to something like Vitepress. Where I'm fully capable of utilizing Vue stateful logic, and writing MD

**Comment by helltraitor** [comment]
> How would you toggle the color of the top component, using the bottom button using MD and MDC syntax?

I would try shared state per page: 
https://nuxt.com/docs/getting-started/state-management

With ```useState(`${useRouter().currentRoute.path}-set-color`)```

As for me, MDC is much friendly then flexible but ugly (in Markdown context) components.
In this case I would like to have something like signals

Is it not suitable for you, take a look on [transformers](https://content.nuxtjs.org/api/advanced#transformers "transformers")
May be this would push you to the right direction

Hope, I helped somehow

**Comment by VividLemon** [comment]
> > How would you toggle the color of the top component, using the bottom button using MD and MDC syntax?
> 
> I would try shared state per page: https://nuxt.com/docs/getting-started/state-management
> 
> With `` useState(`${useRouter().currentRoute.path}-set-color`) ``
> 
> As for me, MDC is much friendly then flexible but ugly (in Markdown context) components. In this case I would like to have something like signals
> 
> Is it not suitable for you, take a look on [transformers](https://content.nuxtjs.org/api/advanced#transformers) May be this would push you to the right direction
> 
> Hope, I helped somehow

And sharing state as described here means you would need to create and share state for every component. Making components more difficult to be reused.

**Comment by helltraitor** [comment]
> How would you toggle the color of the top component, using the bottom button using MD and MDC syntax?

Another variant is to put class inside an element (e.g. ```:class="`${page}-color-switch`"```
This will allow to use component both in default `.vue` pages and markdown component (via class). If you want, you can put several components and give them optional id, that will be applied in class string

Look, that all a theory, can you write what you *cannot* do, in contrast to what you *think* you cannot?
Note: I'm getting interested in this discussion, it full of ideas
