### ISSUE TITLE
Overriding Default Plugins Not Working

### ISSUE THREAD

**Issue by jhull** [nuxt/content#200]
Upgraded to latest (1.4.0) in the hopes that it would solve issue, but it doesn't seem to be.

```
content: {
    markdown: {
      remarkPlugins: () => ['remark-squeeze-paragraphs', 'remark-slug', 'remark-autolink-headings', 'remark-external-links', 'remark-numbered-footnote-labels' ],
      remarkPlugins: ['remark-container']
    }
```

Trying to replace default footnotes with this one above, and it's not working. ([This issue](https://github.com/nuxt/content/issues/181) still here).

Maybe remove the default footnote plugin altogether??

**Comment by jhull** [comment]
Not exactly sure why, but adding the new plugin to the second key resulted in success:

```
    markdown: {
      remarkPlugins: () => ['remark-squeeze-paragraphs', 'remark-slug', 'remark-autolink-headings', 'remark-external-links', 'remark-numbered-footnote-labels' ],
      remarkPlugins: ['remark-container', 'remark-numbered-footnote-labels']
    }
```

**Comment by benjamincanac** [comment]
Hey @jhull,

Since v1.4.0, you can use `remarkPlugins: () =>` (as a function) to override the defaults, or `remarkPlugins: []` (as an array) to add to the existing ones.

In your case, you can use the `remarkPlugins: () =>` only and put everything in it:

```js
 markdown: {
      remarkPlugins: () => ['remark-squeeze-paragraphs', 'remark-slug', 'remark-autolink-headings', 'remark-external-links', 'remark-numbered-footnote-labels' , 'remark-container']
    }
```
