### ISSUE TITLE
Hydration mismatch because of different "newline"

### ISSUE THREAD

**Issue by stenet** [nuxt/content#2000]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `modules`, `tailwindcss`, `content`, `routeRules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.5`, `@nuxt/content@2.5.2`
- Build Modules:    `-`

### Reproduction

* Clone https://github.com/stenet/nuxt-content-hydration-mismatch.
* `npm run dev`
* Open in browser

![image](https://user-images.githubusercontent.com/1838511/231153771-0451b0d4-ed47-4bac-b781-39aaca451593.png)

### Describe the bug

`test.md` was created in Windows 11 + Rider. 
New lines are represented by `\r\n`. 

On hydration this causes a mismatch because `\r\n` != `\n`.

**Comment by bjerggaard** [comment]
I experienced this as well

**Comment by derHodrig** [comment]
A workaround for that until a fix arrives is to use lf as end of line


Is et it up in .editorconfig and .prettierrc so i gets automatically "fixed" by the ide and commands.

**Comment by nobkd** [comment]
I tried to replicate this issue, and as far as I can see, the hydration mismatch only happens with code blocks.
Does that match your experience?

**Comment by nobkd** [comment]
Thanks for the information. I'm currently trying to find the location in the code where the file is read / before Vue gets the data.

As a temporary fix, that's probably much simpler than a custom content renderer I suggest you to use the [`content:file:beforeParse` hook](https://content.nuxtjs.org/api/advanced#contentfilebeforeparse). To get it to work, you have to remove the `.nuxt` directory of your project *once* to delete cached files.

Here'd be the code snippet to replace CRLF line endings of Markdown files with LF:
```ts
// e.g. server/plugins/crlf-to-lf.ts
export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('content:file:beforeParse', (file) => {
    if (file._id.endsWith('.md')) {
      file.body = file.body.replace(/\r\n/g, '\n')
    }
  })
})
```

**Comment by Rednas83** [comment]
Just stumbled on the issue that `newLine` is not displayed in the browser.

Solution is to set the **whitespace** to `pre-line` in css
`<ContentRenderer :value="data || {}" :style="{ whiteSpace: 'pre-line' }" />`
or with tailwind if you use that
`<ContentRenderer :value="data || {}" class="whitespace-pre-line" />`

To fix the hydration issue just change the server's **newLine** to `\n` to match the browser
![Image](https://github.com/user-attachments/assets/d27569fa-ebb9-4c24-9414-95a42741c3ae)
Whereby **LF** is `\n` and **CRLF** is `\r\n`
