### ISSUE TITLE
@nuxtjs/theme-everest Not Found

### ISSUE THREAD

**Issue by Pramod-Devireddy** [nuxt/content#201]
Hi, Nuxt Content is a very cool idea. And a good theme will make it further better. 
I tried to add the theme mentioned at https://content.nuxtjs.org/theme but it is not found in any registry.

Please try to add themes for blog & portfolio website.

### Steps to reproduce

>yarn add @nuxtjs/theme-everest

 or

>npm install @nuxtjs/theme-everest

### What is actually happening?

**error:** An unexpected error occurred: "https://registry.yarnpkg.com/@nuxtjs%2ftheme-everest: Not found".

**Comment by benjamincanac** [comment]
Hey @Pramod-Devireddy,

As mentioned in the docs, this is a work in progress. The `theme` feature is not yet available in Nuxt.js.

Stay tuned!
