### ISSUE TITLE
Better `ignores` implementation / documentation

### ISSUE THREAD

**Issue by davestewart** [nuxt/content#2017]
#### Overview

The current ignores implementation has a few issues:

- options are converted to RegExps which only work as folder / file name _prefixes_
- this a) is not made clear in the docs and b) could be avoided
- content watching / refresh does not respect ignored files

#### Implementation

Looking at the ignore code, it means ignore options can only ever be [prefixes](https://github.com/nuxt/content/blob/main/src/module.ts#L646-L661):

```ts
export const contentIgnores: Array<RegExp> = contentConfig.ignores.map((p: any) =>
  typeof p === 'string' ? new RegExp(`^${p}\|:${p}`) : p
```

This makes sense in the terms of the supplied defaults:

```
ignores: ['\\.', '-'],
```

But is limiting in terms of more flexible ignoring (unless you get quite creative with the input strings).

> Additionally: the implementation suggests that RegExps might be able to be passed, but they seem to get nuked by being squeezed through `getRuntimeConfig()`.

#### Docs

The docs actually don't mention the prefixing, they suggest you can ignore _words_:

- https://content.nuxtjs.org/api/configuration#ignores

This should be clarified.

#### File watching

It looks like the `ignores` config doesn't have any effect on the storage instance at the bottom of `src/module.ts`. 

Saving ignored files still triggers `refreshNuxtData()` via a sockets call.

### Describe the solution you'd like

To support the documented ignores format, change the default to:

```ts
const ignores: string[] = [
  '^[.-]|:[.-]'
]
```

And simplify the `contentIgnores` map to:

```ts
const contentIgnores = contentConfig.ignores.map(p => new RegExp(p))
```

Although, if prefixing is a specific design decision, then document it and provide a couple of examples:

```ts
[
  '.+?\\.txt$' // converts to /:.+?\.txt$/, matching text files only
]
```

To prevent triggering a refresh when changing ignored files, [in the module watch](https://github.com/nuxt/content/blob/main/src/module.ts#L701) use the same algorithm to prevent a sockets broadcast:

```ts
      await nitro.storage.watch(async (event: WatchEvent, key: string) => {
        // Ignore events that are not related to content
        if (isIgnored(key)) {
          return
        }
        ...
      })
```

Finally, as the ignore functionality will be used three times at this point, consolidate into a reusable function:

- https://github.com/search?q=repo%3Anuxt%2Fcontent%20contentIgnores&type=code

### Describe alternatives you've considered

I've been poring through the `ignores` code in the IDE and debugger, and pretty sure this is the only option.

### Additional context

Trying to optimise the updating code in Nuxt Content Assets:

- https://github.com/davestewart/nuxt-content-assets/issues/30

Pretty sure I know enough about Nuxt Content's source now to do a PR.

**Comment by farnabaz** [comment]
Hey @davestewart,
Thanks for explanation, Feel free to open a PR 👍 
Looking forward to seeing your improvement 🙂

**Comment by davestewart** [comment]
Great!

Any insight / preferences regarding the prefix strategy?

I know Content heavily uses unstorage, hence the `:` delimiters.

Ultimately, this means any ignore pattern targets single folder / files names only.

Would you prefer to document or modify this functionality?

**Comment by farnabaz** [comment]
The prefix ignoring is adopted from Nuxt itself (Nuxt ignores files with `-` prefix). So to be consistent, we should keep ignoring these prefixes. But it will be nice to support different kind of ignore patterns.

What you mean by expanding it? I didn't get your idea here.

**Comment by davestewart** [comment]
Ah... **sorry**!

I meant the `:` prefix:

```ts
new RegExp(`^${p}|:${p}`)
```

This will match any segment of an unstorage key:

```
sources:content:path:to:file.md
sources:content:file.md
file.md
```

What I meant was, do you want to transform any user-supplied ignore pattern so it is anchored to unstorage's `:` delimiters?

I should have said delimiters, not prefix!
