### ISSUE TITLE
Syntax highlighting not working from <ProseCode>

### ISSUE THREAD

**Issue by bokub** [nuxt/content#2046]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      modules, content
- Runtime Modules:  @nuxt/content@2.6.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-nh89rr?file=pages/index.vue

### Describe the bug

Syntax highlighting works great when using a code block in a `.md` file, but not at all when using `<ProseCode>` from a `.vue` file

### Additional context

![image](https://user-images.githubusercontent.com/17952318/235116447-9abb7d09-8631-46c7-aee3-5e888c1fe598.png)

**Comment by farnabaz** [comment]
`<ProseCode>` is responsible of rendering the highlighted code not to highlight it. Generally all Prose components are designed to style markdown contents.

**Comment by bokub** [comment]
Hello @farnabaz, 

I'm not sure I understand your answer. When I write the following in a .md file, how is it parsed and transformed?

> \```js
> console.log('Hello World!')
> \```


Why does [ProseCode](https://github.com/nuxt/content/blob/main/src/runtime/components/Prose/ProseCode.vue) have `language` and `highlights` props if it is not responsible of highlighting ?

Is there a way to highlight a piece of code from a `.vue` file to achieve the same result as writing it in a `.md` file ? 

Thanks

**Comment by farnabaz** [comment]
When you write this snippet:

```js
console.log('Hello World!')
```

Content module parse markdown file and highlight your code snippet in server using [Shiki transformer](https://github.com/nuxt/content/blob/main/src/runtime/transformers/shiki) and then in runtime the highlighted code is rendered by ProseCode.

If you want to highlight  code snippets inside a Vue file you can directly import and use [`getHighlightedCode` from Shiki highlighter ](https://github.com/nuxt/content/blob/bc60a54ddf3f2b1a24292a6f78e1183165be942f/src/runtime/transformers/shiki/highlighter.ts#L197) and render them as HTML.
Or 
Create a custom component with render function and use `getHighlightedAST` and use it to implement render function.

**Comment by bokub** [comment]
That's exactly the kind of answer I needed! Thanks @farnabaz, I'm closing this issue and I'll try that soon

Have a good day :+1:

**Comment by bokub** [comment]
If anyone stumbles on this issue, here is the code for a component that takes `code` and `lang` as props, and displays a highlighted version of the code.

```vue
<template>
  <ProseCode :language="lang" :code="code">
    <component is="style" v-html="highlightedCode.styles"></component>
    <code v-if="code" class="p-4 whitespace-pre-wrap" v-html="highlightedCode.code"></code>
  </ProseCode>
</template>

<script setup lang="ts">
  import { useShikiHighlighter } from '@nuxt/content/transformers/shiki/highlighter';
  import { computedAsync } from '@vueuse/core';
  const highlighter = useShikiHighlighter();

  const props = defineProps({
    code: {
      type: String,
      required: true,
    },
    lang: {
      type: String,
      required: true,
    },
  });

  const highlightedCode = computedAsync(
    () => {
      return highlighter.getHighlightedCode(props.code, props.lang, 'github-light');
    },
    {
      code: props.code,
      styles: '',
    }
  );
</script>

<style scoped>
  code :deep(.line) {
    word-break: break-word;
  }
</style>

```
