### ISSUE TITLE
ProseCode doesn't receive the right prop value for meta

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/content#2059]
### Environment

Nuxt 3.4.3
Nuxt Content 2.6.0

### Reproduction

https://codesandbox.io/p/sandbox/dawn-sound-zmvpdl

### Describe the bug

When you try to use `meta` in a custom ProseCode component, the value is actually filename+highlight+meta instead.

![image](https://github.com/nuxt/content/assets/2112282/e6868434-50ee-4fca-86c9-0c38e7a2f505)

![image](https://github.com/nuxt/content/assets/2112282/2dfecb37-19b9-47de-9989-8ae244fa885c)

### Additional context
Per the docs, the value should only be `meta-info=val`
![image](https://github.com/nuxt/content/assets/2112282/05db54a4-08f9-453a-b6ca-717d4cd3cf53)

**Comment by nobkd** [comment]
The meta contains not only meta information, but also filename and highlighted lines by default. And, as this isn't changed anywhere, you can see the result.

https://github.com/nuxt/content/blob/7cd771c472d735f3cf26864ef5b393f6aa83371e/src/runtime/markdown-parser/handler/code.ts#L25

It's probably the easiest to strip the filename and highlights in `parseThematicBlock` and use the result as meta:
https://github.com/nuxt/content/blob/7cd771c472d735f3cf26864ef5b393f6aa83371e/src/runtime/markdown-parser/handler/utils.ts#L8

**Comment by hecktarzuli** [comment]
It looks like if you do not put a space before the filename, everything works as expected.  I'm not sure if that's by design, or if Nuxt Content should allow the absence of a space or not.  I've updated the example.  If that's a hard rule, then the docs just need to be updated.

It comes down to 
`js[my-filename.js] meta` vs `js [my-filename.js] meta`
