### ISSUE TITLE
Missing `"unist-util-stringify-position"` dependency in `package.json`

### ISSUE THREAD

**Issue by jeffsee55** [nuxt/content#2063]
### Environment

yarn v1.22

### Reproduction

Use yarn to add another library that has 'unist-util-stringify-position' as a dependency (an earlier major release). TinaCMS uses a library that uses this. Other notes on reproducing [here](https://github.com/tinacms/tinacms/issues/3921).

```
yarn add tinacms 
```

Notice that yarn will hoist the dependency to the top. 

```
cat ./node_modules/unist-util-stringify-position/package.json
```

This will show the older version (2.0.3)
```
{
  "name": "unist-util-stringify-position",
  "version": "2.0.3",
  "description": "unist utility to serialize a node, position, or point as a human readable location",
  "license": "MIT",
...
```

Yarn always hoists when it won't conflict with another version. In this case, if `@nuxt/content` had listed 'unist-util-stringify-position' as a dependency, the older version wouldn't be hoisted.

### Describe the bug

The dependency is hoisted when it shouldn't be

```
file:///Users/jeffsee/code/scratch/tinacms-nuxt-content/.nuxt/dev/index.mjs:29
import { stringifyPosition } from 'file:///Users/jeffsee/code/scratch/tinacms-nuxt-content/node_modules/unist-util-stringify-position/index.js';
         ^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'stringifyPosition' not found. The requested module 'file:///Users/jeffsee/code/scratch/tinacms-nuxt-content/node_modules/unist-util-stringify-position/index.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
```

### Additional context

I think the only thing that's needed here is to add `unist-util-stringify-position` as a dependency, I believe you'll want a version `>3`. It's being used directly here https://github.com/nuxt/content/blob/af7f1fecd59cdec25e2f365dd2afc46b52c56ee7/src/runtime/transformers/csv/from-csv.ts#L8

**Comment by farnabaz** [comment]
Thanks for explanation
Could you open a PR to update deps?
