### ISSUE TITLE
Improve the code highlighting styles

### ISSUE THREAD

**Issue by kricsleo** [nuxt/content#2069]
### Is your feature request related to a problem? Please describe

In addition to color, code blocks should also have bold, italic, and underlined styles. Shiki supports these styles, but when parsing styles in nuxt/content, only color-related styles are generated, ignoring other styles. 

https://github.com/nuxt/content/blob/main/src/runtime/transformers/shiki/highlighter.ts#L170-L185

This is a comparison(using theme `material-palenight`).

nuxt/content:
<img width="441" alt="preivew_d5e4f280-9042-4f40-a456-f9875693957e" src="https://github.com/nuxt/content/assets/32707098/94febc03-55a6-4a6c-b166-b121cfd0a851">

Shiki:
<img width="476" alt="preview_512abf6d-6155-4faa-9595-3daf241a0e0a" src="https://github.com/nuxt/content/assets/32707098/83c8e47e-9635-4c63-b64c-d881a5b03325">

### Describe the solution you'd like

I think `font-weight`,`font-style` and `text-decoration` should be handled as well, thus making the style more aesthetically restorative. I would be happy to contribute a PR to handle this situation if I can

**Comment by farnabaz** [comment]
Hey @kricsleo,
Feel free to open a PR to improve highlighter 🙂 
Contribution is more than welcome
