### ISSUE TITLE
.svg images from markdown not rendered on page change

### ISSUE THREAD

**Issue by moebiusmania** [nuxt/content#2073]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.5.0`
- Nitro Version:    `2.4.1`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `modules`, `nitro`, `content`
- Runtime Modules:  `@nuxt/content@2.6.0`, `@nuxtjs/tailwindcss@6.7.0`
- Build Modules:    `-`

### Reproduction

You can check it here: https://salvatorelaisa.blog/post/v4-nuxt

if you open or refresh the page, the Nuxt logo is visible, if you go back to the home page and navigate to that post, on page change the logo will not be rendered, even though it appears in the final HTML.

### Describe the bug

in this post https://salvatorelaisa.blog/post/v4-nuxt I've added an `.svg` image in the markdown content (it's the Nuxt logo btw...) you can check the source here https://github.com/moebiusmania/salvatorelaisa.blog/blob/main/content/v4-nuxt.md . 

However when navigating from the home page to the post that image will not appear, it will appear if I refresh the page, so I guess there is some rendering quirk in the navigation.

It's not a big deal for me, but since may be a bit more critical for someone else, I just wanted to report this behavior.

thanks

**Comment by farnabaz** [comment]
As I checked this is related to HTML spec. 

> The intrinsic width of the image in pixels. Must be an integer without a unit.
>
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

`width="100%"` is and invalid attribute, the value should not include unit. You can use `style="width=100%"` instead of `width` attribute if you want to make it full width.

I was able to reproduce this issue with Vue itself in HMR

**Comment by moebiusmania** [comment]
@farnabaz thanks mate! in the end the `style="width=100%"` fixes the behavior. I remember you could add the `%` to the value of images `width=""` (_otherwise its only pixels_), but maybe is a thing of the past.

We can consider this solved, thanks again.
