### ISSUE TITLE
Add tab panel MDC support

### ISSUE THREAD

**Issue by Ayanami-Daisuki** [nuxt/content#2088]
### Is your feature request related to a problem? Please describe

I tried to add a tab panel simmilar to the picture below in the rendered HTML page, but:

* I can't control the display of the content in &lt;slot&gt; label by using custom Prose Component.
* Prose Component doesn't support dynamic parameter.
* v-for grammar can't work on  &lt;slot&gt; label or its parent element.

![image](https://github.com/nuxt/content/assets/76685398/73afdb89-69c5-4ac5-8e75-fb5a7ed69905)

### Describe the solution you'd like

the original markdown file looks like:

```markdown
::tabs
---
tabs:
    - tab1
    - tab2
---

#tab1
content of tab1

#tab2
content of tab2
::
```

or like:

```markdown
::tabs

    :: tab{title="tab1"}
    content of tab1
    ::

    ::tab{title="tab2"}
    content of tab2
    ::

::
```

The rendered HTML looks like the picture above.

### Describe alternatives you've considered

I have achieved similar function by [Marked](https://marked.js.org/) , but I need to use `document.querySeletorAll()` to find all tab elements and apply click event handler. the markdown grammar looks like:

```markdown
@tabs

@tab(tab1)
content of tab1
@tab-end

@tab(tab1)
content of tab1
@tab-end

@tabs-end
```

the resolver's code:

```typescript
/* tab panel */
import { marked } from "marked";

const TabsRegex = /^@tabs([\s\S]+?)@tabs-end/;
const TabRegex = /@tab\((.+?)\)/g;


const tabs: marked.TokenizerAndRendererExtension = {

    name: "tabs",
    level: "block",
    start(text) {
        return text.match(/^@tabs[^-]/)?.index;
    },

   /* find all the titles of individual tabs in this tabs panel and pass the result to renderer() below */
    tokenizer(text, _) {
        const result = TabsRegex.exec(text);

        if (result) {
            let temp = TabRegex.exec(result[1]);
            let buttons = [] as Array<marked.Token>;

            while (temp !== null) {
                this.lexer.blockTokens(temp[1], buttons);
                temp = TabRegex.exec(result[1]);
            }

            const token = {
                type: "tabs",
                raw: result[0],
                buttons: buttons,
                content: []
            };
            this.lexer.blockTokens(result[1], token.content);
            return token;
        }
    },

    /* revieve the result and produce HTML */
    renderer(token) {
        return (
            `<div class="post-tabs">` +
            `<div class="post-tabs-buttons">${this.parser.parse(
                token.buttons
            )}</div>` +
            `<div class="post-tabs-content">` +
            this.parser.parse(token.content) +
            `</div>` +
            `</div>`
        );
    }
};
```

### Additional context

I have tried the custom transformer, but I got error when importing `defineTransformer` in Nuxt 3.5.2 with Nitro 2.4.1.

```
Cannot find module '@nuxt/content/transformers' or its corresponding type declarations.
```

**Comment by farnabaz** [comment]
I don't think you need custom transformers to do so
You can create custom component like [CodeGroup](https://github.com/nuxt-themes/elements/blob/main/components/globals/CodeGroup.vue)
Here is an example of CodeGroup usage. You can see that `code-group` has two direct children which will be treated as tabs:

```md
::code-group

```md [index.md]
::hero
  :::card
    A nested card
    ::card
      A super nested card
    ::
  :::
::
\```

  ::code-block{label="Preview"}
    PREVIEW
  ::

::
```

And result (check https://content.nuxtjs.org/guide/writing/mdc code examples):
![Screenshot 2023-05-31 at 16.48.30.png](https://volta.s3.fr-par.scw.cloud/Screenshot_2023_05_31_at_16_48_30_3cb29c3f82.png)

**Comment by farnabaz** [comment]
Nice catch @nobkd 
I didn't think of that 😬
