### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'facetFilters')

### ISSUE THREAD

**Issue by gitFoxCode** [nuxt/content#2094]
### Environment

Similar to https://content.nuxtjs.org/

### Reproduction

 https://content.nuxtjs.org/

### Describe the bug

Even at https://content.nuxtjs.org/
In console: `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'facetFilters')`

This error breaks the entire search engine:
`entry.9c90eddd.js:1 TypeError: Cannot read properties of null (reading 'click')`

**Comment by Baroshem** [comment]
I think there is a bug in the implementation of the DocSearch as it requires indexName and facetFilters variables to be set:

https://github.com/nuxt-modules/algolia/issues/152#issuecomment-1576556998

**Comment by gitFoxCode** [comment]
solved in https://github.com/nuxt-modules/algolia/issues/152#issuecomment-1576642221
