### ISSUE TITLE
internal component ProseCode class attribute seems to be not working

### ISSUE THREAD

**Issue by narasimhajupally** [nuxt/content#2111]
### Environment

- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.6.6
- Builder:          vite
- User Config:      modules, colorMode, css, content, devtools
- Runtime Modules:  @nuxtjs/tailwindcss@6.7.2, @nuxtjs/color-mode@3.2.0, @nuxt/content@2.7.0, nuxt-icon@0.4.1, @nuxt/image@1.0.0-rc.1
- Build Modules:    -

### Reproduction

We can the following warning
```
Vue warn]: Extraneous non-props attributes (class) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <ProseCode class="language-javascript" code="var num1, num2, sum;\nnum1 = prompt(\"Enter first number\");\nnum2 = prompt(\"Enter second number\");\nsum = parseInt(num1) + parseInt(num2); // \"+\" means \"add\"\nalert(\"Sum = \" + sum); // \"+\" means combine into a string\n" language="javascript"  ... > 
  at <AsyncComponentWrapper class="language-javascript" code="var num1, num2, sum;\nnum1 = prompt(\"Enter first number\");\nnum2 = prompt(\"Enter second number\");\nsum = parseInt(num1) + parseInt(num2); // \"+\" means \"add\"\nalert(\"Sum = \" + sum); // \"+\" means combine into a string\n" language="javascript"  ... > 
  at <ContentRendererMarkdown value=
```
clone this repo `https://github.com/narasimhajupally/tailwind-nuxtjs-starter-blog` and go to route `/blog/code-sample`
you will see the warning [Vue warn] in the developer console.

### Describe the bug

classes like `language-javascript` and `language-python` that are needed for syntax highlighting are not coming into effect.`

**Comment by nobkd** [comment]
I also experience this issue on a fresh project without any language set for the code block.

**Comment by helltraitor** [comment]
Inline code highlight maybe enabled with ``` `<code>`{lang=<lang>} ```
```
`const sum = parseInt('1')`{lang=js}
```

```
Vue warn]: Extraneous non-props attributes (class) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <ProseCode class="language-javascript" code="var num1, num2, sum;\nnum1 = prompt(\"Enter first number\");\nnum2 = prompt(\"Enter second number\");\nsum = parseInt(num1) + parseInt(num2); // \"+\" means \"add\"\nalert(\"Sum = \" + sum); // \"+\" means combine into a string\n" language="javascript"  ... > 
  at <AsyncComponentWrapper class="language-javascript" code="var num1, num2, sum;\nnum1 = prompt(\"Enter first number\");\nnum2 = prompt(\"Enter second number\");\nsum = parseInt(num1) + parseInt(num2); // \"+\" means \"add\"\nalert(\"Sum = \" + sum); // \"+\" means combine into a string\n" language="javascript"  ... > 
  at <ContentRendererMarkdown value=
```

This warning happens because you don't use `documentDriven` mode and that is fine. You can ignore it, override by component (with required properties) or omit this warnings by filtering props in passed data (`:value="post"` in your layout)

As for strange colors in your code block: you changes theme, but not background.
Try set dark theme on default mode and you will see.

Solution is to properly use dark modes (like I did, for example)

As a result, this is not problems of @nuxt/content, but your setup

I'm lucky man, because I define all I want by myself and can widely control stuff
```css
.prose :where(pre):not(:where([class~="not-prose"] *)) {}
```
This selector applies dark background and comes from your tailwind.css
I'm not fan of it, so further solution is up on you.

**Comment by nobkd** [comment]
I have a fresh doc-driven project here: https://stackblitz.com/edit/github-gfxckn?file=nuxt.config.ts
The project is highlighted as soon as you uncomment the `highlight` key.
The Vue warn is there in both cases.

**Comment by bobby169** [comment]
I have the same `vue` warn.
```js
[Vue warn]: Extraneous non-props attributes (class) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <ProseCode class="language-html" code="<p>code styling is easy</p>\n" filename="my-first-blog-post.md"  ... > 
```

**Comment by bobby169** [comment]
I try to define the props `class` without warning again
```js
props: {
    .otherProps,
    class: {
      type: String,
      default: "",
    }
}
```

**Comment by narasimhajupally** [comment]
@helltraitor The main problem is `<ProseCode>` component rendering multiple fragments or text root node. It should render a single root node so inheriting the class will work.

**Comment by bobby169** [comment]
> render a single root node so inheriting the class will work

yes you are right, just adding a single root node should work fine.

**Comment by nobkd** [comment]
@farnabaz this still happens in edge-channel.
Example: <https://stackblitz.com/edit/github-zbixzf?file=content%2Findex.md,package.json>
Open the preview in a new tab and look in the console logs.
```jsx
chunk-RAKT47ZN.js:1449 [Vue warn]: Extraneous non-props attributes (class) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <ProseCode class="language-ts" code="let x: number = 0;\n" language="ts"  ... > 
...
  ```
