### ISSUE TITLE
Compile `node.properties` in Markdown Compiler using `gray-matter.data`

### ISSUE THREAD

**Issue by gtnsimon** [nuxt/content#214]
### Is your feature request related to a problem? Please describe.
- I'm using [`content:file:beforeInsert` hook](https://content.nuxtjs.org/advanced#hooks) to fetch a directory with somes `.md` files and transform `document` in hook.
- I filter `document.body.children` to find if any nodes in the document is using a particular element (match based on `node.tag`).
- If so I get `node.props` of elements matching and do some business logic to add properties to `document`.

But for now, `node.props` is just a regular string after compilation (`{ props: { ':items': "[ 'foo', 'bar', 'baz' ]" } }`) (see [Example file](#example-file) below).

I cannot use `node.props.items` as an array until I render the document with `<nuxt-content :document="document" />` and hit my Vue Component.

Being able to access resolved `node.props` from frontmatter at compile time would allow to perform document changes based on nodes properties.

My use case is to add a property to document with all `node.props.items` values (using `Array.reduce`) from matched elements and add some logic when [fetching content](https://content.nuxtjs.org/fetching) or rendering a [Nuxt Page Component](https://nuxtjs.org/guide/views/#pages).

### Describe the solution you'd like
Would it be possible to add syntax for resolving [frontmatter data](https://github.com/nuxt/content/blob/dev/lib/parsers/markdown/index.js#L90) directly in the [remark Compiler](https://github.com/nuxt/content/blob/dev/lib/parsers/markdown/compilers/json.js#L25)?

I think it could be something like Vue template variables. This should not break `<nuxt-content />` props resolving:

```html
<!-- this -->
<my-element :items="{{ items }}"></my-element>
<!-- or this -->
<my-element :single-item="{{ items[0] }}"></my-element>
<!-- or this -->
<my-element v-bind:items="{{ items }}"></my-element>
<!-- or this -->
<my-element v-bind="{{ myObject }}"></my-element>
<!-- or this -->
<my-element v-bind:items="{{ myObject.items }}"></my-element>
<!-- or others way like Vue -->
```

- The Compiler should match properties defined with fences {{ and }} (customizable?) and resolve value between by looking the data object passed along from gray-matter.
- Supporting the dot-nototation path (using [dot-prop](https://www.npmjs.com/package/dot-prop)?)

### Describe alternatives you've considered
- Actually, https://github.com/nuxt/content/issues/88#issuecomment-638185082 mention the fact that variables gets resolved in `<nuxt-content :document="document" />` but I would like to access resolved `node.props` ahead (and would it be more performant if not resolved when rendering but at compile time?).

- I've tried using [remark-variables](https://github.com/mrzmmr/remark-variables) (modifying `Markdown#generateBody()` according to the usage sample and passing data to the method but it is working only in the "body" of the file and not in HTML elements attrs (did I miss something with plugins order?).

- For my use case, it would work with an Event Bus based approch or using `vuex` to store the property values each time the component gets created/mounted in the page but we can avoid doing this king of stuff on client side rendering for performance and because we can already predict the value in hook using some tree searching and adding properties to `document`.

#### Example file

```md
---
items:
  - foo
  - bar
  - baz
---

# My Awesome Page propulsed by @nuxt/content

<!-- What I do -->
<my-element :items="[ 'foo', 'bar', 'baz' ]">
</my-element>

<!-- What I would like do using frontmatter variables -->
<my-element :items="{{ items }}">
</my-element>
```

#### Markdown JSON tree
```js
{
  type: 'root',
  children: [
    {
      type: 'element',
      tag: 'h1',
      props: { id: 'my-awesome-page-propulsed-by-nuxtcontent' },
      children: [
        {
          type: 'element',
          tag: 'a',
          props: {
            ariaHidden: 'true',
            href: '#my-awesome-page-propulsed-by-nuxtcontent',
            tabIndex: -1
          },
          children: [
            {
              type: 'element',
              tag: 'span',
              props: { className: [ 'icon', 'icon-link', [length]: 2 ] },
              children: [ [length]: 0 ]
            },
            [length]: 1
          ]
        },
        {
          type: 'text',
          value: 'My Awesome Page propulsed by @nuxt/content'
        },
        [length]: 2
      ]
    },
    { type: 'text', value: '\n' },
    { type: 'text', value: '\n' },
    // <!-- What I do -->
    {
      type: 'element',
      tag: 'my-element',
      props: { ':items': "[ 'foo', 'bar', 'baz' ]" },
      children: [ { type: 'text', value: '\n' }, [length]: 1 ]
    },
    { type: 'text', value: '\n' },
    { type: 'text', value: '\n' },
    // <!-- What I would like do using frontmatter variables -->
    {
      type: 'element',
      tag: 'my-element',
      props: { items: [ 'foo', 'bar', 'baz' ] }, // here items get resolved by the Compiler
      children: [ { type: 'text', value: '\n' }, [length]: 1 ]
    },
    [length]: 7
  ]
}
```

Thank you for your time 😄 

I'll be glad to see this feature added to `@nuxt/content` ❤️

**Comment by benjamincanac** [comment]
Hey @gtnsimon,

Have you tried doing:

```md
---
items:
  - foo
  - bar
  - baz
---

# My Awesome Page propulsed by @nuxt/content

<my-element :items="items"></my-element>
```

https://content.nuxtjs.org/writing#vue-components

**Comment by gtnsimon** [comment]
Hi @benjamincanac,

I did tried this way, which works well when `<nuxt-content :document="document" />` is called. My component gets hydrated:

![image](https://user-images.githubusercontent.com/8135290/86367320-14d9b500-bc7c-11ea-9d4e-8fde9eff4fbf.png)

But I would like to get the value ahead of rendering, 

- My file:

```markdown
---
items:
  - foo
  - bar
  - baz
---

<my-element :items="items"></my-element>
```

- My module:

```js
// ~/modules/transform-document/index.js

this.nuxt.hook('content:file:beforeInsert', function document (document) {

  console.log(require('util').inspect(document.body, false, null, true))

})

// output of console.log

{
  type: 'root',
  children: [
    {
      type: 'element',
      tag: 'my-element',
      props: { ':items': 'items' },
      children: [ { type: 'text', value: '\n' }, [length]: 1 ]
    },
    [length]: 1
  ]
}
```

As you can see, `root.children[0].props` is not yet resolved to an `Array`.

So I cannot access the real value of `items` which is defined in frontmatter and iterate over to do some logic over it.

**Comment by benjamincanac** [comment]
@gtnsimon You can actually access front-matter data from the document directly. You don't have to parse the document body:

```js
this.nuxt.hook('content:file:beforeInsert', function (document) {
// document.items
})
```

Here is the documentation for front-matter: https://content.nuxtjs.org/writing#front-matter
