### ISSUE TITLE
Allow to disable automatic usage of `useContentHead`

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/content#2141]
### Is your feature request related to a problem? Please describe

Currently, it's not clear if `nuxt/content` must provide SEO out-of-the box. Current status is in the middle of no SEO and SEO ready (and that's strange but clearly understandable when we look back).

But this behavior can interfere with others modules like nuxt-seo-kit (and submodules) from @harlan-zw.

### Describe the solution you'd like

I think that having this little default is great but for advanced users, allowing to disable completely usage of `useContentHead` could allow to setup custom SEO in the application.

**Comment by harlan-zw** [comment]
FWIW there are some changes on both sides to allow nuxt-seo-kit and nuxt/content to work better.

I think an opt-out is a good idea either way though.

**Comment by Jannchie** [comment]
We can disable `useContentHead` with the following prop
```vue
<ContentDoc :head="false" />
```
