### ISSUE TITLE
Enable use hyphen in path folder

### ISSUE THREAD

**Issue by Jannchie** [nuxt/content#2162]
### Is your feature request related to a problem? Please describe

Currently, using hyphens in the path folder causes routing errors (e.g. /content/zh-CN/xxx).
I wish I could use it.

**Comment by nobkd** [comment]
As far as I see, the hyphen is working correctly.
Your problem is probably that you are trying to use the path with uppercase characters.
You can use them in the folder path, but for the URL they are replaced with their lowercase counterpart.

- Folder path: `/content/zh-CN/xxx`
- URL path: `/zh-cn/xxx`

Here's an example: https://stackblitz.com/edit/github-2w2g9r?file=content%2Findex.md

---

If you really are experiencing problems with the hyphen, please create a reproduction.

**Comment by Jannchie** [comment]
Thanks for the reply.

I've found that the problem only occurs when there is a non-index.md, see this:
https://stackblitz.com/edit/github-2w2g9r-pow71d?file=content%2Ftest-2%2Findex.md

**Comment by nobkd** [comment]
I can still open all routes without problems.
Can you describe what steps I have to follow to experience your issue?
What exactly are your routing errors? Do you have a log or error message?

**Comment by Jannchie** [comment]
https://github.com/nuxt/content/assets/29743310/e000ee83-0798-4033-8731-5c077508f38c

I made a screen record, there is only 404 error in console.

**Comment by Jannchie** [comment]
There is also a warning: [nuxt] Calling `useRoute` within middleware may lead to misleading results. Instead, use the (to, from) arguments passed to the middleware to access the new and old routes.

**Comment by nobkd** [comment]
The `useRoute` warning is quite interesting but seems to have no relevance for this issue.

**Comment by nobkd** [comment]
I did not find some global configuration for this, but here is a possible (not o great) solution:

---

You can do it for single files by overriding the `_path` key in the front-matter of a file:

`content/zh-CN/index.md`:
```yml
---
_path: /zh-CN
---
```

`content/zh-CN/test.md`:
```yml
---
_path: /zh-CN/test
---
```

---

I **thought** it would be possible for a **directory** by adding
```
_path: /zh-CN
```
to the `_dir.yml` of a path (in this case to `content/zh-CN/_dir.yml`), but this does **not** seem to work

**Comment by Barbapapazes** [comment]
> The `useRoute` warning is quite interesting but seems to have no relevance for this issue.

Yes, it's something else related to the middleware inject for documentDriven mode.

**Comment by Barbapapazes** [comment]
> I see... Thank you for clarifying the point. Is there a way to use uppercase letters in paths?

There is a way in this file https://github.com/nuxt/content/blob/2ee6de5cae3285d2fc30e72ef533d7e22a06f973/src/runtime/transformers/path-meta.ts#L70. You can open a PR to enable a flag from the setting.

**Comment by Jannchie** [comment]
> You can open a PR to enable a flag from the setting.

I'm trying to make a pr!

**Comment by Barbapapazes** [comment]
> > You can open a PR to enable a flag from the setting.
> 
> I'm trying to make a pr!

Don't hesitate to ping me if you need help!
