### ISSUE TITLE
[Feature request] Built in support for images under content dir

### ISSUE THREAD

**Issue by DevDengChao** [nuxt/content#2163]
### Is your feature request related to a problem? Please describe

I'm migrating a blog project from VuePress to Nuxt Content, in order to group related files together, I used to put some png images under `_posts` dir, eg: `_post/awesome-title/example.png`, so that I can use it as `./example.png` inside `_post/awesome-title/index.md`.

When migrating, I found Nuxt Content does not support images under `content` dir by default, which means I have to move those images to `public` dir and update the references one by one, or I have to write a transformer myself to support this feature.

### Describe the solution you'd like

Nuxt Content should be able to handle images under `content` dir by default.

### Describe alternatives you've considered

There is a more detailed examples/guide on how to write a proper transformer.

The transformer example shows how to parse a .names file, but it doesnot render it properly when you visit http://localhost:3000 :
`{ "_path": "/", "_dir": "", "_draft": false, "_partial": false, "_locale": "", "_id": "content:1.index.names", "body": [ "Jason", "Jessi", "Joes", "John" ], "title": "", "_source": "content", "_file": "1.index.names", "_extension": "names" }`

**Comment by nobkd** [comment]
You can try making a PR for that.

For the time being, you can use [Nuxt Content Assets](https://github.com/davestewart/nuxt-content-assets/#readme) as mentioned in https://github.com/nuxt/content/issues/106#issuecomment-1496045254
There should also be other solutions in the same issue.
