### ISSUE TITLE
in documents, filename "[...slug].vue" above code block display not correctly

### ISSUE THREAD

**Issue by 13ruceYu** [nuxt/content#2166]
### Environment

- Operating System: Darwin
- Node Version:     v16.18.0
- Nuxt Version:     0.0.0
- Nitro Version:    -
- Package Manager:  PNPM
- Builder:          webpack
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://content.nuxtjs.org/api/components/content-doc#contentdoc

### Describe the bug

<img width="1166" alt="image" src="https://github.com/nuxt/content/assets/32187085/508c0178-e570-4b9e-ac33-c9f024aff929">

**Comment by 13ruceYu** [comment]
I am willing to fix it; however, some CSS styles are not loading properly in my local development environment.
<img width="1512" alt="image" src="https://github.com/nuxt/content/assets/32187085/b9e81a44-8202-4a4e-8074-fd6aa6c4ff11">

**Comment by Atinux** [comment]
Could it be related to the internal parser @farnabaz ?

**Comment by nobkd** [comment]
![](https://user-images.githubusercontent.com/32187085/252948648-508c0178-e570-4b9e-ac33-c9f024aff929.png)

This part is related to the parser, as we use a regex to extract the file name from the square brackets. It matches up to the first closing bracket.

Here's the regex code:
https://github.com/nuxt/content/blob/2ee6de5cae3285d2fc30e72ef533d7e22a06f973/src/runtime/markdown-parser/handler/utils.ts#L23
That is a case we didn't think of.

**Comment by Barbapapazes** [comment]
Yes, css fail to load 
![image](https://github.com/nuxt/content/assets/45267552/7a084415-1b75-475e-9567-d9072d47be15)
