### ISSUE TITLE
Copy yo clipboard when clicking on a ParseCode

### ISSUE THREAD

**Issue by wJoenn** [nuxt/content#2171]
### Is your feature request related to a problem? Please describe
I'd like to copy the content of the ParseCode component when clicking on it

### Describe the solution you'd like
I created a function that does just that. It's using `addEventListener` atm because I can't add a `@click` handler on the component itself without modifying the node_modules but that could easily be done to clean the code a bit
```vue
<script setup lang="ts">
  const copyToClipboard = (pre: HTMLPreElement) => {
    const lines = pre.querySelectorAll(".line") as NodeListOf<HTMLSpanElement>
    const snippet = Array.from(lines).map(line => {
      const spans = Array.from(line.childNodes) as HTMLSpanElement[]

      return spans.map(span => span.innerText).join("")
    })

    navigator.clipboard.writeText(snippet.join(""))
  }

  const handleClickEvent = (event: MouseEvent) => {
    const pre = event.currentTarget as HTMLPreElement

    copyToClipboard(pre)
    updatePreBeforeContent(pre)
  }

  const updatePreBeforeContent = (pre: HTMLPreElement) => {
    pre.classList.add("copied")

    pre.addEventListener("mouseleave", () => {
      pre.classList.remove("copied")
    })
  }

  onMounted(() => {
    const pres = document.querySelectorAll("pre")

    pres.forEach(pre => {
      pre.addEventListener("click", handleClickEvent)
    })
  })
</script>

<style scoped lang="scss">
  pre {
    position: relative;
    
    &.copied::before {
      content: "copied";
    }

    &::before {
      content: "copy";
      color: #e3e3e3;
      position: absolute;
      bottom: 10px;
      right: 10px;
      font-size: 0.8rem;
      opacity: 0;
    }

    &:hover::before {
      opacity: 1;
    }
  }
</style>
```

https://github.com/nuxt/content/assets/75388869/58844d4d-972f-4310-987e-de0bc0c58eb5

### Describe alternatives you've considered
None

**Comment by nobkd** [comment]
You should be able to collect the needed code from the following links. They use a copy button, but I think you can implement it similar to that.

---

[Nuxt Themes Typography Module](https://typography.nuxt.space/) overrides prose code and adds a copy button to the generated code block.
- [`<ProseCode>` override code](https://github.com/nuxt-themes/typography/blob/main/components/global/ProseCode.vue)
- [`<ProseCodeCopyButton>` code](https://github.com/nuxt-themes/typography/blob/main/components/ProseCodeCopyButton.vue)

---

Reference: https://github.com/nuxt/content/discussions/2072#discussioncomment-5957652

**Comment by wJoenn** [comment]
Is there a way for me to create a ProseCode component that would overrides the original one too ?
That'd allow me to do whatever I want without having to fork the repo, it'd be great

**Comment by nobkd** [comment]
Sure. Just put your component with the name ProseCode.vue somewhere in the components/content/ directory

See: https://content.nuxtjs.org/api/components/prose
Third paragraph

**Comment by wJoenn** [comment]
Ohhh Nice. I've read that page 3 times and never actually read the first paragraphs 😓 
Thanks for the links about Topography too, you're right I did see some stuff in there that looks very interesting. I've discovered some Vue composables I had never heard of and they'll probably help.

Cheers Nobkd !
