### ISSUE TITLE
useStorage is not defined when using within nuxt hooks (build time)

### ISSUE THREAD

**Issue by BernardoSM** [nuxt/content#2182]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      extends, nitro
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-kwfyia-u6a3ma?file=app.vue

### Describe the bug

**My main goal is read a github repository, read a .types.d.ts file and add those types to my nuxt project.**

I added nitro config within nuxt.config.ts

```js
...
nitro: {
  storage: {
    github: {
      driver: 'github',
      repo: 'elk-zone/elk',
      branch: 'main',
      dir: '/types',
     },
   },
 }
 ...
```

I created a file within `/server/plugins` and added the code below to read `types.ts` file and it's working fine

```js
export default defineNitroPlugin(async (nitroApp) => {
  const storage = await useStorage().getItem('github:index.ts');
  console.log({ storage });
});
```

But when I try to use the same useStorage function within ['prepare:types' nuxt hook](https://nuxt.com/docs/api/advanced/hooks#nuxt-hooks-build-time), it's saying ` ERROR  useStorage is not defined`.

Is there anyway to use nitro functions (runtime hooks) inside nuxt build hooks? Or is there anyway to achieve my goal?

**Comment by Barbapapazes** [comment]
Hello,

Here a way to solve your issue https://stackblitz.com/edit/github-kwfyia-rhcbwd?file=modules%2Fgithub.ts

In fact, composables are not defined here but you can access to Nitro properties using the correct hook. Ping me if you have some questions about the code.

**Comment by BernardoSM** [comment]
Hi @Barbapapazes thanks for you help,

I didn't know about nuxt modules and that was very helpful. I also didn't need to use `prepare:types`, I could just use [addTypeTemplate](https://nuxt.com/docs/guide/going-further/modules#adding-type-declarations) within `/modules/github.ts` like the code below and it worked!

```ts
import { defineNuxtModule, addTypeTemplate } from '@nuxt/kit';

export default defineNuxtModule({
  async setup(options, nuxt) {
    let storage: string | null = null;

    nuxt.hooks.hook('nitro:init', async (nitro) => {
      storage = await nitro.storage.getItem('github:index.ts');

      console.log(storage)

      addTypeTemplate({
        filename: 'types/rise-api.d.ts',
        getContents: () => storage ? storage : ''
      })
    });
  },
});
```
