### ISSUE TITLE
Failed to resolve component: ContentDoc

### ISSUE THREAD

**Issue by gabrielfojo** [nuxt/content#2184]
### Environment

https://stackblitz.com/github/nuxt/starter/tree/content

### Reproduction

https://stackblitz.com/github/nuxt/starter/tree/content

### Describe the bug

This can be seen in the StackBlitz code , CodeSanboz it's working - It seems that Nuxt 3.6.4 is the problem

**Comment by nobkd** [comment]
https://github.com/nuxt/nuxt/releases/tag/v3.6.5

> 3.6.5 is a hotfix patch release addressing the regression with nuxt/content introduced in v3.6.4.

**Comment by Barbapapazes** [comment]
Is it the same as #2185?

**Comment by nobkd** [comment]
I don't think so, because the version stated there is already `3.6.5`.

But maybe force updating with `nuxi upgrade --force` (to remove `node_modules` and `.nuxt` directories) could help.

**Comment by cossssmin** [comment]
I'm still seeing this with Nuxt 3.6.5 when developing locally:

<img width="455" alt="image" src="https://github.com/nuxt/content/assets/1656595/24720dc0-0796-4887-a9b6-8431554e9c80">

Using it with or without the `path` prop, same error - this is what I have:

```vue
<template>
  <div>
    <ContentDoc 
      path="/privacy"
	  class="mx-auto prose prose-slate"
    />
  </div>
</template>
```

**Comment by wangzhaohe** [comment]
With "nuxt": "^3.6.5", still Failed to resolve component: ContentDoc 

```
[Vue warn]: Failed to resolve component: ContentDoc                                                                              5:56:08 AM
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
hello from middleware auth.ts                                                                                                    5:56:08 AM
Hello World!                                                                                                                     5:56:08 AM
[Vue warn]: Component <Anonymous> is missing template or render function.    
```
