### ISSUE TITLE
Markdown content not rendering in nested page folder

### ISSUE THREAD

**Issue by jofftiquez** [nuxt/content#2186]
### Environment

![image](https://github.com/nuxt/content/assets/8638243/6d9971db-06ca-43fb-9238-0ae13b60a0d5)

Nuxi 3.6.5                                                                                          6:30:00 PM
                                                                                                    6:30:00 PM
RootDir: /Users/centipede/Documents/workspace/personal/vue-stripe/vuestripe.com                     6:30:00 PM
Nuxt project info: (copied to clipboard)                                                            6:30:00 PM

------------------------------
- Operating System: Darwin
- Node Version:     v16.18.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      preset, imports, modules, gtag, srcDir, runtimeConfig, plugins, app, tailwindcss, headlessui, build, image, devtools
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, nuxt-headlessui@1.1.4, nuxt-gtag@0.5.7, @nuxt/content@2.7.1
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                         6:30:00 PM

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/github-r4ywwf?file=pages%2Fdocs%2F[...slug].vue

### Describe the bug

I was expecting the markdown content to be rendered if the `[...slug].vue` is on a nested page. 

```
src
  |- content
    |- index.md
    |- about.md
  |- pages
    |- docs
      |- [...slug].vue
    |- index.vue // I want to have a custom home page
```

I originally want to have a normal custom landing page `pages/index.vue` and have the markdown content under `pages/docs/*`

However I am getting this error:

> Document not found, overwrite this content with #not-found slot in <ContentDoc>.

### Logs

```Shell
Nuxi 3.6.5                                                                                         6:33:41 PM
Nuxt 3.6.5 with Nitro 2.5.2                                                                        6:33:41 PM
                                                                                                   6:33:42 PM
  > Local:    http://localhost:3000/
  > Network:  http://192.168.3.248:3000/

ℹ Using Tailwind CSS from ~/assets/css/tailwind.css                               nuxt:tailwindcss 6:33:42 PM
✔ Nuxt Devtools is enabled v0.6.4 (experimental)                                                   6:33:43 PM
ℹ Tailwind Viewer: http://localhost:3000/_tailwind/                               nuxt:tailwindcss 6:33:43 PM
🌼 daisyUI 3.2.1 https://daisyui.com                                                               6:33:44 PM
╰╮                                                                                                 6:33:44 PM
 ╰─ ✔︎ [ 29 ] themes are enabled. You can add more themes or make your own theme:                  6:33:44 PM
      https://daisyui.com/docs/themes
                                                                                                   6:33:44 PM
    ❤︎ Support daisyUI: https://opencollective.com/daisyui
🌼 daisyUI 3.2.1 https://daisyui.com                                                               6:33:44 PM
╰╮                                                                                                 6:33:44 PM
 ╰─ ✔︎ [ 29 ] themes are enabled. You can add more themes or make your own theme:                  6:33:44 PM
      https://daisyui.com/docs/themes
                                                                                                   6:33:44 PM
    ❤︎ Support daisyUI: https://opencollective.com/daisyui
ℹ Vite client warmed up in 1963ms                                                                 6:33:45 PM
✔ Nitro built in 1081 ms                                                                    nitro 6:33:46 PM
route docs-slug                                                                                    6:33:47 PM
route docs-slug                                                                                    6:33:47 PM
```

**Comment by Barbapapazes** [comment]
Hello, 

To fix your issue, you have to move your `index.md` and `about.md` inside a `docs` folder since `ContentDoc` use `$route.path` to find which content to fetch (https://content.nuxtjs.org/api/components/content-doc#contentdoc).

Hope it will help you!

Here the solution https://stackblitz.com/edit/github-r4ywwf-8epkrk?file=content%2Findex.md

**Comment by jofftiquez** [comment]
> Hello,
> 
> To fix your issue, you have to move your `index.md` and `about.md` inside a `docs` folder since `ContentDoc` use `$route.path` to find which content to fetch ([content.nuxtjs.org/api/components/content-doc#contentdoc](https://content.nuxtjs.org/api/components/content-doc#contentdoc)).
> 
> Hope it will help you!
> 
> Here the solution [stackblitz.com/edit/github-r4ywwf-8epkrk?file=content%2Findex.md](https://stackblitz.com/edit/github-r4ywwf-8epkrk?file=content%2Findex.md)

Thank you @Barbapapazes closing this now! 💪
