### ISSUE TITLE
Unexpected non-props attributes falling-through when using ContentRenderer

### ISSUE THREAD

**Issue by TechAkayy** [nuxt/content#2208]
### Environment

Nuxi 3.6.5                                                                                                                                                                       1:03:30 PM
                                                                                                                                                                                 1:03:30 PM
RootDir: /Users/techakayy/Templates/happy-paws-with-nuxt-tailwindcss                                                                                                             1:03:30 PM
Nuxt project info: (copied to clipboard)                                                                                                                                         1:03:30 PM

------------------------------
- Operating System: Darwin
- Node Version:     v18.12.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@8.19.2
- Builder:          vite
- User Config:      runtimeConfig, modules, pinegrow, css, postcss, content, unocss
- Runtime Modules:  @pinegrow/nuxt-module@3.0.3, @unocss/nuxt@0.54.1, @nuxt/devtools@0.7.1, @nuxt/content@2.7.2, @vueuse/nuxt@10.3.0
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/pinegrow/happy-paws-with-nuxt-tailwindcss

The warnings are thrown only during development. In prod build, the document seems to render fine, https://happy-paws-with-nuxt-tailwindcss.netlify.app/, though the warning makes us wonder if we have got something wrong. Please advise me of any incorrect usage in the below explained context. 

### Describe the bug

1. Clone the above repo, install dependencies, and start dev-server `npm run dev`
2. Open app in browser, and have browser devtools console open
3. Navigate to a blog post (under hamburger menu), for eg. `http://localhost:3000/blog/vue-3-3`
4. The following unexpected warnings are thrown 

<img width="1346" alt="image" src="https://github.com/nuxt/content/assets/73772701/d0c2c0ef-873b-40bf-ba56-c2808faf109a">

### Additional context

In `pages/blog/[...slug].vue`, I'm using the ContentRenderer component to render a document coming from a query. I'm not passing any classes to this component, just the post (second screenshot). 

![image](https://github.com/nuxt/content/assets/73772701/b8f3266f-ee8f-4b1b-9473-b784708d0d10)

<img width="911" alt="image" src="https://github.com/nuxt/content/assets/73772701/87e181a9-c5e0-41ae-9c86-4bace6872906">

### Logs

```Shell
Thanks for looking into this.
```

**Comment by TechAkayy** [comment]
Thxs bunch for the update 😀

**Comment by farnabaz** [comment]
Fixed in 2.8.

**Comment by TechAkayy** [comment]
Thank u 🙏🏾
