### ISSUE TITLE
Add ProseIframe Prose Component

### ISSUE THREAD

**Issue by ejfox** [nuxt/content#2219]
### Is your feature request related to a problem? Please describe
I want to add responsive styling to user-added iframes such as YouTube videos.

### Describe the solution you'd like
When a user adds an iframe, parse it through the iframe prose component to add my own styling and responsive behavior that overwrites the default iframe styling. 

### Describe alternatives you've considered
Right now I do responsive styling / responsive code fixes to embeds before including in markdown but this is brittle and easy for non-technical users to break.

### Additional context
Maybe there is a better, more elegant solution to handling social media embeds, or maybe that belongs in another library- I'd be interested in helping solve the problem wherever, I just need to understand where it belongs in the ecosystem

**Comment by farnabaz** [comment]
You can simply add `ProseIframe` to `content.markdown.tags` in `nuxt.config.ts` and create `ProseIframe` component
```ts
export default defineNuxtConfig({
  content: {
    markdown: {
      tags: { iframe: 'ProseIframe' }
    }
  }
})
```
