### ISSUE TITLE
Open source nuxt-mdc?

### ISSUE THREAD

**Issue by fanzeyi** [nuxt/content#2220]
### Is your feature request related to a problem? Please describe

It looks like [`nuxt-mdc-edge`](https://www.npmjs.com/package/nuxt-mdc-edge) does not actually have a repository on GitHub.

The package listed [`github.com/nuxtlabs/nuxt-mdc`](https://github.com/nuxtlabs/nuxt-mdc) as the repository but that URL is invalid (at least it is not publicly accessible).

Admittedly the source is still accessible on npmjs.com, but I wonder if this is simply an oversight -- the LICENSE file attached to the package declare it being MIT.

### Describe the solution you'd like

Open source `nuxt-mdc` somewhere.

### Describe alternatives you've considered

N/A

**Comment by Atinux** [comment]
It's planned as soon as we have the docs for it 😄

**Comment by nobkd** [comment]
I hope that also goes for [`remark-mdc`](https://www.npmjs.com/package/remark-mdc) ([`github.com/nuxtlabs/remark-mdc`](https://github.com/nuxtlabs/remark-mdc))?

**Comment by maximepvrt** [comment]
I would also need the Nuxt MDC source to be available. I have a contribution that was ready to go as of v2.7.x, but I'm unable to create a Merge Request due to its impact on the MDC template. Looking forward to the availability of Nuxt MDC integration. 😅

**Comment by farnabaz** [comment]
🎉  We've just made `nuxt-mdc` open source, which has now been renamed to `@nuxtjs/mdc`. You can find the repository here: https://github.com/nuxt-modules/mdc

🎉  Additionally, we've also open sourced `remark-mdc`, and its repository can be accessed at: https://github.com/nuxtlabs/remark-mdc
