### ISSUE TITLE
Cannot style .nuxt-content

### ISSUE THREAD

**Issue by nomadoda** [nuxt/content#225]
### Version
@nuxt/content: 1.4.1
nuxt: 2.13.3

Cannot add custom style on `.nuxt-content`.

It worked fine in version `^1.2`.

I believe it's related to root element having class `.nuxt-content-container` instead.

### Steps to reproduce

Add a custom style

```
<style lang="scss" scoped>
  .nuxt-content {
    h1 {
      color: red;
    }
  }
</style>
```

### What is Expected?

A styled `h1` tag as documented [here](https://content.nuxtjs.org/displaying#style).

### What is actually happening?

No styles are applied.

### Workaround

```
<style lang="scss" scoped>
  ::v-deep .nuxt-content {
    h1 {
      color: red;
    }
  }
</style>
```

**Comment by benjamincanac** [comment]
Hey @nomadoda,

You have to remove `scoped`, it prevents css to apply on child components: https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements.
