### ISSUE TITLE
Global Components not rendering in MD Files

### ISSUE THREAD

**Issue by mrniamster** [nuxt/content#2256]
### Environment

Operating System: Darwin
Node Version: v20.5.1
Nuxt Version: 3.7.0
CLI Version: 3.7.0
Nitro Version: 2.6.1
Package Manager: npm@9.8.0
Builder: -
User Config: experimental, css, ssr, nitro, app, modules, devtools
Runtime Modules: @pinia/nuxt@0.4.11, @nuxt/content@2.7.2, @vueuse/nuxt@10.4.0, @vuestic/nuxt@1.0.14
Build Modules: -

### Reproduction

https://stackblitz.com/edit/github-khexbq-kzlgbg?file=nuxt.config.ts,components%2FAlert.vue,app.vue,content%2Fhello.md,package.json

### Describe the bug

The Auto loading - Global Components are not rendering on the MD files from .nuxt/componenets , example for   UI library's

### Additional context

I don't think its a nuxt issue, tried it on nuxt.3.6.5 too, still the same. Happening on the new Version of nuxt/Content

**Comment by farnabaz** [comment]
You need to create `[...slug].vue` under `pages` directory.

Checkout https://stackblitz.com/edit/github-khexbq-gc8xmz?file=nuxt.config.ts,components%2FAlert.vue,app.vue,pages%2F%5B...slug%5D.vue,content%2Findex.md

**Comment by mrniamster** [comment]
Hi @farnabaz  but it still doesn't renders the "Alert" Component

<img width="1081" alt="image" src="https://github.com/nuxt/content/assets/52563039/4d303ac3-4ef1-4d51-9081-d27bebe200e0">

**Comment by nobkd** [comment]
Your `<Alert>` component isn't global...
You have to set the `components/` folder to be global, or move your component to another global folder. E.g. `components/content` or `components/global`

> See the second code block in this section:
https://nuxt.com/docs/guide/directory-structure/components#dynamic-components
> > Alternatively, though not recommended, you can register **all your components globally**, which will create async chunks for all your components and make them available throughout your application.


See https://github.com/nuxt/content/issues/2198#issuecomment-1654642086 (and #2155)

**Comment by m0ksem** [comment]
> Hello @nobkd Generally adding the Componenets inside `components/` makes components accessbile all over the code in nuxt.
> 
> Basically the main question here is When we use ui library like Quasar / Vuestic ([ui-develop.vuestic.dev/ui-elements/data-table](https://ui-develop.vuestic.dev/ui-elements/data-table))
> 
> I want to use them inside the Markdwon files, Do you know how to do it here ? Take this alert UI Component for instance : [ui-develop.vuestic.dev/ui-elements/alert](https://ui-develop.vuestic.dev/ui-elements/alert)

Hi, @mrniamster. You need to place your Alert component under components/content folder to make it work in md files.

As for UI lib components... At least in Vuestic UI we're not registering components as `global`, because I assume it will increase bundle size. 

You can manually register components globally directly from `vuestic-ui` or make a new component which uses component from library in `components/content` folder.


Here is an example:
https://stackblitz.com/edit/github-w9ys9s?file=components/content/Alert.vue,components/content/MyAlert.vue

**Comment by nobkd** [comment]
> Generally adding the Components inside `components/` makes components accessbile all over the code in nuxt.

To explain why you need to set your `components/` folder to be global, **or** you have to *move* your component to a `global` folder:
Other code parts of the project use [auto-importing](https://nuxt.com/docs/guide/concepts/auto-imports), but those don't work from Markdown, YAML, etc..., therefore you have to add them by [making them global](https://content.nuxtjs.org/guide/writing/vue-component#global-components-in-nuxt).
Making components global, ensures that they are included in the main bundle (currently as [async loaded chunks](https://nuxt.com/docs/guide/directory-structure/components#dynamic-components) (see paragraph before second code block)), so your Markdown is rendered out correctly.

**Comment by nobkd** [comment]
A great solution for using VuesticUI components in Markdown would be the following, **which sadly does not work**:

<details>
<summary>Show not working code</summary>

```ts
//nuxt.config.ts
export default defineNuxtConfig({
  modules: ['@nuxt/content', '@vuestic/nuxt'],

  components: {
    dirs: [
      { path: '~/node_modules/vuestic-ui/dist/web-components/src/components/', global: true },
    ],
  },
  // ...
}
```

</details>

**Comment by m0ksem** [comment]
> > Generally adding the Components inside `components/` makes components accessbile all over the code in nuxt.
> 
> To explain why you need to set your `components/` folder(, or the folder where your components used in Markdown are in), to be global, **or** you have to *move* your component to a `global` folder:
> Other code parts of the project use [auto-importing](https://nuxt.com/docs/guide/concepts/auto-imports), but those don't work from Markdown, YAML, etc..., therefore you have to add them by [making them global](https://content.nuxtjs.org/guide/writing/vue-component#global-components-in-nuxt).
> Making components global, ensures that they are included in the main bundle (currently as [async loaded chunks](https://nuxt.com/docs/guide/directory-structure/components#dynamic-components) (see paragraph before second code block)), so your Markdown is rendered out correctly.

Maybe we can analyze which components are used in .MD and register them globally before rendering markdown?

**Comment by mrniamster** [comment]
> > > Generally adding the Components inside `components/` makes components accessbile all over the code in nuxt.
> > 
> > 
> > To explain why you need to set your `components/` folder(, or the folder where your components used in Markdown are in), to be global, **or** you have to _move_ your component to a `global` folder:
> > Other code parts of the project use [auto-importing](https://nuxt.com/docs/guide/concepts/auto-imports), but those don't work from Markdown, YAML, etc..., therefore you have to add them by [making them global](https://content.nuxtjs.org/guide/writing/vue-component#global-components-in-nuxt).
> > Making components global, ensures that they are included in the main bundle (currently as [async loaded chunks](https://nuxt.com/docs/guide/directory-structure/components#dynamic-components) (see paragraph before second code block)), so your Markdown is rendered out correctly.
> 
> Maybe we can analyze which components are used in .MD and register them globally before rendering markdown?

This sounds a good idea @m0ksem , & will also not affect the bundle size

**Comment by mrniamster** [comment]
> Maybe we can analyze which components are used in .MD and register them globally before rendering markdown?
This sounds a good idea @m0ksem , & will also not affect the bundle size

**Comment by emhoracek** [comment]
As someone new to Nuxt, I ran into this and was confused because usually components are auto-imported. I would love it if the docs spelled out that you should make a `content` directory inside `components` to put components that are used in the MDC files.

**Comment by nobkd** [comment]
@emhoracek 
See:
https://content.nuxtjs.org/guide/writing/vue-component
https://content.nuxtjs.org/guide/writing/mdc#block-components

If you have an idea where else in the docs it should be mentioned, you could make a pull request :)

**Comment by emhoracek** [comment]
> @emhoracek See:
> 
>     * https://content.nuxtjs.org/guide/writing/vue-component
> 
>     * https://content.nuxtjs.org/guide/writing/mdc#block-components
> 
> 
> If you have an idea where else in the docs it should be mentioned, you could make a pull request :)

I did see these! My confusion was about what "global" meant. When you click on the links provided to the Nuxt docs, they take you to [https://nuxt.com/docs/guide/directory-structure/components](https://nuxt.com/docs/guide/directory-structure/components). This page says:

> Nuxt automatically imports any components in your [components/ directory](https://nuxt.com/docs/guide/directory-structure/components) (along with components that are registered by any modules you may be using). 

I assumed that this meant that the components in my "components" directory *were* globally available. Nuxt's actually definition of "global" is only in the later section on "Dynamic Components". Since I'm new to Nuxt and Vue, I didn't realize that Content uses Dynamic Components. 

I'll try making a pull request to make this more explicit.

**Comment by nobkd** [comment]
Yeah. Good that you mention it. I've also seen some other people struggle with the meaning of `global` vs `auto-imported` components.
Sounds like a good idea to explicitly state the difference.
