### ISSUE TITLE
Prose examples deleted - Official Documentation

### ISSUE THREAD

**Issue by paurosellfarre** [nuxt/content#2258]
Description:
"Prose" customization examples have been removed in the recent commit: https://github.com/nuxt/content/commit/3db06b23cb52c392690765b2b312fef360e1cc9d

As you can see, if you click on "Source" button from official documentation, it redirects to 404:
https://content.nuxtjs.org/api/components/prose#proseli

![image](https://github.com/nuxt/content/assets/96744558/52b5404e-dfc2-45b2-98db-64830dedc111)

Redirects to:
https://github.com/nuxt/content/tree/main/src/runtime/components/Prose/ProseLi.vue

**Comment by nobkd** [comment]
This will probably be fixed when `nuxt-mdc` is made public.

For the time being, you can look up the latest code here:
<https://www.npmjs.com/package/nuxt-mdc-edge?activeTab=code>
with this path: `/nuxt-mdc-edge/dist/runtime/components/prose/`

**Comment by farnabaz** [comment]
Sorry for the inconvenient
As @nobkd said, The links will be targeted to the `nuxt-mdc` repo once it made public.
Meanwhile, I updated the docs to point the link to the `2.x` repo.
