### ISSUE TITLE
Console warning when overwriting a Prose Component

### ISSUE THREAD

**Issue by leopoldkristjansson** [nuxt/content#2262]
### Environment

- Operating System: Darwin
- Node Version:     v16.17.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.2
- Nitro Version:    2.6.2
- Package Manager:  npm@9.6.4
- Builder:          -
- User Config:      modules, typescript, experimental, app, content, image, css, vite
- Runtime Modules:  @vueuse/nuxt@10.4.1, @nuxt/content@2.7.2, @nuxt/image@1.0.0-rc.1, @pinia/nuxt@0.4.11
- Build Modules:    -

### Reproduction

Add the file `/components/content/ProseCode.vue` and do `npm run dev`.

See stackblitz below:

https://stackblitz.com/edit/github-oh8wfi?file=components%2Fcontent%2FProseCode.vue

<img width="1719" alt="Screenshot 2023-08-29 at 00 16 58" src="https://github.com/nuxt/content/assets/2579324/0368f801-6680-4241-8a02-55543e11e6f0">

### Describe the bug

I am now getting the following warning that I did not get before upgrading to Nuxt 3.7

```
 WARN  [nuxt] Two component files resolving to the same name ProseCode:             

 - /PROJECT_DIR/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue
 - /PROJECT_DIR/components/content/ProseCode.vue
```

According to the Nuxt Content docs, adding a component with the same name is the correct way of overwriting it, no?

From the docs: _To overwrite a prose component, create a component with the same name in your project components/content/ directory (ex: components/content/ProseA.vue)_

Prose Components docs: https://content.nuxtjs.org/api/components/prose

**Comment by manniL** [comment]
These warnings can be ignored and will be resolved in a later Nuxt patch ☺️

**Comment by manniL** [comment]
Tracking in https://github.com/nuxt/nuxt/issues/22876 - Thanks for the detailed description and reproduction 👍🏻
