### ISSUE TITLE
Global Split Components - render function or template not defined in component

### ISSUE THREAD

**Issue by alvarosaburido** [nuxt/content#227]
Now that global components are available along with `@nuxt/components` to be included inside `.md` files, SFC works perfectly, but split components inside `components/global`  prompt `render function or template not defined in component`

### Version
@nuxt/content: `v1.4.1` 
@nuxt/components: `v1.0.6`
nuxt: `2.13.3` 

### Reproduction Link

Code Sandbox [here](https://codesandbox.io/s/nuxtcontent-demo-wl5cx?file=/nuxt.config.js)

### Steps to reproduce
- Add `components: [{ path: "~/components", pattern: "**/*.vue" }],` to `nuxt.config.js` so it  works correctly with split components.
- Add a split component inside `components/global` like this:
```
└── components
    └── global
        └── split
            ├── split.vue
            └── split.js
```
### What is Expected?
The split component inside `global` rendered just like an SFC component.

### What is actually happening?

`render function or template not defined in component: globalSeparated` 
<img width="1679" alt="Screenshot 2020-07-04 at 12 28 01" src="https://user-images.githubusercontent.com/4699008/86510928-93f1f900-bdf4-11ea-8dbe-880e498164be.png">

Notes: I have  also tried `components: [{ path: "~/components", pattern: "**/*.vue" }, { path: "~/components/global", pattern: "**/*.vue" }]` but still same result.

Maybe there is other configuration I can add to make it work or if you guys give me some notion on where to check could I do the changes I could open a PR with it. 😄 

By the way, awesome job done with this module is amazing. Keep the good spirit!.

**Comment by benjamincanac** [comment]
Hey @alvarosaburido,

First of all, really sorry for the delay of the answer.

I just tried it with updated dependencies and renaming the `GlobalSeparated.js` to `script.js` (you can't have two components with the same name), and it works: https://codesandbox.io/s/nuxtcontent-demo-forked-od5iv?file=/components/global/global-separated/GlobalSeparated.vue

You can check out this tutorial on how to split Vue.js components into three files: https://www.youtube.com/watch?v=rzel4E1JGsE

**Comment by alvarosaburido** [comment]
Hey @benjamincanac, don't worry, I also tried days ago with updated deps and all good,  thanks for the tutorial. 😊
