### ISSUE TITLE
Type of `serverQueryContent(event).find()` is different from the actual response

### ISSUE THREAD

**Issue by Hiratake** [nuxt/content#2273]
### Environment

- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.7.0
- Builder:          -
- User Config:      modules, nitro, routeRules
- Runtime Modules:  @nuxt/content@2.8.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-f6avth

### Describe the bug

The type of the result of `serverQueryContent(event).find()` is an object of type `ContentQueryFindResponse<ParsedContent>`.
However, the actual value is an array of `ParsedContent`.

![img01](https://github.com/nuxt/content/assets/23224932/08834fba-859b-4356-9e8f-af751a7a9278)

These properties do not exist.

### Additional context

On StackBlitz, it shows `any` for some reason.
On the local VSCode, the type is displayed, as well as the possible properties that exist for the object.

**Comment by farnabaz** [comment]
This should be fixed in [edge channel](https://content.nuxtjs.org/guide/migration/edge-channel).

**Comment by Hiratake** [comment]
@farnabaz 
Thank you for fixing this issue!
Using [edge channel](https://content.nuxtjs.org/guide/migration/edge-channel) fixed the error.

**Comment by Hiratake** [comment]
Should I close this issue (#2273)? After the release of the new version?

**Comment by farnabaz** [comment]
Released in v2.8.2.
