### ISSUE TITLE
theme button bug on the website

### ISSUE THREAD

**Issue by xarthurx** [nuxt/content#2274]
### Environment

Windows

### Reproduction

See video below:

https://github.com/nuxt/content/assets/1921878/ca69e954-04e5-464f-b217-1278890268d0

### Describe the bug

There seems to be an overlapping of icons on the website.

**Comment by farnabaz** [comment]
One of them (the computer icon) is **system mode**, which means that it changes based on your system's theme.
In your case, your system is in light mode, therefore you see light mode.

**Comment by xarthurx** [comment]
> One of them (the computer icon) is **system mode**, which means that it changes based on your system's theme. In your case, your system is in light mode, therefore you see light mode.

OK. If that, I would expect a drop-down menu... Otherwise, really feels like a bug.

**Comment by farnabaz** [comment]
The UI is actually part of [Docus](https://docus.dev) design.
I'm closing this since it is not related to the Content module itself.
Feel free to open an issue on https://github.com/nuxt-themes/docus to discuss the UI
