### ISSUE TITLE
Add support for multiline strings

### ISSUE THREAD

**Issue by Rednas83** [nuxt/content#2278]
### Description
Not able to copy paste multiple lines into a field

### Suggested solution
![image](https://github.com/nuxt/content/assets/25219229/b3645af7-9745-40a0-b930-bb214d3b120b)
 which is automatically parsed to a multiline string.
`line1\nline2\n`

### Alternative solution
Convert the multiline text to an array of strings
![image](https://github.com/nuxt/content/assets/25219229/77ba6cc8-7aa3-4c38-9fc0-c7c7750ac957)
which is time consuming, less readable and less performant

**Comment by nobkd** [comment]
As that is YAML Notation, have you tried this:
```md
---
description: >
  line1
  line2
---
```

Reference: https://stackoverflow.com/a/3790497

This is untested.

**Comment by Rednas83** [comment]
Thanks @nobkd for pointing me to YAML notation. To keep the same format actually **|+** had to be used.

Hereby a full overview of all the different options
**>**    Replaces newline with spaces (folded) with Single newline at the end (clip)
**>-**  Replaces newline with spaces (folded) with No newline at the end (strip)
**>+** Replaces newline with spaces (folded) with All newline at the end (keep)
**|**     Keep newlines (literal)
**|-**    Keep newlines (literal) with No newline at the end (strip)
**|+**   **Keep newlines (literal) with All newline at the end (keep)**

**Comment by czy1996** [comment]
I understatnd it may be off topic, but I'm seeking help despreratly. 

if i write a multiline data entry in my YAML collection like above, then query it in my code, it actually becomes "line1\\nline2\\n" so line breaking can't be handled as expected.

I tried the notation above but it's not helping

I develop my page on linux, nuxt-content@3.1.1, can anybody shed  some light please?

**Comment by Rednas83** [comment]
You will need to check how eol is configured on your system.
Looks like somewhere `\\n` is configured instead of `\n` (LF)
**vscode**
![Image](https://github.com/user-attachments/assets/505fcb25-5bcd-4b82-95e0-39817b4b4b87)
**linux**
https://jizhang.github.io/blog/2022/08/31/configure-git-line-endings-across-oses/?form=MG0AV3
**windows**
couldn't find the option in regional settings
![Image](https://github.com/user-attachments/assets/4f47b7d4-11d0-417e-9efb-229f6d6ef97b)
but perhaps this could work [untested]
![Image](https://github.com/user-attachments/assets/7b937e28-c40c-43f5-b605-2e248c8614ff)
**linux [not tested]**

![Image](https://github.com/user-attachments/assets/43dac168-b4a7-41aa-936b-43e3b5657299)
