### ISSUE TITLE
HTTP fetch even when project is generated

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/content#2279]
### Environment

/

### Reproduction

Please see https://github.com/nuxt/nuxt/issues/22948

### Describe the bug

Please, see https://github.com/nuxt/nuxt/issues/22948

**Comment by Barbapapazes** [comment]
This is the issue https://github.com/nuxt/nuxt/issues/22948#issuecomment-1702838689

**Comment by farnabaz** [comment]
Thanks, @Barbapapazes
The PR is merged, and the fix is released in edge channel.
I keep this issue open to test the behavior on edge channel.
Do you mind checking the edge channel and sharing a global demo?

**Comment by Barbapapazes** [comment]
> Thanks, @Barbapapazes The PR is merged, and the fix is released in edge channel. I keep this issue open to test the behavior on edge channel. Do you mind checking the edge channel and sharing a global demo?

Hello, @farnabaz! Thanks. You can try the fix here: https://github.com/unjs/website/pull/106/files and a global demo can be found here https://feat-packages-metadata.unjs.pages.dev/packages/c12.

No more call to the API and the payload is loaded and used!
