### ISSUE TITLE
index file being treated as an index

### ISSUE THREAD

**Issue by acidjazz** [nuxt/content#2282]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.3.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `pnpm@8.6.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I have a directory structure where one of my pages needs to actually be called index, `2.index.md` to be more exact, here is the current structure:

```
❯ ls -la 4.api
drwxr-xr-x k staff 224 B  Fri Sep  1 19:21:21 2023  .
drwxr-xr-x k staff 256 B  Fri Sep  1 18:40:24 2023  ..
.rw-r--r-- k staff 1.4 KB Fri Sep  1 18:54:14 2023  1.indexes.md
.rw-r--r-- k staff 3.9 KB Fri Sep  1 19:17:12 2023  2.index.md
.rw-r--r-- k staff 1.4 KB Fri Sep  1 18:29:00 2023  3.backups.md
.rw-r--r-- k staff 2.0 KB Fri Sep  1 18:29:00 2023  4.backup.md
.rw-r--r-- k staff  23 B  Fri Sep  1 19:18:57 2023  _dir.yml
```

### Describe the bug

Instead of the URL being `/api/index` - it treats it as the index page for that directory and just makes it `/api`

Is there any way around this?

**Comment by nobkd** [comment]
Not sure if it works, but it might be worth a try:

In the front-matter of your `4.api/2.index.md` set `_path` property:
```md
---
_path: /api/index
---
```

I think the `_path` has to be the full path from the root `content/`, but not sure.

**Comment by acidjazz** [comment]
thanks @nobkd - that actually works but then it for some reason makes a child node:

<img width="260" alt="image" src="https://github.com/nuxt/content/assets/967369/935b6f1e-cc70-460d-a855-3b36d575df65">

**Comment by nobkd** [comment]
Have you solved that problem?
Or if not, are you able to provide a reproduction e.g. with [Stackblitz](https://nuxt.new/s/content/)

**Comment by acidjazz** [comment]
I have a potential work-around where I have a 2nd index file, I'll share it soon along with a reproduction
