### ISSUE TITLE
Can't override Prose components in nuxt 3.7.0

### ISSUE THREAD

**Issue by wokalek** [nuxt/content#2285]
### Environment

Nuxt 3.7.0 with nuxt/content 2.8.2

### Reproduction

This is because nuxt/content assumes the creation of files like ProseImg, ProseP and others. But Nuxt implements experimental support for components on the server and a check for the same names is written in the component auto-registrar. This needs to be edited on the `nuxt/content` side I think.

### Describe the bug

Raises the warning `Two component files resolving to the same name ProsePre`

And the server crashes with an error 502 Bad Gateway.

**Comment by nobkd** [comment]
The warning about component overrides is already tracked in #2266

The crash with error 502 seems new, as it hasn't been mentioned before.
Are you able to provide a reproduction for that e.g. with [Stackblitz](https://nuxt.new/s/content) ?

**Comment by wokalek** [comment]
@nobkd 502 The 502 error was caused by Nuxt now requiring the `--host` flag to be specified when creating the server. And since I use Nuxt inside Docker, I definitely need to do this.

This was the problem.
