### ISSUE TITLE
Content And Offline mode

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/content#229]
Hello,

I'm trying to build an web app using this module and the [pwa module](https://pwa.nuxtjs.org/). When I try to go offline, the navigator says that he can't fetch the database. Is this a bug, or I miss something or is this impossible ?

![image](https://user-images.githubusercontent.com/45267552/86514105-e260c100-be0f-11ea-8344-6c56be9e26b6.png)

**Comment by f3ltron** [comment]
You will have data with service worker not just pwa. I am not sure that pwa module is adding a sw.

https://pwa.nuxtjs.org/modules/workbox.html. I am not super use to it but t may help

**Comment by Barbapapazes** [comment]
> You will have data with service worker not just pwa. I am not sure that pwa module is adding a sw.
> 
> https://pwa.nuxtjs.org/modules/workbox.html. I am not super use to it but t may help

I have workbox which is enable on my project. I will try many thing to understand what is happening

**Comment by Barbapapazes** [comment]
**So, I thing I understand something !**

As you can see, in production, nuxt will try to fetch a file with the date !

![image](https://user-images.githubusercontent.com/45267552/87234475-98f51080-c3d1-11ea-8b9d-60df2adbaafa.png)

Buuut, in the service worker storage, the filename doesn't have this, so this fetch return an error when offline.

![image](https://user-images.githubusercontent.com/45267552/87234530-0739d300-c3d2-11ea-9268-a34a89f8ceba.png)
(offline fetch, cache enable, the first is because of Network first and the second is the sw fetch)

And the interresting thing is that is you remove `.concat(Date.now())` (in the dist folder, _static mode enable_) , the offline mode will works.

![image](https://user-images.githubusercontent.com/45267552/87234592-d4440f00-c3d2-11ea-9935-b93b589339f3.png)

![image](https://user-images.githubusercontent.com/45267552/87234633-2ab14d80-c3d3-11ea-897f-18363019f8d4.png)

So here my question, what is the goal of this `.concat` ?

**Comment by Atinux** [comment]
The issue was on a new deployment it was not able to fetch the new db.json

One solution could be to use the runtimeConfig and a generation key @benjamincanac

**Comment by Barbapapazes** [comment]
why not to use a sha like images or other content in the build pack ?

**Comment by Barbapapazes** [comment]
So, I try to had a hash in the filename but this hash changed during the build process! Why ? because the module is called twice, at the beginning and at the end ! 😫 And something change in the db ! But what ? Idon't know.

So I decided to use only the data in the database to create my hash. So if content change, the hash change but during the build process I have th same hash ! Nice ! 👌 But not really because the data in the database is not the same in a same build because of the order of load of the file !

So I try to find if I can do something to solve this ! Didn't find how, so I try something else. Try to use the env through the runtimeConfig and the hash of the db, because I need a value which can change at every build but not durint the app is running ! and It works ! PR soon !

![image](https://user-images.githubusercontent.com/45267552/91503123-0f8a9680-e8ca-11ea-8959-9b643c18fc91.png)
