### ISSUE TITLE
ContentSlot requires empty value for "unwrap" prop

### ISSUE THREAD

**Issue by lsmatovu** [nuxt/content#2294]
### Environment

Local environment as below but should not matter because reproduced on different environments.

- Operating System: `Darwin`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.6.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `devtools`, `typescript`, `modules`, `tailwindcss`, `css`, `content`, `postcss`, `googleFonts`
- Runtime Modules:  `@nuxt/content@2.8.1`, `@nuxt/image@1.0.0-rc.1`, `@nuxtjs/tailwindcss@6.8.0`, `@nuxtjs/eslint-module@4.1.0`, `@nuxtjs/google-fonts@3.0.2`, `nuxt-icon@0.5.0`
- Build Modules:    `-`

### Reproduction

[Reproduction on StackBlitz](https://stackblitz.com/edit/github-5nnfco?file=components%2Fcontent%2FArtistPage.vue)

### Describe the bug

While using MDC syntax on a doc-driven site, the usage of `ContentSlot` unwraps and collapses all markdown if `unwrap` is not explicitly passed an empty string.

The documentation states that the default value for `unwrap` is `false`. 

As a user, I can fix this by passing an empty string like so: `<ContentSlot unwrap="" />`

I propose that a better solution would be to change the default value for `unwrap` to an empty string, or to ensure that the default `false` value has the same output.

ContentSlot uses MDCSlot to render the markdown. [Take a look](https://github.com/nuxt-modules/mdc/blob/main/src/runtime/components/MDCSlot.vue#L38) at how `unwrap` is defined by `MDCSlot` based on this prop.

**Comment by nobkd** [comment]
This should have been fixed with https://github.com/nuxt-modules/mdc/commit/39d3bc900817b5fac34040b35a0dadbcd275a0d2 and should be available in when a new version of Nuxt MDC and Nuxt Content is released.

**Comment by lsmatovu** [comment]
I'll go ahead and close this then.
