### ISSUE TITLE
HTML autocompletion on MD in VS Code

### ISSUE THREAD

**Issue by santicros** [nuxt/content#23]
I know it's not a question totally related to the module but I've never used HTML in MD, so I would like to know if is there a way to get autocompletion of HTML on Markdown so it's easier to use with the module?

Thanks so much for your great job!! 🔥

**Comment by benjamincanac** [comment]
Hey @santicros,

Unfortunately I don't have any clue on this, you should look into VSCode markdown extensions.

**Comment by nimonian** [comment]
@santicros If you're desperate, Sublime Text 3's default .md editor has auto completion of html tags!

**Comment by Atinux** [comment]
Hi @santicros 

This is an issue related to VS Code directly, you can look at [their marketplace](https://marketplace.visualstudio.com/search?term=markdown&target=VS&category=All%20categories&vsVersion=&sortBy=Relevance) to find any extension or use Sublime Text 3 like @nimonian suggest :)

**Comment by daltonrooney** [comment]
@santicros For future reference, Emmet supports html autocompletion in markdown in VS Code. Just change your emmet config:

```
"emmet.triggerExpansionOnTab": true,
    "emmet.showExpandedAbbreviation": "never",
    "emmet.includeLanguages": {
        "markdown": "markdown"
    }
```

**Comment by santicros** [comment]
Really thanks @daltonrooney, that was the way to go!!
I had to change some things though:
1. Delete markdown from excluded languages. Seems it's there by default
```json
  "emmet.excludeLanguages": []
```
2. Include markdown but as html, so I get suggestions too
```json
  "emmet.includeLanguages": {
    "markdown": "html"
  },
```
Now you can have html in md fully!! Thanks!

**Comment by MaziarFg** [comment]
@santicros 
Where can I apply these settings?

**Comment by nobkd** [comment]
@MaziarFg 

If you use VS Code:
You can set your global `emmet` settings by using `Ctrl+,` (or `File > Preferences > Settings`), to open your settings, search for `emmet` and edit the entries by following this: https://github.com/nuxt/content/issues/23#issuecomment-641791133
This can also be done by editing the editor's global `settings.json` directly.

**Or** you set it for a project, by adding the same to `.vscode/settings.json` that lives in your project directory (you might have to create it, though).
