### ISSUE TITLE
findSurround ignore where

### ISSUE THREAD

**Issue by jaribu** [nuxt/content#2300]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.1
- Nuxt Version:     3.7.1
- CLI Version:      3.8.3
- Nitro Version:    2.6.3
- Package Manager:  npm@9.5.1
- Builder:          -
- User Config:      modules, content, css, postcss, image, runtimeConfig, typescript, nitro, devtools, build, vue
- Runtime Modules:  @nuxt/content@2.8.2, @nuxt/image@1.0.0-rc.1
- Build Modules:    -
------------------------------

### Reproduction

<script setup>
const { path } = useRoute();
const [prev, next] = await queryContent()
  .only(["_path", "title"])
  .sort({ date: 1 })
  .where({ title: { $eq: "notexist" } })
  .findSurround(path);
</script>

### Describe the bug

Should return null, same result with other where conditions.

**Comment by vernaillen** [comment]
I noticed this issue as well and made a reproduction:  https://stackblitz.com/~/github.com/vernaillen/nuxt-content-findSurround.

**Comment by vernaillen** [comment]
It seems there's already a fix on its way for the next release: https://github.com/nuxt/content/pull/2291

**Comment by nobkd** [comment]
Have you checked, if it is fixed with the [edge channel](https://content.nuxtjs.org/guide/migration/edge-channel)?

**Comment by vernaillen** [comment]
I just checked it now, in both my own project as the reproduction. It is indeed fixed.

**Comment by jaribu** [comment]
Yes, I confirm it works with the edge channel

**Comment by farnabaz** [comment]
Fixed in [v2.8.3](https://github.com/nuxt/content/releases/tag/v2.8.3)
