### ISSUE TITLE
ability to render HTML for RSS and Atom feeds

### ISSUE THREAD

**Issue by acidjazz** [nuxt/content#2306]
I have seen a couple if requests/issues related that are a bit old and none really lead to a solution.  Today we have islands support so I'm starting this to hopefully find a solid solution that a module can later use and/or just some more documentation.

I basically want to add an Atom feed to my blog that injects content so people can read articles w/out having to visit the site.

I am using `serverQueryContent` in a server route and it works great with the feeds package, but i'd like a solid way to add HTML as content.

Currently the best solution is an article that has been taken down https://web.archive.org/web/20220802163409/https://journal.maciejpedzi.ch/generating-rss-feeds-for-a-nuxt-content-site

**Comment by Barbapapazes** [comment]
Hello, it's now possible thanks to this module https://github.com/nuxt-modules/mdc which is included in @nuxt/content!

**Comment by acidjazz** [comment]
> https://github.com/nuxt-modules/mdc

How do I use it? I see this example:
```ts
  const ast = await parseMarkdown(mdc)
```

where do i get `mdc` ? is that the article body? is `ast` the HTML?

**Comment by Barbapapazes** [comment]
Nop, the AST is a transitional state to pass from a language to another.

Unfortunately, you will need to take a look at this component: https://github.com/nuxt-modules/mdc/blob/main/src/runtime/components/MDCRenderer.vue

I think that the best thing to do now is to open an issue on nuxt-modules/mdc to ask for a composable that will convert md to html!

**Comment by acidjazz** [comment]
> https://github.com/nuxt-modules/mdc/blob/main/src/runtime/components/MDCRenderer.vue

Done, thank you https://github.com/nuxt-modules/mdc/issues/44
