### ISSUE TITLE
Cannot use @nuxt/content on windows 

### ISSUE THREAD

**Issue by hermanno18** [nuxt/content#2314]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  npm@9.6.7
- Builder:          vite
- User Config:      components, app, modules, googleFonts, tailwindcss, colorMode, devtools
- Runtime Modules:  @nuxtjs/device@3.1.0, @nuxtjs/google-fonts@3.0.1, @nuxtjs/tailwindcss@6.7.0, @nuxtjs/color-mode@3.2.0, nuxt-icon@0.4.1, @nuxt/content@2.8.2
- Build Modules:    -

### Reproduction

https://github.com/hermanno18/portfolio-v2/tree/content_bug

### Describe the bug

I've installed @nuxt/content on my portfolio made with nuxt 3 folowing the official documentation.
i used this command to install `npm install --save-dev @nuxt/content`
and added this line on my modules in my nuxt.config.js `@nuxt/content`
but when i run my project with `npm run dev`, i got an error into my terminal, as shown in the log section  and my project can't run.

Note that when i remove `@nuxt/content` into mu modules, my project run fine.

### Logs

```Shell
ERROR  [worker reload] [worker init] Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'                                              14:02:13  

  at new NodeError (node:internal/errors:393:5)
  at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1026:11)
  at defaultResolve (node:internal/modules/esm/resolve:1106:3)
  at nextResolve (node:internal/modules/esm/loader:163:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)
```

```[tasklist]
### Tasks
```

**Comment by karadanay7** [comment]
I have the same issue even i have tried to use many node versions. I ve also tried different package managers. I also tried to create new fresh nuxt/content app after creating the new app i still have the same issue. :/

**Comment by nobkd** [comment]
I found this issues that are connected to your problem:
- nuxt/nuxt#19453
- nuxt-modules/mdc#38

**Comment by hermanno18** [comment]
thanks @nobkd, but i taked a look on thoses issues but none of them solved my problem

**Comment by Fyfe0203** [comment]
> thanks @nobkd, but i taked a look on thoses issues but none of them solved my problem

Have you solved this problem?

**Comment by hermanno18** [comment]
> > thanks @nobkd, but i taked a look on thoses issues but none of them solved my problem
> 
> Have you solved this problem?

Not Yet. i've just abendoned the idea of using it and redising my application to use API call instead of statics contents.

Do you have a suggestion for me ? i'm still open for suggestions

**Comment by Fyfe0203** [comment]
> > > thanks @nobkd, but i taked a look on thoses issues but none of them solved my problem
> > 
> > 
> > Have you solved this problem?
> 
> Not Yet. i've just abendoned the idea of using it and redising my application to use API call instead of statics contents.
> 
> Do you have a suggestion for me ? i'm still open for suggestions

I upgraded nuxt-content to 2.9.0, nuxt@3.8.0, and then no errors were reported. You can refer to the following
