### ISSUE TITLE
Numeric sort with findSurround does not work

### ISSUE THREAD

**Issue by Bumbleboss** [nuxt/content#2317]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.7.3
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  bun@1.0.1
- Builder:          -
- User Config:      runtimeConfig, site, typescript, ogImage, css, vite, modules, app
- Runtime Modules:  @nuxt/content@2.8.2, @nuxtseo/module@2.0.0-beta.31
- Build Modules:    -
------------------------------

### Reproduction

.

### Describe the bug

```js
let [ prev, next ] = await queryContent<WorkpageData>()
  .only([ '_path', '_dir', '_draft', '_file' ])
  .sort({ _file: -1, $numeric: true })
  .where({ _dir: 'w', _draft: false })
  .findSurround('/w/' + url)
```

When using `sort({ _file: -1, $numeric: true })` and `find`, it works as intended. But with `findSurround`, it does not.

### Additional context

My content directory:
```
└── content/w
    ├── 1...md
    ├── 2...md
    ├── ...
    ├── 9...md
    ├──10...md
    └──11...md
```

**Comment by farnabaz** [comment]
This should be fixed in the [edge channel](https://content.nuxtjs.org/guide/migration/edge-channel).
Do you mind trying edge channel?

**Comment by Bumbleboss** [comment]
Just checked and it seems to work as intended. Thanks!
