### ISSUE TITLE
EMFILE: too many open files, open '...' during `generate` process

### ISSUE THREAD

**Issue by manniL** [nuxt/content#2320]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.14.2
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  pnpm@7.18.0
- Builder:          -
- User Config:      runtimeConfig, app, nitro, modules, content, tailwindcss
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @vueuse/nuxt@10.4.1, nuxt-icon@0.5.0, @nuxt/content@2.8.2
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/manniL/nuxt-content-2320

### Describe the bug

While working on my website, I noticed a crucial issue: In case there is a site that accesses a lot of files at once (in my case 50) that are *also generated via nuxt content*, you'll receive an `EMFILE: too many open files` error. Alternatively, a ` ERROR  [nuxt] [request error] [unhandled] [500] content.startsWith is not a function` masking the actual error.

This can be solved by chunking the keys and creating a pseudo-queue, instead of using `Promise.all` here
https://github.com/nuxt/content/blob/cae34d7f866d876de4ad04f83fe3f05da3a559c7/src/runtime/server/storage.ts#L108

Will submit a PR shortly.

**Comment by ManasMadrecha** [comment]
Will the linked PR also solve #2354?

**Comment by manniL** [comment]
@ManasMadrecha it should be already live but I'm not sure if it will help with exactly this problem. Give it a try though!
