### ISSUE TITLE
Can nuxt-content parse markdown strings directly?  Similar to v-html in vue。

### ISSUE THREAD

**Issue by ghost** [nuxt/content#2330]
Can nuxt-content parse markdown strings directly?  Similar to v-html in vue。

**Comment by nobkd** [comment]
Same feature request as nuxt-modules/mdc#44

**Comment by maximepvrt** [comment]
😉 same https://github.com/nuxt/content/issues/2019

**Comment by natanfeitosa** [comment]
Have you tried any [of these examples](https://github.com/nuxt-modules/mdc#use) in MDC's README.me?

**Comment by maximepvrt** [comment]
UseMarkdown return a tree. the HTML content is generated by the MDC component from this tree.
