### ISSUE TITLE
Bug: `findSurround` didn't respect the `sort`, `only` parameter

### ISSUE THREAD

**Issue by N-index** [nuxt/content#2337]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.2
- Nitro Version:    2.6.2
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      app, modules, dayjs, content
- Runtime Modules:  @nuxt/content@2.8.2, @unocss/nuxt@0.56.1, @vueuse/nuxt@10.4.1, dayjs-nuxt@1.1.2, @formkit/auto-animate/nuxt@0.8.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ojj9sc?file=content%2Findex.md

### Describe the bug

- `findSurround` not respect the sort parameter, it just obeys the alphabet order of filename.
- `findSurround` not respect the `only` parameter, it returns every field of the article.
- this issue happens both on `queryContent` and `ContentQuery` component.

**Comment by nobkd** [comment]
Probably fixed in edge channel with #2311.

**Comment by N-index** [comment]
Sorry, I just searched `findSurround` keyword in existing issues, and didn't see #2311, so duplicate open this new issue.
Now I checked the edge channel and it has been fixed.
