### ISSUE TITLE
Broken prev next from useContent, regression/breaking change

### ISSUE THREAD

**Issue by Szymon-dziewonski** [nuxt/content#2338]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.1`
- Nuxt Version:     `3.7.3`
- CLI Version:      `3.9.0`
- Nitro Version:    `2.6.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `-`
- User Config:      `modules`, `content`
- Runtime Modules:  `@nuxt/content@2.8.2`
- Build Modules:    `-`

### Reproduction

In 2.7.2 

[c91f92d4-2525-4e10-b20b-323dd0a7c99c.webm](https://github.com/nuxt/content/assets/2566152/46a5d588-a49c-4fee-9c18-99b127a025d1)

Repo with reproduction 
https://github.com/Szymon-dziewonski/NuxtContentPrefetch/tree/broken-pre-next

In 2.8.2 its broken totally (`next` and `prev` method), around 2.7.4 starts breaking with `prev` method only coming from  `useContent`

[60747c95-3b82-4ae0-af35-842b4bcb4a47.webm](https://github.com/nuxt/content/assets/2566152/53dd95dc-8407-4434-af92-b4aa1aa5fe9f)

Repo with reproduction
https://github.com/Szymon-dziewonski/NuxtContentPrefetch/tree/broken-prev-next-2.8.2

Both run `yarn` and then `yarn dev`, check `content` structure and run `http://localhost:3000/1/1.1` then play with it

### Describe the bug

When having nested structure like so:
![image](https://github.com/nuxt/content/assets/2566152/8444deb6-d4fa-44ce-a4a7-6b28de171a9f)

There is breaking change or regression after version 2.7.2 that causes `prev` and `next` methods coming from `useContent` not usable, pointing wrong next and previous links

**Comment by Szymon-dziewonski** [comment]
Hey @farnabaz seems like its fixed on edge channel indeed, so probably this ticket can be closed. Can you maybe point PR that fixes issue?

**Comment by nobkd** [comment]
I think those are related:
#2291
#2311

**Comment by Szymon-dziewonski** [comment]
@nobkd appreciate that :) Thanks

**Comment by farnabaz** [comment]
Released in [v2.8.3](https://github.com/nuxt/content/releases/tag/v2.8.3)
