### ISSUE TITLE
Export ParsedContent types

### ISSUE THREAD

**Issue by cco3** [nuxt/content#2349]
### Is your feature request related to a problem? Please describe

Right now, the types in `@nuxt/content/dist/runtime/types` are not available in the package.json exports.  This makes the eslint resolver choke when following the approach described [in the docs](https://content.nuxt.com/usage/typescript#markdown-specific-types).

```
import type { MarkdownParsedContent } from '@nuxt/content/dist/runtime/types'
```

```
[eslint]   1:1  error    Resolve error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './' is not defined by "exports" in /home/user/project/node_modules/@nuxt/content/package.json
[eslint]     at new NodeError (node:internal/errors:405:5)
[eslint]     at exportsNotFound (node:internal/modules/esm/resolve:359:10)
[eslint]     at packageExportsResolve (node:internal/modules/esm/resolve:695:9)
[eslint]     at resolveExports (node:internal/modules/cjs/loader:567:36)
[eslint]     at Module._findPath (node:internal/modules/cjs/loader:636:31)
[eslint]     at findModulePath (/home/user/project/node_modules/eslint-import-resolver-alias/index.js:99:27)
[eslint]     at exports.resolve (/home/user/project/node_modules/eslint-import-resolver-alias/index.js:75:10)
[eslint]     at withResolver (/home/user/project/node_modules/eslint-module-utils/resolve.js:114:23)
[eslint]     at fullResolve (/home/user/project/node_modules/eslint-module-utils/resolve.js:135:22)
[eslint]     at relative 
```

### Describe the solution you'd like

Add these types to the rest of the exported types (found at `@nuxt/content/dist/types.d.ts`)

**Comment by xarthurx** [comment]
Second this.
Really annoying since I extend the `MarkdownParsedContent` to many interface I'm using.

**Comment by wokalek** [comment]
Same issue

**Comment by cco3** [comment]
This appears to be fixed.  I can now do `import type { MarkdownParsedContent } from "@nuxt/content";`

**Comment by wokalek** [comment]
Just need to update docs then

**Comment by cco3** [comment]
Alright, reopening for docs

**Comment by codeofsumit** [comment]
Docs here are not yet updated
https://nuxtseo.com/docs/sitemap/guides/content
