### ISSUE TITLE
Use 'ASC' and 'DESC' to sort a query rather than 1 or -1

### ISSUE THREAD

**Issue by ekkaiaaa** [nuxt/content#2355]
### Is your feature request related to a problem? Please describe

Using the sentinel values 1 and -1 to indicate whether you want to sort a query in ascending or descending order is not communicative and can be intriguing for new users of the library.

Example from the documentation:
```ts
// Sort by title ascending first then sort by category descending
const articles = await queryContent('articles')
  .sort({ title: 1, category: -1 })
  .find();
```

### Describe the solution you'd like

Using meaningful values like the 'ASC' and 'DESC' strings would be much easier to understand and would bring the query constructor closer to other query languages (e.g. SQL).

Example:
```ts
const articles = await queryContent('articles')
  .sort({ title: 'ASC', category: 'DESC' })
  .find();
```

### Describe alternatives you've considered

None

### Additional context

[Sort option documentation](https://content.nuxt.com/composables/query-content#sortoptions)

**Comment by nobkd** [comment]
[Nuxt Content's sort](https://content.nuxt.com/composables/query-content#sortoptions) tries to be similar to [MongoDB's sorting](https://www.mongodb.com/docs/manual/reference/operator/aggregation/sort/). You can see that also in the [where query description](https://content.nuxt.com/composables/query-content#wherequery).
