### ISSUE TITLE
Content Not Found on Static Hosting

### ISSUE THREAD

**Issue by jordanlevy96** [nuxt/content#2356]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.18.0`
- Nuxt Version:     `3.7.4`
- CLI Version:      `3.9.0`
- Nitro Version:    `2.6.3`
- Package Manager:  `pnpm@8.8.0`
- Builder:          `-`
- User Config:      `ssr`, `content`, `generate`, `devtools`, `modules`, `buildModules`, `css`, `plugins`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.8.0`, `@nuxt/content@2.8.4`
- Build Modules:    `@nuxtjs/pwa@3.3.5`

### Reproduction

https://github.com/jordanlevy96/nuxt-static-content-bug/
See README--generate a static version of the site and the content fails to render.

### Describe the bug

If you build and serve the site statically, it fails to read the content, though it looks like it is cached in a build file: dist/api/_content/cache.1695911551008.json

**Comment by farnabaz** [comment]
Disabling SSR will block all nitro API's and therefore cache will not generate on build. SPA support is experimental and will supported officially in next major version.
Checkout this comment to use experimental feature: https://volta.net/nuxt/content/issues/1746#comment-1519230

**Comment by Billybobbonnet** [comment]
> Disabling SSR will block all nitro API's and therefore cache will not generate on build. SPA support is experimental and will support officially in next major version. Checkout this comment to use experimental feature: [#1746 (comment)](https://github.com/nuxt/content/issues/1746#issuecomment-1346737779)

Enabling SSR will return 404 as well on nitro calls during` ``nuxt generate`  .
![image](https://github.com/nuxt/content/assets/8236816/9a45cd37-9144-4760-ba5d-eba56f372f53)

Can you confirm this @farnabaz ?:

- `ssr: false` is possible as long as you enable the experimental features such as : 
```
content: {
    documentDriven: true,
    // https://content.nuxtjs.org/api/configuration
    experimental: {
      clientDB: true,
    },
  },
```
- `ssr: true` doesn't work with nuxt content v2 (and it breaks nuxt image as well).

**Comment by farnabaz** [comment]
Seems that generation failed because you have some links in your websites which leads to 404 page. This is Nitro's default behavior to fail if it found any 404 page. Try removing those links and generation should be good.
