### ISSUE TITLE
Cannot filter content from a CSV file

### ISSUE THREAD

**Issue by lucpotage** [nuxt/content#236]
### Version
@nuxt/content: 1.4.0
nuxt: 2.13.3

### Reproduction Link
https://codesandbox.io/s/nuxtcontent-demo-zs77u?file=/pages/_slug.vue

### Steps to reproduce
Try to filter content with .only() or .where().

For the following CSV file:

```csv
a, b
hello, world
```

The following line should return something:

```js
const result = await $content('file.csv').where({ a: 'hello' }).fetch()
```

### What is Expected?
To actually filter the content.

### What is actually happening?
An error is thrown from the query builder.

**Comment by lucpotage** [comment]
Mmm, what seems to be a bug might not be. I read this closed issue: https://github.com/nuxt/content/issues/62

It appears we cannot benefit from queries like `.sortBy()`, `.where()` with JSON arrays and CSV. It only works with **directories**, which me when fetching a directory and not a file. Is that right?

However, it would be super useful to enable this on **files** as well. Would you see any drawback?

**Comment by benjamincanac** [comment]
@lucpotage Since CSV files are lines, the data is going to the `body` variable as an array: https://content.nuxtjs.org/writing#example-1, you might want to use JSON for that.

Indeed, each file is stored inside a collection,`sortBy` and `where` applies to the collection, you can't do that on an item.

**Comment by ricky11** [comment]
The docs here : https://content.nuxt.com/composables/query-content#wherequery Do not mentioned if query csv files are not possible.  What is the solution to filter a csv file?
