### ISSUE TITLE
useContent not working with ssr: false

### ISSUE THREAD

**Issue by Gimanh** [nuxt/content#2363]
### Environment

Operating System: Darwin
Node Version: v16.17.1
Nuxt Version: 3.7.3
CLI Version: 3.8.4
Nitro Version: 2.6.3
Package Manager: npm@8.15.0
Builder: -
User Config: modules, content
Runtime Modules: normalizedModule(), @nuxt/content@2.8.2
Build Modules: -

### Reproduction

Clone repository https://github.com/Gimanh/nuxt-content-bug

### Describe the bug

Add content into [...slug.vue]
```
<template>
  <main>
    <ContentDoc />
      {{ data.navigation }}
  </main>
</template>

<script setup>
const data = useContent()
console.log( data.navigation );
</script>
```

You will see navigation data 
Then 
Set ssr: false in nuxt.config useContent will return `undefined`

**Comment by mathieunicolas** [comment]
Looks related to the issue I just posted https://github.com/nuxt/content/issues/2385 ?
useContent works when I come from a page, but looks broken when I refresh or use direct link to a page.
@farnabaz may have a clue for this one ?

**Comment by wikett** [comment]
I have the same issue. Do we have any updates? Thanks
