### ISSUE TITLE
Dark mode: Highlighting specific lines does not work anymore due to !important tag

### ISSUE THREAD

**Issue by PatrikBird** [nuxt/content#2366]
### Environment

I am using [content-wind](https://github.com/Atinux/content-wind) for reproduction.

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      extends
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Reproduction using content-wind: https://stackblitz.com/edit/github-nmtu75?file=content%2F1.index.md

### Describe the bug

Highlighting a specific line within `ProseCode.vue` does not work anymore in dark mode.

Example.md:
\```ts {1}
const foo = 'bar'
let me = 'reproduce you'
\```

The `{1}` adds a highlight class to line 1 which enables specific styles for the lines specified.
Example styles within `ProseCode.vue`:
```vue
<style scoped lang="postcss">
:slotted(pre .line.highlight) {
  @apply bg-yellow-200 dark:bg-green-500;
}
</style>
```
This won't work anymore as it's been overwritten with `!important`.
<img width="458" alt="Screenshot 2023-10-07 at 20 32 02" src="https://github.com/nuxt/content/assets/52401692/0a29f808-4086-4095-a1d2-4fe4c567d959">

If I manipulate my rendered html by disabling the mentioned !important tag, it seems to work as expected.

### Additional context

I thought this comes from shikiji but it got closed with a note to open this issues here: https://github.com/antfu/shikiji/issues/19

Bug only happens in dark mode!

**Comment by nobkd** [comment]
I made a draft PR where I'll try to find a way without `!important`.
The current implementation does not allow this and will have to be changed.

For the time, you'll have to use `!important` on your rules too. :(

**Comment by PatrikBird** [comment]
thanks for your lightning fast response ⚡️

**Comment by nobkd** [comment]
Another thing: Your selector also wouldn't have had enough specificity to override that rule without it being `!important`.

`pre .line.highlight` = `0, 1, 2` (I don't think `:slotted` counts)
vs
`html.dark .shiki span` = `0, 2, 2`

If that rule wouldn't have `!important`:

You'd have had to write something like `pre code .line.highlight` (= `0, 2, 2`) to match the specificity and hope your rule comes after that rule.
Or `pre code span.line.highlight` (= `0, 3, 2`) to beat the specificity.

**Comment by PatrikBird** [comment]
thanks, updated the specifier in the reproduction to `pre code span.line.highlight`

**Comment by nobkd** [comment]
In your example, before, the styles were applied correctly because of using a data attribute as they were scoped. Sorry about that 😅 

The real specificity of your selector `pre .line.highlight[scoped-data-selector]` was therefore `0, 3, 1` (data selectors count the same as classes) and because of that higher than the other one from the beginning. :)

Also... for dark mode, the `.dark` class gets appended additionally.

In light mode, this wouldn't even work if default styles are applied (was not the case for your example) (also changed with PR), because element styles aren't touched by specificity.

---

I just played around a bit, and found out, that the dark color only gets applied properly, when **not** using slotted and scoped. Do you also experience that? If you do, is it maybe a postcss/tailwind/slotted issue?

**Comment by PatrikBird** [comment]
So to apply the styles properly it has to be either:

Global scope without `:slotted`
```vue
<style lang="postcss">
pre code span.line.highlight {
  @apply bg-yellow-200 dark:bg-green-500;
}
</style>
```
---
or `scoped` with `:slotted` ->
```vue
<style scoped lang="postcss">
:slotted(pre code span.line.highlight) {
  @apply bg-yellow-200 dark:bg-green-500;
}
</style>
```
I can verify that in the reproduction and in my repo.

> I just played around a bit, and found out, that the color for dark mode only gets applied properly, when not using slotted and scoped. Do you also experience that? If you do, is it maybe a postcss/tailwind/slotted issue?

This issue only appears to be in the reproduction.. colors get added correctly in dark mode in [my project](https://github.com/PatrikBird/website/blob/055c702d6bc1f810c29d79b3667aaa3968b6ded8/components/content/ProseCode.vue#L38-L44) which uses unocss though. 🫠
