### ISSUE TITLE
Is there a way to fetch markdown files from remote source?

### ISSUE THREAD

**Issue by boussadjra** [nuxt/content#237]
I want to build a personal project where i show the documentation of my online repositories based on their Readme.md files for example :

1. project 1 :
`its docs based on the remote readme`

2. project 2 :
`its docs based on the remote readme`

how can i fetch that remote files and show them in my page something like :

```
  const project1= await $content('https://github.com/boussadjra/vueye-table/blob/master/README.md').fetch()
```

**Comment by lucpotage** [comment]
Hello @boussadjra, it appears your question was already asked in the past, see here: https://github.com/nuxt/content/issues/37.

Although it would be super useful, it does not seem to be part of the roadmap as of now.
