### ISSUE TITLE
Static site build bug | ssr: false (query not found)

### ISSUE THREAD

**Issue by MichaelGitArt** [nuxt/content#2371]
### Environment

- Operating System: Darwin
- Node Version:     v18.9.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, ssr, spaLoadingTemplate, modules
- Runtime Modules:  @nuxt/content@2.8.5
- Build Modules:    -

### Reproduction

Here is a repo. With steps in the README.md
https://github.com/MichaelGitArt/issue-nuxt-content

### Describe the bug

When we build a static site, the app tries to make a request to API. But there is no API, we need to refer to some JSON file.

**Comment by vietanhbui** [comment]
+1

**Comment by yuelikestocode** [comment]
Same issue here.

**Comment by darioackermann** [comment]
Same issue here. Need to workaround it currently... :(
