### ISSUE TITLE
use of flatUnwrap and ContentSlot[unwrap] per the docs doesn't iterate properly through content

### ISSUE THREAD

**Issue by samcarrington** [nuxt/content#2372]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.8.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.15
- Builder:          -
- User Config:      modules, typescript, app, colorMode, nitro, runtimeConfig, content
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxt/content@2.8.5, @nuxtjs/color-mode@3.3.0, @nuxthq/studio@1.0.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-zfuxp6?file=content%2Findex.md,components%2Fcontent%2FcontentList.vue

### Describe the bug

Using the useUnwrap composable to unpack and re-render a list from a markdown file no longer effectively iterates through list items in the pass-through of the used slot from the iteration through flatUnwrap into the ContentSlot component.

The v-for iteration runs through the correct number of items, but the ContentSlot :use and unwrap parameters have no effect on the output, and the whole content of the list is rendered into each item rather than a single item.

**Comment by Lexpeartha** [comment]
The only work around I found for this is to pin version to `~2.7.X` and do workaround mentioned in nuxt/content#2254
Latter is only needed if you want to use nuxt 3.7+

**Comment by mklueh** [comment]
**Any news on this?**

I'd also wish the docs would cover how to use it. I had no idea how the list should look like in my markdown and thought you'd do something like this

```
. a
. b
. c
```

the markdown side on how to use named slots other than "default" is also not covered

**Comment by gsabater** [comment]
I'm having the same issue, right now im worndering if I should use two components or props to print the list items, but as of now, the correct iteration of list items using `<ContentSlot :use="() => item" unwrap="li" />` is not working

**Comment by samcarrington** [comment]
This implementation has been broken over a year now - behaves contrary to the docs and doesn't iterate list items properly.
