### ISSUE TITLE
Docs: Missing icon makes text unreadable

### ISSUE THREAD

**Issue by AaronBeaudoin** [nuxt/content#2382]
### Environment

N/A

### Reproduction

N/A

### Describe the bug

A missing icon is causing text to be very difficult to read.

1. Go to https://content.nuxt.com/usage/navigation.
2. Search the page for "It allows you to overwrite the title and custom properties to directory nodes in navigation."
3. In the code block right below it, the second "tab" is supposed to say `_dir.yml`, but I can barely read it because the text `vscode-icons:file-type-yml` is output directly over top of it.

The docs need to be updated to ensure only existing icons are used. That being said, I also think it might be a better default behavior for the icon module to not rendering anything if an icon does not exists, rather than rendering the text ID of the desired icon.

**Comment by Atinux** [comment]
Sorry about this it is now fixed!
![CleanShot 2023-10-18 at 18 55 33@2x](https://github.com/nuxt/content/assets/904724/f96bb216-fca6-438c-8003-6fa4e50b9eab)
