### ISSUE TITLE
docs: missing a page for deployement

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/content#2387]
### Environment

/

### Reproduction

/

### Describe the bug

Hello,

On the home, there is a card about "Deploy everywhere". But there is nothing is the documentation related to this topic. I think that docs could be improve to explain how content works with static generation, why you should prerender page, how you can do it with route rules !

_Many issues are related to deployement and without being aware of best pratices, it's easy to think that content does not works_

**Comment by Atinux** [comment]
Nice catch, happy to draft something for it?

**Comment by Barbapapazes** [comment]
> Nice catch, happy to draft something for it?

Yes, I could start something!
