### ISSUE TITLE
Support both kebab-case and PascalCase components in markdown content

### ISSUE THREAD

**Issue by lloydjatkinson** [nuxt/content#239]
### Is your feature request related to a problem? Please describe.
Vue supports using components in both formats: `<my-component />` and `<MyComponent />`. See [Vue style guide.](https://vuejs.org/v2/style-guide/#Component-name-casing-in-templates-strongly-recommended)

### Describe the solution you'd like
I'd like Nuxt content to be able to support this as well. Right now it does not:
![image](https://user-images.githubusercontent.com/5633938/86979504-694bcb80-c179-11ea-8e88-844625694d81.png)

### Describe alternatives you've considered
NA

### Additional context
Again, this is supported by Vue. It's also a supported feature in [Gridsome's markdown support.](https://gridsome.org/plugins/@gridsome/vue-remark)

**Comment by benjamincanac** [comment]
Hey @lloydjatkinson,

Since we use [rehype-raw](https://github.com/rehypejs/rehype-raw) to parse HTML in Markdown the syntax is limited.

You can check the documentation about Vue components here: https://content.nuxtjs.org/writing#vue-components.
