### ISSUE TITLE
Unknown custom element: <my-component> - did you register the component correctly?

### ISSUE THREAD

**Issue by razbakov** [nuxt/content#24]
### Version
@nuxt/content: 1.0.0
nuxt-edge: ^2.13.0-26503223.f13b3752

### Reproduction Link

https://codesandbox.io/s/nuxtcontent-demo-keb5g?file=/pages/_slug.vue

### Steps to reproduce

Follow documentation about [vue components](https://content.nuxtjs.org/writing#vue-components)

1) Create component `WidgetScreenshot.vue` and register as global.

2) Create markdown content:

```html

## Screenshot Widget

<widget-screenshot src="/screens/app.png" alt="App Screenshot"></widget-screenshot>

```

### What is Expected?

Component displayed on the page.

### What is actually happening?

```
[Vue warn]: Unknown custom element: <widget-screenshot> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Pages/home.vue> at pages/home.vue
```

**Comment by benjamincanac** [comment]
Hi @razbakov 

Same issue as #22 and #13.

You need to import the components in your page.

**Comment by razbakov** [comment]
Thanks, it works!
