### ISSUE TITLE
New search feature is not working

### ISSUE THREAD

**Issue by cfab** [nuxt/content#2404]
### Environment

Now using node v20.8.0 (npm v10.1.0)
❯ npx nuxi info
Working directory: /Users/f/Desktop/content                                                           14:08:14
Nuxt project info: (copied to clipboard)                                                              14:08:14

------------------------------
- Operating System: Darwin
- Node Version:     v20.8.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, modules, content
- Runtime Modules:  @nuxt/content@2.9.0
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/cfab/content-bug.git

### Describe the bug

I was trying out the new search featured added in content v 2.9. 
- I created a nuxt-content site with npx nuxi@latest init content-app -t content
- added then a search page (search.vue) with the example form the doc. 
- modified also about with some text for the search to have some content
- added a link to search page from the home content. 

On /search we get this error - apparently computed is not defined in the searchContent composable...

search.mjs?t=1698584228061&v=a75ea5b3:41 Uncaught (in promise) ReferenceError: computed is not defined
    at useIndexedMiniSearch (search.mjs?t=1698584228061&v=a75ea5b3:41:29)
    at searchContent (search.mjs?t=1698584228061&v=a75ea5b3:21:22)
    at async setup (search.vue?t=1698584288756:26:104)

**Comment by qmarcos** [comment]
The same here.

You can avoid the error you commented importing computed in your script setup:

```js
<script setup>

import { computed } from 'vue';

const search  = ref('');
const results = searchContent(search);

</script>
```

But then you get additional similar errors, the next one that happened to me related to `createError`.

```
Uncaught (in promise) ReferenceError: createError is not defined
    at searchContent (search.mjs?v=9cca6f01:16:7)
```

**Comment by billsuxx** [comment]
same here, with node 18, nuxt 3.8.0 and nuxt/content 2.9.0

```
search.mjs?v=3cb731eb:41 Uncaught (in promise) ReferenceError: computed is not defined
    at useIndexedMiniSearch (search.mjs?v=3cb731eb:41:29)
    at searchContent (search.mjs?v=3cb731eb:21:22)
```

![image](https://github.com/nuxt/content/assets/4318995/3f6ab6ff-0842-451c-972f-3dcfea8e3959)

**Comment by nobkd** [comment]
@Barbapapazes You're probably the person for this.

**Comment by Barbapapazes** [comment]
Oh 🙁 I need to import every thing since we are on a module (I think it's the issue, will take a look asap)

**Comment by teamupdivision** [comment]
when is the next release for nuxt content planned? The current 2.9.0 one does not contain this fix. Thanks!

**Comment by Priccc** [comment]
The `searchContent` api return a promise. so need use `useAsyncData` for it. I use this way is work.
`const { data, refresh } = await useAsyncData(() => searchContent(searchKey, {}))`

**Comment by rasensio** [comment]
I am still struggling how to get the data from const { data } . If i assign the value to a ref() I'm still getting null. For example. 


```
<script setup>
const results = ref({})
const query = ref('')

const async search = () => {
  const { data, refresh } = await useAsyncData(() => searchContent(query))
  // data is a ref but value is null. 
  // the api call returns an object 

  // if I do this, 
  results.value = data // or data.value I still get nothing
}
</script>
```
![Screenshot 2024-01-01 at 11 46 59 AM](https://github.com/nuxt/content/assets/1261374/17f1e033-e340-46fd-9ec9-f2195aa7257f)

**Comment by JamieCurnow** [comment]
@rasensio I'm not sure if it's the correct way, but I'm doing a similar thing to you and it works like this:

```ts
const searchString = ref('')
const results = ref([])
const searching = ref(false)

const search = async () => {
  searching.value = true
  const res = await searchContent(searchString.value, {})
  results.value = res.value // res is a computed so we pluck out the .value and just add it to our ref
  searching.value = false
}
```

**Comment by andreyquerino** [comment]
I was facing the same problem, and @Priccc  answer solved my problem.

It's like this!
```vue
<script lang="ts" setup>
const searchString = ref('')
const dataSearch = ref()

async function search() {
  const { data, refresh } = await useAsyncData(() => searchContent(searchString, {}))
  dataSearch.value = data
}

</script>

<template>
  <main max-w-xl mxauto my10>
    <input v-model="searchString" @keyup="search()" >
    <pre>{{ dataSearch }} </pre>
  </main>
</template>
```

**Comment by andreyquerino** [comment]
I use the ```<ContentList>``` component directly.

```vue
<script lang="ts" setup>
const searchString = ref('')
</script>

<template>
  <main max-w-xl mxauto my10>
    <input v-model="searchString" >

    <ContentList v-if="searchString" :path="`/posts/${searchString}`" fields="title, thumbnail, date" 
        :query="{
            draft: false,
            sort: [
                {
                    date: -1
                }
            ]
        }" v-slot="{ list }">

            {{ list }}

     </ContentList>

  </main>
</template>
```
