### ISSUE TITLE
Empty .where fetch errors out.

### ISSUE THREAD

**Issue by pxwee5** [nuxt/content#241]
`.where({ isPublished: true })` errors out if no markdown content is found with the `isPublished` attribute. When fetching individual page.

### Steps to reproduce
```
const post = await $content('prefetch-links')
      .where({
        isPublished: true,
      })
      .fetch()
```

Remove all `isPublished` attribute from all content markdown files.

### What is Expected?
Returns empty array.

**Comment by f3ltron** [comment]
Hello can you give a reproduction repo ? I tried in my project. 

prefectch-links / 
 first.md
 second.md

just put `test content`

And everything is working well for me

**Comment by kenhyuwa** [comment]
I also,
I'm trying with code like this:
```js
// Not working properly
const gallery = await $content('gallery')
      ..where({ video: false })
      .sortBy('uid')
      .fetch()
```
or
```js
const gallery = await $content('gallery')
      ..where({ video: { $eq: false } })
      .sortBy('uid')
      .fetch()
```
still not working.
from module refferences [techfort/LokiJS](https://github.com/techfort/LokiJS/wiki/Query-Examples#where-queries)
then i change my code with
```js
const gallery = await $content('gallery')
      .where(function (o) {
        return o.video === false
      })
      .sortBy('uid')
      .fetch()
```
Now, everything is working...

**Comment by Atinux** [comment]
Please re-open with a reproduction :)
