### ISSUE TITLE
[Vue warn]: Failed to resolve component: MDCRenderer when upgrading to Nuxt 3.8.2

### ISSUE THREAD

**Issue by mklueh** [nuxt/content#2443]
### Environment

Nuxt project info:                                                                                                                        19:20:01

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.7.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.7.2
- Package Manager:  yarn@4.0.2
- Builder:          -
- User Config:      extends, devtools, dev, debug, modules, typescript, ssr, routeRules, nitro, linkChecker, css, runtimeConfig, app, build, nuxtIcon, vueuse, content, experimental
- Runtime Modules:  @unocss/nuxt, @nuxt/content, @vueuse/nuxt@10.6.1, nuxt-icon, @nuxtjs/mdc
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                               19:20:01  

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

This is my content config, that has not changed for a long time
````
  content: {
    documentDriven: false,

    highlight: {
      // Theme used in all color schemes.
      theme: "github-light",
      preload: [
        "diff",
        "ts",
        "ini",
        "docker",
        "js",
        "css",
        "java",
        "groovy",
        "markdown",
        "sql",
        "xml",
        "json"
      ]
    },

    markdown: {
      mdc: true,
      toc: {
        depth: 4,
        searchDepth: 4
      }
    }
  },
```

and I'm using the ContentRenderer like this

```
<ContentRenderer :value="post"/>
```

### Describe the bug

I'm suddenly getting

```
[Vue warn]: Failed to resolve component: MDCRenderer
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Component <Anonymous> is missing template or render function.
```

for my application.


I've dropped in `@nuxtjs/mdc` in hope it would resolve the missing component, but seems to be not related.

### Additional context

_No response_

### Logs

_No response_

**Comment by mklueh** [comment]
@shershen08 glad to hear I'm not the only one

**Comment by mklueh** [comment]
@shershen08 I'm neither using the docus theme, nor nuxt ui, but I got it working with nuxt/content:2.9.0 by downgrading some other packages 😅 will look into it more tomorrow

**Comment by robinsimonklein** [comment]
Same issue here

**Comment by mklueh** [comment]
I've resolved it somehow.

I had the suspicion, that

` import { transformerVariantGroup } from "unocss";`

was responsible, so I removed it and it resolved it "somehow" in my reproducer project.

But then the issue appeared again and then I've upgraded

`nuxt-seo-kit` and replaced it with the new version `@nuxtseo/module`

https://nuxtseo.com/nuxt-seo/getting-started/installation

Pls check if you have those packages in place

**Comment by farnabaz** [comment]
Could you try upgrading to latest version of Nuxt and Content module with clean install? (update versions, remove your lock file and then install deps)

**Comment by botmaster** [comment]
I just ran `npx nuxi upgrade` (remove node_modules and yarn.lock).
And it works 🤷‍♂️.

**Comment by R0N1n-dev** [comment]
Still have this issue. 
have tried
    "@nuxt/content": "2.8.5",
    "nuxt": "^3.8.2" and its not working. 

None of the above has worked for me
Waiting for fix

**Comment by Revaycolizer** [comment]
i am having the same issue just initialized a prject and getting this error

**Comment by MrSunshyne** [comment]
same issue

**Comment by paranoidPhantom** [comment]
Same issue, did everything above, not helping.

**Comment by paranoidPhantom** [comment]
Made a blank [code-sandbox](https://codesandbox.io/p/devbox/flamboyant-grass-jrlt2t?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqsce0kt00073j6misdqijsj%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqsce0kt00023j6mg1nlognb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqscq3fl01io3j6menssn0b1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqsce0kt00063j6m0gdy5f33%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqsce0kt00023j6mg1nlognb%2522%253A%257B%2522id%2522%253A%2522clqsce0kt00023j6mg1nlognb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqsce0kt00013j6mk7k4ox53%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqsce0kt00013j6mk7k4ox53%2522%257D%252C%2522clqsce0kt00063j6m0gdy5f33%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqsce0kt00053j6mqopscx41%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqsce0kt00063j6m0gdy5f33%2522%252C%2522activeTabId%2522%253A%2522clqsce0kt00053j6mqopscx41%2522%257D%252C%2522clqscq3fl01io3j6menssn0b1%2522%253A%257B%2522id%2522%253A%2522clqscq3fl01io3j6menssn0b1%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clqscltj6014j3j6m5ndqdpuj%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqscltj6014j3j6m5ndqdpuj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) with only Nuxt 3.9.0 and MDC 0.3.0 and it still does not resolve the component.

**Comment by wJoenn** [comment]
@farnabaz haven't seen this issue in a while.
I'm using nuxt 3.11.1 and /content 2.12.1 now and everything work as intended.

Issue can probably be closed
