### ISSUE TITLE
<ContentDoc /> component path property must be lower letter

### ISSUE THREAD

**Issue by lxxaisy** [nuxt/content#2447]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.14.2
- Nuxt Version:     3.6.2
- CLI Version:      3.10.0
- Nitro Version:    2.7.2
- Package Manager:  pnpm@8.7.4
- Builder:          -
- User Config:      modules, build, devtools, content
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxt/content@2.9.0
- Build Modules:    -
------------------------------

### Reproduction

![WX20231123-191625@2x](https://github.com/nuxt/content/assets/79672674/be1f34cc-4acd-4e6e-9824-1127ca1319d9)
![WX20231123-191637@2x](https://github.com/nuxt/content/assets/79672674/0f7db2e8-c57f-4fd9-b433-2836ccbe2a83)

the first screenshot is the code.the second is the web show. clearly if the route.path is lower letter it works.

### Describe the bug

![WX20231123-190833@2x](https://github.com/nuxt/content/assets/79672674/f4402f1d-dbbd-423b-98ec-6f54ad0989a7)

like the screenshot, the $route.path is **"codepenio/easyComSlider"**. but when i use <ContentDoc /> in the pages/codepenio/easyComSlider.vue can not render the markdown file. when i add path "codepenio/easycomslider" it works.
according to the article,default path is the $route.path. is the path lower letter is neccessary.

please forgive my terrible english.

**Comment by AssetCEO** [comment]
Although the case of URLs does not affect URL resolution in most cases, it is generally recommended to use lowercase and separate each word with a hyphen (-) for SEO purposes. For example, `codepenio/easyComSlider` is recommended to be changed to `codepenio/easy-com-slider`. This is because the URL **easyComSlider** is easily parsed as **ONE** word instead of three words.

雖然URL的大小寫在多數狀況下不影響網址解析。但就SEO的角度來看，通常建議使用小寫，並將各個單字用-隔開。例如 codepenio/easyComSlider ，建議改成 codepenio/easy-com-slider。這是因為**easyComSlider**容易被解析成一個字，而非三個字。

**Comment by lxxaisy** [comment]
Thank you for the comment and the recommend.But the documentation about ContentDoc confused me.The path default value is the $route.path,but when it is not the letter word,it will not work.

**Comment by AssetCEO** [comment]
I agree with your point. Perhaps the official documentation should remind users about this issue, or update the path parsing logic. However, I would recommend the former, for SEO purposes.

**Comment by lxxaisy** [comment]
Thank you again and I will follow your recommend.

**Comment by dominik-kuhn** [comment]
I have the same issue with resolving the path in queryContent(). It doesnt work if capital letters appear in the path. If this is a desired behavior, it should be mentioned in the documentation and also in the migration guide, as it still worked with capital letters in the old version of nuxt-content.
