### ISSUE TITLE
Prerender takes 10 minutes per page!!!

### ISSUE THREAD

**Issue by Neo-Zhixing** [nuxt/content#2449]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.10.2
- Builder:          -
- User Config:      devtools, extends, css, modules, site, sitemap, nitro
- Runtime Modules:  @nuxt/content@2.9.0-28344318.76dc891, @nuxt/ui@2.10.0-28344386.15a40f5, nuxt-simple-sitemap@4.1.6
- Build Modules:    -
------------------------------

### Reproduction

To test this, download this zip file: https://neo-zhixing.github.io/vk-doc-md/dist.zip and put it in `./content/man`

Then, create a new module to populate the prerendering routes
```
import { readdir } from 'fs/promises';

export default defineNuxtModule({
    async setup(_, nuxt) {
        // Set the code highlight configurations
        nuxt.options.nitro.prerender = nuxt.options.nitro.prerender  {};
        nuxt.options.nitro.prerender.routes = nuxt.options.nitro.prerender.routes  [];
        const routes = new Set(nuxt.options.nitro.prerender.routes);

        const results = await readdir('./content/man');
        for (const filename of results) {
            routes.add('/man/' + filename.slice(0, -3));
        }
        nuxt.options.nitro.prerender.routes = Array.from(routes);
    }
})

```

### Describe the bug

Prerendering 2000+ markdown pages take 26s per page locally. On vercel this takes 10s per page 

![image](https://github.com/nuxt/content/assets/8980455/08c4981c-2a1b-414b-ab1a-6c79c8339ad8)

Adding 20ish longer documents and this becomes 10 minutes PER PAGE.

![image](https://github.com/nuxt/content/assets/8980455/b032f969-74c8-4c5d-8007-7941f2980ddb)

What does this mean? It means that your page generation is O(n) to the amount of content. Total prerender time is O(n^2) to the amount of content you have.

This makes nuxt-content unsuitable for anything non-trivial when you have more than 1000 documents.

Removing half the pages and the per-page rendering time reduce by half.

**Comment by kakkokari-gtyih** [comment]
Related to #2476

**Comment by kakkokari-gtyih** [comment]
I'm experiencing the same problem (ref: https://github.com/misskey-dev/misskey-hub-next/issues/72). 
My project has 3000+ markdown documents and it takes about 30 seconds to generate each page.

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.18.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.12.1
- Builder:          -
- User Config:      runtimeConfig, css, modules, app, content, i18n, colorMode, postcss, alias, vite, nitro, hooks, experimental, routeRules
- Runtime Modules:  @nuxt/content@2.10.0, @nuxtjs/i18n@8.0.0, @nuxtjs/color-mode@3.3.2
- Build Modules:    -
------------------------------

![image](https://github.com/nuxt/content/assets/67428053/bba4c61b-b770-4a86-9e80-ad828964c293)
