### ISSUE TITLE
Possibility to order the result of fetchContentNavigation()

### ISSUE THREAD

**Issue by idesignzone** [nuxt/content#2456]
I am trying to create a website menu using the navigation. When I use fetchContentNavigation(), it returns the title and the path of each item but there is no way to order the result. 
Consider for example a "Home" item in a website menu must be always the first in the list.
<img width="158" alt="image" src="https://github.com/nuxt/content/assets/3501211/80ebe3c6-00c3-4d7a-9f62-ba1c0a34f2ec">

**Comment by nobkd** [comment]
You can prefix your files with numbers to set an order: https://content.nuxt.com/usage/content-directory#ordering

This should just be used by fetchContentNavigation.

If you want to insert pages alter, you can just leave some numbers blank to be able to add pages within.
