### ISSUE TITLE
ability to prevent contentdoc from setting title

### ISSUE THREAD

**Issue by Reconnact** [nuxt/content#2458]
### Describe the feature

It would be nice to be able to prevent `ContentDoc` setting the `title` of a page.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by nobkd** [comment]
Sounds related to #1906
You could try this: https://github.com/nuxt/content/issues/1906#issuecomment-1586323956 (`<ContentDoc :head="false" />`)
But I'm not sure, if it fits your use case / helps in any way.
Good Luck

**Comment by Reconnact** [comment]
Thanks, this works!
