### ISSUE TITLE
pnpm build failed nitro-prerenderer cannot be external

### ISSUE THREAD

**Issue by putrafajarh** [nuxt/content#2461]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.18.2
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.1.0
- Builder:          -
- User Config:      app, debug, runtimeConfig, devtools, ssr, modules, content, i18n, swiper, googleFonts, unocss
- Runtime Modules:  @unocss/nuxt@0.57.7, @nuxt/content@2.9.0, @nuxtjs/i18n@8.0.0-rc.5, @vueuse/nuxt@10.6.1, @nuxtjs/google-fonts@3.1.0, nuxt-swiper@1.2.2, nuxt-simple-sitemap@4.1.13
- Build Modules:    -

### Reproduction

`
pnpm install
pnpm build
`

### Describe the bug

cant build

### Logs

```Shell
ℹ Prerendering 1 routes                                                                                                                                nitro 11:38:36 AM
  ├─ /api/_content/cache.1702528706956.json (50ms)                                                                                                      nitro 11:38:36 AM

[nitro 11:38:36 AM]  ERROR  RollupError: Entry module "node_modules/.pnpm/nitropack@2.8.0/node_modules/nitropack/dist/runtime/entries/nitro-prerenderer" cannot be external.


undefined


 ERROR  Entry module "node_modules/.pnpm/nitropack@2.8.0/node_modules/nitropack/dist/runtime/entries/nitro-prerenderer" cannot be external.                   11:38:36 AM

  at error (node_modules/.pnpm/rollup@4.6.0/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
  at ModuleLoader.loadEntryModule (node_modules/.pnpm/rollup@4.6.0/node_modules/rollup/dist/es/shared/node-entry.js:17962:20)
  at async Promise.all (index 0)



 ERROR  Entry module "node_modules/.pnpm/nitropack@2.8.0/node_modules/nitropack/dist/runtime/entries/nitro-prerenderer" cannot be external.                   11:38:36 AM

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by putrafajarh** [comment]
Fixed by update the nitropack
`pnpm update nitropack@2.8.1`

dont know why pnpm dev and build not using same version of nitro

**Comment by joppehoekstra** [comment]
I'm facing the same issue with nitropack@2.9.4
