### ISSUE TITLE
Setting colorMode for .md pages doesn't work

### ISSUE THREAD

**Issue by shershen08** [nuxt/content#2464]
### Environment

-----------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.8.0
- Builder:          -
- User Config:      routeRules, app, extends, modules, css, components, pinceau, content, colorMode, experimental, typescript, nitro
- Runtime Modules:  @nuxt-themes/tokens@1.9.1, @nuxthq/studio@1.0.0, @nuxtjs/color-mode@3.3.2, @nuxt/content@2.8.5, @vueuse/nuxt@10.4.1, nuxt-config-schema@0.4.6, app/module, normalizedModule()
- Build Modules:    -

### Reproduction

Create new nuxt3 app + add nuxt/content module, try setting .md files to have dark layout.
I've tried:
1) in .md files
```
---
title: Home
navigation: false
colorMode: dark
layout: page
---
```
and
```
---
title: Home
navigation: false
colorMode:
  preference: dark
  forced: true
  fallback: dark
layout: page
---
```

2) in `src/app.vue`
```
<script setup>
definePageMeta({
   colorMode: 'dark',
})
</script>
```

3) in `nuxt.config.ts`
```
  colorMode: {
    classSuffix: '',
    preference: 'dark',
    fallback: 'dark',
  }
```
and
```
 content: {
    documentDriven: {
      globals: {
        theme: {
          colorMode: {
            classSuffix: '',
            preference: 'dark',
            fallback: 'dark',
          }
        }
      }
    },
  },
```

nothing of this works.
I can only set color for individual .vue pages with 
```
definePageMeta({
   colorMode: 'dark',
})
```

### Describe the bug

Unable to set dark mode forced for ANY of the `.md` pages. Only possible for `/pages/somepage.vue`, but not for `/content/somefile.md`

**Comment by AssetCEO** [comment]
Variables in .md files do not automatically map to your props. You must manually extract the variable content from .md files.
`const myColorMode = await queryContent('articles').only('colorMode').find();`

**Comment by AssetCEO** [comment]
Variables in .md files do not automatically map to your props. You must manually request the variable content from .md files.
`const myColorMode = await queryContent('articles').only('colorMode').find();`

**Comment by AssetCEO** [comment]
I may have misunderstood your question. If you want to force all pages (including .md pages) to be dark mode, this is a color-mode module related issue. My project is set up like this:

```
// app.vue
const colorMode = useColorMode();
colorMode.preference = 'dark'
```

According to the official documentation of color-mode, `definePageMeta()` is only effective at the page level, which means you need to set it for each page in the `/pages` directory.
