### ISSUE TITLE
✨ Add support for shikiji-transformers

### ISSUE THREAD

**Issue by jd-solanki** [nuxt/content#2465]
### Is your feature request related to a problem? Please describe
I recently migrated my blog from VitePress to Alpine due to Nuxt Studio and realized I can't use syntax like `// [!code --]`. 

### Describe the solution you'd like
As nuxt content already uses shikiji and shikiji do provide support for this syntax can you please enable it?

### Describe alternatives you've considered
None.

### Additional context
Thanks for Nuxt Studio & Alpine ❤️

**Comment by farnabaz** [comment]
This feature is added to @nuxtjs/mdc in https://github.com/nuxt-modules/mdc/pull/117 and is available in [Content 2.10.0](https://github.com/nuxt/content/releases/tag/v2.10.0).
