### ISSUE TITLE
Page title suffix with document title

### ISSUE THREAD

**Issue by avi-agg** [nuxt/content#2466]
How can I suffix my website name on the page title with doc title?

**Comment by AssetCEO** [comment]
In app.vue:

```
<script setup>
useHead({
  titleTemplate: (titleChunk) => {
    return titleChunk ? `${titleChunk} - Site Title` : 'Site Title';
  }
})
</script>
```
You can find more details in this official document: [SEO and Meta](https://nuxt.com/docs/getting-started/seo-meta)

**Comment by avi-agg** [comment]
Thanks a lot!
