### ISSUE TITLE
`/api/_content` Document not found

### ISSUE THREAD

**Issue by Sazzels** [nuxt/content#2478]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.5
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxt/content@2.10.0
- Build Modules:    -
------------------------------

### Reproduction

```
git clone https://github.com/nuxt/starter.git
cd starter/
git checkout content
npm install
npm run build
node .output/server/index.mjs
``` 

### Describe the bug

shouldn't there be a `api` behind that endpoint from where i could get infos like `title, description, updated at`? 

https://content.nuxt.com/get-started/configuration#api

```
GET http://localhost:3000/api/_content

Document not found, overwrite this content with #not-found slot in <ContentDoc>.
```

**Comment by farnabaz** [comment]
`/api/_content` is the `baseURl` for module APIs. The module exposes some APIs under this base.
You can hit `/api/_content/query` and see the result of query API.
