### ISSUE TITLE
Partial content is not accessible via URL

### ISSUE THREAD

**Issue by mlapeyre3** [nuxt/content#2488]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxt/content@2.10.0
- Build Modules:    -
------------------------------

### Reproduction

Please refer to this [stackblitz](https://stackblitz.com/edit/nuxt-starter-nrhegb?file=pages%2F%5B...slug%5D.vue)

### Describe the bug

Hello,
I might have misunderstood the purpose of _partial content.
- I have a static website with a navigation header using fetchContentNavigation().
- I want some page not to be displayed in the navigation menu so I set them as partial (e.g: _about.md)
- However, I still expect to browse http://mydomain/about. This is not the case as I get a 404 Not Found error as if Nuxt Content was completely ignoring the file 🤔

Is this the expected behavior?
Thanks!

**Comment by mlapeyre3** [comment]
✅ In the end I removed the partial prefix `_` and used "navigation: false" in the metadata of the content file.

**Comment by nobkd** [comment]
#2410
