### ISSUE TITLE
When custom ProsePre and ProseCode components, ProseCode do not work

### ISSUE THREAD

**Issue by huala-fun** [nuxt/content#2493]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, modules, content
- Runtime Modules:  @nuxt/content@2.10.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-81yu6z?file=README.md

### Describe the bug

When I use the ProseCode and ProsePre components together, the ProseCode component does not work, but when I use the ProseCode component alone, it can work

**Comment by charlie0228** [comment]
ProseCode is work with inline like `inline code`

**Comment by charlie0228** [comment]
If you want to using inline code like `code`, using `ProseCodeInline.vue`
If you want to using code block line ```, , using `ProsePre.vue`

I also found this issue and release a [PR](https://github.com/nuxt/content/pull/2513)
