### ISSUE TITLE
Vue Components in nested directories 

### ISSUE THREAD

**Issue by Jannchie** [nuxt/content#2500]
In nuxt, vue components under the path `components/Foo/Bar.vue` can be called with `<FooBar />`. Components in `components/content/` are not recognized in this way. 

For example, `components/content/Foo/Bar.vue` cannot be use in markdown file by:

```
::foo-bar
::
```

**Comment by nobkd** [comment]
See https://github.com/nuxt/content/discussions/2155#discussioncomment-6387021
