### ISSUE TITLE
Deprecated Dependency shiki-es@0.14.0 used

### ISSUE THREAD

**Issue by nicokempe** [nuxt/content#2507]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.8.1
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.14.1
- Builder:          -
- User Config:      preset, experimental, devtools, modules, serverMiddleware, nitro, i18n, cloudflareAnalytics, turnstile, css, postcss, mongoose, app, runtimeConfig, routeRules, image, security, content, typescript
- Runtime Modules:  @nuxt/image@1.2.0, @nuxt/devtools@1.0.8, @nuxt/content@2.10.0, @nuxtjs/i18n@8.0.0, @nuxtjs/turnstile@0.6.3, @nuxtjs/tailwindcss@6.10.4, nuxt-security@1.0.0, nuxt-headlessui@1.1.5, nuxt-cloudflare-analytics@1.0.8
- Build Modules:    -
------------------------------

### Context

I'm currently working on a Nuxt 3 project and have encountered a concern regarding dependencies. It appears that `@nuxt/content` version 2.10.0 relies on `shiki-es@0.14.0`, which has been marked as deprecated.

### Describe the bug

**Issue Description:**
While performing a dependency audit using `pnpm why shiki-es`, I discovered this deprecated dependency. Given the importance of maintaining up-to-date and secure dependencies, this raises concerns about future compatibility and potential security issues.

**Expected Behavior:**
Ideally, `@nuxt/content` should use up-to-date, actively maintained dependencies to ensure the stability and security of projects that depend on it.

**Steps to Reproduce:**
1. In a Nuxt 3 project, add `@nuxt/content` version 2.10.0.
2. Run `pnpm why shiki-es` to see the dependency chain.

Is there a plan to update or replace this deprecated subdependency in an upcoming release of `@nuxt/content`? Any information or guidance on this would be greatly appreciated.

### Additional context

Thank you for your attention to this matter and your continued work on `@nuxt/content`.

### Logs

```Shell
$ pnpm install
 WARN  2 deprecated subdependencies found: shiki-es@0.14.0, sourcemap-codec@1.4.8
Packages: +1144

$ pnpm why shiki-es
Legend: production dependency, optional only, dev only

website@v2024.1.1-dev C:\Users\nicokempe\Documents\WorkSpace\GitHub\myorga\myrepo

dependencies:
@nuxt/content 2.10.0
└── shiki-es 0.14.0
```

**Comment by nobkd** [comment]
Refer to #2459

**Comment by nicokempe** [comment]
Havent seen that one, I will close this issue as duplicate
Thank you

**Comment by yangjindong** [comment]
Although the main branch has updated, but in the latest tag: 2.10.0, there's still using shiki-es.
