### ISSUE TITLE
Syntax highlighting does not work when using `pnpm`

### ISSUE THREAD

**Issue by JMaylor** [nuxt/content#2511]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.10.4
- Builder:          -
- User Config:      modules, content
- Runtime Modules:  @nuxt/content@2.10.0
- Build Modules:    -
------------------------------

### Reproduction

1. Create a new project `npx nuxi@latest init content-app -t content` - uses `@nuxt/content v2.10.0`
2. Add any code block to `index.md` file
3. Add highlight theme to `nuxt.config.ts` e.g. `content: { highlight: { theme: 'light-plus' }}`
4. Install packages with `npm install`
5. Start dev server and open `http://localhost:3000`. Code syntax highlighting should work fine.
6. Remove `node_modules/` and `pacakge-lock.json`.
7. Install packages with `pnpm install`.
8. Start dev server and open `http://localhost:3000`. Code is not highlighted.

### Describe the bug

When installing `@nuxt/content` with `pnpm`, code syntax highlighting does not work.

### Additional context

This is probably an upstream issue, but I'm not sure with which package.

**Comment by JMaylor** [comment]
Closing as I think that this is actually an issue with `nuxt/content > 2.8.0`. I'll make a separate issue after more investigation.

**Comment by jairoblatt** [comment]
@JMaylor I had the same issue, Have you discovered anything that fixes this?

**Comment by whcxxb** [comment]
Same problem with syntax highlighting issue and nuxt/img module not working either, same project works fine on macOS.
