### ISSUE TITLE
shikiji/dist/index.mjs does not provide an export named 'addClassToHast'

### ISSUE THREAD

**Issue by shershen08** [nuxt/content#2515]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.9.2
- Builder:          -
- User Config:      ssr, extends, modules, hooks, colorMode, ui, fontMetrics, googleFonts, routeRules, devtools, typescript, content, nitro
- Runtime Modules:  @nuxt/content@2.10.0, @nuxt/ui@2.12.0, @nuxthq/studio@1.0.6, @nuxtjs/fontaine@^0.4.1, @nuxtjs/google-fonts@3.1.1, nuxt-og-image@3.0.0-rc.27, @nuxtjs/tailwindcss@6.9.0
- Build Modules:    -

### Reproduction

"@nuxt/content": "2.10.0",

### Describe the bug

Error when running `nuxt dev`

  SyntaxError: The requested module 'node_modules/shikiji/dist/index.mjs' does not provide an export named 'addClassToHast'

full log:
```
[9:59:05 AM]  ERROR  [worker reload] [worker init] The requested module 'FULL_PATH_HERE/docs/node_modules/shikiji/dist/index.mjs' does not provide an export named 'addClassToHast'

  import { addClassToHast, getHighlighter, loadWasm } from 'node_modules/shikiji/dist/index.mjs';
  ^^^^^^^^^^^^^^
  SyntaxError: The requested module 'node_modules/shikiji/dist/index.mjs' does not provide an export named 'addClassToHast'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

**Comment by farnabaz** [comment]
Do you mind providing a simple reproduction using https://nuxt.new/s/content or a github repo?
