### ISSUE TITLE
Nuxt content in Nuxt UI Pro - WSL2 - Doesn't reload the latest changes in the md file

### ISSUE THREAD

**Issue by shivrajd** [nuxt/content#2518]
### Environment

Here is the output of npx nuxi info:

Nuxt project info:                                                                                                       2:39:47 PM

------------------------------
- Operating System: Linux
- Node Version:     v20.11.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.3.0
- Builder:          -
- User Config:      extends, modules, hooks, ui, fontMetrics, googleFonts, routeRules, devtools
- Runtime Modules:  @nuxt/content@2.10.0, @nuxt/image@1.3.0, @nuxt/ui@2.12.3, @nuxtjs/fontaine@0.4.1, @nuxtjs/google-fonts@3.1.3, @vueuse/nuxt@10.7.2, nuxt-og-image@2.2.4
- Build Modules:    -
------------------------------

### Reproduction

1. create a project using: npx nuxi@latest init content-app -t content
2. run the dev server with: npm run dev
3. open the frontend at http://localhost:3000 
4. now add a new line in the index.md file
5. the new content is reflected on the frontend
6. navigate to the about page by clicking on the link on the home page
7. now navigate back to the index page by clicking on the 'back home' link on the about page
8. The new line you added in step 4 is not showing
9. refresh the page, and the new line added in step 4 shows up.

### Describe the bug

nodejs is installed on wsl2 ubuntu 20.04 on windows 11. After installing the Nuxt UI saas template, the project runs fine with the npm run dev. 

But if we change some content in the md file or yml file (nuxt content files), it doesn't reflect those changes in the UI through HMR or even after closing and restarting the session. If we refresh the page, the changes are reflected but if we navigate to some other page through some link say by clicking on blog in the navigation and then clicking on the blog article again, it shows only the last page version.

Same issue also occurs with just the default nuxt content app installation as mentioned in the steps to reproduce.

**Comment by benjamincanac** [comment]
@shivrajd This should have been fixed already by https://github.com/nuxt/content/commit/78e1eebe08204520915b330538e34b6b29663b04 and released in https://github.com/nuxt/content/releases/tag/v2.11.0.

**Comment by shivrajd** [comment]
@benjamincanac Thank you very much. I updated my package.json to use v2.11.0 and now the changes are getting reflected on all but blog pages. But if I test it out with the new saas template instance it works just fine with the blogs too.

I am going to close this now. Appreciate your help !
