### ISSUE TITLE
`rollup-plugin-inject` failed to parse onig.wasm

### ISSUE THREAD

**Issue by awdr74100** [nuxt/content#2520]
### Environment

- Operating System: Darwin
- Node Version:     v20.11.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.14.2
- Builder:          -
- User Config:      devtools, modules, content
- Runtime Modules:  @nuxt/content@2.11.0
- Build Modules:    -

### Reproduction

Start a fresh Nuxt Content project with:

```zsh
pnpm dlx nuxi@latest init content-app -t content
```

Define configuration:

```ts
export default defineNuxtConfig({
  devtools: { enabled: false },
  modules: ["@nuxt/content"],
  content: {
    highlight: {
      theme: {
        dark: "github-dark",
        light: "github-light",
      },
    },
  },
});
```

Start the development server:

```zsh
pnpm dev
```

### Describe the bug

<img width="1137" alt="截圖 2024-01-22 下午7 31 21" src="https://github.com/nuxt/content/assets/47501692/33497446-dcf8-4b56-8f92-be055466e193">

A warning message appears on the console. Is this the expected result? There seems to be no such problem in the previous version.

**Comment by TheMrMilchmann** [comment]
FYI, I believe that this is causing code highlighting to fail on 2.11.0 when running in development mode (via `nuxi dev`).

**Comment by pi0** [comment]
You can safely ignore this warning (will be solved in next minor version of Nitro).

If you are facing a syntax highlighter failing to work, it might be another issue. Please provide a reproduction 🙏🏼

**Comment by puuble** [comment]
Same problem but i don't use @nuxt/content@2.11.0 I think problem from the who is shiki ?
