### ISSUE TITLE
Cannot use function in option of remarkPlugins in `nuxt.config.ts`

### ISSUE THREAD

**Issue by hopoduck** [nuxt/content#2532]
### Environment

Nuxt project info:  

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      devtools, modules, ui, app, content, googleFonts
- Runtime Modules:  @nuxt/ui@2.11.1, nuxt-icon@0.6.7, @nuxtjs/google-fonts@3.1.1, @nuxtjs/fontaine@0.4.1, @nuxt/image@1.1.0, @nuxt/content@2.11.0, @nuxthq/studio@1.0.6, @vueuse/nuxt@10.7.2, @nuxt/image@1.1.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-khom7f?file=nuxt.config.ts

### Describe the bug

This is my nuxt.config.ts content.

```ts
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    "@nuxt/ui",
    "nuxt-icon",
    "@nuxtjs/google-fonts",
    "@nuxtjs/fontaine",
    "@nuxt/image",
    "@nuxt/content",
    "@nuxthq/studio",
    "@vueuse/nuxt",
    "@nuxt/image",
  ],
  // ...
  content: {
    markdown: {
      toc: {
        depth: 2,
        searchDepth: 3,
      },
      remarkPlugins: {
        "remark-wiki-link": {
          wikiLinkClassName: "internal-wiki-link",
          hrefTemplate: (permalink: string) => {
            return `articles/${permalink}`;
          },
        },
      },
    },
  },
});
```

It uses remarkPlugin, where wikiLinkClassName receives a string as a parameter, and hrefTemplate receives a function as a parameter. When executing with this option given, the hrefTemplate key itself will not be passed, so the default value will be used.

Is there any way to use this option?

**Comment by farnabaz** [comment]
It is not possible to read a function from `nuxt.config`. Functions will be supported in next release which implemented in https://github.com/nuxt-modules/mdc/pull/129

**Comment by hopoduck** [comment]
thank you I will check the details.

**Comment by hanyujie2002** [comment]
Same problem here, my code:

```js
......
      remarkPlugins: {
        'remark-math': {}, 
        'remark-gfm': {},
        'remark-github-beta-blockquote-admonitions': {
          classNameMaps: {
            block: (title) => title,
          }
        }
      },
...
```

**Comment by hanyujie2002** [comment]
@hopoduck Hi, did you solve this problem?

**Comment by hanyujie2002** [comment]
> It is not possible to read a function from `nuxt.config`. Functions will be supported in next release which implemented in [nuxt-modules/mdc#129](https://github.com/nuxt-modules/mdc/pull/129)

Would you please give an example on how to pass a function to remark plugin configurations?

**Comment by hopoduck** [comment]
> [@hopoduck](https://github.com/hopoduck) Hi, did you solve this problem?

@hanyujie2002

Hello.
I have since given up using that plugin and haven't looked into it further.

I sorry I couldn't be more helpful.

**Comment by hanyujie2002** [comment]
> > [@hopoduck](https://github.com/hopoduck) Hi, did you solve this problem?
> 
> [@hanyujie2002](https://github.com/hanyujie2002)
> 
> Hello. I have since given up using that plugin and haven't looked into it further.
> 
> I sorry I couldn't be more helpful.

Thanks for your reply. I have to say this is a drawback for nuxt content. 😢
