### ISSUE TITLE
path parts with utf-8 not working - returning "Document not found"

### ISSUE THREAD

**Issue by acrolink** [nuxt/content#2548]
### Environment

Nuxt project info:                                                                                                                                                                7:07:34 PM

------------------------------
- Operating System: Linux
- Node Version:     v20.11.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.12.1
- Builder:          -
- User Config:      devtools, modules, css, plugins, build, app
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.3, @nuxtjs/google-fonts@3.1.3, @nuxt/content@2.12.0
- Build Modules:    -
------------------------------

### Reproduction

`./pages/products/[...slugCategory]/[...slugProduct].vue`

`./content/products/books/موسوعه.json`

### Describe the bug

accessing the URL at:

`/products/books/موسوعه`

returns:
`Document not found, overwrite this content with #not-found slot in <ContentDoc>.`

However if the `json` file path name is `./content/products/books/my-life.json` then the `url` is working fine when accessing: `/products/books/my-life`

**Comment by nobkd** [comment]
You can try setting `_path` key with your real file path to override `slugify` changing your path.

See related comments:

https://github.com/nuxt/content/issues/1383#issuecomment-1196237686
https://github.com/nuxt/content/discussions/2486#discussioncomment-8003935
