### ISSUE TITLE
Add array support when using fields in markdown

### ISSUE THREAD

**Issue by Rednas83** [nuxt/content#255]
### Is your feature request related to a problem? 
When a field in markdown is initialized with an array only the latest item is fetched from the array

**Something like:**
```
---
title: 'Organizer'
person:
  [
    # Not fetched
    {
      'name': 'john',
      'age': 20,
    },
    # Only last item is fetched
    {
      'name': 'steve',
      'age': 21,
    },
  ]
---
```

**Fetched like:**
await this.$content('organizer').only(['person']).fetch()

### Describe alternatives you've considered
Use json with fields fore each json instead of markdown. 

**Something like:**
{
title: 'Organizer',
person:
  [
    {
      'name': 'john',
      'age': 20,
    },
    {
      'name': 'steve',
      'age': 21,
    },
  ]
}
```

### Describe the solution you'd like
Support for arrays when using fields in markdown when fetching

**Comment by azrikahar** [comment]
Can you provide a reproduction repo? I tried the same setup and I was able to fetch the whole array without any issue. Here is my setup:

`content/organizer.md`:

```md
---
title: 'Organizer'
person:
  [
    {
      'name': 'john',
      'age': 20,
    },
    {
      'name': 'steve',
      'age': 21,
    },
  ]
---
```

`page/index.vue`:

```vue
<template>
  <div>
    <pre>{{ markdown }}</pre>
  </div>
</template>

<script>
export default {
  async asyncData({ $content }) {
    const markdown = await $content("organizer").only(["person"]).fetch();
    return { markdown };
  }
};
</script>
```

http://localhost:3000 output:

```json
{
  "person": [
    {
      "name": "john",
      "age": 20
    },
    {
      "name": "steve",
      "age": 21
    }
  ]
}
```

**Comment by Rednas83** [comment]
I see my mistake now. I expected the fetch to only contain the contents of the field.

Something like:
```
    {
      "name": "john",
      "age": 20
    },
    {
      "name": "steve",
      "age": 21
    }
```

**Comment by azrikahar** [comment]
No worries. Unfortunately The expected fetch you mentioned would be difficult since that is not a valid json. Or perhaps you mean you just want the array directly without having to access `markdown.person` to get the array like my example?

If so, you can actually use object destructuring to achieve that. Here is an example:

`page/index.vue`:

```vue
<template>
  <div>
    <pre>{{ person }}</pre>
  </div>
</template>

<script>
export default {
  async asyncData({ $content }) {
    const { person } = await $content("organizer").only(["person"]).fetch()
    return { person }
  }
};
</script>
```

http://localhost:3000 result:

```json
[
  {
    "name": "john",
    "age": 20
  },
  {
    "name": "steve",
    "age": 21
  }
]
```

I suspect that might be what you are going for. Hope it is!
