### ISSUE TITLE
error for markdown files with empty body

### ISSUE THREAD

**Issue by stefanprobst** [nuxt/content#2551]
### Environment

- Operating System: Linux
- Node Version:     v18.19.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.14.1
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxt/content@2.12.0
- Build Modules:    -

### Reproduction

https://github.com/stefanprobst/issue-nuxt-content

### Describe the bug

for a markdown file with an empty body (see [this one](https://github.com/stefanprobst/issue-nuxt-content/blob/main/content/index.md?plain=1) in the issue repro), i get the following error:

```
{
  "message": "You should use slots with <ContentRenderer>",
  "value": {
    "_path": "/",
    "_dir": "",
    "_draft": false,
    "_partial": false,
    "_locale": "",
    "title": "test",
    "description": "",
    "body": {
      "type": "root",
      "children": [],
      "toc": {
        "title": "",
        "searchDepth": 2,
        "depth": 2,
        "links": []
      }
    },
    "_type": "markdown",
    "_id": "content:index.md",
    "_source": "content",
    "_file": "index.md",
    "_extension": "md"
  },
  "excerpt": false,
  "tag": "div"
}
```

instead, i would expect an empty div.

**Comment by prazdevs** [comment]
Since you are using `ContentRenderer` you need to provide an `#empty` slot to fallback in case the markdown body is empty: https://content.nuxt.com/components/content-renderer#slots

**Comment by stefanprobst** [comment]
thanks for pointing to that section in the docs!

however, the wording is a bit ambiguous and it's still not 100% clear to me whether i *must* provide an `#empty` slot, or if this is a bug ("The empty slot *can be used* to display a default content when the document is empty").
