### ISSUE TITLE
Hope to support string rendering, making it convenient to store documents in a database

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/content#2570]
Hope to support string rendering, making it convenient to store documents in a database

**Comment by nobkd** [comment]
There are already related issues / discussions, so you can try looking around, if you find a solution to your problem in any of them.

Here are related ones I found. Maybe they are a starting point for you.

https://github.com/nuxt/content/discussions/1974#discussioncomment-6064421
#1849
#2330

Also, Nuxt Content uses [nuxt-modules/mdc](https://github.com/nuxt-modules/mdc) for rendering.

nuxt-modules/mdc#44

**Comment by bbhxwl** [comment]
> There are already related issues / discussions, so you can try looking around, if you find a solution to your problem in any of them.
> 
> Here are related ones I found. Maybe they are a starting point for you.
> 
> [#1974 (reply in thread)](https://github.com/nuxt/content/discussions/1974#discussioncomment-6064421) #1849 #2330
> 
> Also, Nuxt Content uses [nuxt-modules/mdc](https://github.com/nuxt-modules/mdc) for rendering.
> 
> [nuxt-modules/mdc#44](https://github.com/nuxt-modules/mdc/issues/44) ...


The following code can run normally, but there are warnings. How should I handle this?

<img width="813" alt="截屏2024-02-21 23 59 56" src="https://github.com/nuxt/content/assets/26525599/c6dea402-4c6e-4c24-93ca-2ff7ebdeee36">
