### ISSUE TITLE
failed import from '#build/*'

### ISSUE THREAD

**Issue by RomanRadaykinFrontend** [nuxt/content#2594]
### Environment

- Operating System: Darwin
- Node Version:     v20.11.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      sharedConfig
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

I don't think I need a replay, it just seems like I'm missing something.

### Describe the bug

<img width="356" alt="Снимок экрана 2024-03-25 в 13 26 38" src="https://github.com/nuxt/content/assets/40523857/9c01d8f4-0a45-45c4-9906-c285b13ce617">
<br/>
TS2792: Cannot find module '#build/services/generated/auth'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?

At the same time, the imports are all correct, I can get into each folder along this path.
When importing '../../../*' everything works ok.
How do I make an auto-import to a custom folder?
Or at least remove the error above.

### Additional context

tsconfig
<code>{
  "extends": "./.nuxt/tsconfig.json",
  "moduleResolution":"node",
}</code>

nuxt.config.ts
<code>export const sharedConfig = {
  devtools: { enabled: true },
  rootDir: __dirname,
  modules: ['@element-plus/nuxt', '@pinia/nuxt'],
  elementPlus: {
    importStyle: 'scss',
    themes: ['dark'],
  },
  plugins: ['plugins/ofetch', 'plugins/store'],
  pinia: {
    storesDirs: ['./sharedStore/*'],
  },
// IT IS NOT WORK
  imports: {
    dirs: ['services'],
  },
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: `
            @use "../../assets/styles/typography.scss" as *;
            @use "../../assets/styles/index.scss" as *;
            @use "../../assets/styles/themes.scss" as *;
            @use "../../assets/styles/elements-rewrite.scss" as *;
            @use "../../assets/styles/elements-colors.scss" as *;
            @use "../../assets/styles/fonts.scss" as *;
          `,
        },
      },
    },
  },
}<code/>

### Logs

```Shell
ERROR  Pre-transform error: Failed to resolve import "#build/services/generated/auth" from "../../sharedStore/auth.ts". Does the file exist?
```

**Comment by farnabaz** [comment]
This is not related to content module.
Try creating a simple reproduction using https://nuxt.new/c/v3 and create issue in https://github.com/nuxt/nuxt if issue persists.
