### ISSUE TITLE
Netlify: POST /_content/index 404

### ISSUE THREAD

**Issue by razbakov** [nuxt/content#26]
### Version
@nuxt/content: v1.0.0
nuxt-edge: 2.13.0-26503223.f13b3752

### Steps to reproduce

```
yarn build
```

### What is Expected?

- `/dist/_content/` folder is present
- website is deployable as static website on Netlify

### What is actually happening?

- Open deployed site on Netlify
- Console show: Error 404 for `POST /_content/index`

**Comment by benjamincanac** [comment]
Hey @razbakov,

Could you provide a reproduction link on codesandbox for example?

Are you trying to deploy a SPA?

**Comment by razbakov** [comment]
Yes, spa.

It makes a POST request to /_content/ which doesn't exists. How does this API work? Does it require server?

**Comment by benjamincanac** [comment]
Have you tried nuxt generate? It will be better for SEO purposes.

This module has been thought mainly for this use case.

**Comment by razbakov** [comment]
Here is example - https://codesandbox.io/s/nuxtcontent-demo-keb5g

**Comment by razbakov** [comment]
`nuxt generate` solved the problem
