### ISSUE TITLE
Cannot access 'useNitroApp' before initialization

### ISSUE THREAD

**Issue by Ru1ers** [nuxt/content#2600]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.18.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  pnpm@8.15.4
- Builder:          -
- User Config:      features, devtools, modules, content, i18n
- Runtime Modules:  @nuxtjs/i18n@8.2.0, @nuxt/ui@2.15.0, @pinia/nuxt@0.5.1, @nuxt/content@2.12.1
- Build Modules:    -

### Reproduction

Use @ nuxt/content in the nuxt project. When I use Hooks, I get an error message when starting the project:
```
ERROR  [worker reload] [worker init] Cannot access 'useNitroApp' before initialization                                                                                                                             16:33:49  


at <anonymous> (node_modules\.pnpm\nitropack@2.9.4\node_modules\nitropack\dist\runtime\error.mjs:5:1)
at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

### Describe the bug

/server/plugins/content.ts

```
export default defineNitroPlugin((nitroApp) => {
// @ts-ignore
nitroApp.hooks.hook('content:file:afterParse', (file) => {
if (file._id.endsWith('.md')) {
}
})
})
```
Write according to the instructions in the document

**Comment by pi0** [comment]
Can you please make a runnable reproduction? 🙏🏼

**Comment by Ru1ers** [comment]
Sorry to bother you, it's been resolved.
I guess it has something to do with my local environment. After I deleted node_modules and reinstalled it, there was no problem.

**Comment by Lionberg** [comment]
cleanup did not help. constantly have this error `Cannot access 'useNitroApp' before initialization`.  And I do NOT use Nitro directly.
