### ISSUE TITLE
can not fetch the markdown files

### ISSUE THREAD

**Issue by HomyeeKing** [nuxt/content#262]
```
async asyncData ({ $content, params }) {
    const {doc} = await $content(params.slug || 'index').fetch()
    return doc
  }
```
![image](https://user-images.githubusercontent.com/49113249/87427375-43a84180-c613-11ea-96cb-eca253451d4c.png)
![image](https://user-images.githubusercontent.com/49113249/87427496-76ead080-c613-11ea-8875-2af53d46ae10.png)

**Comment by benjamincanac** [comment]
@HomyeeKing I would suggest to surround your $content call in a try/catch and call the nuxt error method so it doesn't crash and displays the error page from layouts/error.vue.

```js
async asyncData({ $content, params, error }) {
    let doc
    try {
      doc = await $content(params.slug || 'index').fetch()
    } catch (e) {
      return error({ statusCode: 404, message: 'Page not found' })
    }

    return {
        doc
    }
}
```

As for your error, it would be easier with a reproduction link but are your sure you have an index.md file inside content/ folder?

**Comment by HomyeeKing** [comment]
> reproduction

![image](https://user-images.githubusercontent.com/49113249/87525951-c6390b80-c6bc-11ea-9f3c-80df9b83c40c.png)

of course I have **index.md**
I have no idea where is wrong, I think it's **content's**  bug,

**Comment by HomyeeKing** [comment]
alright , problem solved,  I think it's A ...  network problem or something went wrong,  after a NIGHT , it comes back on track
