### ISSUE TITLE
Nuxt Content + Typescript + nuxt-composition-api + statically generated meta from $content

### ISSUE THREAD

**Issue by brett-ep** [nuxt/content#264]
It took me a while to figure out how to do this, but... yeah: 

Nuxt Content + Typescript + nuxt-composition-api + statically generated meta from $content

https://gist.github.com/Glutnix/64d768c0e2f780c5247905f4ee4d65ab

Not sure who I should really be sharing this with, but I want to make sure it gets integrated into Nuxt documentation somewhere, somehow.

If there's interest, I'll make a codesandbox.

If you know a better way to do this with Typescript and no composition-api, I'd like to see that oo..

**Comment by benjamincanac** [comment]
Hey @brett-ep,

Indeed it could be interesting to have this kind of example on the documentation, could you make a PR to add it inside the [Integrations section](https://content.nuxtjs.org/integrations) under `nuxt-composition-api`?

Thanks!

**Comment by mathe42** [comment]
I think the only special think about this you can use `useStatic` or `useFetch` or `useAsync`. `useStatic` is for not ssr the best option but that is not special in the context of the content module.

As you can see in my project here https://github.com/mathe42/EC-Website-test/blob/master/pages/downloads/_.vue#L38 that there are quite compact options.
