### ISSUE TITLE
How get content from other repos ?

### ISSUE THREAD

**Issue by borisdamevin** [nuxt/content#265]
Hi,

I try to develop one plateform with Nuxt for get in on place docs from multiple repositories.
But I can't get the content from outside `content` folder, someone has one solution for get content outside the default folder ?

Thank you.

**Comment by azrikahar** [comment]
I'm not sure if I understood the question correctly, but if you wish to change the source from the default `content` folder to another folder, [you can use the "dir" property](https://content.nuxtjs.org/configuration#dir) to set it to another folder of your choice.

Example:

`nuxt.config.js`:

```js
export default {
    ...
    content: {
        dir: 'docs'
    }
    ...
}
```

This means nuxt/content will target `docs` folder from now on.

**Comment by borisdamevin** [comment]
Not in that way, I try to get content from multiple sources, like `node_modules` packages.

**Comment by azrikahar** [comment]
Based on what I understood from the source code, seems like currently it will only search/walk through 1 specific directory, which is the `dir` property we mentioned, [as seen in this line of code](https://github.com/nuxt/content/blob/dev/lib/database.js#L69) (`this.dir`). 

I believe one possibility was supposed to making the root directory `/` as the dir so it will crawl through `node_modules` as well.  However, I do think that is risky especially if there are tons of packages in node_modules, so they actually added sort of a fail-safe [at this line](https://github.com/nuxt/content/blob/dev/lib/database.js#L92) which basically ignores `node_modules` and any file/directory that starts with `.` (based on the regex used).

Just curious, is there a specific use case where you need to get content from `node_modules` as well?

**Comment by borisdamevin** [comment]
Use case:

Multiple repositories & each has this own docs in ``.md`` and I want assemble all docs in one place, with one design, set menu, etc...., but I want keep on each projects this own docs.

So one content platerform with multiple content sources.

**Comment by mathieunicolas** [comment]
Maybe you can ` git clone` the repos in your `content` folder and create a cron job to `git pull` each repo ?

**Comment by borisdamevin** [comment]
Yes, but I try to find one more usefull method.

**Comment by mayashavin** [comment]
You can add the other repo as submodule by using `git submodule add link-to-your-repo`. I did that recently on my project.
https://github.blog/2016-02-01-working-with-submodules/
Hope it helps

**Comment by AdrianoCahete** [comment]
You can fetch Github API.

This repo for example: https://api.github.com/repos/nuxt/content/git/trees/bef85f4bf2018cf59ada8188bb65dc05feb313a2

```
{
  "sha": "bef85f4bf2018cf59ada8188bb65dc05feb313a2",
  "url": "https://api.github.com/repos/nuxt/content/git/trees/bef85f4bf2018cf59ada8188bb65dc05feb313a2",
  "tree": [
    {
      "path": ".editorconfig",
      "mode": "100755",
      "type": "blob",
      "sha": "9142239769f522e59cfcebe8ae5d57dc4dc90822",
      "size": 207,
      "url": "https://api.github.com/repos/nuxt/content/git/blobs/9142239769f522e59cfcebe8ae5d57dc4dc90822"
    },
    {
      "path": ".eslintignore",
      "mode": "100644",
      "type": "blob",
      "sha": "5588d5dbcc3e98d2e32f89dfe9ec6349ef2a9ac8",
      "size": 67,
      "url": "https://api.github.com/repos/nuxt/content/git/blobs/5588d5dbcc3e98d2e32f89dfe9ec6349ef2a9ac8"
    },
(...)
```

**Comment by rahulkumarsingh73690** [comment]
> Yes, but I try to find one more usefull method.

I am also looking for this but didn't get good solution

**Comment by borisdamevin** [comment]
Any chance to see this option on one of next version?

**Comment by Tahul** [comment]
Hello :)

The multi-source is now a native feature from @nuxt/content!

We will need contributions to add new drivers, but it should now be possible!

If you want to load multiple directories from same file-system, you can look at this answer:
https://github.com/nuxt/content/issues/1004#issuecomment-1121139255

Otherwise, I would suggest tracking this issue:
https://github.com/nuxt/content/issues/1049

I am closing this as this won't be a part of roadmap to add this in v1 and other issues are tracking the same topic for v2.

Feel free to re-open with a PR if you manage to add this in v1!

Thanks a lot for all these discussions in this issue, this helps a lot to understand your needs for future updates!
