### ISSUE TITLE
Ordered incorreclty

### ISSUE THREAD

**Issue by moshetanzer** [nuxt/content#2676]
### Environment

ui.nuxt.com

### Reproduction

https://ui.nuxt.com/pro/components/aside-links

### Describe the bug

Hey,

Have seen this all over the place. 

However, here is an example,

Even though the Aside comes before Asidelinks, the botoom navigation treats it the opposite way:

https://ui.nuxt.com/pro/components/aside-links

**Comment by owljackob** [comment]
I think this issue is a mistake as it talks about an issue with Nuxt UI Pro, not Nuxt Content.

**Comment by moshetanzer** [comment]
nope. for some reason nuxt content mixes up order of md files. have a look
at repo

**Comment by farnabaz** [comment]
I didn't get your point here. Could you describe with some explanation?

**Comment by nobkd** [comment]
> [!Note]
> Seems like this has been fixed already.

Previously the sidebar had:

- Aside
- **AsideLinks** (current page)
- AuthForm

and the bottom navigation had:

- prev: Content
- next: Aside

I think.

**Comment by farnabaz** [comment]
Thanks for explanation. 
Indeed, it should be fixed in https://github.com/nuxt/content/commit/316263956086f093d0d4c0db22f26c99eefaa2cb#diff-38a54ced486da37abc46993ca56426c2918c4852e8b73254a025e3226d9d8873R304
