### ISSUE TITLE
Upgrade to @nuxt/content 2.13.1 breaks static page generation

### ISSUE THREAD

**Issue by Mini-ghost** [nuxt/content#2688]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      modules, content, app, css, colorMode, vite, runtimeConfig, nitro, svgoLoader, experimental
- Runtime Modules:  @nuxt/image@1.7.0, @nuxt/content@2.13.1, @unocss/nuxt@0.59.4, @nuxtjs/color-mode@3.4.2, @vueuse/nuxt@10.11.0, @nuxtjs/sitemap@5.3.2, nuxt-svgo-loader@0.4.0
- Build Modules:    -
------------------------------

### Reproduction

N/A

### Describe the bug

In @nuxt/content 2.13.0, when I run `nuxt generate`, it successfully builds all my static pages. However, after upgrading to 2.13.1, it only creates `404.html` and `200.html` along with other pages related to `@nuxtjs/sitemap`.

I found this is related to issue #2681. It seems the fix was intended to resolve an issue with `nuxt/i18n`, but it has disrupted the existing functionality. Is there a better approach? Would it be better to address this issue directly within `nuxt/i18n`?

Currently, we need to add the following to `nuxt.config.ts` to continue working as expected:

```ts
export default defineNuxtConfig({
  // ...
 
  nitro: {
    prerender: {
      routes: ['/'],
    },
  },
});
```

**Comment by awwaiid** [comment]
I confirm both the problem (`'/'` not included implicitly) and that adding it explicitly makes it work.

**Comment by damisparks** [comment]
@Mini-ghost I appreciate you for sharing. I used your workaround.
```ts
export default defineNuxtConfig({
  // ...
 
  nitro: {
    prerender: {
      routes: ['/sitemap.xml', '/'],
    },
  },
});
```

**Comment by Skyost** [comment]
Thanks for the workaround guys.

**Comment by farnabaz** [comment]
This is actually not related to Content module but Nuxt itself. There is a regression in Nuxt which cause removing `/` from pre-render routes and therefore static generation breaks.

I second on https://github.com/nuxt/content/issues/2688#issuecomment-2214638068, the only workaround for now is to add `/` into `nitro.prerender.routes` or `routeRules`

**Comment by Mini-ghost** [comment]
@farnabaz Thank you for your explanation. If this is expected by the team, then it’s fine! Should I close this issue?

However, wouldn't it be better to highlight this point in the release log? For users, being able to identify potential issues from the release log could significantly reduce confusion.

**Comment by farnabaz** [comment]
@Mini-ghost Indeed it would be better if we add a note in docs or releases.
This issue supposed to be fixed in latest Nuxt patch but still exists and waiting to be fixed in next patch.

Feel free to close the issue, I'll update release notes to note about regression

**Comment by Mini-ghost** [comment]
Thank you very much for your work. 🙌
