### ISSUE TITLE
docs(bugs): content.nuxt.com is 404 error

### ISSUE THREAD

**Issue by shinGangan** [nuxt/content#2698]
### Environment

- Google Chrome : 126.0.6478.127

### Reproduction

-

### Describe the bug

When I accessed the official documentation today (July 10, 2024 19:30 (JST)), a 404 error was returned.
No pages are displayed.

Are you getting build errors with the latest release?

![image](https://github.com/nuxt/content/assets/44604921/c7ef2f7b-12cb-4a61-9049-cadd680e0af2)

**Comment by farnabaz** [comment]
Thanks for the issue
Should be fixed now

**Comment by shinGangan** [comment]
@farnabaz , thank you for your response!

I can now view it without any problems, and I think I can resume my research. 💚
