### ISSUE TITLE
Footnote support?

### ISSUE THREAD

**Issue by jhull** [nuxt/content#27]
Wondering why Markdown footnotes:

```
Sam ate a sandwich.[^opinion]

[^opinion]: It was a very good sandwich.
```

does not seem supported in this module.

My hand-rolled Nuxt CMS used several MarkdownIt modules in the `extend` key in `nuxt.config.js`. Is there a way I can add these to `content`?

Previous config was:

```
    extend (config, ctx) {
      config.resolve.alias['vue'] = 'vue/dist/vue.common',
      config.module.rules.push({
        test: /\.md$/,
        loader: 'frontmatter-markdown-loader',
        include: path.resolve(__dirname, 'content'),
        options: {
          typographer: true,
          markdownIt: markdownIt({ html: true }).use(markdownItFootnote)          
             .use(require('markdown-it-video'), {
                vimeo: { 
                  options: {'responsive': true },
                  height: '',
                  width: ''
                },
             })
}
```

**Comment by benjamincanac** [comment]
Hey @jhull,

Footnotes are a non-standard markdown extension and aren't supported by default.

However you could use Vue.js components directly in your markdown files to have the same result, see the [documentation](https://content.nuxtjs.org/writing#vue-components).

**Comment by jhull** [comment]
I just noticed Nuxt has [a MarkdownIt module](https://github.com/nuxt-community/modules/tree/master/packages/markdownit) already. Does this not integrate with the Content module?

**Comment by benjamincanac** [comment]
This modules doesn't use markdown-it but [marked](https://github.com/markedjs/marked)

**Comment by cschweda** [comment]
This might be a possible solution:

[https://github.com/markedjs/marked/issues/1562#issuecomment-551269829](https://github.com/markedjs/marked/issues/1562#issuecomment-551269829)

The lack of footnote support is a non-starter -- especially in academic circles where many documents are authored in markdown these days. 

And, sure, I realize footnotes are "non-standard" -- okay, fair enough -- but markdown-it has a module that easily adds footnotes.

Are there plans for the ability to swap out 'marked' for 'markdown-it'? 

Sort of like how [frontmatter-markdown-loader has this option](https://hmsk.github.io/frontmatter-markdown-loader/options.html#custom-compiler)?

**Comment by benjamincanac** [comment]
Hey @cschweda,

Markdown footnotes are now supported in [v1.1.0](https://github.com/nuxt/content/releases/tag/v1.1.0).

Tell me if you encounter any issue.

**Comment by cschweda** [comment]
Will do. Thank you! :)

**Comment by jhull** [comment]
While the footnotes now show up, they don't work with "relative" footnotes (`[^word]` instead of [^1]). The link to the footnote shows the actual `word` rather than a 1, or 2, etc. The way it works with Markdown footnotes everywhere else.

**Comment by samidalouche** [comment]
> Markdown footnotes are now supported in [v1.1.0](https://github.com/nuxt/content/releases/tag/v1.1.0).

Is there any plan to support multi-paragraph footnotes?
Thanks
