### ISSUE TITLE
Add Default Language Field to Nuxt Config for Shiki Code Highlighting

### ISSUE THREAD

**Issue by raphi-0901** [nuxt/content#2715]
### Is your feature request related to a problem? Please describe
If a codeblock has no language specified at all, Shiki simply does not highlight anything. An extra field in the nuxt config would be nice to set an default or fallback language if the specified language does not exist or is not present at all.

### Describe the solution you'd like
Add a fallback/default language field to nuxt config. 

### Describe alternatives you've considered
I tried to rewrite the ProsePre.vue and set the language there but it seems that the Shiki highlighting process is done before getting passed as a prop.

**Comment by farnabaz** [comment]
Thank you for creating an issue, However having a default language seems not a standard solution.
Markdown renderers treat missing languages as text language.  

However, you can use [`content:file:beforeParse`](https://content.nuxt.com/recipes/hooks#contentfilebeforeparse) to replace *\`\`\`* with **\`\`\`some-language**  in your own project.
