### ISSUE TITLE
Slot components don't work anymore

### ISSUE THREAD

**Issue by borisdamevin** [nuxt/content#272]
### Version
@nuxt/content:  v1.4.1
nuxt: v2.13.3

### Reproduction

https://codesandbox.io/s/goofy-brahmagupta-o2bvh

### Steps to reproduce

Create one component with ``<slot/>`` and call it on markdown with content inside. 

### What is Expected?

The component need to be convert in HTML.

### What is actually happening?

The component is not converted in HTML.

**Comment by benjamincanac** [comment]
Hey @borisdamevin, could you provide a reproduction link?

**Comment by borisdamevin** [comment]
@benjamincanac Updated.

**Comment by benjamincanac** [comment]
Hey @borisdamevin, thanks for the reproduction. It seems there is an issue with local components registration in development.

This is not an issue with `<slot/>` but with your component that is not imported.

For now, to solve the issue you can put your components inside `components/global/` using Nuxt 2.13+ and setting `components: true` in your `nuxt.config.js`, see [Vue components](https://content.nuxtjs.org/writing#vue-components) > `Global components`.

**Comment by benjamincanac** [comment]
Duplicate #261
