### ISSUE TITLE
When I set useHead in app.vue, the webpage title does not change after leaving the content-related page

### ISSUE THREAD

**Issue by censujiang** [nuxt/content#2727]
### Environment

```console
------------------------------
- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  bun@1.1.18
- Builder:          -
- User Config:      modules, alias, vite, components, experimental, css, scripts, imports, nitro, routeRules, devServer, site, content, app, devtools, device, features, eslint, arco, compatibilityDate, future
- Runtime Modules:  @vueuse/nuxt@10.11.0, @unocss/nuxt@0.61.5, @pinia/nuxt@0.5.1, @nuxtjs/color-mode@3.4.2, @nuxt/eslint@0.3.13, arco-design-nuxt-module@0.1.0, @nuxt/content@2.13.2, @nuxt/image@1.7.0, @censujiang/vite-plugin-version-mark/nuxt@0.0.13, nuxt-schema-org@3.3.9, @nuxt/scripts@0.6.4, @nuxtjs/device@3.1.1, @nuxtjs/robots@4.0.2, @nuxtjs/sitemap@5.3.5, @vueuse/motion/nuxt@2.2.3
- Build Modules:    -
------------------------------
```

### Reproduction

[https://stackblitz.com/edit/github-3pgxeg?file=app.vue](https://stackblitz.com/edit/github-3pgxeg?file=app.vue)

### Describe the bug

As the title says, please open the link I provided to minimize the problem.
When visiting /about, the title is the one set in app.vue. Please click the text on this page to navigate to the / page (this page is supported by content). The page title is the one set in the corresponding file, but the page title will not change when navigating to /about again.
Summary: After browsing the content-related page, browsing other pages will not change to the corresponding title

**Comment by unitythemaker** [comment]
I am also having the same issue. The useHead works in layouts but not in app.vue. Also this also applies to titleTemplate, or anything such as meta, link, htmlAttrs etc., simply useHead isn't working at all in app.vue.
Has anyone been able to fix this? Or are we not supposed to call useHead from app.vue?
