### ISSUE TITLE
Typecheck fail: Property 'useNuxtImage' does not exist on type

### ISSUE THREAD

**Issue by insub** [nuxt/content#2737]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.1.0
- Builder:          -
- User Config:      modules, debug, devtools, future, routeRules, vue, imports, content, shadcn, css, colorMode, app, pwa, features, eslint, compatibilityDate
- Runtime Modules:  @vueuse/nuxt@10.9.0, @unocss/nuxt@0.61.5, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxtjs/color-mode@3.4.1, @vite-pwa/nuxt@0.7.0, @nuxt/eslint@0.3.12, ./modules/shadcn, @nuxt/content@2.13.2
- Build Modules:    -
------------------------------

### Reproduction

"@nuxt/content": "2.13.2"

### Describe the bug

When I perform `pnpm typecheck` (`vue-tsc --noEmit`), the following error occurs:

```
node_modules/.pnpm/@nuxtjs+mdc@0.8.3_magicast@0.3.4_rollup@4.18.0/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue:15:52 - error TS2339: Property 'useNuxtImage' does not exist on type '{ components: { prose: boolean; map: { p: string; a: string; blockquote: string; "code-inline": string; code: string; em: string; h1: string; h2: string; h3: string; h4: string; h5: string; h6: string; hr: string; ... 10 more ...; tr: string; }; }; headings: { ...; }; }'.

15 const imgComponent = useRuntimeConfig().public.mdc.useNuxtImage ? resolveComponent('NuxtImg') : 'img'
```

However, I have not used @nuxt/image, and there is no image component in the code. My tsconfig.json is as follows:
```
{
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "skipLibCheck": true
  },
  "exclude": ["node_modules"]
}
```

And I have tried both TypeScript versions 5.4.5 and 5.5.2, but the error still occurs. How should I fix it?

**Comment by haashemi** [comment]
Hi. I've had the same issue. Installing [Nuxt Image](https://image.nuxt.com/get-started/installation) fixed it for me.
