### ISSUE TITLE
The MDC files are available during development but not after the build process

### ISSUE THREAD

**Issue by 0x77dev** [nuxt/content#2753]
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v20.14.0`
- Nuxt Version:     `3.12.4`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `bun@1.1.20`
- Builder:          `-`
- User Config:      `experimental`, `runtimeConfig`, `appConfig`, `devtools`, `routeRules`, `nitro`, `extends`, `modules`, `ui`, `image`, `vite`, `future`, `pwa`, `content`, `wellKnown`, `build`, `app`, `compatibilityDate`
- Runtime Modules:  `@nuxt/content@^2.13.2`, `@nuxt/ui@^2.17.0`, `@zadigetvoltaire/nuxt-well-known@^0.0.13`, `nuxt-time@^0.1.3`, `@formkit/auto-animate/nuxt@^0.8.2`, `@nuxt/image@1.7.0`, `@vite-pwa/nuxt@0.9.1`, `@nuxt/eslint@^0.5.0`
- Build Modules:    `-`
```

### Reproduction

Just place `.mdc` files in the content folder and try to build. Then, send a `GET` request to `http://localhost:3000/api/_content/query`. The list does not contain the Markdown (`.mdc`) content, while in development it does. However, the `.md` files work in both development and build environments.

### Describe the bug

The MDC (`.mdc`) files are available during development, but they are not included after the build process. However, the Markdown (`.md`) files are working as intended.

**Comment by james-astalty** [comment]
We're also noticing this.
