### ISSUE TITLE
Unable to unset option `content.markdown.anchorLinks.exclude`

### ISSUE THREAD

**Issue by JakeIsMeh** [nuxt/content#2764]
### Environment

(stackblitz)
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.0
- CLI Version:      3.13.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules, routeRules, content
- Runtime Modules:  @nuxt/content@2.13.2
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-sgrg2e

### Describe the bug

By default, H1s are excluded from anchor link generation. However, attempting to unset the `content.markdown.anchorLinks.exclude` array in `nuxt.config.ts` does not work.

### Additional context

I've narrowed it down to Nuxt merging the default array with the config array (see below) thus far but am unsure if this behavior is an intentional configuration and so I'm filing this bug down here instead of upstream.

![Screenshot 2024-08-23 200748](https://github.com/user-attachments/assets/a4a35d0f-5723-4b7d-b373-b7a23069ee3d)

**Comment by nobkd** [comment]
If you want all headings to have links, you can set anchorLinks to true

**Comment by tulindulin** [comment]
Still not fixed in 2025 👎
