### ISSUE TITLE
When running nuxt generate, if there is a dot (".") in the path of a content file, the gives 404 

### ISSUE THREAD

**Issue by pmcp** [nuxt/content#2765]
### Environment

- Operating System: Darwin
- Node Version:     v20.14.0
- Nuxt Version:     3.13.0
- CLI Version:      3.13.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@8.15.5
- Builder:          -
- User Config:      devtools, modules, routeRules, compatibilityDate
- Runtime Modules:  @nuxt/content@2.13.2
- Build Modules:    -

### Reproduction

You can find a test repo here: https://github.com/pmcp/nuxtContentPathIssue

If a page is added to the content folder that has a dot, it will not be generated when running nuxt generate.

### Describe the bug

_I don't know if this by design, but I couldn't find any info about this. If I overlooked, I apologise!_

I came across the issue that when I generate pages, they won't generate. After some test I've found out that the reason was dots in the path of the pages.

In the test repo I have a file with and without a dot. You can see when generating that only the file without dot gets generated.

### Additional context

I use DecapCMS, with content in different languages. The i18n setup of Decap uses dots in the paths of the files to distinguish between languages ([https://decapcms.org/docs/i18n/](https://decapcms.org/docs/i18n/)).

**Comment by pmcp** [comment]
I just found another issue mentioning the same error: https://github.com/nuxt/content/issues/2368

**Comment by farnabaz** [comment]
This is related to Nitro's pre-render logic which does not crawl routes with unknown extension. (Having do in file name is like having a dot in a route, and characters after dot will taken as file extension)

What you can do it to manually add those routes into `routeRules` in `nuxt.config.ts`. In your case:

```ts
export default defineNuxtConfig({
  routeRules: {
    '/about.something': { prerender: true },
  }
})
```
