### ISSUE TITLE
How to render excerpt without lost bindings from frontmatter?

### ISSUE THREAD

**Issue by 7iomka** [nuxt/content#2768]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.18.2
- Nuxt Version:     3.13.0
- CLI Version:      3.13.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@4.4.1
- Builder:          -
- User Config:      srcDir, compatibilityDate, devtools, modules, routeRules, tailwindcss, shadcn, components, typescript, vue, postcss
- Runtime Modules:  shadcn-nuxt@0.10.4, @nuxtjs/tailwindcss@6.12.1, @nuxt/image@1.8.0, @nuxt/eslint@0.5.4, @nuxt/content@2.13.2
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-yzzmyf?file=pages%2Findex.vue,content%2Fprojects%2Fproj1.md

### Describe the bug

If we try to use `ContentRendererMarkdown` for some field of `ContentDoc` with type of `ParsedContent` or it partial, we see that data-bindings from frontmatter is broken, and all variables becomes strings values, and we see warnings for this in console as well.
So, how to render the parts of data with `ContentRendererMarkdown` without this behavior? Or this is expected?

**Comment by farnabaz** [comment]
Just pass `data` prop to markdown renderer.

In your case, pass `doc` as data:

```vue
<ContentRendererMarkdown v-if="doc.excerpt" :value="doc.excerpt" :data="doc"/>
```

**Comment by 7iomka** [comment]
> Just pass `data` prop to markdown renderer.
> 
> In your case, pass `doc` as data:
> 
> ```
> <ContentRendererMarkdown v-if="doc.excerpt" :value="doc.excerpt" :data="doc"/>
> ```

Wow - thanks!
From the docs this is very unclear, because I don't fount any example like that.

**Comment by farnabaz** [comment]
Indeed it is not clear in docs. Feel free to drop a PR to update docs if you want to :)
