### ISSUE TITLE
WebSocket connection to 'wss://xxxx/api/chat/1' failed:

### ISSUE THREAD

**Issue by uubyte** [nuxt/content#2769]
### Environment

"nuxt": "3.13.0"

### Reproduction

WebSocket connection to 'wss://xxxx/api/chat/1' failed:

### Describe the bug

本地是可以的，为什么打包到服务器报错WebSocket connection to 'wss://xxxx/api/chat/1' failed:

### Logs

```Shell
WebSocket connection to 'wss://xxxx/api/chat/1' failed:
```

**Comment by farnabaz** [comment]
I don't see any relation between content module and this websocket connection. Maybe you should open an issue in Nuxt's main repo.

And make sure to provide a good reproduction example for better understanding of your issue. You can use https://nuxt.new/ to create a reproduction

**Comment by Aravinda93** [comment]
@farnabaz Even I am seeing the same issue in my Nuxt content website even though I am using latest Nuxt content and Nuxt npm versions.
<img width="795" alt="Screenshot 2024-09-12 at 23 14 06" src="https://github.com/user-attachments/assets/1c14e945-377c-4415-9c06-c6f9edf44560">
