### ISSUE TITLE
Hooks not working

### ISSUE THREAD

**Issue by nightlyworker** [nuxt/content#2798]
### Environment

- Operating System: Linux
- Node Version:     v20.11.1
- Nuxt Version:     3.13.1
- CLI Version:      3.13.1
- Nitro Version:    2.9.7

### Reproduction

  export default defineNitroPlugin((nitroApp) => {
    nitroApp.hooks.hook('content:file:beforeParse', (file) => {
        console.log('content:file:beforeParse')
    });
  
    nitroApp.hooks.hook('content:file:afterParse', (file) => {
        console.log('content:file:afterParse')
    });
    console.log('Nitro plugin initialized');
  });
  

### Describe the bug

Hooks are not working. 

console.log('content:file:afterParse') is never printed.
console.log('content:file:afterParse') is never printed.

console.log('Nitro plugin initialized'); is printed

As per guide here:
https://content.nuxt.com/recipes/hooks

Can you please provide some guidance, how to works with nuxt content hooks ?
Thank you

EDIT: Forgot the magic word -> Please 🙏

**Comment by AloisSeckar** [comment]
@nightlyworker did you solved the issue? I am having the same problem - logs inside those hooks never print out for me...

**Comment by AloisSeckar** [comment]
Does that mean all markdown files are processed by Nuxt Content only once when Nitro starts and then they are statically served?

**Comment by AloisSeckar** [comment]
This is my plugin:

```
// server/plugins/content.ts
export default defineNitroPlugin((nitroApp) => {
  console.log('init plugin')
  nitroApp.hooks.hook('content:file:beforeParse', (file) => {
    console.log('before parse')
    if (file._id.endsWith('.md')) {
      file.body = preventSingleLetterOrphans(file.body)
    }
  })
})
```

`before parse` is never logged, not even when whole Nitro server starts up...
