### ISSUE TITLE
<ContentList> How do I sort render in chronological order?

### ISSUE THREAD

**Issue by sooooooooooooooooootheby** [nuxt/content#2826]
I didn't find any instructions on sorting in the document, and I'm curious as to how he sorted it. Even for a newly created article, it can be randomly placed anywhere rather than being fixed at the beginning or end, and it feels like it's being rendered according to some strange rule.

![Image](https://github.com/user-attachments/assets/c87ed858-9d38-4cae-8a92-7d088a7c045a)

My articles are sorted by time using the `---` identifier, but I can't find any relevant instructions on how to sort them by time.

![Image](https://github.com/user-attachments/assets/baab0768-2731-426f-907d-9df93c1b21b9)

**Comment by farnabaz** [comment]
You can use `queryContent().sort()`. Checkout [Docs](https://content.nuxt.com/composables/query-content#sortoptions)

**Comment by sooooooooooooooooootheby** [comment]
> You can use `queryContent().sort()`. Checkout [Docs](https://content.nuxt.com/composables/query-content#sortoptions)

thank you
