### ISSUE TITLE
Combining Nuxt Content and openAPI: true gives rollup errors, breaks build

### ISSUE THREAD

**Issue by pmcp** [nuxt/content#2839]
### Environment

- Operating System: Darwin
- Node Version:     v20.14.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.3
- Package Manager:  pnpm@9.9.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/eslint@0.6.1, @nuxt/content@2.13.4, @nuxt/image@1.8.1, @nuxtjs/tailwindcss@6.12.2
- Build Modules:    -

### Reproduction

Starting with https://github.com/nuxt-hub/starter and adding nuxt content.

### Describe the bug

When I add 

```
  nitro: {
    experimental: {
      // Enable Server API documentation within NuxtHub
      openAPI: true
    }
  },
```

to nuxt.config, it gives me the error

```
RollupError: virtual:#nitro-internal-virtual/server-handlers-meta (32:7): Identifier "_vtEFC3Meta" has already been declared

30: import _P2WQbkMeta from "/Users/pmcp/Documents/GitHub/kdm/node_modules/.pnpm/@nuxthub+core@0.8.6_ioredis@5.4.1_magica...
31: import _vtEFC3Meta from "/Users/pmcp/Documents/GitHub/kdm/node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magic...
32: import _vtEFC3Meta from "/Users/pmcp/Documents/GitHub/kdm/node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magic...
           ^
33: import _vtEFC3Meta from "/Users/pmcp/Documents/GitHub/kdm/node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magic...
34: import _qfWoImMeta from "/Users/pmcp/Documents/GitHub/kdm/node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magic...

```

This experimental feature is included in the nuxthub starter, it seems to only break if **nuxt content** is added.

Combining Nuxt Content and openAPI: true seems to be the issue (for me).

**Comment by papiitodev** [comment]
I have same issue when Combining Nuxt content and openAPI ..
`RollupError: virtual:#nitro-internal-virtual/server-handlers-meta (15:7): Identifier "_jaiXzxMeta" has already been declared`

**Comment by farnabaz** [comment]
Thanks for the issue. This is related to Nitro and should be handled there. Nuxt Content uses the same file to register three different routes in Nitro; thus, Nitro creates three different imports with that same hash.
//cc @pi0 

However, we can avoid this by creating different files for the query API in the module.

**Comment by pi0** [comment]
@farnabaz Can you please create an upstream issue? 🙏🏼
