### ISSUE TITLE
[v3] Github repository source is copied in .data but not present in database

### ISSUE THREAD

**Issue by arkhaiel** [nuxt/content#2841]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.20.4`
- Nuxt Version:     `3.14.159`
- CLI Version:      `3.15.0`
- Nitro Version:    `2.10.4`
- Package Manager:  `pnpm@9.12.3`
- Builder:          `-`
- User Config:      `default`
- Runtime Modules:  `@nuxt/content@3.0.0-alpha.6`, `@nuxt/eslint@0.6.1`
- Build Modules:    `-`

### Version

3.0.0-alpha.6

### Reproduction

```ts
export const collections = {
  content: defineCollection({
    type: 'page',
    source: '**/*.md',
  }),
  test: defineCollection({
    type: 'page',
    source: {
      repository: 'https://github.com/arkhaiel/nsi-md',
      path: '/',
    },
  }),
}
```

### Description

The `.data/content` folder contains the content of the github repo I provided, but the sqlite database doesn't. The database contains the MD file I put in the local `content` directory.
I don't know if it's a normal behaviour since it's an alpha module or if it's a bug, but here's my report !

Fresh empty nuxt3 project + @nuxt/content@next module, nothing more.

![Image](https://github.com/user-attachments/assets/486b8e25-8b36-459e-afed-fa997dba62f1)

### Logs

```shell-script

```

**Comment by farnabaz** [comment]
The path in the source is a glob pattern which matches the content files.
If your repository contains markdown in root directory, you can try using:

```
test: defineCollection({
    type: 'page',
    source: {
      repository: 'https://github.com/arkhaiel/nsi-md',
      path: '**',
    },
  }),
```

As you already faced it, `path` is a misleading name for pattern, that's why we renamed it to `include`. The rename will release in next version

**Comment by arkhaiel** [comment]
Oh, thanks ! I got it, I was indeed unsure about what to put in the path key 🤓

**Comment by farnabaz** [comment]
Alpha.7 is released,  you can rename `source.path` into `source.include`.
