### ISSUE TITLE
ContentRenderer Class Attribute

### ISSUE THREAD

**Issue by llayz46** [nuxt/content#2850]
### Environment

- Operating System: Windows_NT
- Node Version:     v22.11.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/content@3.0.0-alpha.6, @nuxtjs/tailwindcss@6.12.2, @nuxtjs/google-fonts@3.2.0
- Build Modules:    -

### Version

v3.0.0-alpha.6

### Reproduction

<ContentRenderer :value="article" tag="article" class="content max-w-3xl mx-auto mt-12" />

### Description

When we pass some classes to ContentRenderer, in the web the "class" attribute is transforming to "clas". So the classes are not working

### Logs

```shell-script

```

**Comment by llayz46** [comment]
Line 212 of ContentRenderer : 

<template>
  <MDCRenderer
    :key="key"
    :body="body"
    :data="data"
    **:clas="props.class"**
    :tag="props.tag"
    :prose="props.prose"
    :unwrap="props.unwrap"
    :components="componentsMap"
    :data-content-id="debug ? value._id : undefined"
  />
</template>

**Comment by farnabaz** [comment]
Thanks for the issue,
Fixed in https://github.com/nuxt/content/commit/e81703523c487aacd9fe2d69a18e1c9a87dd18da
