### ISSUE TITLE
Inconsistent placement of custom fields form the .md files

### ISSUE THREAD

**Issue by iBobik** [nuxt/content#2856]
### Environment

- Operating System: Darwin
- Node Version:     v22.10.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.9.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/content@3.0.0-alpha.6, @nuxt/fonts@0.10.2, @nuxt/image@1.8.1, @nuxt/ui@2.19.2, @vueuse/nuxt@11.2.0, @nuxtjs/i18n@9.1.0
- Build Modules:    -

### Version

3.0.0-alpha.6

### Reproduction

https://codesandbox.io/p/devbox/brave-bogdan-8myc2y?workspaceId=11463712-f2b6-4ff2-abfc-9afdf4b3cb02

### Description

When I place custom field in the front matter:
```
---
title: Example article
image: /images/products/test.jpeg
---
```
define schema for it (like [recommanded in the docs](https://content3.nuxt.dev/docs/files/markdown#define-a-collection)):
```
  products: defineCollection({
    type: 'page',
    source: 'products/*.md',
    schema: z.object({
      image: z.string(),
    }),
  }),
```

Typing tells me the field is on the object root:

![Image](https://github.com/user-attachments/assets/6d7daffd-3d07-4ae9-a0b9-ad2cd2b99bcd)

But it actually is accesible in the meta subobject:

> meta.image: /images/products/test.jpeg
> image:

Even if typing does not expect it there:

![Image](https://github.com/user-attachments/assets/b4299347-4be4-4fbf-a8a4-055e8d0cbdf0)

**Comment by farnabaz** [comment]
This is related to cached data in `.data/content` directory. The next version will respect collection changes and will clear cache automatically.

But for now in alpha.6 you can remove `.data/content` directory in your project and restart Nuxt to  force a re-index.
This will solve the issue.

**Comment by iBobik** [comment]
Hi, thank you, removal of the .data/content directory helped.
