### ISSUE TITLE
Full support for JSON file with body

### ISSUE THREAD

**Issue by mayashavin** [nuxt/content#286]
### Is your feature request related to a problem? Please describe.
Some CMS such as NetlifyCMS allows user to write in markdown and export these content as a JSON file with `body` property which contains the actual content to your local repo directory, for example:
```json
{
  "title": " Hello World",
  "body": "## Hello World\nThis is a blog",
  "description": "Blah blah",
}
```
If I use Nuxt-content to fetch this file, according to documentation, the `body` property is removed from the document object, hence it is impossible to render using `nuxt-content` component with it.

### Describe the solution you'd like
`body` should present in the document object received after `$content.fetch()` resolves. If there is none, a `body` property should be created. If there is an existing one, it should preserve the original `body` property value.

**Comment by mathe42** [comment]
I think using your JSON example should just work... Where did you read that body is removed?

**Comment by pmelnichuk** [comment]
@mathe42, can confirm it doesn't parse body markdown from json. Just ran into the same issue.

**Comment by benjamincanac** [comment]
@mayashavin I've just added an example on how to achieve this behaviour on the documentation, let me know if this works for you.

https://content.nuxtjs.org/advanced#contentfilebeforeinsert (the 2nd example)
