### ISSUE TITLE
`queryCollectionItemSurroundings` should support `.where()` and `.order()`

### ISSUE THREAD

**Issue by L33Z22L11** [nuxt/content#2864]
### Problem

I'm currently developing my blog and need to retrieve surrounding posts based on their dates instead of filenames.

### Probably solution

Use `queryCollection().surroundings()` to find surrounding articles with options.

**Comment by farnabaz** [comment]
Released in [v3.0.0-alpha.8](https://github.com/nuxt/content/releases/tag/v3.0.0-alpha.8).
