### ISSUE TITLE
MDC: ProseCodeInline being parsed as ProseCode

### ISSUE THREAD

**Issue by JessicaSachs** [nuxt/content#2885]
### Environment

- Operating System: `Darwin`
- Node Version:     `v22.9.0`
- Nuxt Version:     `3.13.2`
- CLI Version:      `3.14.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.1.1`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Version

v3.0.0-alpha.7

### Reproduction

sqlite doesn't work so this won't run, but the code works.
https://stackblitz.com/edit/github-c2mjun-enapdv?file=content%2Findex.md

Screenshot of workaround/using `:prose-code-inline` which _does_ work.

**Rendered Site**
![Image](https://github.com/user-attachments/assets/ea4dfc59-77bf-42b3-9e09-8a1a2c290f48)

**MDC**
![Image](https://github.com/user-attachments/assets/7fff7424-3ef9-4262-9848-d01e125c020c)

### Description

MDC parser issue. Inline code blocks are broken and rendering as multiline code blocks. When using shorthand MDC component syntax, the component is correctly mapped.

### Logs

```shell-script

```

**Comment by farnabaz** [comment]
The `prose-inline-code` is not available in v3. 
There is two prose components:
- `ProseCode`: inline codes within the paragraph
- `ProsePre`: block/multi-line codes

I wasn't able to run your reproduction, I'd update it and it seems to work fine with codes. Checkout https://github.com/farnabaz/content-v3-prose-code

**Comment by JessicaSachs** [comment]
Oh! I see. That's perfectly fine. Let me try.

**Comment by JessicaSachs** [comment]
I took a shot at the docs. Feel free to close if it's not helpful
