### ISSUE TITLE
Unable to animate webp in markdown

### ISSUE THREAD

**Issue by cadamsdev** [nuxt/content#2899]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.18.1`
- Nuxt Version:     `3.13.2`
- CLI Version:      `3.14.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.14.2`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. Create a nuxt + nuxt content project
2. Install nuxt-image `npx nuxi@latest module add image`
3. In markdown add an image to an animated webp file.
```
![animated image](/images/animated.webp)
```
3. Run the dev server go to the page notice the webp image is not being animated.

### Describe the bug

When we reference an animated webp in markdown using nuxt content it doesn't animate.
```
![animated image](/images/animated.webp)
```

Under the hood it uses NuxtImg but it doesn't set the `animated: true` modifier.

e.g When using NuxtImg directly we would do this.
```
<NuxtImg src="images/animated.webp" :modifiers="{ animated: true }" />
```

Here's an example animated webp image
[animated.webp.zip](https://github.com/user-attachments/files/18063054/animated.webp.zip)

### Workaround

Create component "AnimatedImage.vue" in "components/content/AnimatedImage.vue"
```vue
<template>
  <NuxtImg :src="src" :modifiers="{ animated: true }" :alt="alt" />
</template>

<script setup lang="ts">
defineProps<{
  src: string
  alt: string
}>()
</script>
```

In the markdown use it like this
```
:animated-image{src="/images/animated.webp" alt="Some text"}
```

**Comment by farnabaz** [comment]
You can pass attributes to your image directly in markdown.

```md
![animated image](/images/animated.webp){:modifiers='{ "animated": true }'}
```

this will pass modifiers to `NuxtImg`.

Checkout docs to read more about attributes syntax: https://content.nuxt.com/usage/markdown#attributes

**Comment by cadamsdev** [comment]
> You can pass attributes to your image directly in markdown.
> 
> ![animated image](/images/animated.webp){:modifiers='{ "animated": true }'}
> this will pass modifiers to `NuxtImg`.
> 
> Checkout docs to read more about attributes syntax: https://content.nuxt.com/usage/markdown#attributes

Oh perfect, that works. Thanks! I didn't realize you can pass an object like that. I'll close this ticket.
