### ISSUE TITLE
Fetching content from multi sources

### ISSUE THREAD

**Issue by adhamfarrag** [nuxt/content#290]
Hi! I'm trying to fetch content from multi sources

```js
async asyncData({ $content, params }) {
    const team = await $content('teamOne/people', 'teamTwo/people')
      .sortBy('slug')
      .fetch()

    return { team }
  },

```

And it didn't work.. if there isn't any other way to fetch content from same sources, can you add it ? Thank you.

**Comment by georgwittberger** [comment]
I suppose this would clash with the current API contract of the `$content` function. The function can take multiple arguments which then form a path in the content directory. In your example the function would attempt to load the content files from `$content_dir/teamOne/people/teamTwo/people`. See https://content.nuxtjs.org/fetching#contentpath-options

Support for your use case may be possible by adding another property to the `options` object which can be passed as last argument to the `$content` function.

Meanwhile, as a workaround you should simply call the `$content` function two times to query the two collections separately, then combine the two results to one array and sort it using a custom compare function which compares the `slug` property.

**Comment by adhamfarrag** [comment]
Thanks for this idea, I had to separate content. :)
I still hope you can add it to a next version.
