### ISSUE TITLE
Add `language-text` Class to Maintain Compatibility with VuePress Code Blocks

### ISSUE THREAD

**Issue by odanado** [nuxt/content#2906]
### Is your feature request related to a problem? Please describe
I am migrating the Vuepress documentation to Nuxt.js and Nuxt Content.

In the process, I found differences regarding class generation for code blocks.

VuePress and Nuxt Content generate different class names for the following code blocks.
![Image](https://github.com/user-attachments/assets/5ad8fd1f-6c5f-436e-9f3e-fff227e43498)

|| VuePress | Nuxt Content |
|-|-|-|
|Image|![Image](https://github.com/user-attachments/assets/48bc58c2-b00a-48ee-a18b-37164858af41)|![Image](https://github.com/user-attachments/assets/c98511af-dafe-43fa-aa83-e76948e4a7f9)|
|Description| Has `language-` and `language-text` classes | Has not `language-` and `language-text` classes |
|Implement|https://github.com/vuejs/vuepress/blob/9fb4bb00925d9409e6732118e996411c6a82c85d/packages/%40vuepress/markdown/lib/preWrapper.js#L16|https://github.com/syntax-tree/mdast-util-to-hast/blob/f511a93817b131fb73419bf7d24d73a5b8b0f0c2/lib/handlers/code.js#L26-L28|

repo: https://github.com/odan-sandbox/vuepress-nuxt-content-code-block-compare

I use `language-*` as a selector to write styles in my project. If the differences between VuePress and the current system are small, migration will be smooth.

### Describe the solution you'd like

We have implemented a new `rehype` plugin that adds `language-text` to the class if node.lang is null.

### Describe alternatives you've considered

We will update ProsePre.vue to add the `language-text` class when no language is specified.
https://github.com/nuxt-modules/mdc/blob/main/src/runtime/components/prose/ProsePre.vue

### Additional context

Nothing.

**Comment by farnabaz** [comment]
Thanks for the explanation,
It makes sense to add `language-text` to code blocks without any language.

You can try the changes in https://pkg.pr.new/@nuxt/content@6371a19
