### ISSUE TITLE
Custom component rendering issue

### ISSUE THREAD

**Issue by naiheyoung** [nuxt/content#2909]
> When I use a custom component, the content outside the component will be swallowed or regarded as the content of the default slot

```md
<CodePanel>
    <template #win>wincode</template>
    <template #mac>maccode</template>
</CodePanel>

## code (this content will not be rendered)
```

> But when I write it in one line, the content outside the component renders fine, but the slot doesn't work again

```md
<CodePanel><template #win>wincode</template><template #mac>maccode</template></CodePanel>
(Slot content is not rendered)
```

> I tried the `::` syntax and it renders fine but there is a small problem.
> By default, it will wrap the slot content with a layer of `p` tag

```md
::CodePanel
#win
wincode
#mac
maccode
::
```

![Image](https://github.com/user-attachments/assets/bcdd5b81-c914-440b-8574-2ec6bf835615)

> When I wrap the slot content with a block tag, the `p` tag is replaced

```md
::CodePanel
#win
<div>wincode</div>
#mac
<div>maccode</div>
::
```

![Image](https://github.com/user-attachments/assets/2119e9de-48d0-43ba-ab77-f246b9c40d92)

> I tested it and found that all inline tags will be wrapped with a layer of `p` tag

```md
::CodePanel
#win
<strong>wincode</strong>
#mac
<strong>maccode</strong>
::
```

![Image](https://github.com/user-attachments/assets/52087ef2-cc97-447e-8fe8-0510db66a334)

## Needs

> When using components, do not swallow the content outside the component

> When using the `::` syntax, the slot content should not be wrapped in a `p` tag

Please tell me how to do it❓

**Comment by farnabaz** [comment]
Wrapping inline element into `<p>` is the default behavior of all markdown parsers.

But Module provides two different way to remove this paragraph:

1. Using `<slot mdc-unwrap="p" />`: If you have access to modify component source, you can add `mdc-unwrap="p"` to your slots and module will remove the wrapping paragraph

```vue
<template>
  <div>
    <slot mdc-unwrap="p" />
  </div>
</template>
```

2. Use `{unwrap="p"}` in slot definition in markdown: If you don't have access to modify the component of you don't want to unwrap paragraph every time you use the component you can define unwrap in markdown
```md
::CodePanel
#win{unwrap="p"}
<strong>wincode</strong>
#mac{unwrap="p"}
<strong>maccode</strong>
::
```

**Comment by farnabaz** [comment]
Note that these syntaxes are available in Content v3.

If you are using Content V2, you consider using `<MDCSlot unwrap="p" />` in you component to render slots and unwrap the paragraph

**Comment by naiheyoung** [comment]
OK. Thank you.
