### ISSUE TITLE
documentDriven prerender - crawler not working if link has query parameters

### ISSUE THREAD

**Issue by gitFoxCode** [nuxt/content#2910]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.12.2
- Nuxt Version:     3.13.0
- CLI Version:      3.13.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@3.7.0
- Builder:          -
- User Config:      app, modules, algolia, content, fonts, colorMode, tailwindcss, site, schemaOrg, nitro, runtimeConfig, sourcemap, experimental, compatibilityDate
- Runtime Modules:  @nuxt/content@2.13.2, @nuxt/image@1.7.0, @nuxt/ui@2.18.4, @nuxt/fonts@0.6.1, nuxt-og-image@3.0.0-rc.65, @nuxtjs/algolia@1.10.2, nuxt-schema-org@2.2.0
- Build Modules:    -
------------------------------

### Reproduction

1. `npx nuxi@latest init content-app -t content`
2. Remove `/pages` and set `documentDriven` to true
3. Create something like `content/test/tester.md`
4. Link it in index.md:
```markdown
Look at the [Content documentation](https://content.nuxtjs.org/) to learn more. [TEST](/test/tester?tab=yex)
```
5. `npm run generate`
6. `npm run preview`
7. Go to `/`
8. Click TEST link
9. Everything is working
10. Refresh
11. `Document not found`

### Describe the bug

During `nuxt generate`, with `prerender: { routes: [ "/"] }` the Nuxt crawler works by scanning the homepage and prerendering every page it finds through links. However, if we have a link like `<a href="/test?tab=xyz">xyz</a>`, it is not prerendered as a separate test/index.html.

### Logs

```Shell

```

**Comment by farnabaz** [comment]
This is not related to content module, it is the behaviour of Nuxt Crawler. Routes with query params will not be written on the disk.

Feel free to open an issue in upstream repo and seek for possible solutions
