### ISSUE TITLE
[V3] ContentSlot does not display expected content 

### ISSUE THREAD

**Issue by narr07** [nuxt/content#2914]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.18.0
- Nuxt Version:     3.14.0
- CLI Version:      3.15.0
- Nitro Version:    2.10.2
- Package Manager:  pnpm@9.12.3
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxthub/core@0.8.5, @nuxt/content@3.0.0-alpha.8, @nuxthq/studio@2.2.1, @nuxt/eslint@0.6.1, @nuxt/ui@2.20.0, @nuxt/fonts@0.10.3
- Build Modules:    -
------------------------------

### Reproduction

[https://github.com/narr07/teja2web](https://github.com/narr07/teja2web)

### Describe the bug

I am experiencing an issue with the use of ContentSlot in Nuxt Content v3 like example. When using `<ContentSlot name="title" />` and `<ContentSlot name="description" />`, the content does not display as expected. However, when using regular slots (`<slot name="title" />`) or like this  
```
<ContentSlot name="description">
 <template #default>
   Description fallback content
 </template>
</ContentSlot>
``` 
the content displays correctly.

### Additional context

I have tried providing fallback content within ContentSlot, but it still does not appear.
The version of Nuxt Content I am using is v3.0.0.
The code used to implement ContentSlot is as follows:

```
<template>
  <h3 class="font-semibold">
    <ContentSlot name="title" />
  </h3>
  <span>
    <ContentSlot name="description" />
  </span>
</template>
```

### Logs

```Shell

```

**Comment by farnabaz** [comment]
`ContentSlot` is removed in Content v3 and you can simply use Vue's native `<slot />`

```vue
<template>
  <h3 class="font-semibold">
    <slot name="title" />
  </h3>
  <span>
    <slot name="description" />
  </span>
</template>
```
