### ISSUE TITLE
Add option for Content Collections to access raw file content

### ISSUE THREAD

**Issue by maximepvrt** [nuxt/content#2921]
## Description
In the current alpha version of `@nuxt/content` v3, it seems that hooks have been removed, and accessing the raw content of files has become impossible without them (which, to be fair, didn’t work properly in v2 either). For certain use cases, it is crucial to retrieve the raw file content before parsing it with `parseMarkdown()` or other custom transformations.

This feature has been a recurring request in the community, as evidenced by issues like #2803 and #2490. Adding a direct method or option to retrieve the raw file content would enhance the flexibility of the module and cater to advanced use cases.

## Use Case
In my specific case, I need to process the raw file content in my page before parsing it with `parseMarkdown()`.

**Comment by oneminch** [comment]
According to #2925, these hooks are now available in `v3`. They are available in build time (instead of runtime using server plugins as in `v2`). Here is the documentation: https://content3.nuxt.dev/docs/advanced/hooks. @maximepvrt

**Comment by maximepvrt** [comment]
Thank you for the update and the link to the documentation! It's great to see the return of hooks in v3 🎉.

However, I’ve noticed that these hooks don’t work with Nuxt Studio, even if the project is not configured as a static build. The issue seems to be that the Content API is replaced by Studio's API, which prevents hooks from functioning properly.

This is precisely why I’m suggesting the addition of a raw option in the Content Collections API. Having this option would provide a straightforward way to access raw file content, regardless of the environment (Studio or not), and would address scenarios where hooks are not a viable solution.

**Comment by oneminch** [comment]
That's similar to what I’m suggesting in #2803.

**Comment by farnabaz** [comment]
In version 3 you can define `rawbody` field in the collection's schema to store raw content in the database. checkout https://content3.nuxt.dev/docs/advanced/raw-content
The integration with the studio for `rawbody` is still in progress.

**Comment by oneminch** [comment]
Does that mean raw content can also be accessed from an `afterParse` hook if the field is defined in the collection schema?

**Comment by farnabaz** [comment]
Yes, the module will fill `rawbody` before calling the hook.

**Comment by maximepvrt** [comment]
So cool ! Thanks @farnabaz @larbish 💚
