### ISSUE TITLE
[V3] - queryCollection cannot find content when using srcDir

### ISSUE THREAD

**Issue by rutbergphilip** [nuxt/content#2932]
### Environment

- Operating System: `Darwin`
- Node Version:     `v22.11.0`
- Nuxt Version:     `3.15.0`
- CLI Version:      `3.17.2`
- Nitro Version:    `2.10.4`
- Package Manager:  `npm@10.9.0`
- Builder:          `-`
- User Config:      `default`
- Runtime Modules:  `@nuxt/content@3.0.0-alpha.8`
- Build Modules:    `-`

### Reproduction

https://github.com/rutbergphilip/nuxt-content-v3

### Describe the bug

Using content v3 along with srcDir, queryCollection cannot find and retrieve any content.

## Code
<img width="445" alt="Image" src="https://github.com/user-attachments/assets/d696d22e-d50e-432e-8cde-d4371e39db33" />

## With srcDir
<img width="1511" alt="Image" src="https://github.com/user-attachments/assets/6a8ae783-d30c-4c1c-9b18-8f6748b80603" />

## Without srcDir
<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/01912061-7a6e-487d-9d7d-471c21396746" />

### Logs

```Shell

```

**Comment by farnabaz** [comment]
Content module looks for `rootDir` to find the `content` directory. You can either define `rootDir` in `nuxt.config` or move `content` directory out of `src` directory.

**Comment by productdevbook** [comment]
Cannot find name 'queryCollection'.ts-plugin(2304)


with `  future: { compatibilityVersion: 4 },` I seem to have a similar problem. For some strange reason, no imports are coming in.

**Comment by farnabaz** [comment]
Do you ming updating your repository?

**Comment by productdevbook** [comment]
I actually updated and this console.log is not printing. All the other modules work but the content module won't start the scan.

![Image](https://github.com/user-attachments/assets/8b45e2a8-41dc-42f7-8b61-b9db91d4de55)

**Comment by farnabaz** [comment]
I guess you didn't push the commit, can't see your commit in the repo https://github.com/rutbergphilip/nuxt-content-v3

**Comment by rutbergphilip** [comment]
> I guess you didn't push the commit, can't see your commit in the repo https://github.com/rutbergphilip/nuxt-content-v3

I think he's working on a standalone repo, I will push changes to mine regarding the path when I get home in about 20 min.

**Comment by rutbergphilip** [comment]
> I guess you didn't push the commit, can't see your commit in the repo https://github.com/rutbergphilip/nuxt-content-v3

Pushed with srcDir and content moved to root. Thank you for elaborating on how it works. 😄
https://github.com/rutbergphilip/nuxt-content-v3

**Comment by productdevbook** [comment]
yes I was trying privately, I sent a [pr](https://github.com/nuxt/content/pull/2934) that solved the problem. It is not related to this issue, just in a similar installation, the module was not working for me.
