### ISSUE TITLE
Page files with special characters (Å,Ä,Ö) results in 404

### ISSUE THREAD

**Issue by Adamkillander96** [nuxt/content#298]
### Version
@nuxt/content: 1.5.0
nuxt: 2.14.0

### Reproduction Link
https://codesandbox.io/s/nuxtcontent-demo-qlh6z?file=/content/index.md

### Steps to reproduce

1. Have a file named with Å, Ä or Ö in the content folder. These are Swedish letters, but this issue is present for all Scandinavian characters. 
2. Navigate to the page with a special character in it.  
3. 404 :( 

### What is Expected?
Nuxt Content should fetch and display the file 'frågor'.

### What is actually happening?
It tries to fetch 'fr%25C3%25A5gor' which results in a 404.

#### Other 
I noticed this issue on my production site were it can't prefetch pages with those characters, but it can display them. When I created the reproduction link, it wont even display the page with special characters, just a 404 error.

**Comment by renoirb** [comment]
Are you running on a Mac or Linux, or on Windows?

On Linux/macOS it might work, but your issue boils down to one of the oldest IETF http design decision about (unicode in an URL (link to similar StackOverflow quesrion)](https://stackoverflow.com/q/2742852)

**Comment by Adamkillander96** [comment]
I am on Windows. So this is may not really be a Nuxt or Nuxt Content issue, more of a systems issue.
That's good, thanks for taking your time and answering! :)
