### ISSUE TITLE
Wysiwyg (rich editor) when editing mode?

### ISSUE THREAD

**Issue by ctwhome** [nuxt/content#303]
Hi! it looks like the next most obvious step right? a WYSIWYG editor when editing the articles? is that an idea that is in your minds already??

Something like https://quilljs.com/ or https://ui.toast.com/tui-editor/?

thanks for the hard work!

**Comment by mathe42** [comment]
Maybe we can add a option go define an editor component. Should be quite easy. If @benjamincanac think this is worth adding I would work in this.

**Comment by ctwhome** [comment]
I think it will bring even a bigger feeling like a headless CMS / simple to use alternative.

**Comment by mathe42** [comment]
@ctwhome just created #308 :D (is still WIP...)

**Comment by ctwhome** [comment]
This is going to be huuuuge 👆🍷
