### ISSUE TITLE
Images in static folder not loaded in production

### ISSUE THREAD

**Issue by Abdulqudus001** [nuxt/content#307]
I have a `logo.svg` file in my `static/img` folder and is loaded in my header component. But whenever I visit a page that has `nuxt-content`, the `img` folder does not get loaded.

This only happens in production. I deployed the site using netlify

**Comment by Atinux** [comment]
@Abdulqudus001 Please provide a CodeSandBox or a repository with a reproduction and re-open the issue so we can take a look at it ☺️
