### ISSUE TITLE
value.split is not a function

### ISSUE THREAD

**Issue by AncaIO** [nuxt/content#315]
Since I could not re-open issue #20... 

This error appears when frontmatter includes yaml lists:

```
---
tags: ['a', 'b']
---
```
or 
```
---
tags: 
    - a
    - b
---
```
I encountered the issue at `nuxt dev` if adding 'tags' to `content.fullTextSearchFields` option.

As a workaround, one can use `tags: a, b`, but then having to split the string. 

_Originally posted by @AncaIO in https://github.com/nuxt/content/issues/20#issuecomment-667232238_

**Comment by benjamincanac** [comment]
@AncaIO We're depending on [LokiDB](https://github.com/LokiJS-Forge/LokiDB#readme) and its [full-text-search plugin](https://www.npmjs.com/package/@lokidb/full-text-search) which doesn't support this.

Check out #178 for a workaround.

**Comment by benjamincanac** [comment]
Duplicate #20
