### ISSUE TITLE
nuxt generate or nuxt export? (documentation issue)

### ISSUE THREAD

**Issue by AncaIO** [nuxt/content#316]
The current documentation [here](https://content.nuxtjs.org/advanced#static-site-generation) writes:

> Since Nuxt 2.13+, nuxt export has a crawler feature integrated which will crawl all your links and generate your routes based on those links. Therefore you do not need to do anything in order for your dynamic routes to be crawled.

> When using nuxt generate, you need to specify the dynamic routes with generate.routes, because Nuxt does not know what these routes will be so it can't generate them.

while in the blog post about the [latest nuxt release (2.14)](https://nuxtjs.org/blog/nuxt-static-improvements#back-to-old-school-commands) they say they deprecate `nuxt export` in favor of `nuxt generate`. 

**Which one should we use if we want the "crawler" feature?** 

I suspect `nuxt generate` does that, since when running `nuxt generate` it tried to build for a wrongly configured route and threw an error, but it would be nice to have a definitive answer and updated documentation. 

To the makers of this friggin' awesome module: thanks a million, I am beyond ecstatic with the functionality so far.

**Comment by benjamincanac** [comment]
@AncaIO Thanks for reporting this, it was indeed for Nuxt 2.13. I will update the documentation asap.

With Nuxt 2.14 you should use `nuxt generate` 👍

**Comment by benjamincanac** [comment]
The documentation has been updated: https://content.nuxtjs.org/advanced#static-site-generation.
