### ISSUE TITLE
Docs: border layout issue for TOC on larger screens?

### ISSUE THREAD

**Issue by arjanski** [nuxt/content#317]
Hello content team,

First of all, thank you for this magnificent module, it's such a pleasure to use!

I noticed a small layout issue (?) in the docs, not sure this is deliberate or not? On full HD screens or bigger, the gray border of the fixed TOC area does not fill the whole screen vertically:

![Bildschirmfoto 2020-07-31 um 20 24 39](https://user-images.githubusercontent.com/13831998/89066179-4f169f00-d36d-11ea-8595-8fff3b3729be.png)

### Version
Not applicable, as this issue is directed towards the Nuxt Content docs.

### Reproduction Link
Any view on https://content.nuxtjs.org/ with the TOC enabled on the left-hand side.

### Steps to reproduce
-

### What is Expected?
I would expect the vertical gray border area which separates the TOC from the main content area to be either a) sized at 100% height, or b) to be invisible. Currently the gray border area has the height of the TOC `<aside>` element. On > full HD screens, there's a gap (even though the TOC itself is fixed).

If this was not a design decision and a) is desirable, I would suggest to erase the `lg:h-auto` class from the child element of `<aside>`:

`<div class="lg:sticky lg:top-0 lg:pt-16 lg:-mt-16 overflow-y-scroll h-full">`

### What is actually happening?
-

**Comment by benjamincanac** [comment]
@arjanski Thanks for reporting this, it's now fixed and should be released soon!
