### ISSUE TITLE
Configurable container for markdown

### ISSUE THREAD

**Issue by razbakov** [nuxt/content#32]
### Is your feature request related to a problem? Please describe.

I would like to include components into markdown content and let them keep their styles, for example:

```markdown
# What to do next?

<v-btn to="/signup">Sign up</v-btn>

Or you can also:
- read articles
- listen podcasts
```

The common approach to style markdown content is to put it in some container like `.typo` , `.typography` or `.markdown` and style it like this:

```css
.typo h1 { font-size: 2rem; }
.typo a { color: blue; }
```

I use TailwindCSS for components and even if I have `v-btn` with `text-white` it will be blue in output.

It would be great to add to wrap markdown content into some container with some specific class and make it configurable.

### Describe the solution you'd like

```js
export default {
  content: {
    markdown: {
      container: 'typo' // default ''
    }
  }
}
```

### Describe alternatives you've considered

Right now I am using frontmatter with `notypo: true` which disables my default `typo` class in wrapper.

Another option is to use scoped css or `!important` in components

**Comment by benjamincanac** [comment]
Hey @razbakov,

When using `<nuxt-content>` component to display the markdown body, the html is wrapped around a `.nuxt-content` class. Codeblocks are also wrapped around a `.nuxt-content-highlight` class.

If you want an example on how to style the markdown, you can take a look at the module documentation: https://github.com/nuxt/content/blob/master/docs/pages/_slug.vue#L65

**Comment by razbakov** [comment]
@benjamincanac it won't solve my problem with blue button. Will it?

**Comment by Atinux** [comment]
Hi @razbakov 

I think that you should use scoped css in your vue components or use the  `>` selector in your css:

```css
.nuxt-content > h1 {
  /* only style markdown h1 */
}
```

**Comment by razbakov** [comment]
@Atinux do you think my suggestion is overkill?

**Comment by Atinux** [comment]
I think what you want to do can be made with a remark plugin :)
