### ISSUE TITLE
[@nuxt/content-theme-docs] Custom Router

### ISSUE THREAD

**Issue by AGDholo** [nuxt/content#320]
Can I load the document separately in the secondary route?
Like this:

- /home : There is my components page
- /docs : There is my docs page

**Comment by Atinux** [comment]
Hi @AGDholo 

Can you be more specific? You want to have the theme on /docs and have handle other routes with pages/ ?

**Comment by AGDholo** [comment]
@Atinux 
Like https://nuxtjs.org/ ,
My main page may not be docs,
Even I can create multiple documents

https://nuxtjs.org/
https://nuxtjs.org/guide
https://nuxtjs.org/api
https://nuxtjs.org/resources

**Comment by Atinux** [comment]
In that case I recommend to directly use your own implementation instead of the theme

**Comment by AGDholo** [comment]
@Atinux 
Thank you very much for your answer

Is there a similar separation plan in the future? If this component overrides the global behavior by default, most functions of nuxt are not available.

**Comment by benjamincanac** [comment]
@AGDholo Unfortunately for now it will stay like that. The goal of this theme is to create a full documentation website without code by just writing markdown files. If you need a more complex app, feel free to use the code of the theme to create your own implementation.
