### ISSUE TITLE
[@nuxt/content-theme-docs].  Markdown Table

### ISSUE THREAD

**Issue by nathanhenniges** [nuxt/content#325]
### Version
"@nuxt/content-theme-docs": "^0.1.3",
"nuxt": "^2.14.0"

### Reproduction Link

https://codesandbox.io/s/nuxtcontent-demo-g7qkn

Dark Mode
![image](https://user-images.githubusercontent.com/19924836/89106348-cccebf00-d3ee-11ea-919d-72dc415e675d.png)
Light Mode
![image](https://user-images.githubusercontent.com/19924836/89106363-dc4e0800-d3ee-11ea-8944-75717184c9e5.png)

### Steps to reproduce
Create a markdown table

### What is Expected?
Header on the table (when in dark mode) to be readable.  

### What is actually happening?
When dark mode is enabled the header of the table is unreadable unless you highlight it.

**Comment by benjamincanac** [comment]
Hey @nathanhenniges, this should now be fixed in `@nuxt/content-theme-docs` v0.2.0
