### ISSUE TITLE
[@nuxt/content-theme-docs] Global components dir in theme-docs

### ISSUE THREAD

**Issue by jerosoler** [nuxt/content#326]
Is possible autoload global components in the theme-docs.

Folder: components/global/Hello.vue

Only load the components from theme.

**Comment by Atinux** [comment]
Nice catch, we will add this improvement on the next release!

**Comment by jerosoler** [comment]
Great! Thanks!! 🎉

**Comment by jerosoler** [comment]
Hello @Atinux 

It would also be interesting to be able to override the component.

For example: 
components/global/app/AppLangSwitcher.vue

Override the packages/theme-docs/src/components/global/app/AppLangSwitcher.vue

It could be possible?

**Comment by benjamincanac** [comment]
@jerosoler Could you detail your use-case on overriding components? For example the `AppLangSwitcher.vue` component automatically adapts depending on the locales you set, do you want to override the design?

**Comment by jerosoler** [comment]
@benjamincanac Yes, for change design. 
For example in lanswitcher add the flag icon. 

Or add extras to the footer for example (rrss).
Other example add small description to logo.

For no duplicate all package.

**Comment by benjamincanac** [comment]
The `@nuxt/content-theme-docs` package has been released in `v0.3.0`, you should be able to use your own components now! 

About overriding components, this is something we have to think about. Would you mind opening another issue for this?

**Comment by jerosoler** [comment]
Thanks! ;) 

New issue #328
