### ISSUE TITLE
[@nuxt/content-theme-docs] Override default components

### ISSUE THREAD

**Issue by jerosoler** [nuxt/content#328]
Hello
 
It would also be interesting to be able to override the component.

For example:
components/global/app/AppLangSwitcher.vue

Override the packages/theme-docs/src/components/global/app/AppLangSwitcher.vue

Example use:

For example in lanswitcher add the flag icon.

Or add extras to the footer for example (rrss).
Other example add small description to logo.

For no duplicate all package.

It could be possible?

**Comment by jerosoler** [comment]
Comment in #326

**Comment by abarkhurst** [comment]
Is this enhancement been implemented? I cannot find any way to override the default AppFooter component.

**Comment by danpastori** [comment]
I've been trying to figure this out as well and I don't think it's possible as of right now. I did have a couple thoughts on how this would be possible and willing to explore them more to help work with the team to put together a PR. 

## Config Override for Components
If there was a way to map which components are overwritten through the NuxtJS config I think this would be extremely convenient. What I'm envisioning is if you could eject a specific component, make your changes, and then define in the `nuxt.config.js`. When the theme is compiled, it'd include the changes made.

Some sort of config like:

```
{
...
overrides: {
header: '/custom/global/CustomHeader.vue'
}
...
}
```
## Ability to Eject Template and Customize Changes
With VuePress you can eject the default template and make the changes necessary. There is a warning when doing this that it won't be supported any longer, and for most cases that's fine. If there was a way we could do this with the default theme, that'd be wonderful.

These are just a few things I was thinking about, obviously very top level over view. If there are any open PRs or if any of these sound like a way to explore more, I'd be willing to contribute in any way. I love Nuxt Content and the default theme is gorgeous. Just a few enhancements would be amazing 😇

**Comment by jaydrogers** [comment]
Allowing theme customizations would be a huge help.

I wonder if @benjamincanac can chime in with any thoughts?

What is the best way to move forward on this? Is this something that could get a PR created so there is "official support"? Or is it best to just create our theme?

Obviously our goal would be to stay aligned with the official theme because it's incredible and we wouldn't have to maintain a whole theme for a few changes.

I know this is a new project and there is a lot in motion right now, but having any sort of direction on this would be a great help. 🙌

**Comment by benjamincanac** [comment]
Just created a PR to handle this. Let me know what you think ☺️

**Comment by danpastori** [comment]
This is absolutely amazing!! I can't wait to give this a try!

The only question I have is if in the documentation we could link to what was already designed for the components that can be overwritten? For example, I speak from our use-case and I know others may be different, but we need to adjust the right side bar by adding social shares. The default design is gorgeous, and we want to use 99% of it. This would just make it easy to "eject" a component and use it in our own theme.

If this is something you find useful, would it help if I contribute the links in the docs? I'll append it to your PR.

**Comment by benjamincanac** [comment]
@danpastori I just updated the documentation on how it's going to work and added the links of each component to GitHub.

**Comment by danpastori** [comment]
So cool, this explains a ton! Thank you so much for your hard work, we will keep an eye on the PR and implement it right away 👍

**Comment by benjamincanac** [comment]
The previously linked PR was merged but to fulfill another purpose. Still waiting on the next release of `@nuxt/components` to handle components override.

**Comment by philschmid** [comment]
@benjamincanac any update on this?

**Comment by jaydrogers** [comment]
Just in case you missed it, there is a major theme change coming soon: https://github.com/nuxt/content/issues/726

Probably will be easier us to modify our own theme now 🤞

**Comment by ArsalaBangash** [comment]
I'm also looking for an update or solution to this. Linked to #774

**Comment by przemekhernik** [comment]
Hi guys! Does someone have an update here?
