### ISSUE TITLE
nuxt generate doesn't export content

### ISSUE THREAD

**Issue by osadasami** [nuxt/content#338]
### Version
@nuxt/content: ^1.5.0
nuxt: ^2.14.0

### Steps to reproduce

Inside `pages` folder I create file `_.vue` to handle all `nuxt/content` markdown files in `content` folder. That's the only page I have in that folder

```
pages
└── _.vue
```

```js
// pages/_.vue
<template>
  <div>
    <nuxt-content :document="doc"></nuxt-content>
  </div>
</template>

<script>
export default {
  async asyncData({ $content, params }) {
    const doc = await $content(params.pathMatch).fetch()

    return { doc }
  }
}
</script>
```

In `content` folder I have these pages

```
content
├── calcs
│   └── days.md
├── hello.md
└── index.md
```

In development mode I can navigate to root path `/` and `content/index.md` is opened. I can easly navigate through all pages in `content` folder

### What is Expected?

I expect that `nuxt generate` will export `content/*` pages to static pages but got nothing

```
dist
├── 200.html
├── README.md
├── _nuxt
├── favicon.ico
├── icon.png
├── sw.js
├── v.png
└── vuetify-logo.svg
```

### What is actually happening?

Doesn't export pages in `content` folder

**Comment by benjamincanac** [comment]
Hey @osadasami, with Nuxt 2.14 there is a crawler when running `nuxt generate`, however if there are pages that cannot be found you might need to specify the `generate.routes` property: https://nuxtjs.org/api/configuration-generate#routes.

You can also check the [@nuxt/content documentation](https://content.nuxtjs.org/advanced#static-site-generation) about this.

**Comment by osadasami** [comment]
@benjamincanac Thank you! I got it worked. Now all pages from `content` folder is exported properly

In `nuxt.config.js`, after `modules: [...]` key write that code

```js
generate: {
  async routes() {
    const { $content } = require('@nuxt/content')
    const files = await $content('/', { deep: true }).only(['path']).fetch()

    return files.map(file => file.path === '/index' ? '/' : file.path)
  }
},
```

**Comment by surgiie** [comment]
I get the following error:

```
ERROR  $content is not a function                                                                           19:09:52

  at routes (nuxt.config.js:15:27)
  at node_modules/defu/dist/defu.js:70:16
  at _defu (node_modules/defu/dist/defu.js:29:19)
  at _defu (node_modules/defu/dist/defu.js:36:18)
  at node_modules/defu/dist/defu.js:53:14
  at Array.reduce (<anonymous>)
  at Function.arrayFn (node_modules/defu/dist/defu.js:52:17)
  at _default (node_modules/@nuxt/content-theme-docs/src/index.js:180:32)
  at nuxt.config.js:2:31
  at g (node_modules/jiti/dist/jiti.js:1:55111)


```

When attempting this solution.
