### ISSUE TITLE
Folder name

### ISSUE THREAD

**Issue by borisdamevin** [nuxt/content#34]
Why `content` instead of `contents` in plural like other folders in NuxtJS main structure?

**Comment by nimonian** [comment]
Nuxt's usage of the word _content_ is certainly

> Content _noun_ information made available by a website or other electronic medium

and not either of

> Contents _noun (pl)_ the things that are held or included in something
> Contents _noun_ a list of the chapters or sections given at the front of a book or periodical

Used in this way, `content` is a partitive noun and should not be pluralised, and is no less consistent with Nuxt's folder naming structure than `middleware`, another partitive noun. Pluralising partitive nouns is a common mistake with certain words in English, as in "this paper will use the following _notations_"; it should be _notation_.

**Comment by borisdamevin** [comment]
Thank you for explanation! :)
