### ISSUE TITLE
How to retrieve all documents in a hook ?

### ISSUE THREAD

**Issue by brumartins** [nuxt/content#340]
Hi everyone 😃 

### Question
I read [from the docs](https://content.nuxtjs.org/advanced#contentfilebeforeinsert) that we can use hooks to perform some actions on the documents before they are inserted. The `content:file:beforeInsert` hook allows you to modify a document, but it doesn't give access to the list of documents as a whole.

Is there another hook to do so, something like `content:files:beforeInsert` (*files* with an 's') ? I'm asking because the documentation says *the module adds some hooks* but only one is described. And in the `nuxt.config.js` file, there is no access to the `$content()` method, right?

I could use a library like [front-matter](https://www.npmjs.com/package/front-matter) to manually retrieve all the documents along with their metadata, but maybe there is a more elegant solution.

### Why I'm asking
I'm building a multi-language (French and English) blog with a headless CMS and I'm struggling against slug translations. I can ask a blogger to add the English slug when writing a French article, so that the link exists between the two languages. But I don't want him to repeat this actions the other way around, ie, adding the French slug to the English article. This is the reason why I wanted to add the missing translated slugs to the document metadata, via hooks.

I hope I was clear enough, feel free to ask for more information if needed!

Thanks 😄

**Comment by Atinux** [comment]
Hi @brumartins 

This is a difficult decision since by adding files the database won't be the same as the file system.

I suggest to directly support this logic in your application, if the path does not exist, try in the other language and display an alert stating that this article/page is not yet translated.

**Comment by brumartins** [comment]
Thank you @Atinux for your answer 👍 
I'll keep my workaround then. Have a good day 🙂
