### ISSUE TITLE
@nuxt/content 404 error in production with dynamic route

### ISSUE THREAD

**Issue by giticon** [nuxt/content#346]
@nuxt/content: 1.5.3
nuxt: 2.14

here

[(https://nuxtjs.org/api/configuration-generate#routes)](https://nuxtjs.org/api/configuration-generate#routes)

```
generate: {
    routes: ['/users/1', '/users/2', '/users/3']
}
```

but if we have a dynamic page ( ex. _slug ) to load single posts with 

```[_slug]
async asyncData({ $content, params }) {
    const article = await $content('articles', params.slug).fetch();
        return {
	    article
	}
    }
}
```

we get an error

`GET http://www.site.net/_nuxt/static/1596555038/blog/title_post/payload.js`

because in production mode Nuxt can't create dynamic routes from a list of markdown-posts.

How to fix this problem? Is there a way to get a dynamic route with generate command (in production)?

In dev mode all is ok

**Comment by benjamincanac** [comment]
Hey @giticon, you can check the documentation on [static site generation](https://content.nuxtjs.org/advanced#static-site-generation) to learn how to configure your `generate.routes` using `@nuxt/content`.

**Comment by giticon** [comment]
tnx @benjamincanac 

error was here

```
generate: {
    async routes () {
      const { $content } = require('@nuxt/content')
      const dynamicRoutes = await $content('articles').only(['slug']).fetch()
      return dynamicRoutes.map(myroute => myroute.slug === '/index' ? '/' : '/blog/' + myroute.slug)
    },
  },
```

because my /content/dir was "articles" whereas my route was "blog/_slug"

On return i changed "path" with 

`'/blog/' + myroute.slug`

**Comment by basicBrogrammer** [comment]
Does this still need to be done with the nuxt web crawler?
