### ISSUE TITLE
[@nuxt/content-theme-docs] Add page for tags

### ISSUE THREAD

**Issue by ricardogobbosouza** [nuxt/content#357]
Load tags from github, similar to releases

https://api.github.com/repos/:owner/:repo/tags

**Comment by pi0** [comment]
It would be also nice if `CHANGELOG.md` ([example](https://github.com/nuxt-community/proxy-module/blob/master/CHANGELOG.md)) is automatically read for release notes and versions. Many packages don't need to setup github release integration or would be inside a mono-repo where repo..changelog is not 1 to 1.

**Comment by farnabaz** [comment]
Hey there 👋

@nuxt/content-theme-docs is moving away and will not get any updates, very soon we will open-source Docus, a brand new theme based on Nuxt 3, and Content v2 with lots of fixes, improvements, and new features.

I’m closing this issue in favor of the new docs theme. Keep an eye on #726 for updates

I will add this to the enhancements list for Docus.
