### ISSUE TITLE
When a compoenent is added inside a md file, the rest of the md content is not displayed.

### ISSUE THREAD

**Issue by ctwhome** [nuxt/content#360]
### Version
@nuxt/content: v1.5.3
nuxt: v2.14.1

### Codesandbox 
https://codesandbox.io/s/focused-lovelace-butwp?file=/content/index.md

The problem is that after adding a component from the components/global folder, stops rendering the rest of the document

Not showing the rest of the document:
![image](https://user-images.githubusercontent.com/4195550/89532578-49e4a480-d7f2-11ea-9b1c-52dc6cfa65c0.png)

Now yes, when the component is out
![image](https://user-images.githubusercontent.com/4195550/89532667-74366200-d7f2-11ea-905c-ce834b4c2148.png)

**Comment by ctwhome** [comment]
Forgot to not use self-closing tags.

**Comment by drewda** [comment]
Just happened to me, too. Turns out in my case I did have a closing tag, but it had a typo and didn't match the component name in the opening tag :)

**Comment by mohamberger** [comment]
I just had the same problem. I wrote the component in Markdown in PascalCase. With kebab-case it works fine.
