### ISSUE TITLE
[@nuxt/content-theme-docs] Third-party components not working in docs theme. Am I missing a step?

### ISSUE THREAD

**Issue by jmalley** [nuxt/content#363]
Issue: When using the docs theme, third-party components aren't registered.

**My setup:**

- Fresh nuxt/content project with docs theme
- Followed [this guide](https://nuxtjs.org/blog/improve-your-developer-experience-with-nuxt-components) on how to use a third party component library, with npm linked local sample project. Components set to true in config, and third party library referenced in buildModules, as per the guide.
- EDIT: [Repo](https://github.com/jmalley/nuxt-docs-test)

"dependencies": {
    "@nuxt/content-theme-docs": "^0.3.0",
    "nuxt": "^2.14.0"
  }

**Error message:**

[Vue warn]: Unknown custom element: <kru-counter> - did you register the component correctly?

I'm able to use local components, just not the third-party ones. Shouldn't it work? Is there a missing piece or am I misunderstanding how the docs theme works?

**Comment by benjamincanac** [comment]
Hey @jmalley, could you provide a reproduction of your project? What third party library are you using? Does this library takes advantage of the `@nuxt/components` hook?

```js
this.nuxt.hook('components:dirs', dirs => {
  // Add ./components dir to the list
  dirs.push({
    path: join(__dirname, 'components')
  })
})
```

**Comment by jmalley** [comment]
Hi @benjamincanac, I've added the repo [here](https://github.com/jmalley/nuxt-docs-test).

I'm using [the Kru-components sample library](https://github.com/Krutie/Kru-Components) from the guide, cloned and unmodified. It does have that components hook.

**Comment by adrianschubek** [comment]
@jmalley Are you on Windows? 

I had a similar issue #343 with global components. They didn't work in a **@nuxt/content-theme-docs** project even though hooks are set. 

In a regular @nuxt/content project everything worked.

**Comment by jmalley** [comment]
@adrianschubek Yep, WSL. Can you confirm you didn't have this issue on WSL2?

**Comment by adrianschubek** [comment]
My global components work on WSL2 (Ubuntu) without any issues 👍 .

**Comment by jmalley** [comment]
I don't think this is a duplicate of #343, because I am able to use local global components in my docs project, just not third party ones via npm link. It might be related though.

**Comment by cogor** [comment]
I have same issue on Windows, but on vercel my global component working fine 😥

**Comment by jmalley** [comment]
@benjamincanac - I figured out a work-around for my issue. In .nuxt > components > plugin.js I added the following, and the third-party component works:

`KruCounter: () => import('../../../Kru-Components/src/components/Counter.vue' /* webpackChunkName: "components/global/base/Counter" */).then(c => c.default || c),`

It would be great if in content-theme-docs, there was a standardized way of activating third-party components so they are available globally... is there a more elegant way to add to the globalComponents constant array?
