### ISSUE TITLE
[@nuxt/content-theme-docs] read CHANGELOG.md

### ISSUE THREAD

**Issue by ricardogobbosouza** [nuxt/content#367]
https://github.com/nuxt/content/issues/357#issuecomment-670471004

**Comment by farnabaz** [comment]
Hey there 👋

@nuxt/content-theme-docs is moving away and will not get any updates, very soon we will open-source Docus, a brand new theme based on Nuxt 3, and Content v2 with lots of fixes, improvements, and new features.

I’m closing this issue in favor of the new docs theme. Keep an eye on  #726 for updates

I will add this to the enhancements list for Docus.
