### ISSUE TITLE
[@nuxt/content-theme-docs] move color mode switcher to app header

### ISSUE THREAD

**Issue by adrianschubek** [nuxt/content#369]
It's hard for users to switch between dark/light mode as they need to scroll to the bottom. 
Especially on longer pages, a new visitor might not even notice that a dark mode is available.
The mobile version already has this feature in nav dropdown.

A solution would be to move color mode switcher to app header and/or maybe an option in `settings.json` to toggle this behavior.

**Comment by Atinux** [comment]
I suggest instead to support the system color scheme by default as well as an actions box.
Once you set the color mode, it is useless to keep it in the header honestly

**Comment by k16e-me** [comment]
Isn't it possible to move it anywhere you want? For example, in the default page, when the theme is installed, there's command for it. Thing is, how do you edit the theme's header/footer to your liking?

**Comment by Atinux** [comment]
We plan to support overwriting components soon, see https://github.com/nuxt/content/pull/542

**Comment by benjamincanac** [comment]
The previously linked PR was merged but to fulfill another purpose. Still waiting on the next release of `@nuxt/components` to handle components override.

**Comment by farnabaz** [comment]
`@nuxt/content-theme-docs` is moving away and will not get any updates, very soon we will open-source Docus, a brand new theme based on Nuxt 3 and Content v2 with lots of improvements and new features. 


Closing this issue in favor of the new docs theme. Keep an eye on #726 for updates
