### ISSUE TITLE
Cannot remove default plugins

### ISSUE THREAD

**Issue by sambrezo** [nuxt/content#377]
### Version
@nuxt/content: v1.4.0, v1.6.0

### Steps to reproduce
```
export default {
  content: {
    markdown: {
      remarkPlugins: (plugins) => {
        const denyList = ['remark-autolink-headings']
        return plugins.filter((plugin) => !denyList.includes(plugin))
      },
    },
  },
}
```

### What is Expected?
`remark-autolink-headings` is not loaded

### What is actually happening?
`mergeConfig` works as intended, but the default plugins get concated to the filtered list by `nuxt-contrib/defu` as [documented](https://github.com/nuxt-contrib/defu#remarks).

**Comment by benjamincanac** [comment]
@sambrezo A new `v1.7.0` release has been published which now uses `defu.arrayFn`, this should fix your issue.

Feel free to reopen if it's still there after upgrading.

**Comment by romain130492** [comment]
I believe header should not by default be anchor link!

**Comment by alexanderhorner** [comment]
Yea, or at least give us an easy option to disable it. Or at the *very least*, mention it in the documentation.
