### ISSUE TITLE
Code block file and line numbers not being formatted

### ISSUE THREAD

**Issue by davydnorris** [nuxt/content#383]
### Version
@nuxt/content: 1.6.0
nuxt: 2.14.1

### Reproduction Link
https://codesandbox.io/s/agitated-chaum-i8yvg?file=/content/index.md

### Steps to reproduce
See example - using file name and line numbers as shown in the documentation

### What is Expected?
Output as per the documentation

### What is actually happening?
Filename is being shown outside the block
Line numbers not being highlighted

**Comment by benjamincanac** [comment]
@davydnorris Indeed for the filename, it's up to you to style it, check the css we use in the theme docs: https://github.com/nuxt/content/blob/dev/packages/theme-docs/src/assets/css/main.css#L56.

About the line numbers, it's a bit more complex as you might need to use prismjs on client-side, check out #28.

**Comment by davydnorris** [comment]
Thanks for this! Could we possibly improve the documentation around this capability, as I spent ages trying to work out why mine wasn't displaying like it does in the documentation on the feature - I assumed you would automatically get what what was shown :-)
