### ISSUE TITLE
Can Nuxt/Content have proper pagination built in?

### ISSUE THREAD

**Issue by k16e-me** [nuxt/content#384]
While developing my first website with Nuxt/Content module, I realized the blog page, as is customary, will need proper pagination. In such a case, the number of posts to be displayed on each page can be limited to a certain number on `fetch()` with same number of posts spread across multiple pages according as there are posts.

My question is can't Nuxt/Content have such proper pagination built in? In the docs, [I see you can fetch a previous/next content to any current url](https://content.nuxtjs.org/snippets#pagination) from a list of related url collection, which works on a "single" page. However, nothing is spoken or written about pagination on a main archive.

Before asking, I did search and come across [this resource](https://github.com/nuxt/content/issues/293). But, it'd be nice if it was built-in and the code to make it happen simpler, just as simple as how "footnotes" are currently handled. 

Having proper pagination for all collection archives hits me as an urgent need/enhancement to Nuxt/Content. Could this be looked into soon enough? 

Thanks.

**Comment by benjamincanac** [comment]
@k16e-me Are `limit` and `skip` methods not enough for what you're trying to achieve? https://content.nuxtjs.org/fetching#limitn
