### ISSUE TITLE
generate sitemap.xml 

### ISSUE THREAD

**Issue by odanado** [nuxt/content#386]
### Is your feature request related to a problem? Please describe.
`@nuxtjs/sitemap` can generate a sitemap dynamically by specifying the `routes` option.
But `@nuxt/content` doesn't support sitemap generation.

### Describe the solution you'd like
Update `sitemapOptions` on the occurrence of the `sitemap:generate:before` event.
https://github.com/nuxt-community/sitemap-module#hooks

Here's a sample code.
https://github.com/odanado/blog/blob/8ca87f3dc63477d870f09b24b115cd25f3cd8996/app/modules/sitemap.ts

**Comment by odanado** [comment]
If https://github.com/nuxt-community/sitemap-module/issues/143 is resolved, this issue will also be resolved.
Therefore, there is no need to do anything.

**Comment by HannesOberreiter** [comment]
This is my current workaround to generate a sitemap, don't know if it is the best solution but it works for me.

`nuxt.config.js`

```javascript
import path from 'path';
import glob from 'glob';
....
sitemap: {
    hostname: URL,
    path: 'sitemap.xml',
    routes: () => {
      const files = glob.sync(path.join(__dirname, '/dist/**/*.html'));
      const urls = files.map(function(file){
        const url = path.relative(
          path.join(
            __dirname, '/dist/'), 
            file
          ).replace('index.html', '');
          return {
            url: url,
            lastmodfile: file
          }
      })
     return urls;
    },
    i18n: true,
    cacheTime: 1000 * 60 * 60 * 2,
    trailingSlash: true,
    gzip: true
  }
```

Cheers
Hannes
