### ISSUE TITLE
Config merging broken if array

### ISSUE THREAD

**Issue by mathieutu** [nuxt/content#399]
### Version
@nuxt/content: v1.6.1
nuxt: v2.14.3 

### Steps to reproduce
Use an array as config in content.

Exemple: 
```js
content: {
    markdown: {
      remarkExternalLinks:
        content: [
            { type: 'text', value: '1st' },
			{ type: 'text', value: '2nd' }
        ],
      }
    }
  },
```

### What is Expected?
The array should be passed as it to the plugin options.

```json
{
	"name":"remark-external-links",
	"options":{
		"content": [
			{"type":"text","value":"1st"},
			{"type":"text","value":"2nd"}
		]
	}
}
```
### What is actually happening?

The array is converted to an object.
```json
{
	"name":"remark-external-links",
	"options":{
		"content":{
			"0":{"type":"text","value":"1st"},
			"1":{"type":"text","value":"2nd"}
		}
	}
}
```

Everything happens in the lib/utils.js file.
In the second iteration the array is recursively passed to the mergedConfig function, and is converted to an object by the reduce.

Thanks for your work.

**Comment by mathieutu** [comment]
For the record, you can't use a function in this case too, because of the `typeof value === 'function' && defaultValue` condition.

**Comment by benjamincanac** [comment]
@mathieutu Would you mind trying #408 to ensure it solves your problem?
