### ISSUE TITLE
How to avoid generating routes for nonexistent articles?

### ISSUE THREAD

**Issue by rodrigocvb** [nuxt/content#416]
I have the following structure:

```
content/
    articles/
        en/
            my-first-article.md
        pt/
            meu-primeiro-artigo.md
            meu-segundo-artigo.md // not every file has its correspondence in the other language
```
The problem is that the crawler (I think) is trying to generate routes such as en/meu-primeiro-artigo and pt/my-first-article. I have several _Error generating route_ when running _yarn generate_.

The blog is working fine. Does anybody know how could I avoid those errors? How to avoid the crawler to generate routes for nonexistent articles? Thanks!

**Comment by azrikahar** [comment]
Hi, would you mind providing a reproduction link on CodeSandbox? Or perhaps you can share it in a public repo (with sensitive data redacted/removed if you wish)?

From what I know, the crawler will only generate the routes if it sees `nuxt-link`s that are targeting/pointing to the non-existent articles, so we might need to find out why the nuxt-links will be created in the first place.

**Comment by brumartins** [comment]
Hi, do you use the i18n module as well ? Maybe your lang switcher isn't able to determine the right slug of the article in other languages and ends up putting the same slug.

**Comment by rodrigocvb** [comment]
Hey guys! Thanks a lot for answering my question. You both helped me to figure out what was going on. I only have 'pt-BR' posts for now, but in each post page I had a language switcher that was pointing to a non-existent route. My bad.
