### ISSUE TITLE
Generate HTML for RSS Feed content property

### ISSUE THREAD

**Issue by RobotOptimist** [nuxt/content#425]
I'm working on my RSS feed for my blog. Things are going great, but I've got a hangup.

I want to generate the content for my blog in the content property for the RSS feed, however I'm using a mix of markdown and vue components in my .md files. 

Using the existing methods I can generate the JSON AST or simply pass in the markdown content with no problems, but getting the Vue components to render as html is another hurdle. 

Sure, I could go through my blog posts and remove the Vue components but where's the fun in that?

So I've been thinking about how to do this and wondering if nuxt/content has an API or something that already does what I need and I just missed it. 

Anyway, here is the relevant piece of nuxt.config.js for reference, I've defined my create function to be reused

(btw this version is friendly with `nuxt generate` which your version in the Integrations section does not seem to be - I get an error when I use your version with `nuxt generate` but I plan to simplify this and update your docs with this alternate version)

```
const create = async (feed) => {
  feed.options = {
    title: "James MacIvor's Blog",
    description: "Technology, Business, Teaching and Mentoring",
    link: process.env.NODE_ENV === 'production' ? 'https://www.macivortech.com/feed.xml' : 'localhost:3000/feed.xml'
  }

  // eslint-disable-next-line global-require
  const { $content } = require('@nuxt/content')
  if (posts === null || posts.length === 0)
    posts = await $content('blogs').fetch()

  posts.forEach((post) => {
    const url = process.env.NODE_ENV === 'production' ? `https://www.macivortech.com/blog/${post.slug}` : `localhost:3000/blog/${post.slug}`
    feed.addItem({
      title: post.title,
      id: url,
      link: url,
      description: post.description,
      content: post.stuff
    })
  })
}

export default {
...
  modules: [
    'nuxt-svg-loader',
    '@nuxtjs/dotenv',
    '@nuxt/content',
    '@nuxtjs/feed'    
  ],

  feed: [
    {
      path: '/feed.xml',
      create,
      cacheTime: 1000 * 60 * 15,
      type: 'rss2'
    },
    {
      path: '/feed.json',
      create,
      cacheTime: 1000 * 60 * 15,
      type: 'json1'
    }
  ],

  hooks: {
    'content:file:beforeInsert': async (document) => {
      // *do magic stuff here*
      const html = doTheMagic(document)

        document.html= html;
      }
    }
  },
...
}
```

I'm definitely learning some new stuff here - but I think I can accomplish this using a workflow like this:

In the hook: 'content:file:beforeInsert':

1. Create a dummy Vue instance
2. Use your existing render function NuxtContent //or something, not sure I want to create the entire unified md to html process here, but if I have to?
3. Pass in the document
4. Use a Vue SSR process (??really uncertain about this??) to resolve the Vue Components
5. Append the resulting html to the document
6. Pull the html into the feed content property in the create function

So the question, does my goal make sense? (I don't typically mess with RSS so I'm learning as I go)
Does the challenge I'm outlining make sense?
Can you give me some guidance on my suggested plan? 

Thanks

**Comment by RobotOptimist** [comment]
Okay I figured this out and it was a lot easier than I thought it would be. 

First, the 6 steps I outlined? Way off base LOL. Wrong. 

But, it is possible - you could use the prerender steps from the Vue SSR documentation - just to break it down in case some one does have a requirement to do it this way: 

You'd need to first pull in these packages: 

* @prerenderer/prerenderer
* @prerenderer/renderer-puppeteer
* html-minifier (optional)

then you'd need to follow the steps from the [prerenderer documentation](https://www.npmjs.com/package/@prerenderer/prerenderer) and pass in the renderer-puppeteer as the renderer.

there is no particular reason to use the puppeteer renderer over jsdom except that the [prerender-spa-plugin uses puppeteer](https://github.com/chrisvfritz/prerender-spa-plugin/blob/master/package.json) and not jsdom.
html minification is optional, but I'm sure it'd be nice.

It would work (maybe) to do it that way, but it is a lot of reinventing the wheel. Why do all of that when nuxt is already doing it for me when I use `nuxt generate`?

So yes, instead of doing all of that I'm reading in the html file generated from nuxt generate. 

here's the create function:

```
const fs = require('fs').promises;
const path = require('path');

let posts = [];

const constructFeedItem = async (post, dir, hostname) => {  
  const filePath = path.join(__dirname, `dist/rss/${post.slug}/index.html`);
  const content = await fs.readFile(filePath, 'utf8');
  const url = `${hostname}/${dir}/${post.slug}`;
  return {
    title: post.title,
    id: url,
    link: url,
    description: post.description,
    content: content
  }
} 

const create = async (feed, args) => {
  const [filePath, ext] = args;
  console.log('in create func');
  const hostname = process.NODE_ENV === 'production' ? 'https://www.macivortech.com' : 'http://localhost:3000'
  feed.options = {
    title: "James MacIvor's Blog",
    description: "Technology, Business, Teaching and Mentoring",
    link: `${hostname}/feed.${ext}`
  }
  const { $content } = require('@nuxt/content')
  if (posts === null || posts.length === 0)
    posts = await $content(filePath).fetch();

  for (const post of posts) {
    const feedItem = await constructFeedItem(post, filePath, hostname);
    feed.addItem(feedItem);
  }
  return feed;
}
```

and then in your nuxt.config.js

```
modules: [
    '@nuxtjs/dotenv',
    '@nuxt/content',
    '@nuxtjs/feed'    
  ],

  feed: [
    {
      path: '/feed.xml',
      create,
      cacheTime: 1000 * 60 * 15,
      type: 'rss2',
      data: [ 'blog', 'xml' ]
    },
    {
      path: '/feed.json',
      create,
      cacheTime: 1000 * 60 * 15,
      type: 'json1',
      data: [ 'blog', 'json' ]
    }
  ],
```

so because feed generation occurs after the routes are generated, those files are there to be pulled in using plain ol' file read actions.

you can then append it to the feed, no need to modify the document object at all. 

This means that all of your vue components, any remark plugins or any of that stuff will be rendered in your content field properly as html. this works best with rss2 xml since it encodes all of that html automatically. For json you'll need to escape it.

Another thing to keep in mind is that this will render any header/footer and junk you might have from your layout page. I chose to create an alternate page for the blog that did not include any header/footer stuff in order to keep the rss content clean of any of that junk.

You can view my solution in its entirety [here](https://github.com/RobotOptimist/macivor/tree/nuxt-content).

I'll be working on a pull request for the docs section and probably a blog post too because why not.

I hope this helps someone!

**Comment by dword-design** [comment]
@RobotOptimist I just built [nuxt-content-body-html](https://github.com/dword-design/nuxt-content-body-html) for that purpose.

Usage is simple, just add it before `@nuxt/content` in your module config like so:

```js
export default {
  modules: [
    'nuxt-content-body-html',
    '@nuxt/content',
  },
}
```

Then you can access it via `doc.bodyHtml`.

It will also use the default markdown plugins from `@nuxt/content` and you can add additional ones. See the README for details and tips about RSS feed generation.
