### ISSUE TITLE
Add the option to extend default parser functionality

### ISSUE THREAD

**Issue by nielsdB97** [nuxt/content#432]
### Is your feature request related to a problem? Please describe.

I would like to extend the markdown parser to strip my `// prettier-ignore` comments. These are needed in development but I don't want my visitors to see them. I have found the [`extendParsers`](https://content.nuxtjs.org/configuration#extendparser) option but as far as I can tell it will [override](https://github.com/nuxt/content/blob/4b3417edde4faed1cc92153881e2527575d3e28e/packages/content/lib/database.js#L181) the original parser.

### Describe the solution you'd like

Instead of overriding the original parser, I would like to extend its functionality by mutating the string it will parse.

### Describe alternatives you've considered

Re-implement the default parser.

### Additional context

This is the logic I came up with for stripping prettier comments:
```typescript
function removePrettierIgnoreFromCodeBlocks(file: string) {
	const fileWithoutPrettierComments = file
		.replace(/^ \/\/ prettier-ignore\n/gm, "")
		.replace(/ \/\/ prettier-ignore\n/gm, "\n");

	return fileWithoutPrettierComments;
}
```

**Comment by mathe42** [comment]
You can overwrite the paser with something like (untestet!):

```js
const md = new require('@nuxt/content/parser').Markdown(options.markdown /* add default options combined with your own options */)

const myParser = (file) => md.toJSON(removePrettierIgnoreFromCodeBlocks(file))
```

**Comment by nielsdB97** [comment]
@mathe42 thank you so much for the quick response! Your solution works perfectly, the only downside is that I have to use internals for which there are no types available. I therefore have to stick to `require` statements rather than using `import`.

I still wonder if it would be nice to have a function-like syntax for extending the config without having to use these internals, something like this:

```javascript
function customMarkdownParser(file: string) {
	const MarkdownParser = require("@nuxt/content/parsers").Markdown;
	const { getOptions } = require("@nuxt/content/lib");

	const markdownOptions = getOptions().markdown;
	const md = new MarkdownParser(markdownOptions);

	const fileWithoutPrettierIgnore = removePrettierIgnoreFromCodeBlocks(file);
	return md.toJSON(fileWithoutPrettierIgnore);
}

export default {
	content: {
		extendParser: (defaultParser) => ({
			...defaultParser,
			".md": defaultParser.md(customMarkdownParser),
		}),
	},
}
```

For now I ended up with this config:

```typescript
function removePrettierIgnoreFromCodeBlocks(file: string) {
	return file
		.replace(/^ \/\/ prettier-ignore\n/gm, "")
		.replace(/\/\/ prettier-ignore\n/gm, "\n");
}
function customMarkdownParser(file: string) {
	const MarkdownParser = require("@nuxt/content/parsers").Markdown;
	const { getOptions } = require("@nuxt/content/lib");

	const markdownOptions = getOptions().markdown;
	const md = new MarkdownParser(markdownOptions);

	const fileWithoutPrettierIgnore = removePrettierIgnoreFromCodeBlocks(file);
	return md.toJSON(fileWithoutPrettierIgnore);
}

export default {
	content: {
		extendParser: {
			".md": customMarkdownParser,
		},
	},
}
```

**Comment by mathe42** [comment]
With your above solution something like
```js
export default {
	content: {
		extendParser: (defaultParser) => ({
			...defaultParser,
			".md": file => postCompiler(defaultParser[".md"](preCompiler(file))),
		}),
	},
}
```

should be posible... I might add that  👍
