### ISSUE TITLE
Support for i18n

### ISSUE THREAD

**Issue by uporot1k** [nuxt/content#44]
Hello, thanks for such a wonderful module. I have a question, is there any possibility to use i18n together with your module?

**Comment by juliomrqz** [comment]
If your using [nuxt-i18n](https://github.com/nuxt-community/nuxt-i18n), you can save you files in different directories based on your supported languages and fetch them like this.

```js
export default {
  async asyncData({ app, params, $content }) {
    const { slug } = params;
    const posts = await $content("blog", app.i18n.locale, slug).fetch();

    return { posts };
  },
};
```

**Comment by uporot1k** [comment]
There is my code 
`async fetch() {
    this.submenu = await this.$content('submenu', this.$i18n.locale, 'index').fetch().catch();
  },`

but when i switch page, content wouldn't update(

**Comment by Atinux** [comment]
@juliomrqz answer is the one I recommend, and also the one we use in the content documentation: https://github.com/nuxt/content/blob/master/docs/pages/_slug.vue#L31

**Comment by uporot1k** [comment]
> @juliomrqz answer is the one I recommend, and also the one we use in the content documentation: https://github.com/nuxt/content/blob/master/docs/pages/_slug.vue#L31

But what if i want use this module not on page component. I have nav which i want place in .md file and get it in fetch function.
