### ISSUE TITLE
Link to edit the page in Github is invalid

### ISSUE THREAD

**Issue by antho1404** [nuxt/content#455]
If the repository doesn't contain a `docs` directory, the link to edit the file is invalid.

https://github.com/nuxt/content/blob/36769de75b73f5826674c564424cd77f26824fb7/packages/theme-docs/src/components/app/AppGithubLink.vue#L35

The `docs` is hardcoded in the link. It might be better to have it as a setting parameter.

### Version
"@nuxt/content-theme-docs": "^0.5.6"

### Reproduction Link
https://github.com/liteflow-labs/docs

### Steps to reproduce
- Clone the repo
- npm i
- npm run dev
- Go to `localhost:3000`
- Click on "Edit this page on GitHub"

### What is Expected?
- The page open is 
https://github.com/liteflow-labs/docs/edit/master/content/en/index.md

### What is actually happening?
The page open is
https://github.com/liteflow-labs/docs/edit/master/docs/content/en/index.md
and this creates a 404

**Comment by mkalayci35** [comment]
+1

**Comment by mkalayci35** [comment]
@antho1404 https://content.nuxtjs.org/themes/docs#manual-setup

**Comment by antho1404** [comment]
@mkalayci35 I'm not sure I get the reason for this link. The manual setup doesn't change anything in the "edit this page" link or am I missing something?
The issue I'm describing is the "edit this page" link to github that is invalid if the project content is at the root and not in a `docs` directory.

**Comment by kaka-ruto** [comment]
Linked to #430
