### ISSUE TITLE
The (custom) dark theme primary color is not accessible

### ISSUE THREAD

**Issue by Larsklopstra** [nuxt/content#465]
The (custom) dark theme primary color is not accessible.

### Version

all

### Steps to reproduce

Create a Tailwind CSS color palette with the `500` tint being accessible on a white background and inaccessible on a dark background.

### What is Expected?

In the dark mode, the primary color should be `400` instead of `500` to make it more accessible.

### What is happening?

The dark mode uses `500` as the primary color which causes many color palettes to be inaccessible.

**Comment by benjamincanac** [comment]
@bdrtsky What do you think about this?

**Comment by mayashavin** [comment]
@benjamincanac anyone working on this? Got the same complaint also.

**Comment by benjamincanac** [comment]
@mayashavin Not at the moment no but I agree this should be done, if anyone wants to make a PR 🙂

**Comment by mayashavin** [comment]
@benjamincanac so you should expect a PR from me soon :)

**Comment by farnabaz** [comment]
Hey there 👋 

`@nuxt/content-theme-docs` is moving away and will not get any updates, very soon we will open-source Docus, a brand new theme based on Nuxt 3 and Content v2 with lots of fixes, improvements, and new features.

I’m closing this issue in favor of the new docs theme. Keep an eye on #726 for updates
