### ISSUE TITLE
Option to specify a list type

### ISSUE THREAD

**Issue by sausin** [nuxt/content#473]
### Is your feature request related to a problem? Please describe.
The current [list component](https://content.nuxtjs.org/themes/docs/#list) provides an easy way to display a visually appealing unordered list.

### Describe the solution you'd like
However, the default list includes green checkmarks. In scenarios where, for example, you want to show a list of things to be cautious about, it seems a bit odd to have green checks. It may be useful to consider the following options (while having similar color scheme as [alert component](https://content.nuxtjs.org/themes/docs/#alert)):
- info icon (bluish color - corresponding to info in alert component)
- warning triangle icon (yellowish color - corresponding to warning in alert component)
- cross icon (red color - corresponding to danger in alert component)

### Describe alternatives you've considered
It's obviously straightforward to build one's own component to achieve this functionality, but it seems like the logical step to have the default support a few other types.

### Additional context

If this is acceptable, I can attempt a pull request to add this enhancement.

**Comment by benjamincanac** [comment]
@sausin Indeed it would be really nice, this is something I wanted to improve but didn't find the time.

A PR would be more than welcome ✨

If you want to add more icons, we're using [tailwindlabs/heroicons](https://heroicons.com/).
