### ISSUE TITLE
Template with slot not getting rendered

### ISSUE THREAD

**Issue by alexgrozav** [nuxt/content#48]
### Version
@nuxt/content: 1.0.2
nuxt: 2.12.2

### Reproduction Link
https://codesandbox.io/s/nuxtcontent-demo-fp7i6?file=/content/index.md
### Steps to reproduce
When using the `template` tag together with named slots `<template slot="slotname">`, the content of the template does not get rendered.

### What is Expected?
The `<template slot="slotname">` should render properly.

### What is actually happening?
The `<template slot="slotname">` does not render properly. Whatever you put inside, it gets rendered as `Template Content`.

<img width="321" alt="image" src="https://user-images.githubusercontent.com/6179477/82884107-f5988b00-9f4b-11ea-8b21-649df2804e32.png">

**Comment by Atinux** [comment]
Hi @alexgrozav 

At the moment it is not supported indeed, this would have to be handled in https://github.com/nuxt/content/blob/master/lib/templates/nuxt-content.js but not sure how to implement it.

**Comment by delapuente** [comment]
After #121 you will be able to use the [new Vue.js syntax for slots](https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots) to make it work.
