### ISSUE TITLE
Add JSON array of objects support (mono-files)

### ISSUE THREAD

**Issue by monsieurnebo** [nuxt/content#480]
### Is your feature request related to a problem? Please describe.
This package is made to process data from a "**one file = one entry**" principle:

```
content/
  articles/
    article-1.json
    article-2.json
  home.json
```

While this structure makes sense for articles and/or pages where each entry contains a lot of data, this is not always the case.

Let's take for example a **huge** list of employees where each entry contains only a few keys. The management of this data is easier in a single JSON file, in the form of an object table:

```json5
// content/employees.json
[
  {
    "name"       : "Philippe Etchebest",
    "picture"    : "philippe-etchebest.jpg",
    "position"   : "Chef"
  }, {
    //...
  }
]
```

### Describe the solution you'd like
I would expect that `nuxt/content` process this array as a data source, allowing me to use queries on it. Fore instance:
```js
const employees = $content("employees").where({ position: { $ne: "Chef" } }).fetch();
```

Giving us the opportunity to use a JSON mono-file, containing an array of objects where "**one object = one entry**".

### Describe alternatives you've considered
The alternative would be:
- Use JS module import instead, and native Array methods (find, filter, ...)
- Change our data structure to fit the current `nuxt/content` philosophy

### Additional context
Related issues:
https://github.com/nuxt/content/issues/112
https://github.com/nuxt/content/issues/36

**Comment by monsieurnebo** [comment]
Thanks for the quick feature development!

@benjamincanac  Please note that the [macOS CI seems to have failed](https://github.com/nuxt/content/runs/1144101088) 🔍

**Comment by benjamincanac** [comment]
@monsieurnebo Indeed, I've reran the jobs, it's now fine! Thanks 🙂

**Comment by emilsgulbis** [comment]
Is there any reason why this doesnt work on directory? Would be useful for multi-language site that have directory structure like /en/home.json

**Comment by stronglify13** [comment]
This feature is lost in Nuxt Content 2 ??
or if could someone help me, how should I implement it?
