### ISSUE TITLE
Offset when using footnotes ?

### ISSUE THREAD

**Issue by cfabrice** [nuxt/content#481]
As I have a fixed header navigation, I need to pass an offset value so that when I click on footnote (in the bottom of the page) i end up with my footnote call under my header and not hidden behind it !
Possible ?
If yes, how ?
Thank you.

**Comment by cfabrice** [comment]
I found the solution ;-)
html {
  scroll-padding-top: 100px; /* height of sticky header */
}

**Comment by cfabrice** [comment]
If it helps anyone, I did it like this, but I'm interested in a neater css solution ! 

```
mounted() {
    const myFunction = function (e) {
      const attribute = this.getAttribute('href').replace('#', '')
      e.preventDefault()
      const destination = document.getElementById(attribute)

      const rect =
        destination.getBoundingClientRect().top +
        document.documentElement.scrollTop

      const offset = 100

      window.scrollTo({
        left: 0,
        top: rect - offset,
        behavior: 'smooth',
      })
    }

    const elements = document.querySelectorAll('[class*=footnote-]')
    for (let i = 0; i < elements.length; i++) {
      elements[i].addEventListener('click', myFunction, false)
    }
  }
```

**Comment by benjamincanac** [comment]
@cfabrice Have you tried using the `scroll-margin-top` css property on your headings?

```
h2, h3 {
scroll-margin-top: 100px;
}
```

**Comment by cfabrice** [comment]
Well... That's perfect ;-) Thank you.
