### ISSUE TITLE
Can't disable plugins

### ISSUE THREAD

**Issue by ToxicMushroom** [nuxt/content#485]
### Version
@nuxt/content: 1.9.0, 1.4.1 (tested both)
nuxt: 2.14.5

### Reproduction Link
https://github.com/ToxicMushroom/melijn-site
https://v2.melijn.com/guides/starter

### Steps to reproduce
set remarkPlugins to an empty array

### What is Expected?
no remark plugins are loaded

### What is actually happening?
defaults are still loaded

**Comment by ToxicMushroom** [comment]
I saw this issue as well and I was able to disable the plugins now, but why does setting it to an empty array have no effect?
https://github.com/nuxt/content/issues/377

**Comment by benjamincanac** [comment]
In order to override the default plugins, you have to use a function. See the override plugins section in the documentation: https://content.nuxtjs.org/configuration#markdown.
