### ISSUE TITLE
Algolia DocSearch

### ISSUE THREAD

**Issue by ricky-sb** [nuxt/content#487]
### Is your feature request related to a problem? Please describe.
When I search in Nuxt Content on the Docs theme, I get this: 
![image](https://user-images.githubusercontent.com/10700079/93406124-bfa54c80-f843-11ea-80cd-c343de698145.png)  

I don't know which page my search query is on, and what the relevant results are at a glance.

### Describe the solution you'd like
I want to get a preview of the content, like how we have it on Nuxt.js's docs
![image](https://user-images.githubusercontent.com/10700079/93406605-eb750200-f844-11ea-987b-0871342e866b.png)

### Describe alternatives you've considered
VuePress has [integrated Algolia DocSearch as an option](https://vuepress.vuejs.org/theme/default-theme-config.html#algolia-search), and it's really nice. I much prefer Nuxt's Docs theme, and I'd love to supercharge it with Algolia.

### Additional context
* [Nuxt's Docs Site has Algolia](https://github.com/nuxt/nuxtjs.org)
* [Here's how VuePress integrated it](https://github.com/vuejs/vuepress/pull/201/files)
* [Article on Integrating Algolia DocSearch with JAMStack](https://www.vojtechruzicka.com/jamstack-search-algolia/)

**Comment by lupas** [comment]
Hey @ricky-sb 
I started this draft PR https://github.com/nuxt/content/pull/523 and plan to finish it up soon.
Some styling and minor bugfixes missing, but should not take too long. Feel free to participate.
