### ISSUE TITLE
"Edit this page on GitHub" link doesn't work on 0.6.0

### ISSUE THREAD

**Issue by antho1404** [nuxt/content#492]
With the introduction of github custom domains https://github.com/nuxt/content/pull/458, the edit this page link is generated with the `/repo` that is a valid URL for the API but not for the page on github.

### Version
@nuxt/content-theme-docs: 0.6.0
nuxt: 2.14.4

### Reproduction Link
https://content.nuxtjs.org/

### Steps to reproduce
Click on the "Edit this page on GitHub" link at the bottom of the page

### What is Expected?
Being redirected to the github page

### What is actually happening?
Got a 404 from github

**Comment by benjamincanac** [comment]
@antho1404 Indeed it has been fixed in #489 and just released in v0.6.1.

**Comment by antho1404** [comment]
Perfect 👍
