### ISSUE TITLE
"Cannot read property 'dbHash' of undefined" error only when using "nuxt generate"

### ISSUE THREAD

**Issue by azrikahar** [nuxt/content#493]
### Version
@nuxt/content: 1.9.0
nuxt: 2.14.5

Just a note, I've also faced this back in @nuxt/content@1.8.1 but I didn't manage to open an issue for it until now.

### Reproduction Link
CodeSandbox link: https://codesandbox.io/s/focused-ardinghelli-w37fd?file=/package.json

Note that I changed the "dev" script to `yarn generate && yarn start` since this issue won't happen in development mode.

#### Screenshot from CodeSandbox
![chrome_Vrzi1kFJca](https://user-images.githubusercontent.com/42867097/93566094-12574380-f9bf-11ea-98f6-efd0545345a3.png)

#### Screenshot from my local machine
![chrome_bqIipl8erx](https://user-images.githubusercontent.com/42867097/93566213-43d00f00-f9bf-11ea-8000-f4e08c49757e.png)

### Steps to reproduce
1. Create files in `categories` folder under `contents` directory.
2. Use Nuxt's `fetch()` method, with `fetchOnServer: false`, and get the categories via `this.$content('categories').fetch()`.
3. It stucks at "Loading..." since it can't fetch from the db-###.json file because the `dbHash` is undefined.

Another side note: Even if I remove the line `fetchOnServer: false`, yes the data are shown because the html are built in the generate process, but this error actually still happens, as seen here:
![chrome_LDxP62a7TR](https://user-images.githubusercontent.com/42867097/93567026-8c3bfc80-f9c0-11ea-975e-6d8338fded4d.png)

### What is Expected?
It should show "loading..." briefly (because I'm using fetch() and $fetchState.pending), then load the data properly from the db file. As shown in the following sequence:
![chrome_D7TAYexQ2G](https://user-images.githubusercontent.com/42867097/93567112-bbeb0480-f9c0-11ea-8395-815cf64473fa.png)
![chrome_kr2ZGaBYCa](https://user-images.githubusercontent.com/42867097/93567118-c0172200-f9c0-11ea-84a4-a86c21920ad9.png)

Once again the above screenshots are achieved using `yarn dev`, not `yarn generate && yarn start`. But it still is the expected outcome if we used the generate command.

### What is actually happening?
It can't find the db file since there is a hash appended to it, but the `dbHash` wasn't defined in `generate` environment for some reason.

### Additional troubleshooting
When I follow the error stack, I am lead to here:
![chrome_3kBqxtYdEm](https://user-images.githubusercontent.com/42867097/93567891-f012f500-f9c1-11ea-96af-05c835e7a716.png)

Based on the looks of it (with the "only", "without" etc few lines below it), I believe this is the minified code from this source code:
https://github.com/nuxt/content/blob/769c10a07321e05820e8e4fe1f13ce0d2f721fb1/packages/content/templates/plugin.static.js#L10

Which then seems to be related to this area:
https://github.com/nuxt/content/blob/769c10a07321e05820e8e4fe1f13ce0d2f721fb1/packages/content/lib/index.js#L164-L185

I honestly don't understand much, but maybe we need to pass `dbHash` via here?
https://github.com/nuxt/content/blob/769c10a07321e05820e8e4fe1f13ce0d2f721fb1/packages/content/lib/index.js#L207-L216
Since I'm not sure when did we pass `dbHash` into the $config.content or nuxtState.content here: `const { dbHash } = ctx.$config ? ctx.$config.content : ctx.nuxtState.content`.

Maybe it's the following line not having effect somehow even when it's meant to pass it to client side with publicRuntimeConfig?
https://github.com/nuxt/content/blob/769c10a07321e05820e8e4fe1f13ce0d2f721fb1/packages/content/lib/index.js#L169

---

Not sure if this info is useful or not, but I think the timeline where I start seeing this issue makes some sense based on the date of #438. I believe I did this with generate without any issue before that, unfortunately I can't be sure since I did it in some test projects and I scraped them.

**Comment by benjamincanac** [comment]
@azrikahar Have you tried with `target: 'static'` in your `nuxt.config.js`? This needs to be set when using `nuxt generate`.

**Comment by azrikahar** [comment]
@benjamincanac that works. Oh my... I kept assuming `nuxt generate` is only meant for `target: 'static'`, thus I thought it will default to static automatically. Sorry for the misunderstanding.

Would you mind explaining how `nuxt generate` differs from `nuxt build` when it's `target: 'server'`?

**Comment by Atinux** [comment]
Hi @azrikahar 

We had to keep the old behaviour (not full static) when using `nuxt generate` and `target: 'server'`, this behaviour tends to be removed in Nuxt 3 anyway and we don't recommend to actually use it.

**Comment by azrikahar** [comment]
@Atinux I was wondering why it's possible to do so (without warnings etc), thus I wanted to clear up my understanding. But then the `keep the old behaviour` decision definitely makes perfect sense and I didn't thought about it. Thank you very much for the clarification! Closing this now :)
