### ISSUE TITLE
sortBy

### ISSUE THREAD

**Issue by tevfiksirin** [nuxt/content#499]
Hello, 

[I created the project based on the blog post.](https://nuxtjs.org/blog/creating-blog-with-nuxt-content)

![Nuxt](https://downloader.disk.yandex.ru/preview/bc93c52397c0301af59c7bfba8218f1396b7952e4cd1556711ac572eef53bc7b/5f68c799/0GZZ-MDNEq4J8W8chE9sdfB20Y_Uegz5SHjNC1qrBbJKCui1LNIL5-vRqvvTQgknrZOEWMU6iMBz_Zm-N-vMsg==?uid=0&filename=2020-09-21_14-29-07.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&owner_uid=236189226&size=1600x757  "Nuxt")

I used the code below to show the contents

```js
export default {
  async asyncData({ $content, params }) {
    const articles = await $content('articles', params.slug)
      .only(['title', 'description', 'img', 'slug', 'author', 'alt'])
      .sortBy('createdAt', 'desc')
      .fetch()

    return {
      articles,
    }
  },
}
```

I want to show the results by the creation date.

## Netlify output

[![Netlify](https://downloader.disk.yandex.ru/preview/113ec68c322e67b70cc0571f3d669cfde1ee1db299b75abe0f8a5ed2dfbb739e/5f68c9ea/Kolei8ucbWbMlhXueeD3TDH72IKYTIivwgpGEDXfkf30Se0Ql6t23mAWc7SW7fL6zTzNqccDzvEGtqGWJDmmRw==?uid=0&filename=netlify.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&owner_uid=236189226&size=600x400 )](https://wonderful-hamilton-dc6902.netlify.app/)

## Surge output

[![Surge](https://downloader.disk.yandex.ru/preview/282e4f187606227a23635889584902f455c8a3b710a94673bb943e1ac6f6ef99/5f68cb9a/g7PdhsZLxh0jyrC43dyD7pn-YQkoWBRKdLX69z2rUZanpo9NeNHlSs4N0ACUZAogJudro1HGugxFnSkZEK789g==?uid=0&filename=surge.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&owner_uid=236189226&size=600x400 )](https://painful-profit.surge.sh/)

Why does [netlify show](https://wonderful-hamilton-dc6902.netlify.app/) different while [surge shows](https://painful-profit.surge.sh/) it the way I want.

What could I be missing?

Thanks.

**Comment by Atinux** [comment]
Hi @tevfiksirin 

The problem is that on Netlify, when cloning the repo it won't respect the `createdAt` (default to filesystem).

We recommend to set yourself the `createdAt` field in your Markdown metadata.

**Comment by tevfiksirin** [comment]
Thanks for the explanation @Atinux

**Comment by mrleblanc101** [comment]
I seem to have the same issue using Github Pages (with Github Actions).
Am I missing something ? Why doesn't it use the Git timestamp instead of the operating system created_at ?
