### ISSUE TITLE
How can I import @nuxt/content in nuxt.config?

### ISSUE THREAD

**Issue by maratumba** [nuxt/content#511]
With Nuxt 2.14, there is a problem with the newly added crawler feature, basically it runs out of memory. So I'm trying to use the `routes` setting in configuration file. In order to generate the dynamic routes, I need to access to the `content` object in `nuxt.config.js`. But importing in nuxt doesn't work:

```js
import content from "@nuxt/content";
// TypeError: content_1.content is not a function
import content from "@nuxt/content";
// TypeError: content_1.default(...).fetch is not a function
```
How can I import `@nuxt/content` in `nuxt.config.js`?

**Comment by Atinux** [comment]
Hi @maratumba 

Did you read https://content.nuxtjs.org/advanced#static-site-generation ?

**Comment by maratumba** [comment]
I'd missed that somehow. So it's not possible. In the meantime I found an ugly workaround (reading files manually with `fs` module, in case anyone coming across this needs it). 

Thanks for the reply @Atinux

**Comment by Atinux** [comment]
Did you read this code block @maratumba 

It is possible but you need to require `@nuxt/content` inside `generate.routes`:

```js
export default {
  modules: [,
    '@nuxt/content'
  ],
  generate: {
    async routes () {
      const { $content } = require('@nuxt/content')
      const files = await $content({ deep: true }).only(['path']).fetch()

      return files.map(file => file.path === '/index' ? '/' : file.path)
    }
  }
}
```

**Comment by maratumba** [comment]
God, what's wrong with me, I missed that too. Thank you again.
