### ISSUE TITLE
Dynamically changing the route for nuxt content articles

### ISSUE THREAD

**Issue by briancaffey** [nuxt/content#514]
I'm moving my blog from jekyll to Nuxt using full static mode with nuxt/content and I have a question about how to rewrite the paths that are generated by file system routing. 

Jekyll takes markdown files like `YYYY-MM-DD-my-article.md` and generates a route for this article like `/YYYY/MM/DD/my-article`. I currently have all of my content files in the `YYYY-MM-DD-my-arcitle.md` format and would like to keep the routing the same as it was with Jekyll, but nuxt/content generates URLs like `/YYYY-MM-DD-my-article`. I'm not sure if this is a content-specific question, but how can I achieve this type of path (`/YYYY/MM/DD/my-article`)? I looked into using hooks in the content documentation for beforeParse and beforeInsert but I don't think those are what I need.

**Comment by shadow81627** [comment]
I think you would have to setup folders in the `/pages` folder something like:

```txt
pages/
--| _year/
----| _month/
------| _day/
-------| _id.vue
```

Check the nuxt routing docs for more detail: https://nuxtjs.org/guide/routing/#dynamic-nested-routes

**Comment by briancaffey** [comment]
Thank you for the suggestion @shadow81627 , this worked for me.
