### ISSUE TITLE
Firefox Searching

### ISSUE THREAD

**Issue by Airbus5717** [nuxt/content#515]
in firefox browser the search doesnt work 
it opens a quick find instead

**Comment by NozomuIkuta** [comment]
I assume that you are talking about theme docs.

As far as I search, `keyup` event is fired after default action is performed: i.e., it's too late to prevent default.
`keydown` or `keypress` event should be what we would have to work with.

By the way, current theme docs is going to be replaced by a new theme, Docus, so this kind of fix might be applied to Docus only. 🤔
