### ISSUE TITLE
[@nuxt/content-theme-docs] `/pages` don't seem to work when using `theme()`

### ISSUE THREAD

**Issue by davestewart** [nuxt/content#522]
Hi,

When I use the docs theme, routes don't seem to work for `/pages`.

If don't use the `theme()` helper, they work.

Is it impossible to use both together, or do I need to configure something?

Thanks

**Comment by benjamincanac** [comment]
@davestewart Indeed, you cannot create `pages` when using the theme since it's already a Nuxt app. Routes can be added only by adding markdown files in the `content` folder.

**Comment by davestewart** [comment]
OK, thanks Benjamin.

As I've got you... any way to add multiple top-level sections? Such as Guide, API, etc?

I'm guessing my best best would be to eject the theme at this point and use it as a starting point for something bigger...

**Comment by kissu** [comment]
True that an external page would be nice for some basic OAuth for example. ^^

**Comment by bagaskarala** [comment]
true, i need this theme for only in `/docs` directory
