### ISSUE TITLE
content:before / content:init hook before parsing any content file.

### ISSUE THREAD

**Issue by vanling** [nuxt/content#526]
### Is your feature request related to a problem? Please describe.
Currently I am downloading a lot of json files into the content folder before I run `npm run generate` i've tried every hook in Nuxt i could find, but somehow there is no usable hook before the message `ℹ Parsed 17 files in 0,6 seconds @nuxt/content` 
i've tried the `content:file:beforeParse` but this gets executed for every existing file.

### Describe the solution you'd like
Would love to be able to have a `content:init' or `content:before` to do some async file downloads before content gets parsed

### Describe alternatives you've considered
Currently i am working around this problem by having another `npm run download` that executes download + generate, but i rather have this extra code in my nuxt-hooks.js file

### Additional context
none

**Comment by mathe42** [comment]
Did you tried the normal nuxt hooks so "ready", "render:before", "build:before".

I think "ready" should be called before nuxt-content is started.

**Comment by vanling** [comment]
@mathe42 Thank you for your reply. I think I had console logged every hook I could find in Nuxt, but now I am not sure about the ready hook. I will try that later today or tomorrow morning. If it doesn’t work I will drop the output/order of hook logs under here.

**Comment by vanling** [comment]
@mathe42 Thanks again :) currently i can work around my issue using modules:before. 

I hope @nuxt/content team still understands why "content:parsed:before" or something similar would help me and maybe other people. 

```
modules:before
ℹ Parsed 10637 files in 2,3 seconds   @nuxt/content
modules:done	  
ready
build:before  
builder:prepared         
builder:extendPlugins    
build:extendRoutes       
build:templates
build:compiled
build:done    
close
modules:before
modules:done	  
render:before	 
render:resourcesLoaded   
render:setupMiddleware	   
render:errorMiddleware	   
render:done   
ready
listen         
generate:before
generate:distRemoved     
generate:distCopied      
generate:extendRoutes    
generate:route
render:routeContext
generate:page 
generate:routeCreated    
generate:done 
close
```

**Comment by mathe42** [comment]
I created a PR. I think this should be the right place. If you want to test it just add the one line in you node_modules... :D

**Comment by vanling** [comment]
@Atinux Yes, I would love a hook before 'ℹ Parsed 10637 files in 2,3 seconds   @nuxt/content' and a content ready would also be useful.

**Comment by vanling** [comment]
@Atinux i'm currently able to do what i want with your 'content:options' hook from https://github.com/nuxt/content/pull/618 so i can close this :)

Thanks 👍  i will trade this feature request in for another ;)
