### ISSUE TITLE
Globally injected methods unavailable in component preview with <nuxt-content>

### ISSUE THREAD

**Issue by ol-ko** [nuxt/content#551]
Dear team!

I've been looking forward to using @nuxt/content to generate a static documentation site for the UI library.
And it's working brilliantly except for one special use-case.

The components of our UI library rely on the presence of `$t` method on the Vue instance - we're using `vue-i18n` that puts that method on the Vue prototype. 

Now when I add the necessary plugins to my Nuxt + @nuxt/content project this method is present and usable in the Nuxt project itself, but not in the preview of components, that is generated by `<nuxt-content>`.

Here's the repo to illustrate the issue and the setup: https://github.com/ol-ko/nuxt-content-lib-docs-with-i18n

Now I understand there are limitations to what `<nuxt-content>` is able to do in terms of previewing Vue components, but maybe there's an obvious workaround I am missing?

Any help highly appreciated! 🙏

**Comment by benjamincanac** [comment]
Hey @ol-ko,

Just tried your repo and it seems to work fine for me:

<img width="821" alt="Screenshot 2020-10-12 at 13 02 43" src="https://user-images.githubusercontent.com/739984/95739597-5e7a6880-0c8b-11eb-9128-0427fd6d08cf.png">

**Comment by ol-ko** [comment]
Damn @benjamincanac what am I doing wrong? 😂 
Shall we compare our yarn.lock files? I ran out of ideas...

**Comment by ol-ko** [comment]
It is easy to assume people miss basic things, but I did reinstall node modules, removed lockfiles, cleared cache, reinstalled node and even my MacOS at some point :)
