### ISSUE TITLE
search by index using fuse.js

### ISSUE THREAD

**Issue by pi0** [nuxt/content#553]
### Is your feature request related to a problem? Please describe.

Currently, searching through content is possible using `where` query.  it requires loading entire `db.json` on client-side which is big and also is not smart enough when user input is not exactly matching. 

### Describe the solution you'd like

 We can utilize [fuse.js](https://fusejs.io/) to create small index chunks and do fuzzy search.

`nuxt.config`

```js
export default {
  content: {
    indexes: {
       modules: [ 'name', 'description', 'author.name', 'tags' ] 
   }
 }
}
```

```js
await $content.search('modules', 'http')
```

### Describe alternatives you've considered

Although it is possible using services like Algolia (#523) and in fact it is more efficient overall, it requires depending on an external service and custom setup. Even if docs supports it, the main content module goal was to remove dependency on API endpoints so this solution would be still useful.

### Additional context

Not fully related, but we can also create an auto index using fuzzy.js based on crawler URLs to detect 404 typos like when one goes to `/api/options` and if we moved to `/options`, we can show a friendly message and link "Did you meant /options?"`

**Comment by benjamincanac** [comment]
@pi0 Indeed, it would be really nice!

However this would prevent using the `search` with `where` and other chaining method.
