### ISSUE TITLE
Using @nuxt/content to display a markdown formatted string ?

### ISSUE THREAD

**Issue by gilles6** [nuxt/content#554]
Can I also use `@nuxt/content` to display a string variable containing markdown ? Or do I need to install extra package like `@nuxtjs/markdownit` to be able to do it ?

```
<template>
  <div>
    <nuxt-content>{{myString}}</nuxt-content>
  </div>
</template>
<script>
export default {
  data() {
    return {
      myString: 'Hello **World**'
    }
  }
}
</script>
```

**Comment by benjamincanac** [comment]
@gilles6 Unfortunately you can't do that, the `nuxt-content` component is used to transform JSON AST into HTML, it doesn't parse markdown. However you can use `markdownit` or `marked` to achieve this result.
