### ISSUE TITLE
nuxt-content-docs icon-dark.png and icon-light.png path does not respect router.base

### ISSUE THREAD

**Issue by craigharman** [nuxt/content#561]
### Version
@nuxt/content: v1.10.0
@nuxt/content-theme-docs: 0.7.2
nuxt: 2.14.3

### Reproduction Link
- not accessible

### Steps to reproduce
Create a new docs theme project in a sub folder eg. /docs
In nuxt.config.js add
```
router: {
		base: '/docs/',
	},
```
The theme respects the /docs folder, but the icon pngs are referencing the root so they cannot be found.

### What is Expected?

Rather than <img src="/img-light.png">
Generate <img src="/docs/img-light.png">

### What is actually happening?

Icon src attribute is <img src="/img-light.png">

**Comment by 4ern** [comment]
I had the same problem. I solved it by removing the leading slash.

`"logo": {
    "light": "logo-light.svg",
    "dark": "logo-dark.svg"
  },`
