### ISSUE TITLE
How do you edit/replace the logo at the same dimension?

### ISSUE THREAD

**Issue by k16e-me** [nuxt/content#572]
When I replaced the Nuxt/Content logo, both light and dark, with mine, the size is squeezed because my dimension of svg/png doesn't quite match that of the former. How do I edit this?

**Comment by farnabaz** [comment]
Hey there 👋 

`@nuxt/content-theme-docs` is moving away and will not get any updates, very soon we will open-source Docus, a brand new theme based on Nuxt 3 and Content v2 with lots of fixes, improvements, and new features.

I’m closing this issue in favor of the new docs theme. Keep an eye on #726 for updates
