### ISSUE TITLE
How Do I Edit the Footer (Built with Nuxt) Section

### ISSUE THREAD

**Issue by k16e-me** [nuxt/content#579]
Hi, I'd love to pointed to how to edit/customize areas/sections of the Docs theme. For example, I'd love to add more content and links at the footer, the "Built with Nuxt" section. I'd also love to remove the light/dark toggle, as I want my doc to only be available in dark mode.

All in all, I'd love to see how I can take more control of sections of the theme.

Thanks.

**Comment by benjamincanac** [comment]
Hey @k16e-me, it will be possible once #542 is merged.

**Comment by k16e-me** [comment]
Whew, @benjamincanac, that's good news. Thanks.

**Comment by benjamincanac** [comment]
The previously linked PR was merged but to fulfill another purpose. Still waiting on the next release of `@nuxt/components` to handle components override.

**Comment by jsbroks** [comment]
@benjamincanac v1.2.0 was released 23 days ago?

**Comment by k16e-me** [comment]
O, awesome. How come I never noticed? Let me go look-see. Thanks!

**Comment by k16e-me** [comment]
> The previously linked PR was merged but to fulfill another purpose. Still waiting on the next release of `@nuxt/components` to handle components override.

O, I must have misunderstood. So, components override is as yet not possible?

**Comment by jsbroks** [comment]
@k16e-me Release v1.20 of `@nuxt/components` allows for components override

**Comment by farnabaz** [comment]
Closing this issue because docs-theme is deprecated and will not receive any updates.
