### ISSUE TITLE
[theme-docs] remark-footnotes plugin doesn't work since version 0.7

### ISSUE THREAD

**Issue by NozomuIkuta** [nuxt/content#583]
### Version

@nuxt/content: v1.0.0
@nuxt/content-theme-docs: v0.7.2
nuxt: v2.14.7

### Reproduction Link

https://codesandbox.io/s/busy-jennings-vbogj?file=/content/index.md

This demo doesn't use theme-docs but just forked [the one written in the issue template](https://codesandbox.io/s/nuxtcontent-demo-l164h), because the bug is actually due to `@nuxt/content` itself.

### Steps to reproduce

- Upgrade `@nuxt/content` to `v1.10.0`
- Use footnotes in markdown contents
- See the rendered page

### What is Expected?

- Footnotes are correctly rendered.
- Or, all the remark-related dependencies should have been updated at once.

### What is actually happening?

- Footnotes are not correctly rendered.
- Or, major update of remark plugins was published without the dependency.

### Additional context (what I found)

#531 major-updated `remark-footnotes` to `v3.0.0` and it has already been published as a part of `@nuxt/content@1.10.0`.
However, [as written in the official repo of `remark-footnotes`](https://github.com/remarkjs/remark-footnotes) or warned in the console of the demo above, `remark-footnotes@3.0.0` requires `remark-parse@9.0.0`. #567 is to update `remark-parse` but it has not yet been merged and published.

So, until #567 is published, we can't use footnotes in markdown contents. I'm not sure there is a workaround, though.

**Comment by NozomuIkuta** [comment]
Ah, I found `remark-parse@9.0.0` was published 10 days after `remark-footnotes@3.0.0` was published. So, it was be just a timing issue, since there is no way the renovate app know the relationship between them and include them into one PR. The app just creates PRs in a certain interval, doesn't it?

**Comment by cschweda** [comment]
So there's no immediate solution until the bundled Remark is updated?

**Comment by mathe42** [comment]
Did someone tried `yarn add remark-footnotes@2` ?

**Comment by cschweda** [comment]
> Did someone tried `yarn add remark-footnotes@2` ?

Yup -- just tried this. 

```npm i remark-footnotes@2```

Footnotes seem to render properly -- and I didn't see the installation warning.

Just to make sure, I deleted ```node_modules``` and ```package-lock.json``` -- and did a full ```npm install```.

Everything seems fine -- so for the moment, at least -- this seems like a work around.

Thanks!

**Comment by NozomuIkuta** [comment]
@cschweda 

Thank you for testing!

By the way, it might work as well to install `remark-parse@9.0.0`, removing `node_modules` and `package-lock.json`.
