### ISSUE TITLE
[remark-footnotes] Warning: please upgrade to remark 13 to use this plugin

### ISSUE THREAD

**Issue by pangxieju** [nuxt/content#585]
Mac 10.15.6
node v12.19.0
npm 6.14.8

docs https://content.nuxtjs.org/installation/

package.json
`
"@nuxt/content": "^1.10.0",
"nuxt": "^2.14.7"
`

nuxt.config.js
`
  modules: [
    // https://go.nuxtjs.dev/content
    '@nuxt/content',
  ],
`
![WX20201019-103936](https://user-images.githubusercontent.com/18155203/96395570-8a4f9e00-11f7-11eb-9604-ce2797c5429b.png)

According to the configuration of the document, I don't know why the error is reported.

**Comment by NozomuIkuta** [comment]
@pangxieju 

My bug report #583 would help you understand the situation.

**Comment by pangxieju** [comment]
@NozomuIkuta 
Thank you for your help! I tried to upgrade "remark-parse", but the problem is still not solved.

**Comment by NozomuIkuta** [comment]
@pangxieju 

Workaround was found and shared in #583. 🙋
