### ISSUE TITLE
images lazy loading

### ISSUE THREAD

**Issue by ilijanovic** [nuxt/content#586]
Is it possible to add an additional attribute to my images in my markdown content?

like `data-src="..."` if somebody is using IntersectionObserver or `loading="lazy"` if somebody wants to use native browser lazy loading.

I did not find any solution. I found an hint to do it while the project do its build with `build: { ... }`?

**Comment by benjamincanac** [comment]
Hey @ilijanovic, have you tried using [@nuxt/image](https://github.com/nuxt/image) module directly in your markdown?

**Comment by ilijanovic** [comment]
@benjamincanac thank you for your response. No i have not. This seems to be pretty new and sounds interessting. I will take a look at it to implement it to my blog. Thank you!
