### ISSUE TITLE
[remark-footnotes] Warning: please upgrade to remark 13 to use this plugin

### ISSUE THREAD

**Issue by pangxieju** [nuxt/content#593]
Before reporting a bug, please make sure that you have read through our documentation and you think your problem is indeed an issue related to our module. Yes!

### Version
@nuxt/content: "^1.10.0"
nuxt: "^2.14.6"

![1603249930663](https://user-images.githubusercontent.com/18155203/96669019-f9132f80-138e-11eb-8a92-f35b28ac2755.jpg)

**Comment by bickauskaslaurynas** [comment]
same problem

**Comment by mathe42** [comment]
1. Bad title as this seems unrelated.
2. Exists this Problem in Production?
3. Please provide a reproduction.

**Comment by pangxieju** [comment]
Thank you, the problem has been resolved. 
[https://github.com/nuxt/content/issues/585](url)
