### ISSUE TITLE
CSS/Styles in Component Not Applying

### ISSUE THREAD

**Issue by k16e-me** [nuxt/content#608]
When. I create a custom component, I'm using the Docs Theme, the styles I write in the style block don't apply. So I have in a `Portrait.vue` file, as an example:
```
<template>
    <figure>
        <img :src="src" alt="" class="w-64"/>
        <figcaption v-text="caption"/>
    </figure>
</template>

<script>
    export default {
        props: ['src', 'caption']
    }
</script>

<style lang="scss" scoped>
    figure {
        float: left;
    }
</style>
```
Now, when I call the Portrait component like so:
```
<graphic
    :src="'/kb_selfie_1015_new_20_kabolobari_benakole_portraiture.jpg'"
    :caption="'Portrait of Kabolobari Benakole self-taken on phone camera.'">
</graphic>
```
in a `.md` file, the styles either from Tailwind classes or written in the style block don't apply.

Question is, how do you apply styles to a custom component using the Docs theme, what extra step might I be missing?

**Comment by Atinux** [comment]
@k16e-me you can try with removing the `scoped`  attribute in the `<style>` ?

**Comment by k16e-me** [comment]
> @k16e-me you can try with removing the `scoped` attribute in the `<style>` ?

O, that works. Thanks.

**PS** Is there a reason why it must be "unscoped" to work? I'd love if worked `scoped` no less. The idea of not making it global.

**Comment by GoulartNogueira** [comment]
@k16e-me , I don't know how to scope. But I know 2 ways to avoid a mess in your project:

## 1. Unique Class

```
<template>
    <figure class="LEFTFIGURE">
        ...
    </figure>
</template>

<style lang="scss">
    figure.LEFTFIGURE {
        float: left;
    }
</style>
```

---

## 2. Father Element

Another way to limit the scope is by encapsulating it inside another exclusive element and selecting this father is CSS:

```
<template>
    <div class="special-father"
        <figure>
            ...
        </figure>
    </div>
</template>

<style lang="scss">
    div.special-father figure {
        float: left;
    }
</style>
```

Both ways **are still global**, but they will not mess up the rest of your project, unless you use the exact same names elsewhere.
