### ISSUE TITLE
Can I run content plugin in SPA mode after npm run build?

### ISSUE THREAD

**Issue by Utwo** [nuxt/content#609]
So the question is, if I can run the content plugin (liveEdit) after I build the project with `npm run build` in SPA mode or static one. 

I would like to experiment a new app (actually it's a personal project) that would work something like this:
connect to github :arrow_right:  select a nuxt project repo with content plugin :arrow_right:  the code will be cloned in a cloud function :arrow_right:  the cloud function will install dependencies :arrow_right:  the cloud function will run `npm run build` :arrow_right:  the cloud function will save the dist to a bucket. 

Now in browser, load the dist from the bucket in an iframe with content liveEdit enabled. When the user double click on content and change the text, the browser will intercept the call with a service worker and edit the proper markdown/json/yaml in memory. When the user finish with all the editing, I will make a new commit to Github.

What do you think? Maybe a bit similar to #240

**Comment by Atinux** [comment]
It is indeed similar, we are planning to add this feature for v2, to have live edit in production connected to your GitHub repo.

**Comment by Utwo** [comment]
Awesome, I'll wait for Nuxt v2 then, thank you!
