### ISSUE TITLE
[@nuxt/content-theme-docs]: Using Vue in Markdown?

### ISSUE THREAD

**Issue by 4ern** [nuxt/content#611]
Hello is it possible to use vue within the markdown? So like [Vuepress](https://vuepress.vuejs.org/guide/using-vue.html#using-vue-in-markdown)?

Unfortunately I have not found anything for this.

**Comment by cschweda** [comment]
Like this?

https://content.nuxtjs.org/writing#vue-components

**Comment by 4ern** [comment]
No i want to write some data to use this in a component inside the markdown file.
i do not want to write an extra component for it.

```js

export default {
  data() { 
    myData: 'foo'
  }
}

```

**Comment by benjamincanac** [comment]
@4ern You can use Vue.js components in the markdown but you can't use Vue interpolation or syntax directly in markdown unfortunately. Maybe you can try to take a look at [remark-vue](https://github.com/medfreeman/remark-vue) by adding it to the [remark plugins](https://content.nuxtjs.org/configuration#markdownremarkplugins) (haven't tested yet).
