### ISSUE TITLE
Code block with file name requires invalid syntax

### ISSUE THREAD

**Issue by rchl** [nuxt/content#630]
### Version
@nuxt/content: v1.10.0
nuxt: v2.14.5

### Steps to reproduce
Create a code block with a filename info string:

``````
```js {}[nuxt.config.js]
{
  modules: [
    'nuxt-i18n'
  ],
}
```
``````

### What is Expected?

That the file name is rendered in the generated code block and the code block is highlighted in the editor.

### What is actually happening?

The file name doesn't show up.

It works after removing the space between `js` and `{}` but then it's not a valid markdown block and the code block is not highlighted in editors or github.

**Comment by rchl** [comment]
commonmark spec says:

> The content of a code fence is treated as literal text, not parsed as inlines. The first word of the info string is typically used to specify the language of the code sample, and rendered in the class attribute of the code tag. However, this spec does not mandate any particular treatment of the info string.

https://spec.commonmark.org/0.28/#info-string

So it says that the first word is typically a language code. But it's not very specific how "word" is determined. Is it by parsing according to a word boundary (`\w` in regex) or separated by space or newline? I'm not sure.

The truth is that neither github nor ST highlights such code blocks as those expect there to be a new-line or a space after the language tag.

**Comment by Atinux** [comment]
Fixed with https://github.com/nuxt/content/pull/621
