### ISSUE TITLE
Serve @nuxt/content from a subdirectory

### ISSUE THREAD

**Issue by kr-apps** [nuxt/content#635]
Hi people,

I cloned the repository for the theme and `nuxt/content` assumes your project is served from the root of your domain. 

Is there a way to change this option to `/docs` if my project will be hosted in a subdirectory called `docs`.

I need my docs to be a static site, so I build them using the `npm run generate` command, but instead to browse the documentation on `http://example.com` I want to browse it on `http://example.com/docs`.

**Comment by NozomuIkuta** [comment]
@kr-apps 

Nuxt Content is a Nuxt module, and it doesn't decide where Nuxt app is mounted, as far as I know.

You can change the base URL via `router.base` option in `nuxt.config.js`.

```javascript
```

, which is an alias to [`base` option of Vue Router](https://router.vuejs.org/api/#base).

**Comment by kr-apps** [comment]
@NozomuIkuta 

Thank's, now it works. 

I didn't now we can use and override the router property inside the theme function, I thought we can change just the properties that came with the theme's package and were explained in the docs.
