### ISSUE TITLE
Alternative to LokiDB

### ISSUE THREAD

**Issue by paraboul** [nuxt/content#64]
LokiDB doesn't seem to be actively maintained :
https://github.com/LokiJS-Forge/LokiDB/issues/168#issuecomment-505748914

One major issue I encountered, for instance, is that default `LokiOperatorPackage` doesn't support date comparison (`$eq` is implemented as `===` which doesn't work against `Date` object). It's a bit weird because its predecessor (LokiDB) implemented `$dteq` for this precise reason.

In the meantime, it seems possible to extends `LokiOperatorPackage` in order to provide custom comp operators.

That being said, I wonder if there is a more robust alternative to LokiDB

**Comment by benjamincanac** [comment]
Hey @paraboul 

I hear you it was an issue for us as well, however LokiDB supports full-text search natively which was a requirement for us.

Have to dig a bit more but they have a `LokiAbstractOperatorPackage` which would solve your date comparison issue: https://github.com/LokiJS-Forge/LokiDB/blob/master/packages/loki/src/operator_packages.ts#L484.

**Comment by felixheck** [comment]
Weirdly, most of the original operators are not supported at all.
Would love to find an alternative or a way to extend/customize the Loki instance/collection.
