### ISSUE TITLE
Is there a way to specify a slug property for JSON array?

### ISSUE THREAD

**Issue by chasebank** [nuxt/content#650]
From the [JSON Array docs](https://content.nuxtjs.org/writing/#arrays)
> Since the slug is by default taken from the path and missing in this case, you have to define it in your objects for this feature to work properly.

Understood. But is there no way to specify an existing property to be used as the slug? An existing ID for example. Some equivalent of track-by... (Sorry if that's an overly simplistic way of thinking about it).

**Comment by benjamincanac** [comment]
@chasebank At this moment there isn't. The `slug` property being required you have to define it to fetch one of the flattened element from the array. It isn't required however if you just need to fetch a list of documents.
