### ISSUE TITLE
A particular line in a code block breaks Nuxt content...

### ISSUE THREAD

**Issue by lukeocodes** [nuxt/content#652]
This is so odd... 

### Version
@nuxt/content: v1.10.0
nuxt: 2.14.7

### Reproduction Link

1. Go here: https://learn.vonage.com/blog/2020/08/19/how-to-send-an-sms-with-ionic-dr
2. See errors in console

### Steps to reproduce

1. Create a markdown file
2. Start a `typescript` or `js` codeblock and include this
  ![image](https://user-images.githubusercontent.com/956290/99879764-c61ac080-2c06-11eb-9316-e8de4489e94a.png)
3. Save
4. Generate
5. View file via the web

### What is Expected?

File renders fine!

### What is actually happening?

- Errors in console
  ![image](https://user-images.githubusercontent.com/956290/99879794-05491180-2c07-11eb-85dc-a2d79f1d7211.png)
- Fails to be crawled by the nuxt crawler (errors)
  ![image](https://user-images.githubusercontent.com/956290/99879394-b4d0b480-2c04-11eb-9892-90a045b2e4b5.png)
- SSR skipped due to crawler error

**Comment by Geminii** [comment]
Hi @lukeocodes 👋 
Could you provide a minimal code reproduction on codesandbox ? 
I can take a look if you want and purpose a PR 😀
