### ISSUE TITLE
regression(theme-docs): indentation breaks vue components

### ISSUE THREAD

**Issue by danielroe** [nuxt/content#657]
### Version
@nuxt/content-theme-docs: v0.8.1
nuxt: v2.14.7

### Reproduction Link
**Working** (`@nuxt/content-theme-docs` v0.7.2): https://composition-api-7k8yhhohi.vercel.app/getting-started/setup. See https://github.com/nuxt-community/composition-api/commit/e0b5c7f6f6ec793fad9aff84665274b9539168a7
**Not working** (`@nuxt/content-theme-docs` v0.8.1): https://composition-api-72k1yazd2.vercel.app/getting-started/setup. See https://github.com/nuxt-community/composition-api/commit/f9b135ad455bf492eb65d588bbf54c6966199d4f

See https://github.com/nuxt-community/composition-api/pull/299 for context

### Steps to reproduce
Clone https://github.com/nuxt-community/composition-api
`cd docs && yarn dev`
Visit http://localhost:3000/getting-started/setup

### What is Expected?
The indentation should apply to the entire component.

### What is actually happening?
The indentation breaks the component rendering

**Comment by farnabaz** [comment]
Closing in favor of Docus. #726
