### ISSUE TITLE
Markdown grammar did not parse successfully

### ISSUE THREAD

**Issue by 81777268** [nuxt/content#659]
### Version
@nuxt/content:  1.8.1
nuxt: 

### Steps to reproduce

![image](https://user-images.githubusercontent.com/26462331/100095734-ec09c480-2e95-11eb-9469-116286622c1a.png)

![image](https://user-images.githubusercontent.com/26462331/100095772-faf07700-2e95-11eb-8f77-f549566ee3f8.png)

![image](https://user-images.githubusercontent.com/26462331/100095792-0479df00-2e96-11eb-942a-86a79df168d7.png)

generate

There is no problem with the HTML after the page is statically packaged. The markdow is parsed into a table, but after deploying to S3, the table is replaced with the markdow syntax when the page is opened. Why is this?

why?
When will db-****.json replace the content in HTML?

**Comment by NozomuIkuta** [comment]
@81777268 

I believe this issue is already resolved by #653, which has not yet been released.
