### ISSUE TITLE
[theme doc] no fallback language -> return 404 page not found

### ISSUE THREAD

**Issue by flapili** [nuxt/content#663]
### Reproduction Link
https://content.nuxtjs.org/fr/themes/docs/ (this page is actually indexed by google)

### What is Expected?
a fallback page like for https://fr.nuxtjs.org/faq/deployment-pm2, or at least a message saying "this page is available in [list of availables languages]" + links

### What is actually happening?
page not found

**Comment by Geminii** [comment]
Hey @flapili 👋 
Resolves once #670 will be merge 😀😀
Coming soon ❤️
