### ISSUE TITLE
Display Prev/Next blog page buttons using URL query (pagination)

### ISSUE THREAD

**Issue by sts-ryan-holton** [nuxt/content#665]
I've been searching the Nuxt JS Content docs to try and find some kind of example where I can list out all of my blog posts on a page and have some kind of blog pagination.

I did manage to find an article, but it suggested using the following URL structure:

- https://example.com/blog/page/1
- https://example.com/blog/page/2

And the parent `/blog` page would redirect to the `/page/`1`.

I actually want to utilise the URL query and hopefully have something simplier.

I'm currently getting all of my blog posts on my page:

- https://domain-monitor.io/blog

```javascript
<script>
export default {
  head () {
    return {
      title: 'Domain Monitor | Blog',
      meta: [
        { hid: 'og:title', name: 'og:title', content: 'Domain Monitor | Blog' },
        { hid: 'description', name: 'description', content: 'Domain Monitor updates, product news, useful guides and information to help you start monitoring your next domain. Starting reading today.' },
        { hid: 'og:description', name: 'og:description', content: 'Domain Monitor updates, product news, useful guides and information to help you start monitoring your next domain. Starting reading today.' }
      ]
    }
  },
  async asyncData ({ $content }) {
    const blogs = await $content('blog')
                        .sortBy('createdAt', 'desc')
                        .fetch()
    return {
      blogs
    }
  }
}
</script>
```

I'm displaying my blogs via a `v-for="(blog, index) in blogs"`.

I was thinking of using a Javascript `.slice()` method to slice the array, and then when I click a Next button it changes the URL to:

- https://domain-monitor.io/blog?page=2

But I got stuck trying to find a proper implementation of this, and wondered how this would scale with hundreds of posts...

Any suggestions?

**Comment by NozomuIkuta** [comment]
@sts-ryan-holton 

Here are some information for you to achieve your goal,

As for URL structure, it doesn't matter whichever you use `/page/:pageNumber` or `/blog?page=pageNumber`.
[Nuxt provides you such information via `context`](https://nuxtjs.org/docs/2.x/internals-glossary/context).

As for pagination, or fetching a certain number of contents in other words, Nuxt Content provides native methods: `skip()` and `limit()`.

You can use [`skip()` method](https://content.nuxtjs.org/fetching#skipn) to exclude first _n_ number of contents from the result.
Since page number starts from `1`, let's pass `(pageNumber - 1) * numberOfPostsPerPage` to `skip()` method.

Next, you want to fetch a _slice_ which is consisted of a certain number of contents.
Let's use [`limit()` method](https://content.nuxtjs.org/fetching#limitn) for such case.

I believe now you can achieve your goals.

**Comment by sts-ryan-holton** [comment]
@NozomuIkuta I've tried implementing what you've suggested, and have the following:

```javascript
async asyncData ({ $content, route }) {
  const pageNumber = route.query.page ? route.query.page : 1
  const perPage = 5

  const blogs = await $content('blog')
                      .sortBy('createdAt', 'desc')
                      .skip((pageNumber - 1) * perPage)
                      .limit(perPage)
                      .fetch()
  return {
    blogs
  }
}
```

`blogs` is what I'm looping over with a `v-for`, however, when I pass (for instance) `?page=3` to my URL, my posts remain at **5** and don't move to the next 5 posts, what's wrong here?

**Comment by NozomuIkuta** [comment]
@sts-ryan-holton 

If you depends on URL query, `route.query` would be always an empty object on SSR.
Please refer to [nuxt.js/issues/7572](https://github.com/nuxt/nuxt.js/issues/7572), where a core team member recommends to use `mounted` in such case.

Sorry for lack of information.

**Comment by sts-ryan-holton** [comment]
@NozomuIkuta Just tried mixing it up with the `mounted()` hook, now, `pageNumber` isn't defined apparently lol

```javascript
data () {
  return {
    pageNumber: 1
  }
},
mounted () {
  if (this.$route.query.page) this.pageNumber = this.$route.query.page
},
async asyncData ({ $content }) {
  const pageNumber = this.pageNumber
  const perPage = 5

  const blogs = await $content('blog')
                      .sortBy('createdAt', 'desc')
                      .skip((pageNumber - 1) * perPage)
                      .limit(perPage)
                      .fetch()
  return {
    blogs
  }
}
```

**Comment by NozomuIkuta** [comment]
@sts-ryan-holton 

`mounted` is called _after_ `asyncData` is completed. You have to move the whole logic to fetch blogs to `mounted` hook, so that you can use `this.$route.query.page` there.

By the way, to be honest, you should review Nuxt's basics such as [its lifecycle](https://nuxtjs.org/docs/2.x/concepts/nuxt-lifecycle).
Nuxt community well organizes information for us to achieve our goals in most cases. 🙌

**Comment by sts-ryan-holton** [comment]
@NozomuIkuta Thanks for you reply, I've been working on implementing blog navigation as per your suggestion and have got the page navigation working nicely now with a URL param, prev/next buttons and some basic validation on those buttons for when a user is on page one (preventing them going back a page)

I'm not sure though this is normal...

It takes 6 whole seconds to load all of my content when loading the page, granted that it doesn't do this when navigating between "pages", but I only have 35 articles at the moment which isn't a lot, and wonder whether we're looking at 12 seconds to load 70 articles?

What would you recommend here? Because in production mode, the page remains blank until it's finished fetching those articles...

Here's my code if you're interested:

```html
<template>
  <div>
    <section class="py-4 py-lg-8 bg-light position-relative">
      <b-container v-if="!isLoading">
        <b-row>
          <b-col cols="12" md="6" v-for="(blog, index) in blogs" :key="index" :class="blogs.length == 1 ? 'mx-auto' : ''">
            <!-- blog cards -->
          </b-col>
        </b-row>
        <b-row v-if="blogs.length >= 1">
          <b-col class="text-center">
            <b-button pill variant="primary" size="lg" @click="prevPage" :disabled="pageNumber <= 1">Prev Page</b-button>
            <b-button pill variant="primary" size="lg" @click="nextPage" :disabled="pageNumber >= blogs.length">Next Page</b-button>
          </b-col>
        </b-row>
      </b-container>
      <b-container v-else class="text-center">
        <b-row>
          <b-col>
            <b-spinner style="width: 2.5rem; height: 2.5rem;" variant="primary" label="Loading posts"></b-spinner>
            <h5 class="mt-2 mb-0 font-weight-normal text-muted">Loading posts...</h5>
          </b-col>
        </b-row>
      </b-container>
    </section>
  </div>
</template>
```

And the JS...

```javascript
<script>
export default {
  data () {
    return {
      blogs: [],
      isLoading: true,
      pageNumber: this.$route.query.page ? this.$route.query.page : 1,
      perPage: 6
    }
  },
  mounted () {
    this.fetchBlogs()
  },
  methods: {

    /*
    ** Fetch all blogs
    */
    async fetchBlogs () {

      // if statement to prevent screen flicker when navigating between
      // pages, not sure about navigation back and fourth between articles
      // though as it persists here
      if (this.blogs.length <= 0) this.isLoading = true

      // this takes a long time, suspect there's some improvements that can
      // be done somehow?
      this.blogs = await this.$content('blog')
                              .sortBy('createdAt', 'desc')
                              .skip((this.pageNumber - 1) * this.perPage)
                              .limit(this.perPage)
                              .fetch()

      this.isLoading = false
    },

    /*
    ** Previous page
    */
    prevPage () {
      this.pageNumber--
      this.configurePage()
    },

    /*
    ** Next page
    */
    nextPage () {
      this.pageNumber++
      this.configurePage()
    },

    /*
    ** Page config
    */
    configurePage () {
      this.$router.push({ query: { page: this.pageNumber } })
      this.fetchBlogs()
    }

  }
}
</script>
```

I've looked into caching, but wonder how I would really implement that, and I am reguarly adding new content so don't want search engines to fall behind here.

**Comment by sts-ryan-holton** [comment]
Any update here?
