### ISSUE TITLE
list in md file does not work as expected

### ISSUE THREAD

**Issue by ryosukemitake** [nuxt/content#668]
very appreciate for all of your great work for this project.
I'm really enjoying to create my blog with nuxt/content!

However, I realized that parts of my md file is not converted as I expected.

I tried to make the list content in md file as official doc shows.
https://content.nuxtjs.org/themes/docs#list

however it does not work as my codesandbox below.
please check it 
https://codesandbox.io/s/pedantic-chaum-j1mm1?file=/content/en/about.md

**Comment by ryosukemitake** [comment]
sorry 
the doc explained already
https://content.nuxtjs.org/ja/themes-docs#list

I missed it thanks

**Comment by ryosukemitake** [comment]
I tried to make the list content in md file as official doc shows.
https://content.nuxtjs.org/themes/docs#list

however it does not work as my codesandbox below.
please check it 
https://codesandbox.io/s/pedantic-chaum-j1mm1?file=/content/en/about.md

**Comment by NozomuIkuta** [comment]
@ryosukemitake 

You have to define items in [the front matter](https://content.nuxtjs.org/themes/docs#front-matter) as well as other document properties.

```markdown 
---
title: 'Sample Page'
items:
  - Item1
  - Item2
  - Item3
---

<list :items="items"></list>
```

[`NuxtContent` component binds properties defined in front matter to components when rendering](https://github.com/nuxt/content/blob/b2f45db0b16ecdf21981f6eff0afdc851829ccbe/packages/content/templates/nuxt-content.js#L18-L24).
