### ISSUE TITLE
Support for .txt files

### ISSUE THREAD

**Issue by jbnv** [nuxt/content#67]
### Describe the solution you'd like
Support retrieving lists of strings from `.txt` files.

### Describe alternatives you've considered
If you're retrieving the list of strings to display it as a bulleted list, you can store it as a `.md` file. You can also store it in a `.json` file. The idea is that `.txt` allows for storing the list with no delimiters or styling.

**Comment by benjamincanac** [comment]
@jbnv You can already do that with a `.csv` file.

**Comment by jbnv** [comment]
The idea is that .txt allows for storing the list with no delimiters or styling.
