### ISSUE TITLE
Generated blog posts are: "Duplicate, submitted URL not selected as canonical" according to Google Search Console

### ISSUE THREAD

**Issue by sts-ryan-holton** [nuxt/content#674]
### Version
@nuxt/content: v1.10.0
nuxt: v2.14.4

### Reproduction Link

- https://domain-monitor.io/blog

### Steps to reproduce

Not really sure there's any steps to reproduce other than ensuring that a Nuxt JS website is in `universal` mode and is a `static` site.

Needless to say, here's my **nuxt.config.js** file:

```javascript
export default {
  /*
  ** Nuxt rendering mode
  ** See https://nuxtjs.org/api/configuration-mode
  */
  mode: 'universal',
  /*
  ** Nuxt target
  ** See https://nuxtjs.org/api/configuration-target
  */
  target: 'static',
  /*
  ** Env variables
  */
  env: {
    BASE_URL: process.env.BASE_URL || "https://domain-monitor.io",
    API_URL: process.env.API_URL || "http://127.0.0.1:8000",
    ONESIGNAL_PUSH_APP_ID: process.env.ONESIGNAL_PUSH_APP_ID || "",
    ONESIGNAL_SAFARI_WEB_ID: process.env.ONESIGNAL_SAFARI_WEB_ID || "",
    GA_ID: process.env.GA_ID || ""
  },
  /*
  ** Headers of the page
  ** See https://nuxtjs.org/api/configuration-head
  */
  head: {
    title: 'Domain Monitor',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'og:title', name: 'og:title', content: 'Domain Monitor' },
      { hid: 'description', name: 'description', content: 'Keep track of your expiring domains today for FREE with our FREE domain monitoring product.' },
      { hid: 'og:description', name: 'og:description', content: 'Keep track of your expiring domains today for FREE with our FREE domain monitoring product.' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
      { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap' },
      { rel: 'stylesheet', href: 'https://fonts.googleapis.com/icon?family=Material+Icons' }
    ]
  },
  /*
  ** Global CSS
  */
  css: [
    '@/assets/scss/domain-monitor.scss'
  ],
  /*
  ** Bootstrap Vue
  */
  bootstrapVue: {
    bootstrapCSS: false,
    bootstrapVueCSS: false
  },
  /*
  ** Plugins to load before mounting the App
  ** https://nuxtjs.org/guide/plugins
  */
  plugins: [
    { mode: 'client', src: '@/plugins/bootstrap-vue-icons' },
    { mode: 'client', src: '@/plugins/vue-axios' },
    { mode: 'client', src: '@/plugins/vee-validate' },
    { mode: 'client', src: '@/plugins/vue-moment' },
    { mode: 'client', src: '@/plugins/content-images' },
    { mode: 'client', src: '@/plugins/content-videos' }
  ],
  /*
  ** Auto import components
  ** See https://nuxtjs.org/api/configuration-components
  */
  components: true,
  /*
  ** Nuxt.js dev-modules
  */
  buildModules: [
    ['@nuxtjs/google-analytics', {
      id: process.env.GA_ID
    }]
  ],
  /*
  ** Nuxt.js modules
  */
  modules: [
    'bootstrap-vue/nuxt',
    '@nuxtjs/axios',
    '@nuxtjs/auth',
    '@nuxtjs/onesignal',
    '@nuxtjs/pwa',
    '@nuxt/content',
    '@nuxtjs/sitemap',
    ['@nuxtjs/component-cache', { maxAge: 1000 * 60 * 5 }] // 5 minutes
  ],
  /*
  ** Auth config
  */
  auth: {
    redirect: {
      login: '/account/login',
      logout: '/account/login',
      callback: '/account/login',
      home: '/account/domains'
    },
    strategies: {
      local: {
        login: { url: 'auth/login', method: 'post', propertyName: 'token' },
        logout: { url: 'account/logout', method: 'post' },
        user: { url: 'auth/user', method: 'get', propertyName: 'user' }
      }
    }
  },
  /*
  ** One Signal
  */
  oneSignal: {
    init: {
      appId: process.env.ONESIGNAL_PUSH_APP_ID,
      safari_web_id: process.env.ONESIGNAL_SAFARI_WEB_ID,
      allowLocalhostAsSecureOrigin: true,
      welcomeNotification: {
          disable: true
      }
    }
  },
  /*
  ** Axios module configuration
  ** See https://axios.nuxtjs.org/options
  */
  axios: {
    baseURL: process.env.API_URL
  },
  /*
  ** Build configuration
  ** See https://nuxtjs.org/api/configuration-build/
  */
  build: {
    extractCSS: true,

    extend (config, ctx) {
      const vueLoader = config.module.rules.find((rule) => rule.loader === 'vue-loader')
      vueLoader.options.transformAssetUrls = {
        video: ['src', 'poster'],
        source: 'src',
        img: 'src',
        image: 'xlink:href',
        'b-img': 'src',
        'b-img-lazy': ['src', 'blank-src'],
        'b-card': 'img-src',
        'b-card-img': 'img-src',
        'b-card-img-lazy': ['src', 'blank-src'],
        'b-carousel-slide': 'img-src',
        'b-embed': 'src'
      }
    }
  },
  /*
  ** Sitemap configuration
  ** See https://www.npmjs.com/package/@nuxtjs/sitemap#setup
  */
  sitemap: {
    hostname: process.env.BASE_URL, // https://www.yoursite.com
    exclude: [
      '/account/recovery',
      '/account/reset',
      '/account/profile',
      '/account/domains/add',
      '/account/domains',
      '/account/monitors/add',
      '/account/monitors',
      '/help/account/introduction',
      '/help/monitors/introduction',
      '/help/domains/introduction'
    ],
    routes() {
      return getRoutes();
    },
  }
}
```

I'll also attach the template responsible for building up a blog post page _(that I've generated)_ inside of **pages/blog/_slug.vue**

```javascript
<template>
  <div>

    <section class="py-3 bg-light position-relative">
      <b-container>
        <b-row>
          <b-col cols="12" lg="8">
            <b-card no-body class="card--post">
              <div class="bg-primary card-img-top" v-if="post.image">
                <b-card-img :src="require(`~/assets/images/${post.image ? post.image : 'content/blog/default.svg'}`)" :alt="post.alt ? post.alt : 'Another Domain Monitor blog post just for you!'" top></b-card-img>
              </div>
              <b-card-body class="p-3 p-md-4">
                <b-row v-if="post.categories">
                  <b-col>
                    <h6 class="mb-n1">
                      <b-badge variant="light" v-for="(category, index) in post.categories" :key="index" class="text-lowercase mb-1 mr-1 p-1 p-md-2"># {{ category }}</b-badge>
                    </h6>
                  </b-col>
                </b-row>
                <b-row>
                  <b-col>
                    <nuxt-content :document="post" class="content content--post" />
                  </b-col>
                </b-row>
              </b-card-body>
            </b-card>
          </b-col>
          <b-col cols="12" lg="4">
            <ContentSearch class="mt-3 mt-lg-0" />
            <b-card no-body v-if="blogs" class="mt-3">
              <b-card-header class="bg-white">
                <b-row>
                  <b-col>
                    <h3 class="h5 font-weight-bold mb-0">More posts</h3>
                  </b-col>
                </b-row>
              </b-card-header>
              <b-list-group flush>
                <b-list-group-item v-for="(blog, index) in blogs" :key="index" :to="`/blog/${blog.slug}`" class="py-2 px-3">
                  <b-row>
                    <b-col cols="8">
                      <h6 class="mb-0 font-weight-bolder text-dark">{{ blog.title }}</h6>
                    </b-col>
                    <b-col class="d-flex align-items-center text-right">
                      <div class="w-100">
                        <b-button pill size="sm" type="button" variant="light" class="btn-action text-center">
                          <span class="material-icons md-18 d-flex align-items-center justify-content-around">arrow_forward</span>
                        </b-button>
                      </div>
                    </b-col>
                  </b-row>
                </b-list-group-item>
              </b-list-group>
            </b-card>
            <b-card no-body class="mt-3">
              <b-card-header class="bg-white">
                <b-row>
                  <b-col>
                    <h3 class="h5 font-weight-bold mb-0">All posts</h3>
                  </b-col>
                </b-row>
              </b-card-header>
              <b-list-group flush>
                <b-list-group-item to="/blog" class="py-2 px-3">
                  <b-row>
                    <b-col cols="8">
                      <h6 class="mb-0 font-weight-bolder text-dark">Read more of our great product news and updates</h6>
                    </b-col>
                    <b-col class="d-flex align-items-center text-right">
                      <div class="w-100">
                        <b-button pill size="sm" type="button" variant="light" class="btn-action text-center">
                          <span class="material-icons md-18 d-flex align-items-center justify-content-around">arrow_forward</span>
                        </b-button>
                      </div>
                    </b-col>
                  </b-row>
                </b-list-group-item>
              </b-list-group>
            </b-card>
          </b-col>
        </b-row>
      </b-container>
    </section>

  </div>
</template>

<script>
export default {
  layout: 'blog',
  head () {
    return {
      title: `${this.post.title} - Domain Monitor Blog`,
      meta: [
        { hid: 'og:title', name: 'og:title', content: `${this.post.title} - Domain Monitor Blog` },
        { hid: 'description', name: 'description', content: this.post.description },
        { hid: 'og:description', name: 'og:description', content: this.post.description }
      ]
    }
  },
  async asyncData ({ $content, params }) {
    const post = await $content('blog', params.slug)
                        .fetch()

    const blogs = await $content('blog')
                         .sortBy('createdAt', 'desc')
                         .limit(5)
                         .fetch()

    const [prev, next] = await $content('blog')
      .only(['title', 'slug'])
      .sortBy('createdAt', 'desc')
      .surround(params.slug)
      .fetch()

    return {
      post,
      prev,
      next,
      blogs
    }
  }
}
</script>

```

### What is Expected?

I would've thought that when building a Nuxt JS website using `npm run build && npm run generate` that there wouldn't be any duplicated URLs (supposedly indicated by search console).

### What is actually happening?

Recently, I've been publishing content on a daily basis to my Nuxt JS website. I have content written within a `/content/blog/` directory which is then built into pages when running the `npm run build && npm run generate` command. They're also then visible within the `sitemap.xml` file.

I run these commands upon every deployment _(after a new piece of content has been added)_ and then clear the cache in CloudFlare.

It's been a few weeks now, and some of the content has been indexed just fine by Google, but for some reason, the vast majority of my blog post pages are "excluded" from search console because of:

> Duplicate, submitted URL not selected as canonical

_(see attached screenshot)_

Now, I'm not sure whether this is an issue related to:

- **My configuration** (although I doubt it because some pages have been indexed just fine)
- The **Content Module**, since that's where all of my content is written and I'm sure the **Content Module** plays some role in generating static files and has some code built in terms of what's injected into each page.
- **Nuxt JS itself,** but again, I don't think so because my other pages _(which aren't blog related are just fine)_
- The **Sitemap Module**, but I wouldn't want to duplicate this Github issue twice for something that could be more likely related to the **Content Module**

In terms of suggestions, supposedly there are two ways to resolve this from my research, both of which don't seem right...

1. Set a `noindex` meta tag on the pages which are showing this exclusion notice.
2. Remove the page and redirect it to a similar page

Now, I'm trying to figure out more about why I might be getting this error, and if there's some config or something I've missed, and what might be causing my exclusion errors since I can't find anything in Search Console suggesting the root cause...

![Screenshot 2020-12-07 at 14 19 31](https://user-images.githubusercontent.com/25177538/101368243-d1284e80-389e-11eb-88dc-61fb4cc27660.png)

My primary concern here is that the number of pages _(all of my content pages)_ continue to rise and have a negative effect on my SEO.

![Screenshot 2020-12-07 at 15 41 16](https://user-images.githubusercontent.com/25177538/101371437-a809bd00-38a2-11eb-846e-d8c817dc37f8.png)

**Comment by sts-ryan-holton** [comment]
@Atinux Interesting to note, I wouldn't of thought that Google sees them as the same article, it's possible, but considering the number of pages being "excluded" is quite high, I think it goes beyond that. What was the purpose of adding the canonical tag to the Nuxt JS website? Is it on every page?

**Comment by Atinux** [comment]
It is do avoid duplicates with trailing slash.

You should check why Google is giving you similar pages for 2 different urls, since it has nothing to do with Nuxt

**Comment by sts-ryan-holton** [comment]
@Atinux I do think there's something wrong somewhere with this module since upon closer investigation, more than just my blog posts are being counted as "Duplicate, submitted URL not selected as canonical", in fact, pages like my sign in page, account creation page, terms page etc... something is wrong somewhere with one of the modules...

```
modules: [
    'bootstrap-vue/nuxt',
    '@nuxtjs/axios',
    '@nuxtjs/auth',
    '@nuxtjs/onesignal',
    '@nuxtjs/pwa',
    '@nuxt/content',
    '@nuxtjs/sitemap',
    ['@nuxtjs/component-cache', { maxAge: 1000 * 60 * 5 }] // 5 minutes
  ],
```

and as per my original point, I'm trying to figure out what one is to blame here.

![Capture](https://user-images.githubusercontent.com/25177538/101738749-8422c300-3abe-11eb-9c27-a08c94c65fce.PNG)

**Comment by Atinux** [comment]
Google does not give you more information?

**Comment by NicoPennec** [comment]
@sts-ryan-holton  About the sitemap config, you should enable the [`trailingSlash`](https://github.com/nuxt-community/sitemap-module#trailingslash-optional---boolean) option to `true`, in order to be consistent with the HTTP 301 redirects (eg. `https://domain-monitor.io/blog` => `https://domain-monitor.io/blog/`)

```js
  sitemap: {
    hostname: process.env.BASE_URL,
    trailingSlash: true,
    ...
  },
```

**Comment by sts-ryan-holton** [comment]
@NicoPennec the default option for trailing slashes is already 'false' which is what I want? I don't want a trailing slash at the end of my URLs

**Comment by sts-ryan-holton** [comment]
> Google does not give you more information?

Unfortunately not, they're incredibly generic, I wish there was more information available here for the precise reasons

**Comment by sts-ryan-holton** [comment]
Just an update, I've done the following:

- Added the `trailingSlash: true` option, purely because the pages that **are** ranking in the search engine already end with trailing slashes and [supposedly](https://www.google.com/search?q=trailing+slash+page+indexing+in+google&oq=trailing+slash+page+indexing+in+google&aqs=chrome..69i57j33i10i160l2.5400j0j9&sourceid=chrome&ie=UTF-8) Google sees a page with and without a trailing slash as two pages.

- I've added the following to my layouts, so that I'm not editing each page's `head` section:

```javascript
export default {
  head () {
    const { path } = this.$route
    const pathWithSlash = path.endsWith('/') ? path : `${path}/`
    let canonical = `https://domain-monitor.io${pathWithSlash}`
    return {
      link: [
        { rel: 'canonical', href: canonical }
      ]
    }
  }
}
```

Not sure about internal links though? All of my Nuxt JS content links, for internal links don't actually have trailing slashes on those, not sure if it'll have any impact?

I'll re-submit the `sitemap.xml` to the Search Console and see what happens over the next few days, I'm hoping the number of excluded pages declines

**Comment by davydnorris** [comment]
I had the same problem and it's all about how nuxt handles redirects between pages with and without the trailing slash.

I managed to solve mine by adding trailing slashes to all my nuxt/content pages in the sitemap, but I actually think there was a bug involving trailing slashes and it was recently fixed. I haven't had time to play with it yet but I think that may solve this issue as well

**Comment by davydnorris** [comment]
I think this was the related issue [https://github.com/nuxt/nuxt.js/issues/7934](https://github.com/nuxt/nuxt.js/issues/7934)

**Comment by sts-ryan-holton** [comment]
@davydnorris That's interesting, yet I thought that there might be something up. After implementing what I [said](https://github.com/nuxt/content/issues/674#issuecomment-742761219) I would, I've actually seen that Google has brought back these pages, and so they're not excluded any more!

Might be worth reacting to this comment for anyone else experience a similar issue, closing out this issue now then! :)

<img width="927" alt="Screenshot 2020-12-18 at 10 59 40" src="https://user-images.githubusercontent.com/25177538/102607410-29254780-4120-11eb-8610-365400e79049.png">
