### ISSUE TITLE
Codeblock on mobile view

### ISSUE THREAD

**Issue by ivanskodje** [nuxt/content#675]
### Is your feature request related to a problem? Please describe.
When we view a page with a codeblock / snippet (```) the width is prevented to fit the screen, and you will instead get a horizontal scroller on the entire page, instead of the codeblock. This will make viewing the codeblock/snippet on mobile bad.

(image shows that the box wont fit the width, but instead prevents the rest of the page from shrinking in width)

![image](https://user-images.githubusercontent.com/6776092/101391404-8cafa980-38c4-11eb-82cc-56aaacbb17f1.png)

### Describe the solution you'd like
I would like the width of the codeblock shrink along with the screen width, and show a horizontal bar on the codeblock, instead of simply stopping shrinkage on the entire page.

Perhaps this can be solved with some CSS hacking, but a out-of-the-box option would be very handy.

**Comment by ivanskodje** [comment]
I might be mistaken, as I have recently discovered that the vue page that wont shrink in width seem to shrink in width when I visit the page directly. This may indicate badly written code, which means this may be closed if that truly is the case, and that the horizontal scrollbars work for you.

**Comment by Geminii** [comment]
Hi @ivanskodje 👋 
I'm sorry but i don't understand your problem about codeblock / snippet. 
I try to reproduce on different browser and responsive. 
I got an horizontal scrollbar in each case and not effect about the width. 

Could be provide me more detail or a case to reproduce step to got the same result ?

**Comment by ivanskodje** [comment]
Closing the issue, at it appears it is not anything wrong with nuxt content, but the vue page I am adding it on. It has very strange behavior, as the issue only appears when I go to the page via  a nuxt-link, but not when I visit the page URL directly.
