### ISSUE TITLE
Customize headline anchor to fulfill accessibility requirements

### ISSUE THREAD

**Issue by LukaHarambasic** [nuxt/content#679]
### Version

* @nuxt/content: 1.5.0
* nuxt: 2.14.0

### Reproduction Link

* [Live version](https://harambasic.de/posts/almost-free-setup-for-ngos-startups-and-side-projects/)
* [Repo](https://github.com/LukaHarambasic/harambasic.de)

### Steps to reproduce

1. Display a markdown file with some headlines, e.g. [this file](https://github.com/LukaHarambasic/harambasic.de/blob/main/content/posts/almost-free-setup-for-ngos-startups-and-side-projects.md) with `<nuxt-content class="content" :document="item" />`
2. Checkout the generated HTML headlines

### What is Expected?

1. Add an option to toggle this feature
2. Customize these links, e.g. to add a text - even if it's hidden (maybe also add this text as default)

I stumbled across this issue while testing the accessibility of my website with [Wave Evaluation](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) (recommended by the [vue guidelines](https://v3.vuejs.org/guide/a11y-resources.html)):

![image](https://user-images.githubusercontent.com/22857823/101895829-574ada80-3ba8-11eb-9c6d-2fca4c1c86fe.png)

### What is actually happening?

The following HTML is generated. And I'm currently not using the anchors but even if I use them the same problem would occur.

```
<h2 id="whats-this-post-about" data-v-2f98b604="">
  <a href="#whats-this-post-about" aria-hidden="true" tab-index="-1" data-v-2f98b604="">
    <span class="icon icon-link" data-v-2f98b604=""></span>
  </a>
  What's this post about?
</h2>
```

Described problem also on https://content.nuxtjs.org/displaying:
![image](https://user-images.githubusercontent.com/22857823/101896275-05ef1b00-3ba9-11eb-9099-d01765508ca1.png)

Thank's,
Luka

**Comment by rbndelrio** [comment]
This problem lies within the `remark-autolink-headings` plugin defaults. WAVE's error is a bit of an edge case since the link will never be read by a screenreader (re: `aria-hidden` and `tabindex`), but it would most likely be satisfied by a `title` attribute.

Hypothetically, this can be fixed by overriding the default config: 
```js
//nuxt.config.js
  //...
    markdown: {
      remarkAutolinkHeadings: {
       // Option 1
       linkProperties: { ariaHidden: 'true', tabIndex: -1, title: 'Link to Section' },

       // Option 2
       content: {
        type: 'element',
        tagName: 'span',
        properties: {className: ['icon', 'icon-link']},
        children: [{type: 'text', value: 'Link to Section'}]
       },
      }
    }
  //...
```

Up to this point nuxt-content has never changed remark/rehype plugin defaults, I'm not sure whether that convention would change now.

**Comment by LukaHarambasic** [comment]
> This problem lies within the `remark-autolink-headings` plugin defaults. WAVE's error is a bit of an edge case since the link will never be read by a screenreader (re: `aria-hidden` and `tabindex`), but it would most likely be satisfied by a `title` attribute.
> 
> Hypothetically, this can be fixed by overriding the default config:
> 
> ```js
> //nuxt.config.js
>   //...
>     markdown: {
>       remarkAutolinkHeadings: {
>        // Option 1
>        linkProperties: { ariaHidden: 'true', tabIndex: -1, title: 'Link to Section' },
> 
>        // Option 2
>        content: {
>         type: 'element',
>         tagName: 'span',
>         properties: {className: ['icon', 'icon-link']},
>         children: [{type: 'text', value: 'Link to Section'}]
>        },
>       }
>     }
>   //...
> ```

Thank's for pointing this out! <3 

> Up to this point nuxt-content has never changed remark/rehype plugin defaults, I'm not sure whether that convention would change now.

I agree, but maybe it's worth mentioning it in the docs?

Thanks,
Luka
