### ISSUE TITLE
Content excerpt support

### ISSUE THREAD

**Issue by nahokomatsui** [nuxt/content#68]
### Describe the solution you'd like

Please provide a way to fetch plain content body texts (not the body object of the current fetching result), in order to display excerpt on pages such as content list view.
Feature like [Content Excerpt of VuePress](https://vuepress.vuejs.org/theme/writing-a-theme.html#content-excerpt) would be awesome.

### Describe alternatives you've considered

Having `<nuxt-content>` prop for displaying excerpt and other selected content properties would be useful too.

**Comment by benjamincanac** [comment]
@nahokomatsui Have you tried to use [remark-excerpt](https://github.com/manovotny/remark-excerpt)?

You can extend plugins in @nuxt/content: https://content.nuxtjs.org/configuration#markdownplugins

**Comment by Atinux** [comment]
We could support it I guess @benjamincanac if ` <!— more —>` is in the content.

Then we would need to have `<nuxt-content :document=“doc” excerpt>` to display `doc.excerpt`

**Comment by nahokomatsui** [comment]
Thank you for your considerations.

For your information, I tried registering remark-excerpt plugin following @benjamincanac 's advice on my example repo: https://github.com/nahokomatsui/nuxt-content-excerpt

Just adding the plugin to configuration causes omitting not-excerpt contents from the all fetched contents.
In my example case I want it to show the entire contents on article detail page (`/articles/_slug.vue`) but it is not possible.

I also tried parsing contents with remark-excerpt inside [content:file:beforeInsert hook](https://content.nuxtjs.org/advanced#contentfilebeforeinsert) but it didn't work well either.
The plugin does not seem to support parsing the tree of the object the hook receives as an argument.

Therefore It would be appreciated if it is supported inside Nuxt Content module with @Atinux 's way.

**Comment by benjamincanac** [comment]
@nahokomatsui Have you tried using excerpt inside `content:file:beforeInsert` hook using the `text` variable instead of the `body`?

**Comment by nahokomatsui** [comment]
@benjamincanac I tried it on [this commit](https://github.com/nahokomatsui/nuxt-content-excerpt/commit/9b58ffe26105ee220a7bbf222052dd7d3a11f0d4) but it makes excerpt value undefined.
I think the plugin's transformer expects HTML node tree, not markdown text.
https://github.com/manovotny/remark-excerpt/blob/master/index.js#L15

**Comment by benjamincanac** [comment]
@nahokomatsui Until we support it, you could do something like:

```js
const remark = require('remark');
const excerpt = require('remark-excerpt');

...

'content:file:beforeInsert': (document) => {
  document.excerpt = await remark()
    .use(excerpt)
    .process(document.text)
}
```

**Comment by nahokomatsui** [comment]
@benjamincanac Sorry for misunderstanding.
On the [latest commit](https://github.com/nahokomatsui/nuxt-content-excerpt/commit/1e55340f051d1665711c93f999d3ea3fc4d44cca#diff-a216f5c067bcf89f670f6d5d950695b8) I succeeded in retrieving only plain excerpt texts using remark plugin properly and retext-stringify plugin additionally.
This workaround should be enough until it is officially supported in a more integrated way. Thank you.

**Comment by mathieunicolas** [comment]
My "101" solution : I manually add a new field in the YAML, which contains a "résumé", or the first paragraph of my doc.

**Comment by imlautaro** [comment]
I solved the problem just with this code:
```
const articles = await $content('articles').fetch()
articles.map((article) => {
	article.excerpt = { body: article.excerpt }
})
return { articles }
```
Then you can use `<nuxt-content :document="article.excerpt" />`.
