### ISSUE TITLE
[docs-theme] Code groups global/page section

### ISSUE THREAD

**Issue by jsbroks** [nuxt/content#683]
### Is your feature request related to a problem? Please describe.

It's annoying to have to click the code block label for every code block shown on the page.

As commonly seen in other documentation such as stripe and google cloud docs, when a user selects a code block type, it converts all code blocks on the page to be of the same label if they exist.

### Describe the solution you'd like

Selecting a code block label will make all labels the same if they exist in other code blocks.

**Comment by farnabaz** [comment]
Hey there 👋

@nuxt/content-theme-docs is moving away and will not get any updates, very soon we will open-source Docus, a brand new theme based on Nuxt 3, and Content v2 with lots of fixes, improvements, and new features.

I’m closing this issue in favor of the new docs theme. Keep an eye on  #726 for updates

I will add this to the enhancements list for Docus.
