### ISSUE TITLE
Missing documentation on how to use `excerpt` in page

### ISSUE THREAD

**Issue by kylewelsby** [nuxt/content#686]
It is not explicitly clear on the documentation of how to consume the `excerpt` on pages. 

It would be idea to update the documentation with a solution to this. 

Current work-around solution:

```html
<nuxt-content
  :document="{ body: page.excerpt }"
>
```

### Version
@nuxt/content: 1.11.0
nuxt: any

### Reproduction Link
https://codesandbox.io/s/cool-frost-9zp9x?file=/pages/_slug.vue

### What is Expected?
Markdown JSON AST rendered to page.

### What is actually happening?

If `body` is not defined, nothing will render.  The above code is a workaround for now.

**Comment by kylewelsby** [comment]
I intend to improve the docs,

But I also think the suggestion is rather fine too to make it a well-rounded feature. 👍

**Comment by romain130492** [comment]
how can we hide the except on article page ? or at least to identify its an excerpt ? @benjamincanac
