### ISSUE TITLE
Links are always broken somewhere

### ISSUE THREAD

**Issue by bmulholland** [nuxt/content#716]
### Version
https://github.com/nuxt-community/auth-module

I'm helping out with the auth module, and putting special focus into its docs, which need a lot of love.

I'm finding it's ambiguous which link path to use for those docs:

* If you're browsing on github, then you'll need relative links with ".md" in the path.
* If browsing on the docs site, then you cannot use ".md".
* If browsing on Github, then paths should be relative (e.g. "../api/auth")
* If browsing on the docs site, then paths _cannot_ be relative, because relative paths break when you have a trailing slash, and the trailing slash is inconsistently present (see below).

If you browse using the sidebar, then no trailing slash is applied. But, at least on Firefox, if you load the URL directly, or refresh the page, then a trailing slash is added. That slash indicates a directory, which adds another layer for relative links to traverse. For example, the "cookie scheme" link will work if you go to https://auth.nuxtjs.org/schemes/local, but not work if you go to https://auth.nuxtjs.org/schemes/local/

**Comment by farnabaz** [comment]
Hey there 👋 

`@nuxt/content-theme-docs` is moving away and will not get any updates, very soon we will open-source Docus, a brand new theme based on Nuxt 3 and Content v2 with lots of fixes, improvements, and new features. 

Closing this issue in favor of the new docs theme. Keep an eye on #726 for updates
