### ISSUE TITLE
Docs Theme: Support for categories / links in NavBar?

### ISSUE THREAD

**Issue by dobomode** [nuxt/content#718]
Does `Nuxt Content`'s `Doc theme` support categories / links in the NavBar similar to how the default theme in `VuePress` works? This is very useful in case you are building large docs content, where fitting everything in the Sidebar would become overwhelming.

For example, with category / link support in the NavBar, you could build one section for `Guide`, another for `API Reference`, etc., and have separate versions of the Sidebar for each.

**Comment by Geminii** [comment]
> Does `Nuxt Content`'s `Doc theme` support categories / links in the NavBar similar to how the default theme in `VuePress` works? This is very useful in case you are building large docs content, where fitting everything in the Sidebar would become overwhelming.

Hi @dobomode 👋 
It's not possible for the current version of doc theme, but new one will permit to many things like supercharge default components (like Navbar etc). 

> For example, with category / link support in the NavBar, you could build one section for Guide, another for API Reference, etc., and have separate versions of the Sidebar for each.

You can create category and put each page on it directly but not create sub-category. Or you want to do something else ?

**Comment by dobomode** [comment]
> Hi @dobomode 👋

Hi @Geminii 
Thanks for the quick response.

> It's not possible for the current version of doc theme, but new one will permit to many things like supercharge default components (like Navbar etc).

This would be great. Looking forward to having this functionality.

Cheers.
