### ISSUE TITLE
Crawler does not work during nuxt generate when ssr config property is set to false

### ISSUE THREAD

**Issue by CodeRevver** [nuxt/content#728]
### Version
    "@nuxt/content": "^1.11.1",
    "nuxt": "^2.14.12"

### Reproduction Link

https://github.com/CodeRevver/nuxt-crawler-bug

### Steps to reproduce
1. Clone the repo: https://github.com/CodeRevver/nuxt-crawler-bug
2. Install packages and run ````npm run generate````
3. Evaluate the dist folder and note that crawler does not pick up the blog posts. 

![image](https://user-images.githubusercontent.com/5285928/105578785-87c28e80-5d7a-11eb-9cbe-09d85c7e498d.png)

However it will work when I enable SSR in the nuxt.config.js as per below:
````
  ssr: true// Enable Server Side rendering
````

Then run ````npm run generate```` again and note that the crawler picks up the blog posts.

![image](https://user-images.githubusercontent.com/5285928/105578830-e0922700-5d7a-11eb-891b-13443386db3e.png)

### What is Expected?
````npm run generate```` should crawl the blog posts during build even when ssr is turned off in the nuxt.config.js

### What is actually happening?
````npm run generate```` is not crawling my blog posts when ssr is disabled in nuxt.config.js.  This is causing 404's when a user refreshes the page on a blog post. 

If this is intended functionality, it should be more present on the docs because I can't find any information on it there.

**Comment by danielroe** [comment]
@CodeRevver That is the behaviour I would expect. I would always recommend having `{ ssr: true }` for static sites unless you have a very good reason not to. (Otherwise you lose most of the benefits of static sites.)

PRs to the docs are always welcome though.
