### ISSUE TITLE
Redirect and Not Found page

### ISSUE THREAD

**Issue by Shugar** [nuxt/content#730]
Hey!

I have following folder structure: 
![image](https://user-images.githubusercontent.com/5647725/105764580-34159800-5f68-11eb-8e7e-b65c0a27e06a.png)

![image](https://user-images.githubusercontent.com/5647725/105764666-4e4f7600-5f68-11eb-8734-f28c93b031a4.png)

Everything works perfectly, but I have two cases which are not working.

Two questions:
1. How can I redirect to another page if slug does not found? For example: I changed a slug, but already pushed link to blog outside the app. When somebody opens old link it would not show anything, because slug is changed, so I want to redirect to another page in specific cases.
2. When I put anything into slug (like localhost:3000/blablabla) it's trying to find "blablabla" in my content, but It should show Not Found Page because there is no page for "blablabla". Right now plugin is trying to find "blablabla" and drops an error, but I have "error" page in layouts as explained in Nuxt documentation. How can I show the error page instead of letting plugin searching for slug? Screenshot below: 

![image](https://user-images.githubusercontent.com/5647725/105764980-c453dd00-5f68-11eb-8464-d6f84b2402c8.png)

Thank you!

**Comment by Shugar** [comment]
Looks like that this issue is also related to one of my questions https://github.com/nuxt/content/issues/622

**Comment by Shugar** [comment]
Hey @Atinux 

Thank you for your answer.

Just tried to use one of your examples, but got the same result as before:
![image](https://user-images.githubusercontent.com/5647725/105841521-cc059700-5fe5-11eb-8409-2c216efedc8a.png)
![image](https://user-images.githubusercontent.com/5647725/105841543-d3c53b80-5fe5-11eb-8a24-2c4754a2f613.png)

**Comment by Atinux** [comment]
My bad, you need to wrap you $content with try catch and use error() on the catch block

**Comment by NozomuIkuta** [comment]
FYI: here is [how theme docs handles cases where no document is fetched](https://github.com/nuxt/content/blob/a6274e482947dc177c795cc00867aa266bd91ddb/packages/theme-docs/src/pages/_.vue#L51-L69).

**Comment by Shugar** [comment]
Worked! Thank you for answers.
