### ISSUE TITLE
Search through multiple fields?

### ISSUE THREAD

**Issue by 684efs3** [nuxt/content#731]
When fetching content, is there a way to search through multiple fields that you specify? For example, I want to search through two specific fields, but it looks like I can only search through one field.

**Comment by Billybobbonnet** [comment]
You can use the [default search indexes](https://content.nuxtjs.org/configuration/#fulltextsearchfields) to search multiple fields. However, if you want to set multiple searches with multiple fields, you can't afaik. Either default & multiple, either a single search field.
