### ISSUE TITLE
Fetch instead of asyncData in child component

### ISSUE THREAD

**Issue by sakurasato** [nuxt/content#734]
Hi. I try to understand how fetch is working in the documentation but I'm unable to get data that is available in $content like **title**, **slug**, **body** when in component. I create [stackoverflow question here](https://stackoverflow.com/questions/65907990/how-do-you-use-components-with-data-from-nuxt-content-module), if someone can help me please I really be appreciating. Thank you ❤️

**Comment by sakurasato** [comment]
Hi @Atinux! Thank you for helping me ☺️ 

I update the codebox you send me it is here https://codesandbox.io/s/boring-jepsen-v623f

To explain, I try to get a component that goes in content module pages and regular Nuxt pages but can't retrieve data with Fetch inside component I thinks.

**Comment by danielroe** [comment]
@sakurasato What is `this.params` meant to be? It's undefined.

**Comment by sakurasato** [comment]
Hi @danielroe! I thought maybe I needed to have params as argument because when I call only `this.$content().fetch()` I think it gives me an array of the pages but what I want is the things inside each page title, body, slug and because Im looking for the information from specific page I thinks the this.params is needed. I try with your solution now `this.$route.params` and see if it works. Thank you so much Daniel!

**Comment by sakurasato** [comment]
I change `component/Form.vue` to

```
<template>
  <div>
    <p>Form component</p>
    <!-- I think works for `_slug` -->
    <p v-if="page">{{ page.title }}</p>
    <!-- I think works for all non content module pages `contact.vue` -->
    <p v-else>{{ title }}</p>
  </div>
</template>

<script>
export default {
  async fetch() {
    this.page = await this.$content(this.$route.params).fetch();
  },
  data() {
    return {
      page: {},
    };
  },
};
</script>
```
but still no works. I have this right?

**Comment by danielroe** [comment]
@sakurasato Check out the API documentation - https://content.nuxtjs.org/fetching.

**Comment by sakurasato** [comment]
Ok I read again. Thank you!
