### ISSUE TITLE
Copy paste code blocks

### ISSUE THREAD

**Issue by gemmadlou** [nuxt/content#74]
### Copy paste code blocks

The syntax highlighting is brilliant. I didn't realise it came part of @nuxt/content. But I also would love to be able to copy-and-paste the syntax with a single click. Maybe it's beyond the scope of what the module does.

In fairness, I have no thoughts on the best way to implement this but I'd be happy to investigate if you think it's a worthwhile addition to the library.

**Comment by benjamincanac** [comment]
Hey @gemmadlou 

This module uses PrismJS on server-side, to extend it you can use it client-side and use the [Copy to Clipboard](https://prismjs.com/plugins/copy-to-clipboard/) prism plugin and do something like that in your page:

```js
import Prism from 'prismjs'
import 'prismjs/plugins/copy-to-clipboard/prism-copy-to-clipboard.js'

export default {
  mounted () {
    Prism.highlightAll()
  }
}
```

**Comment by gemmadlou** [comment]
That sounds more than reasonable. Thanks @benjamincanac . I'm happy for this to close.

**Comment by tommypratama** [comment]
I just tried, but the clipboard doesn't show up in the code block in the markdown.

*plugins/prism.js*
```js
import Prism from 'prismjs'
import 'prismjs/plugins/copy-to-clipboard/prism-copy-to-clipboard.js'
export default Prism
```

*pages/blog/_slug.vue*
```js
<script>
import Prism from "~/plugins/prism";

export default {
  mounted() {
    Prism.highlightAll();
  },
};
</script>
```

*nuxt.config.js*
```js
purgeCSS: {
   whitelistPatternsChildren: [/token$/],
},
plugins: ["~/plugins/prism"],
```

**Comment by idesignzone** [comment]
You could convert the markdown to a string and use [useClipboard](https://vueuse.org/core/useClipboard/)


```
<template>
   <ContentQuery path="YOUR_PATH" find="one" v-slot="{ data }">
      <div @click="copyMarkdownContent">copy</div>
      <ContentRenderer :value="data">
           <ContentRendererMarkdown class="clipboard" :value="data" ref="clipboardContent" />
      </ContentRenderer>
   </ContentQuery>
</template>

<script setup>
const { copy } = useClipboard()

function copyMarkdownContent() {
  const markdownElement = document.querySelector('.clipboard');
  const markdownText = markdownElement?.innerText || ''; // Get the text content from the rendered markdown
  if (markdownText) {
    copy(markdownText) // Copy the markdown content to the clipboard
      .then(() => {
        alert('Markdown content copied to clipboard');
      })
      .catch(() => {
        alert('Failed to copy content');
      });
  }
}
</script>
```
