### ISSUE TITLE
How to enable copy button on a codeblock?

### ISSUE THREAD

**Issue by Croodo** [nuxt/content#741]
How can I enable a copy button on a code block? 
Also, how can I pass actual data on the button from that code block? (Suppose I have two code block on the same page.

**Comment by NozomuIkuta** [comment]
@Croodo 

If you are using theme docs, such feature is enabled by default, isn't it?

If you are using Nuxt Content module in your own app, you can refer to [how theme docs provide the feature](https://github.com/nuxt/content/blob/dev/packages/theme-docs/src/components/app/AppCopyButton.vue).
Or, you can refer to the dependency directly: [clipboard.js](https://www.npmjs.com/package/clipboard).

I hope this helps you.

**Comment by Croodo** [comment]
I was creating my custom theme.
Thanks for the doc link problem solved.

**Comment by Croodo** [comment]
> @Croodo
> 
> If you are using theme docs, such feature is enabled by default, isn't it?
> 
> If you are using Nuxt Content module in your own app, you can refer to [how theme docs provide the feature](https://github.com/nuxt/content/blob/dev/packages/theme-docs/src/components/app/AppCopyButton.vue).
> Or, you can refer to the dependency directly: [clipboard.js](https://www.npmjs.com/package/clipboard).
> 
> I hope this helps you.

Right now I can show the clipboard through adding the component on my markdown file like <copy-button></copy-button>. Can you tell me how can I configure it on every code block by default?

**Comment by NozomuIkuta** [comment]
@Croodo 

Here is how theme doc attaches copy button to every code block ([link to code](https://github.com/nuxt/content/blob/master/packages/theme-docs/src/pages/_.vue#L94-L102)).

By the way, implementation of theme docs is worth taking a look at once ([link to package](https://github.com/nuxt/content/tree/master/packages/theme-docs)).
It's just an normal Nuxt app (no fear!), and we can find get much inspiration or even answers to our questions.

Good luck! 👍 

---

Let me close this issue with this message.
