### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by sts-ryan-holton** [nuxt/content#744]
### Version
@nuxt/content: v1.11.1
nuxt: v2.14.12

### Reproduction Link

- https://domain-monitor.io/blog/how-to-get-more-high-quality-backlinks/

### Steps to reproduce

1. Run page through [Page Speed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdomain-monitor.io%2Fblog%2Fhow-to-get-more-high-quality-backlinks%2F)
2. Try running page through Lighthouse (Incognito window)

### What is Expected?

I would've thought the performance of a single blog page would be better in full static mode serving HTML from the Content module.

### What is actually happening?

I'm looking through the list of "to dos" that I need to do for my website, and one of those items is investigating and ideally improving the performance on my Nuxt JS website.

This issue is primarily linked to the content module since it provides 90% of the content on my site, and according to both Lighthouse, and Google Page Speed Insights, the performance of these web pages isn't as good as it can be.

What I'm trying to figure out, is what settings can I turn on, or remove related to this module to improve it's performance and efficiency.

![lighthouse](https://user-images.githubusercontent.com/25177538/106653121-4b6b0b80-658e-11eb-923c-2372e2283457.PNG)

![insights](https://user-images.githubusercontent.com/25177538/106653193-62116280-658e-11eb-99dc-b27bcbba8cca.PNG)

**Comment by AustinGil** [comment]
If you drill down into the lighthouse report, most of the issues I see are with things Nuxt content has no control over. The top issues are around image sizes and formats. After that it's 3rd party resources from OnSignal, Reddit, Google Fonts, Mailchimp, AddThis, Google Analytics, etc.

**Comment by AustinGil** [comment]
Here's what Lighthouse reports as opportunities. It's mostly around images and 3rd party JS, so I would probably start there. 

![image](https://user-images.githubusercontent.com/4879075/106654880-839e2a00-654d-11eb-8969-2551e74276ea.png)

It looks like most of the content is limited to 600px wide, but several of the images are much larger than that. The largest is 2862px wide and over 300kb. Serving the correct sized images (and optimized) could be a big improvement.

**Comment by danielroe** [comment]
@AustinGil is right - and the good news is that soon we'll have a Nuxt component to make it very simple to follow best practice for images.
