### ISSUE TITLE
CodeBlock filename config for highlight.js

### ISSUE THREAD

**Issue by Croodo** [nuxt/content#745]
How can I pass filename from a codeblock to the wrap of highlight.js 

```js
import highlightjs from 'highlight.js'
const wrap = (code, lang) => `<pre><code class="hljs ${lang}">${code}</code></pre>`

export default {
  modules: ['@nuxt/content'],

  content: {
    markdown: {
      highlighter(rawCode, lang) {
        if (!lang) {
          return wrap(highlightjs.highlightAuto(rawCode).value, lang)
        }
        return wrap(highlightjs.highlight(lang, rawCode).value, lang)
      }
    }
  }
}
```

**Comment by NozomuIkuta** [comment]
@Croodo 

`content.markdown.highlighter` receives 4 arguments, 3rd of which is an object containing file name.
You can see more details in documentation ([link to the part](https://content.nuxtjs.org/configuration#markdownhighlighter)).

For your reference, here is implementation of theme docs' prism highlighter ([link to code](https://github.com/nuxt/content/blob/master/packages/content/parsers/markdown/handlers/code.js)).
