### ISSUE TITLE
Nuxt/Content generates invalid headers ids when header contains diacritics/accents

### ISSUE THREAD

**Issue by snajjar** [nuxt/content#748]
The following markdown:

    ### Prêter en échange d'intérêts

will generate a h3 header with an invalid id (as HTML ids can't contain accents or diacritics)

    <h3 id="prêter-en-échange-dintérêts" data-v-f58a9f50="">Prêter en échange d'intérêts</h3>

That makes it impossible to target with in-page links, like `#prêter-en-échange-dintérêts`

### Version
@nuxt/content: v1.11.1
nuxt: v2.14.12

### What is Expected?

Nuxt should [normalize id strings](https://stackoverflow.com/questions/990904/remove-accents-diacritics-in-a-string-in-javascript), to generate valid html ids.

This is possible with the *normalize* method of the String class, like in the following example from the above stackoverflow link:

    const str = "Crème Brulée"
    str.normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    > "Creme Brulee"

### What is actually happening?

Generated headers id are not HTML-valid when headers contains diacritics/accents.

**Comment by leandromatos-hotmart** [comment]
Duplicate #702

**Comment by NozomuIkuta** [comment]
@leandromatos-hotmart 

Thank you for reporting duplication.
Let me close this ticket.
