### ISSUE TITLE
Plugins not installed?

### ISSUE THREAD

**Issue by Strahinja** [nuxt/content#75]
Possible @nuxt/content bug. Could also be related to [`remark`](https://github.com/remarkjs/remark) or [`remark-twemoji`](https://github.com/madiodio/remark-twemoji) and [`remark-frontmatter`](https://github.com/remarkjs/remark-frontmatter).

Related: https://github.com/madiodio/remark-twemoji/issues/8, https://github.com/remarkjs/remark-frontmatter/issues/13

### Version
@nuxt/content: latest (1.2.0)
nuxt: latest (2.12.2)

### Reproduction Link
https://github.com/Strahinja/remark-bug

### Steps to reproduce
```
$ yarn install
$ yarn generate
```

### What is Expected?
No warnings.

### What is actually happening?
```
WARN  remark-twemoji is not installed
WARN  remark-frontmatter,yaml is not installed
```

**Comment by Strahinja** [comment]
Update: the issue with `remark-twemoji` is [resolved by installing `twemoji`](https://github.com/madiodio/remark-twemoji/issues/8#issuecomment-636511097). As stated in the linked comment, it would be nice if this warning was more clear.

`remark-frontmatter` part of the bug is still unresolved.

**Comment by ChristianMurphy** [comment]
For remark-frontmatter, the issue is in nuxtjs/content

Nuxt content currently does not support settings in remark plugins
https://github.com/Strahinja/remark-bug/blob/110d158f46814454ed3b9eda0e40df5e1aa739aa/nuxt.config.js#L50
https://github.com/nuxt/content/blob/0e217dc20d742c0531c69a829e007ab7e9673086/lib/parsers/markdown/index.js#L67-L75

That is why the error is `remark-frontmatter,yaml is not installed` instead of separating the plugin from the settings it concatenated them together, creating an invalid package name.

**Comment by ChristianMurphy** [comment]
Also based off the code, there may be an undocumented way to do this already
```diff
  content: {
    markdown: {
      plugins: [
        'remark-twemoji',
-        ['remark-frontmatter', 'yaml'],
+       'remark-frontmatter'
      ],
+    frontmatter: "yaml"
    },
  },
```

**Comment by Strahinja** [comment]
@ChristianMurphy, thanks for the workaround. I think I'll take a look at that code and possibly try to come up with a PR.

**Comment by benjamincanac** [comment]
Hey,

Plugins can be configured as described here: https://content.nuxtjs.org/configuration#markdown.

> Each plugin is configured using its name in camelCase: remark-external-links => externalLinks.

However, a PR is actually ongoing to refactor plugins, so you might be able to configure them this way.

**Comment by benjamincanac** [comment]
@Strahinja If you're trying to get data using `remark-frontmatter` plugin, @nuxt/content already does this by default: https://content.nuxtjs.org/writing#front-matter

**Comment by Strahinja** [comment]
Thanks, it seems I missed that part of the documentation. I'm migrating from frontmatter-markdown-loader with markdown-it, so I thought that including that package explicitly was needed. Still, this warning message is misleading and comes up as inaccurate when the package is actually installed. Looking forward to the next iteration of @nuxt/content! :)
