### ISSUE TITLE
Fetching content inside fetch() / Whole database injected

### ISSUE THREAD

**Issue by fabianwohlfart** [nuxt/content#754]
### Version
@nuxt/content: v1.11.1
nuxt: v2.14.12

### Reproduction Link
https://github.com/fabianwohlfart/test__content-nuxt-fetch-async-data

### Steps to reproduce
run generate
run start
go to page-a
reload page-a

### What is Expected?
fetch() produces code splitted payloads / fetch() payload is merged with the page payload

### What is actually happening?
whole content database is loaded
![Ohne Titel 8](https://user-images.githubusercontent.com/15716389/107336212-21977480-6ab9-11eb-9cb6-46a5e5a317f0.jpg)

so i am not really sure if its a bug,
but its definitely nothing i thought would happen.

within the @nuxt/content docs getting data from the database is always done in asyncData(), this works well at the page level.
if you fetch data at the component level with fetch(), the whole database.json is inserted by nuxt. this does not scale well...

how do you fetch data from the database inside components, for example if you want to build a navigation or a footer? is there a best practice for this? (— i thought about making »database« routes inside /pages/ from which i will manually fetch the payload from within the components... which feels a bit over complex for what i want to achieve)
whats the mechanic behind it, is it somewhere documented?

**Comment by fabianwohlfart** [comment]
@danielroe Sorry, this is not the problem. I updated the example with more content to make it more clear:
The problem is that I only fetch Page A and Page B `.where({ nav: { $eq: true }})`, but the whole database with all pages (C, D, E, F...) is loaded. Please reopen.

**Comment by fabianwohlfart** [comment]
Oh that is interesting. So if I add a trailing slash and refresh »Page A« the DB is **not** loaded initally, but when I click on the link to the other page »Page B« (also with a trailing slash) the DB is still loaded. Is there anything I can do to prevent this? From my understanding, and I just rechecked it, all the data is available in the payload of the page, so i dont get why it loads the whole DB separately?!

**Comment by fabianwohlfart** [comment]
I guess Nuxt doesn't need to know, because it can simply lookup the payload data of the current page. Its written to both, no?
Anyways, thanks for your time, and I will recheck in 2.15.

**Comment by fabianwohlfart** [comment]
Dear all and @danielroe,
I updated to nuxt 2.15 and content 1.13.1, but the problem still exists.
I updated my example repo to show the error.

Here is what happens:
The problem occurs if we have a layout-level component and a page-level component.
The page-level component does not get fetched correctly if we start at page which does not contain this page-level component and navigate to its containing route: its missing some pages.
(e.g from page-b.vue / _slug.vue to index.vue)
To prevent the missing pages we can use this.$fetch() to refetch the content.
But this.$fetch() will load the whole database, and not only the content from async fetch ()

Is there a solution to this problem:
a) fetching on page load
b) $fetch() only loading the needed payload?

**Comment by fabianwohlfart** [comment]
All routes are generated.
![nuxt-fetch](https://user-images.githubusercontent.com/15716389/107949156-21094d00-6f95-11eb-9722-670922b9a8c6.jpg)

Not sure what you mean by this questions. I expected that fetch() will merge into the pages payload.js, like asyncData(), no? 
And then a this.$fetch() would lookup this pages payload for the fetch content.
Because the layout-level component works fine. its the page-level component that behaves strange.
And therefor is a route to let fetch _know_ where it is.

Or how would you add data from nuxt/content to a component?

**Comment by danielroe** [comment]
@fabianwohlfart Sorry, I misunderstood your earlier comment. 🙏  However, I can't replicate the issue you're talking about with [your codesandbox](https://codesandbox.io/s/dry-tree-8wn2g?file=/package.json).

**Comment by fabianwohlfart** [comment]
Thanks for the sandbox. Actually I can replicate it with it:

1. Load /
2. See navigation of all pages A – F
3. Click a page link
4. Click back
5. See that the navigation only holds pages A + B (not empty, not all, but only two?!)
6. Reload / to see all navigation items A – F again

Do I miss anything?
I think it loads the wrong fetch from the fetch array?
fetch[0] = two items
fetch[1] = 6 items

I think I just answered my whole issue with this.
**Use a fetchKey**

**Comment by fabianwohlfart** [comment]
This is the solution.

But also I think an improvement would be that nuxt automatically gives a fetchKey after the components name, if its not set by the dev, no?

And also I dont understand why it takes the first fetch item and not the second...
