### ISSUE TITLE
Images wrapped in <p> tags

### ISSUE THREAD

**Issue by robert-moore** [nuxt/content#76]
### Version
@nuxt/content: v1.2.0
nuxt: v2.12.0

### Reproduction Link
https://codesandbox.io/s/nuxtcontent-demo-pfror?file=/content/index.md

### Steps to reproduce
Any markdown with an image
```
![](https://cdn-images-1.medium.com/max/1280/1*tBJ7iUluy2Yhobd6qGUKQA.png)
``

### What is Expected?
I would not expect markdown images to be wrapped in paragraph tags

### What is actually happening?
Markdown images are wrapped in <p> tags.

**Comment by thely** [comment]
This is an aspect of Markdown, not nuxt/content. Content uses remark plugins to process Markdown text - it looks like there's a plugin called [remark-unwrap-images](https://github.com/remarkjs/remark-unwrap-images) that does exactly what you're looking for.

**Comment by robert-moore** [comment]
Thanks @thely 

For reference on adding remark plugins

`yarn add remark-unwrap-images` or `npm i remark-unwrap images`

And then add this to your nuxt.config.js

```
content: {
  markdown: {
    plugins: ['remark-unwrap-images']
  }
},
```

**Comment by shash7** [comment]
Does this work? I'm using the remark-unwrap-images plugin and my img tag is still wrapped in a p tag.

**Comment by robert-moore** [comment]
@shash7 yeah it's working for me

**Comment by shash7** [comment]
Strange. Its not working for me.

**Comment by thely** [comment]
@shash7 , what version of nuxt/content are you using? Support for Remark plugins was only added in 1.2.0, which came out last week.

**Comment by shash7** [comment]
I'm using 1.0.0
Guess that explains the issue.

**Comment by Komputerchik** [comment]
Strange. Its not working for me.
