### ISSUE TITLE
Content module is blocking startup for parsing

### ISSUE THREAD

**Issue by pi0** [nuxt/content#767]
Modules can return a promise or be async in order to prepare nuxt context but not for other runtime operations since it makes `nuxt dev` stuck until initial parsing is done. (nuxtjs.org for instances takes 9,2 seconds on a corei7 CPU to parse and during this time we are blocking build)

I think we can move [database.init](https://github.com/nuxt/content/blob/2037ee87edc39018646f12f2d02ece1d2f80c7c1/packages/content/lib/index.js#L112) to a parallel promise instead of awaiting in main body. (not sure if any internals need to be updated to ensure init is done or not)

Also would be nice if in future versions doing parse off-thread (using node workers) to avoid blocking even-loop.

**Comment by ManUtopiK** [comment]
Sometimes I got this issue. I solve it by deleting the folder `node_modules/.cache`

**Comment by Atinux** [comment]
This is not the case with content v2 anymore. For v1 I don't think we will solve that issue (lack of time).
