### ISSUE TITLE
Missing/default content

### ISSUE THREAD

**Issue by jbnv** [nuxt/content#77]
### Is your feature request related to a problem? Please describe.

I'm using Nuxt+Content to develop an encyclopedia for my fiction project. Each character can have several MD files. Many minor characters have folders but no or little content, so a lot of these files just don't exist.

My character information view attempts to get some of these files from the API. When the file is missing, that results in a 404 from the API and an error line in devtools. My development standard is to have my console free of errors. However, I haven't found any way to either suppress the errors or have the API return some default content. 

### Describe the solution you'd like

**Part 1.** Recognize if a folder contains a `_default` folder. If it does, the data in that file can be served for paths into its sibling folders that don't have the requested file.

So for example, take this directory structure:

```
characters
|- _default
|- |- backstory.md
|- luke_skywalker
|- |- backstory.md
|- lando_calrissian
|- jabba_the_hut
```

Since `characters/lando_calrissian` doesn't have a `backstory.md` file, the call `$content('characters','lando_calrissian','backstory')` would fail. But with this feature, it would pull the `backstory.md` file from `characters/_default` and serve that instead.

**Part 2.** If a folder contains a `_missing.json` file, then an attempt to retrieve a file from that folder or subfolders that doesn't exist would serve the `_missing.json` file instead. This would at least let the path return *something*, and the consumer would decide for itself what to do with it.

So, given the example above, `$content('characters','lando_calrissian','backstory')` could try the following paths:

1. characters/lando_calrissian/backstory
1. characters/_default/backstory
1. characters/lando_calrissian/_missing
1. characters/_missing
1. _missing

Of course, both of these methods would be configurable. 

### Describe alternatives you've considered

I suppose that I could refactor my code and get all of the data for the character as one object, and parse it accordingly. However, I have several different components, and this assumption may not hold for all of them.

**Comment by TheLearneer** [comment]
I am not sure if the dev team will consider this idea, but the thing is you can already check for fallbacks..

```js
// This will return an empty array if no file is found in the specified path...
const backstory = await $content('characters')
  .where({ path: 'lando_calrissian/backstory' })
  .fetch();

// You can also do the same by providing a specific front matter id to the file
const backstory = await $content('characters')
  .where({ id: 'lando_calrissian/backstory' }) // Provide your unique id combo
  .fetch();
```

In the above usage if the specific file is found, it will be returned else `backstory` will be an empty array. _Backstory is always an array..._

Further if you like to have a fallback file fetched you can simply do another fetch to the default file...
```js
const backstoryFallback = await $content('characters')
  .where({ path: '_default/backstory' })
  .fetch();
```

---

If you don't like the idea of fetching the content twice for the fallback handling you can also do this:
```js
const backstories = await $content('characters').fetch();

// Then filter them as you like / or find the specific one you want
const backstory = backstories.find((story) => {
  return ['/lando_calrissian/backstory', '/_default/backstory'].includes(story.path);
})
```
The example above will try to find `/lando_calrissian/backstory` file first, but if it doesn't exists, it will fetch and return `/_default/backstory`. If it is also not found, it will be empty array once again.
I am not sure if fetching entire list will have any impact on performace, but you can test it out for yourself.

---

I hope I was able to understand your queries and make a good suggestion. :smile:

**Comment by benjamincanac** [comment]
Hey @jbnv,

I think this is way too specific to be implemented inside @nuxt/content.

@TheLearneer suggestion seems the way to go!
