### ISSUE TITLE
How to create a TOC that can interact with content.

### ISSUE THREAD

**Issue by oceanlvr** [nuxt/content#789]
How could I create a TOC  that can interact with contents. When I scroll down the page and TOC will be update.
just like nuxt/content docs `https://content.nuxtjs.org/`:

![Kapture 2021-02-22 at 17 01 49](https://user-images.githubusercontent.com/36698124/108685997-cd1bdc80-752f-11eb-993c-ca373584f6c8.gif)

the `toc` iterm will be updated with content scroll.

**Comment by NozomuIkuta** [comment]
@oceanlvr 

For your information, Nuxt Content Theme Docs uses [vue-scrollactive](https://www.npmjs.com/package/vue-scrollactive) package.

https://github.com/nuxt/content/blob/4ba67b4522f11db97ec2f8c161bd2aa98655db37/packages/theme-docs/src/plugins/vue-scrollactive.js#L1-L4

https://github.com/nuxt/content/blob/e85daf0bfc6491e96555fad9bb1a9772be2a323a/packages/theme-docs/src/index.js#L98-L104

https://github.com/nuxt/content/blob/4ba67b4522f11db97ec2f8c161bd2aa98655db37/packages/theme-docs/src/components/app/AppToc.vue#L14-L32

**Comment by oceanlvr** [comment]
@NozomuIkuta Thanks, it's all I need. `scrollactive` makes toc highlight easier.

**Comment by oceanlvr** [comment]
updated code:

```vue
<div class="table-content">
  <p class="title">{{ $t('docs.menu') }}</p>
  <scrollactive highlight-first-item active-class="is-active" :offset="20" tag="ul" alwaysTrack>
    <li v-for="item in toc" :key="item.id" :class="['item', `depth-${item.depth}`]">
      <a class="scrollactive-item" :class="{ 'is-active': `#${item.id}` === hash }" :href="`#${item.id}`">{{ item.text }}</a>
    </li>
  </scrollactive> 
</div>
```
