### ISSUE TITLE
"createdAt" property is missing

### ISSUE THREAD

**Issue by benlutz** [nuxt/content#79]
Hi, the documentation states, that createdAt and updatedAt properties are added. This, however, is not true, because createdAt is missing.

### Version
@nuxt/content: v1.0.2
nuxt: v2.12.0

### Reproduction Link
You can reproduce it on your own sandbox, looking at the api _content
https://codesandbox.io/s/nuxtcontent-demo-l164h
Key and Value for createdAt are missing.

**Comment by thely** [comment]
Do you mean that createdAt and updatedAt don't physically appear in the .md file, or that they have `undefined` values if you try to access them inside a page component? I believe they're injected into the remark JSON representation on save, but aren't visible in the file, same as the slug. Try logging `[object].createdAt` and you'll get a date string like `2020-05-23T00:53:08.000Z`.

**Comment by benlutz** [comment]
@thely I know, that they do not appear in the in the .md file but should be injected into the JSON representation. However, only updatedAt is injected and createdAt is completely missing in the json representation. You can see it by looking at the json of the sandbox (calling _content)

https://l164h.sse.codesandbox.io/_content

**Comment by benjamincanac** [comment]
Are you using the last version of @nuxt/content, v1.2.0?

**Comment by benlutz** [comment]
well that fixes that. thank you I guess. Another lesson learned: keep updating your modules...
