### ISSUE TITLE
Custom Database Hash

### ISSUE THREAD

**Issue by amotarao** [nuxt/content#792]
### Is your feature request related to a problem? Please describe.
I want to change the database hash.

### Describe the solution you'd like
I can customize db-hash.

### Describe alternatives you've considered
add custom hash option in content.

### Additional context

nuxt.config.js
```js
export default {
  content: {
    dbHash: 'hogefuga'
  }
}
```

Similar options in nuxt.js:  https://github.com/nuxt/nuxt.js/blob/691f21c6832323902d899b56566dd97d63683528/packages/config/src/config/generate.js#L17-L22

**Comment by NozomuIkuta** [comment]
Looking up the source code, it seems to become possible by letting Nuxt content uses user option in the part below.

https://github.com/nuxt/content/blob/b2f45db0b16ecdf21981f6eff0afdc851829ccbe/packages/content/lib/index.js#L174-L195

Then, the hash is used when fetching data in plugin.

https://github.com/nuxt/content/blob/4ba67b4522f11db97ec2f8c161bd2aa98655db37/packages/content/templates/plugin.static.js#L10

https://github.com/nuxt/content/blob/4ba67b4522f11db97ec2f8c161bd2aa98655db37/packages/content/templates/plugin.static.js#L33-L43

This would be a chance for you to contribute by submitting a PR. 😀 
By the way, I'm not sure what is a use case of changing db hash, so I appreciate if you share yours for example.

**Comment by amotarao** [comment]
I have a case where I want to fix the hash.

If custom hash is added, It's like generate.staticAssets.version option in nuxt.js.

**Comment by amotarao** [comment]
I think it's an unrelated issue.
I don't know it was closed.

**Comment by amotarao** [comment]
If resolve #534 with or without #792, #792 should be open.
