### ISSUE TITLE
theme-docs components not loading with fresh install from npx create-nuxt-content-docs

### ISSUE THREAD

**Issue by Soviut** [nuxt/content#794]
### Version
@nuxt/content: 1.6.0
@nuxt/content-theme-docs: 0.10.0
nuxt: v2.15.2

### Steps to reproduce

- ensure latest node LTS is installed (14.16.0)
- `npx create-nuxt-content-docs my-docs`
  - project name: `my-docs`
  - project title: `My Docs`
  - documentation url: (I put my docs URL)
  - twitter username: (I put a twitter `@name`)
  - package manager; `npm`
- wait while it installs without error
- visit `http://localhost:3000`
- see the /content/index.md page loads
- open the devtools console
- see dozens of errors reporting...
  ```
  Unknown custom element: <alert> ... found in <NuxtContent> at .nuxt/content/nuxt-content.dev.vue
  Unknown custom element: <list> ... found in <NuxtContent> at .nuxt/content/nuxt-content.dev.vue
  Unknown custom element: <IconTwitter> ... found in <AppHeader> at node_modules/@nuxt/content-theme-docs/src/components/app/AppHeader.vue
  Unknown custom element: <IconGithub> ... found in <AppHeader> at node_modules/@nuxt/content-theme-docs/src/components/app/AppHeader.vue
  etc...
  ```

### What is Expected?

The components that belong to the theme-docs should be registered and render correctly.

### What is actually happening?

The components that belong to the theme-docs are not being automatically registered.

### Additional

I also tried using `yarn create nuxt-content-docs my-docs` but got the same issue.

**Comment by NozomuIkuta** [comment]
It seems same issue as #785.
