### ISSUE TITLE
vue components not registering in markdown, via global or local registration 

### ISSUE THREAD

**Issue by ryanrapini** [nuxt/content#801]
I cannot get vue components to appear in my markdown files. I tried adding vue components to the `components/global` folder, and also locally importing the components. Neither seems to work. In general, I am trying to include an image file in my markdown content but finding it rather complex.

**To Reproduce**
1. Clone repository https://github.com/ryanrapini/ryanrapini.github.io
2. Run `yarn install`
3. Run `yarn dev`
3. Navigate to the Portfolio tab in browser and inspect console for errors (screenshot below)

**Expected behavior**
I expected that this would work as it is documented here:
https://content.nuxtjs.org/writing#vue-components

In my understanding, if I write vue components and add them to the `/components/global/` folder, they would be automatically imported for me.

Additionally, I tried manually importing the components into the vue file, and I find that the components work just fine there. However, when I try to use them in the markdown file, they do not appear.

**Screenshots**
![Screenshot_20210226_105205](https://user-images.githubusercontent.com/286087/109322803-f8dce200-780f-11eb-94c4-6cfa7ca23358.png)

**Additional context**
Using  Nuxt @ v2.15.2

Relevant code:

### In `portfolio.md`:
```
<example></example>

<v-img src="thumbnails/aofarm.jpg"></v-img>
```
### in `pages/portfolio/index.vue`
```
<script>
import Example from '~/components/global/Example'
import VImg from '~/components/global/VImg'

export default {
components: {
	Example,
	VImg
},
  async asyncData({ $content }) {
    const page = await $content('portfolio').fetch()

    return {
      page
    }
  }
}
</script>

<template>
  <article class="container mx-auto content pt-10">
	<example />
	<v-img src="thumbnails/aofarm.jpg" />
    <nuxt-content :document="page" />
  </article>
</template>

<style lang="scss">
@import '../../styles/_settings.scss';
@import '../../styles/main.scss';
</style>

```
### in `Example.vue`
```
<template>
	<p>A</p>
</template>
```
### in `VImg.vue`
```
<template>
  <img :src="imgSrc()" :alt="alt" />
</template>

<script>
export default {
  name: 'Test',
  props: {
    src: {
      type: String,
      required: true
    },
    alt: {
      type: String,
      default: ''
    }
  },
  methods: {
    imgSrc() {
      try {
        return require(`~/assets/${this.src}`);
      } catch (error) {
        return null
      }
    }
  }
}
</script>
```
I have wasted almost two hours on this now... I found discussion around images here, which is where I found the v-img code.
#106 
When this didn't work I tried a simpler "example" vue component hoping to isolate the issue.

I am aware of multiple discussions on this topic, specifically #24, #22, and #13 but was unable to find a solution from reviewing those threads... Perhaps I am missing something?

Any help is greatly appreciated.

**Comment by teegee** [comment]
You're missing 'components: true' in your nuxt config. See https://nuxtjs.org/docs/2.x/directory-structure/components/

Unless it's something else -- I'm a nuxt newbie :)

**Comment by ryanrapini** [comment]
thanks @teegee, this was the issue!

**Comment by madsh93** [comment]
Is there a way to import manually? I am not using automatic component import, as I've had issues with it before.
