### ISSUE TITLE
Possible feature: Is lokidb fullTextSearch required when fullTextSearchFields is empty[] ?

### ISSUE THREAD

**Issue by vanling** [nuxt/content#810]
Is Lokidb fullTextSearch required when you set `fullTextSearchFields` to an empty array?
Is it used for anything else then `.search()` and if not could it be a change in the template to not load it in static builds.

Just curious because im looking around what can be done to make my whole static build smaller.

> ./node_modules/@lokidb/full-text-search/lokidb.full-text-search.js (10.25 KB) gzip
> ./node_modules/@lokidb/full-text-search/lokidb.full-text-search.js (30.34 KB) parsed
> ./node_modules/@lokidb/full-text-search/lokidb.full-text-search.js (83.05 KB) stat

**Comment by vanling** [comment]
Would something like this work? _(this <%= syntax is still magic to me)_

**templates/plugin.static.lazy.js**
```
<%= options.fullTextSearchFields.length > 0 ? import LokiFullTextSearch from '@lokidb/full-text-search' %>
<%= options.fullTextSearchFields.length > 0 ? LokiFullTextSearch.register() %>
```

**Comment by NozomuIkuta** [comment]
I guess it's possible.

By the way, for your information, Nuxt uses Lodash to compile templates of modules ([link](https://nuxtjs.org/docs/2.x/directory-structure/modules/#template-plugins)).
