### ISSUE TITLE
How to use $content() inside hook "content:file:beforeInsert"

### ISSUE THREAD

**Issue by brunodeangelis** [nuxt/content#812]
How do I use `$content()` inside the hook `content:file:beforeInsert`? I want to replace a field in my document that is a slug, with its equivalent full field that is on another collection.

Ideally my code would look like this:

```js
// before: document.address = "20-northmoor-road"

hooks: {
  "content:file:beforeInsert": (document) => {
    if (document.extension === ".md" && document.dir === "/letters") {
      const readableAddress = await $content("addresses", document.address).fetch();
      document.address = readableAddress.address;
    }
}

// after: document.address = "20 Northmoor Road, Oxford"
```

But where do I get `$content` from? I've tried every way:
`const { $content } = require("@nuxt/content");`
`const { content } = require("@nuxt/content");`
`const $content = require("@nuxt/content");`
`const content = require("@nuxt/content");`

The last one is the only one that's not `undefined`, but it doesn't have `fetch` function on it.

If `$content()` can't be used inside the hook: is there any other way in which I can query or get the data from my collections? Regarding this, I have also used the `database` object provided by the hook.

```js
hooks: {
  "content:file:beforeInsert": (document, database) => {
    if (document.extension === ".md" && document.dir === "/letters") {
      // this returns undefined,
      const addresses = database.db._collections[0]._data;

     // but when I log database.db._collections, they do have a _data object. What's wrong?
    }
}
```

Any questions I would be glad to answer. Thank you!

**Comment by NozomuIkuta** [comment]
@brunodeangelis 

First, you can't use `$content()` method in `content:file:beforeInsert` hook.

Second, `content:file:beforeInsert` hook is called for each file in `content` directory, and the order of insertion is not guaranteed.
In other words, even if you can access internal documents in database directly, `"addresses"` file may not yet have been inserted.

---

Although I'm not sure how you manage readable addresses, why wouldn't you define an object whose key is raw address and value is readable one?

```javascript
// addresses.js
export default {
  "20-northmoor-road": "20 Northmoor Road, Oxford"
}
```

```javascript
// nuxt.config.js
import addressMap from 'path/to/addresses.js'

export default {
  hooks: {
    "content:file:beforeInsert": (document, database) => {
      if (document.extension === ".md" && document.dir === "/letters") {
        document.address = addressMap[document.address] || document.address
      }
    }
  }
}
```

**Comment by brunodeangelis** [comment]
@NozomuIkuta 

Thanks for your reply. You've clarified some of the doubts I had.

I ended up doing all the work/data merging in `asyncData`, since I have very few pages. It now looks something like this to fetch all the `letters`:

```js
async asyncData({ $content }) {
  const letters = await $content("letters").sortBy("number").fetch();
  let promises = [];

  for (const letter of letters) {
    promises.push(
      new Promise(async (resolve) => {
        let letterPromises = [];

        if (letter.recipient) {
          letterPromises.push(
            $content("recipients", letter.recipient)
              .fetch()
              .then((recipient) => {
                letter.recipient = recipient;
              })
          );
        }

        if (letter.address) {
          letterPromises.push(
            $content("addresses", letter.address)
              .fetch()
              .then((address) => {
                letter.address = address;
              })
          );
        }

        await Promise.all(letterPromises);

        resolve();
      })
    );
  }

  await Promise.all(promises);

  return { letters };
},
```

This way I can have some sort of "relational" content.
