### ISSUE TITLE
Dynamic routes not discovered in nuxt 2.15.2

### ISSUE THREAD

**Issue by camhart** [nuxt/content#819]
### Version
@nuxt/content: 1.14.0
nuxt: 2.15.2

>Since Nuxt 2.14+, nuxt generate has a crawler feature integrated which will crawl all your links and generate your routes based on those links. Therefore you do not need to do anything in order for your dynamic routes to be crawled.
https://content.nuxtjs.org/advanced/#static-site-generation

### What is Expected?
I'm finding the crawler doesn't find the routes in 2.15.2.  I still need to use the old solution (see code below)

``` nuxt.config.js
  generate: {
    subFolders: true,
    async routes() {
      const { $content } = require('@nuxt/content')
      const files = await $content({ deep: true }).only(['path']).fetch()
      const ret = files.map(file => file.path === '/index' ? '/' : file.path)
      console.log(`generate routes\n${JSON.stringify(ret, null, 2)}`)
      return ret
    }
  },
```

### What is actually happening?
No dynamic routes are discovered.

**Comment by ManasMadrecha** [comment]
Automatic route generation works only if there is some link shown in any page or md file. It won't generate automatically a link even if you have that md file in Content folder. 

If your Content folder is small, maybe try showing some list of all posts in some page, or if your Content folder is huge, try showing a list of children posts on an individual post using `where` option with `dir` query. 

Then, Automatic route generation will work perfectly.
