### ISSUE TITLE
Document how to display content outside component (e.g., RSS)

### ISSUE THREAD

**Issue by philipithomas** [nuxt/content#82]
Users will want to display their content outside of components, such as in an RSS feed. Currently, the [displaying content](https://content.nuxtjs.org/displaying#component) page only discusses using a component to render content. The document object does not include HTML or a plaintext summary that could be used for this. 

### Describe the solution you'd like

On the `Displaying content` page, document how to include content programmatically, such as in an RSS feed.

**Comment by rclement** [comment]
I solved this very use-case last week when migrating to `@nuxt/content` in my website, along with `@nuxtjs/feed-module` : https://github.com/rclement/romain-clement.net/blob/master/nuxt.config.ts#L28

Almost everything needed is already in the documentation: https://content.nuxtjs.org/advanced#programmatic-usage

A nice addition to the documentation would be a basic code snippet to integrate with `@nuxtjs/feed-module`, which takes care of everything feeds-related automagically.

@philipithomas did you want to start a PR for this or may I start one?

**Comment by philipithomas** [comment]
@rclement Looks like you have a great solution. If you want to open a PR, that would be great! 

I'm busy this week, but if this issue is still open by the weekend, I may try to update the docs using your example code.

**Comment by philipithomas** [comment]
@rclement It looks like your RSS feed returns the `summary` as the content, rather than the body of your markdown. Is that right? 

I'd like to return the entire article body in the `content` section of the RSS.

**Comment by rclement** [comment]
@philipithomas Yes that's right, this is common practice so that potential readers are still coming back to your site (so you can obtain some more meaningful analytics metrics if you're into this stuff). And using `@nuxt/content` you do not have access to a textual version of the body directly, only the JSON AST.

However you have access to the `text` field containing the raw body during the hook `file:beforeInsert` according to: https://content.nuxtjs.org/advanced#contentfilebeforeinsert
You could copy it and/or process it in some way to extract a plain-text body to be injected afterwards in feeds `content` section.

**Comment by Atinux** [comment]
Thank you for your answers @rclement, a PR for integrating with feed module is more thank welcome 🙏

**Comment by rclement** [comment]
@philipithomas @Atinux I started PR #93, feel free to comment and correct it!

**Comment by benjamincanac** [comment]
@rclement Thanks for the PR!

**Comment by lukeocodes** [comment]
Here's me building integration with `nuxtjs/feed` and you merge a PR showing how to do it :D 

Bu, #93 still uses summary, without a good way to take the JSON AST and turn it into a string of HTML. 

Besides storing `text` against the object and running it through a parser, any suggestions on how to achieve this?

**Comment by Atinux** [comment]
I believe this could be done by using the https://github.com/syntax-tree/hast-util-to-html package from document.body, could you try?

**Comment by TheLearneer** [comment]
@Atinux That throws error on me.. Any idea why ??

![image](https://user-images.githubusercontent.com/23402178/84002191-c0e2f580-a987-11ea-88ff-636df830d1a5.png)

```js
import hastUtilToHtml from 'hast-util-to-html';

async create(feed, info) {
  // info is valid here...
  feed.options = { /* options here */ };
  const articles = await $content(info.content).fetch();
  // articles is a valid array...
  articles.forEach((article) => {
    const url = `${info.url}${article.slug}`;
    feed.addItem({
      title: article.title,
      id: url,
      link: url,
      date: article.created,
      description: article.summary,
      content: hastUtilToHtml(article.body)
    })
  })
}
```

**Comment by lukeocodes** [comment]
Yeh, I can confirm it doesn't appear to like the hast format. I've been away from the keyboard so I'll dive into the config and see if this is possible. If anyone else has managed it, sharing is caring <3 

Thanks @Atinux!
