### ISSUE TITLE
Is there any options to specify content url regardless to file structure?

### ISSUE THREAD

**Issue by maemaemae3** [nuxt/content#822]
I have a question related to this issue: [Allow a way to modify slugs](https://github.com/nuxt/content/issues/15).

I'm going to make a new blog, and make all url of articles like `mysite.com/slug`.
But organize articles will be difficult if I put all articles right below `/contents`, so I want to sort articles in each `/contents/year/month` dir, but don't want to make the url like `mysite.com/[year]/[month]/slug`.

Can't I place foobar.md file in `/content/[year]/[month]/slug.md` and make the article url like `http://mysite.com/slug` instead of `http://mysite.com/[year]/[month]/slug` ?
Or is there any options like putting `permalink: url_of_article` in [Front Matter](https://content.nuxtjs.org/writing/#front-matter) so that I can specify the url of each article?

**Comment by ManasMadrecha** [comment]
Your `content` folder structure can be anything and independent of how you create your `pages` structure.

Suppose, in `content` folder, you have `posts` folder (with any number of sub-folders).

In `pages`, simply create `pages/blog/_slug.vue` file. 
In this file, fetch your posts.


```js

<script>
export default {
  data() {
    return {
      posts: [],
    };
  },
  async fetch() {
    
    // use this if the post slug you want is same as your posts md files
    this.posts = await this.$content("posts", {deep: true})
      .where({ slug: this.$route.params.slug })
      //  
      .fetch();

     // or if you want to keep your filename as anything, 
    // then use this by having `slugurl` or similar property in the post frontmatter which can act as slug.
    this.posts = await this.$content("posts", {deep: true})
      .where({ slugurl: this.$route.params.slug })
      .fetch();

    this.posts = this.posts[0];

   // Then in your <template>, you can easily use <NuxtContent /> and pass on `posts` as `document` prop.
  },
};
</script>

```

**Comment by maemaemae3** [comment]
Oh my god, I was merely an idiot. Its really simple!
I got it, thank you very much!
