### ISSUE TITLE
Markdown Ordered Lists does not work

### ISSUE THREAD

**Issue by openHacking** [nuxt/content#824]
### Version
@nuxt/content: latest
nuxt: latest

### Steps to reproduce
1. git clone https://github.com/nuxtlabs/demo-blog-nuxt-content.git
2. Open http://localhost:3000/blog/some-interesting-title
3. Modify the content of the article and add the following content

```js
1. First item
2. Second item
3. Third item
     1. Indented item
     2. Indented item
4. Fourth item

- First item
- Second item
- Third item
     - Indented item
     - Indented item
- Fourth item
```

### What is Expected?
1. First item
2. Second item
3. Third item
     1. Indented item
     2. Indented item
4. Fourth item

- First item
- Second item
- Third item
     - Indented item
     - Indented item
- Fourth item

### What is actually happening?
The rendering result does not show the list sort number
![image](https://user-images.githubusercontent.com/72927208/110895537-eba61400-8334-11eb-82de-44a44a58811b.png)

**Comment by openHacking** [comment]
"@nuxt/content": "1.10.0",
    "nuxt": "2.14.7"

looks good

**Comment by Mark-Brightcloud** [comment]
same issue here too. please keep me posted when this is resolved. thanks!

"@nuxt/content": "1.14.0",
"nuxt": "2.15.3"

**Comment by kpeter1994** [comment]
I also ran into this problem, but then I realized that it was only tailwind that disabled <ol> and <ul> formatting.
