### ISSUE TITLE
Second level subfolders return 404

### ISSUE THREAD

**Issue by retroriff** [nuxt/content#827]
"@nuxt/content": "^1.14"
"nuxt": "^2.15.0"

I have created a "category" folder inside content, that contains a tree of categories and subcategories as shown below:

content/category/
content/category/category1-slug/index.md
content/category/category1-slug/category11-slug/index.md
content/category/category2-slug/index.md

This is code that reads the content:

    export default {
      async asyncData({ $content, params, error }) {
        let categories
            try {
              categories = await $content('category', { deep: true }, params.slug)
                .only(['title', 'dir', 'createdAt', 'updatedAt', 'path'])
                .sortBy('createdAt', 'desc')
                .fetch()
            } catch (e) {
              error({ message: 'Categories not found' })
            }
            return { categories }
      }
    }

While I can load categories from the first nested level, second level returns a 404

example.com/category/category1-slug/ => Works
example.com/category/category1-slug/category11-slug/ => Page Not Found 404
example.com/category/category11-slug/ => Page Not Found 404

I reported it as a bug but maybe I am not calling the nested categories correctly. You can check it here:

https://codesandbox.io/s/dank-haze-x98h4
https://github.com/retroriff/nuxt-content-nested-categories

**Comment by NozomuIkuta** [comment]
@retroriff 

You are making mistakes in terms of directory structure. 

According to [the official documentation](https://nuxtjs.org/docs/2.x/directory-structure/pages#dynamic-pages), if you want to make `category` and `subcategory` as `params`, you have to define them as directories whose names begin with `_`:

- `pages/category/_category/index.vue` corresponds to URL `category/<category>`.
- `pages/category/_category/_subcategory.vue` corresponds to URL `category/<category>/<subcategory>`.

Here is a [demo (CodeSandbox)](https://codesandbox.io/s/nuxt-content-nested-route-1qyjw?file=/pages/category/_category/_subcategory.vue).

**Comment by retroriff** [comment]
Great! It works like a charm. Thank you for your help. 

Regarding the nested categories, do you have any example of getting a complete nested categories that shows their hierarchy, which could be used for a categories list?  I guess that the result from $content should iterarate to itsself. However without `{ deep: true }` it does not find the subfolders.
