### ISSUE TITLE
Vuepress like features in md file like Templating and Alert Infoboxes

### ISSUE THREAD

**Issue by ManasMadrecha** [nuxt/content#829]
### Is your feature request related to a problem? Please describe.

1. Currently, even for displaying basic lists in `.md` file, we have to create `list` component in `global` folder and pass Frontmatter's property to it as a prop. 
2. Similarly, we cannot display the properties in the Frontmatter inside the `.md` file's body. We can only pass them as props in components, thus making it necessary to create component for each and every small thing.
3. Sometimes, we need Infoboxes (like information, warning, success) in `.md` file. Currently, the only option is to create a slot-based component as pass props into it. In Vuepress, it comes handy with [custom containers](https://vuepress.vuejs.org/guide/markdown.html#custom-containers).

### Describe the solution you'd like

1. It would be great to have [Templating and Interpolation](https://vuepress.vuejs.org/guide/using-vue.html#templating) possible like vuepress in the body part of `.md` file itself.
2. `remark-directive` plugin-like inbuilt solution for the 3rd problem mentioned above.

### Describe alternatives you've considered

1. People can use `remark-directive` plugin to at least avoid writing `<></>` like content in md files. But that requires creating custom plugin to convert the tags and nodes, which is very difficult for novice developers. Until Vuepress like `custom components` feature is considered, at least some documentation on how to implement such `custom plugin for general directives` in Snippets section of the website can be made available.
2. For Templating and Interpolation, is there any recent update scheduled?

Thank you for creating such awesome Nuxt Content module.

**Comment by ManasMadrecha** [comment]
@Atinux 

# Templating

Oh, then it's alright if Templating isn't available in md files. 

> I still believe we can find a way to support this but might be tricky.

Anyway, as you are hopeful, it would be great to have this feature even in 6 months from now.

# remark-directive

## Why do we need it for Content module?
1. We already can use global components in `.md` files. So, we can create `<alert>` or any `<info>` type component and use it in `.md` file, and pass props. But, the main issue is using `<></>` type content which is a hassle, especially when typing on mobile.
2. With `remark-directive` plugin, we can not only avoid `<>`, but even avoid use of even writing full **closing tags** which is currently a must in Content module.
  - So, both 1. and 2. can be written in easy way like this
  ```md
  :::info{type=alert}
     ### Remember!
     abc abc
     any content
   :::
  ```
3. Even for normal text where we need to change background colour, or something like that, 
  - we have to write: `<span class="bg-pink-100">text</span>`. 
  - with remark-directive simply like this, `:span[text]{.bg-pink-100}`.
This type of writing is very easy of write.

### So, How to use remark-directive plugin for Content?

Currently, on Content's website, we have an example of how to directly add options for any `remark` plugin.

```js

export default {
  content: {
    markdown: {
      remarkPlugins: [
        ['remark-emoji', { emoticon: true }]
      ]
    }
  }
}
```

**But the different thing about `remark-directive` plugin is that it doesn't have options to be added. Rather, it demands a new plugin to be created which can be chained to it, for e.g. `htmlDirectives` is the custom plugin below**

```js

var vfile = require('to-vfile')
var report = require('vfile-reporter')
var unified = require('unified')
var parse = require('remark-parse')
var directive = require('remark-directive')
var remark2rehype = require('remark-rehype')
var format = require('rehype-format')
var stringify = require('rehype-stringify')

var visit = require('unist-util-visit')
var h = require('hastscript')

unified()
  .use(parse)
  .use(directive)
  .use(htmlDirectives)
  .use(remark2rehype)
  .use(format)
  .use(stringify)
  .process(vfile.readSync('example.md'), function (err, file) {
    console.error(report(err || file))
    console.log(String(file))
  })


// This plugin is just an example! You can handle directives however you please!
function htmlDirectives() {
  return transform

  function transform(tree) {
    visit(tree, ['textDirective', 'leafDirective', 'containerDirective'], ondirective)
  }

  function ondirective(node) {
    var data = node.data || (node.data = {})
    var hast = h(node.name, node.attributes)

    data.hName = hast.tagName
    data.hProperties = hast.properties
  }
}
```
This code is from @remarkjs/remark-directive Github's page.

## So we even have custom plugin's code, then what's the Issue?
1. Simply, as a novice developer, I am unable to know where should I add this aforementioned custom code in Content's nuxt config.
2. Maybe I have to create a new custom plugin, so should `htmlDirectives` be a remark or a rehype plugin?
3. How to do this?

### Example needed
So, it would be very helpful if some example on this is added to Snippets section of Content website, which can basically show how to use remark plugins which need a plugin of their own.

Thanks in advance. 😄

**Comment by ManasMadrecha** [comment]
Hi @Atinux 

By some trial and error, `remark-directive` is working very well now in my code. 😃 

### How?
I added an `htmldirectives` plugin under `plugins` folder, and added this code:

```js

const visit = require('unist-util-visit')
const h = require('hastscript')

module.exports = function () {
  return function transformer(tree, file) {
    visit(
      tree,
      ["textDirective", "leafDirective", "containerDirective"],
      ondirective
    );
    function ondirective(node) {
      var data = node.data || (node.data = {});
      var hast = h(node.name, node.attributes);

      data.hName = hast.tagName;
      data.hProperties = hast.properties;
    }
  }
};
```

Then, I registered this above plugin in `remark` (and not in rehype) plugins in `nuxt-config` in `content.markdown.remarkPlugins`.

### Usage

Now, I am able to use Vuepress-like custom container blocks (colourful) by creating either 
- multiple global components like (`alert.vue`, `warning.vue`, `success.vue`). Benefits? No need of props. 
```md
:::success
abc content
:::
```
- just a single component (`info.vue`) and passing props to it, like --> 
 ```md
:::info{type=success}
abc content
:::
```

Anyway, as my project is simple (but with tens of thousands of md file), I wanted simple colourful components. But for others, they may make any component they want.

Hope this helps.

**Comment by sp0ken** [comment]
I'm also struggling with a similar issue.
We're migrating from Markdown-it to Nuxt-content and one of crucial missing element is the possibility to add custom attributes. Mainly classes.
This seems to be such an important feature for larger scale markdown usage.

The documentation is a bit lacking on custom remark plugins such as the one for remark-directive.

@ManasMadrecha I've tried your solution but it seems that my markdown is never parse by the plugins.

**Comment by ManasMadrecha** [comment]
Well, it works for me. I am using latest versions of Nuxt and Content and remark-directive.

I created a new plugin inside `plugins` folder called `directive-custom.js`.
In that, I pasted the above code.

then, in my `nuxt-config.js`, I registered both `remark-directive` plugin and above `directive-custom.js` plugin like this:

```js
  content: {
    markdown: {
      tocDepth: 4,
      remarkPlugins: [
        ['remark-breaks'],
        ['remark-directive'],
        ['~/plugins/remark/directive-custom.js'],
        ['@silvenon/remark-smartypants', { dashes: 'oldschool' }],
      ],
    },
  },

```

It works fine. 😊
You can now write simply like this in your markdown files:

```markdown

Hello, I'm an :u[underlined text].

:::ul{.tw-flex .tw-flex-wrap}
::li[first item on the list]
::li[second item on the list side by side]
:::

**Comment by sp0ken** [comment]
@ManasMadrecha 
I was missing remark-directive in my plugin list. It's working now.
Thanks again I was going mad.

**Comment by ManasMadrecha** [comment]
@Atinux 
### Templating
**I found a hack to add templating inside md files.**

1. Simply created a global component `md-data.vue`
```vue
<template>
  <span>{{data}}</span>
</template>

<script>
export default {
  props: ["data"]
};
</script>
```

2. Now, in md files, I can use this component for basic maths calculations, showing yaml frontmatter data and simple functions. 

```md
<md-data data="123+123"></md-data>
```

This outputs as 246. Perfect 👌🏻🚀

**Comment by gsjen** [comment]
I was able to get templating working by adding the following function to the `nuxt-content` component and calling it for text nodes:
```
function interpolateText(text, context) {
  const regex = new RegExp(/{{(.*?)}}/g)
  let match
  if ((match = regex.exec(text))) {
    let body = 'with (this) { return ('
    let index = 0
    do {
      body += `'${text.substring(index, match.index)}'+(${match[1]})+`
      index += match.index + match[0].length
    } while ((match = regex.exec(text)))

    body += `'${text.substring(index)}'`
    body += ') }'

    return new Function(body).call(context)
  }
  return text
}
```
I have to add I found it awkward using interpolation in markdown (probably due to the lack of syntax highlighting), so I only use it in component slots.

**Comment by ManasMadrecha** [comment]
@gsjen This seems amazing. And where should we add this above function to the `nuxt-content` component?

**Comment by gsjen** [comment]
Here is a complete copy of my version of `nuxt-content`:
```javascript
import info from 'property-information'

const rootKeys = ['class-name', 'class', 'style']

const rxOn = /^@|^v-on:/
const rxBind = /^:|^v-bind:/
const rxModel = /^v-model/
const nativeInputs = ['select', 'textarea', 'input']
const interpolate = /{{(.*?)}}/g

function evalInContext(code, context, slotProps, slotArgs) {
  return new Function(slotProps, 'with(this) { return (' + code + ') }').call(
    context,
    slotArgs
  )
}

function interpolateText(text, context, slotProps, slotArgs) {
  const regex = new RegExp(interpolate)
  let match
  if ((match = regex.exec(text))) {
    let body = 'with (this) { return ('
    let index = 0
    do {
      body += `'${text.substring(index, match.index)}'+(${match[1]})+`
      index += match.index + match[0].length
    } while ((match = regex.exec(text)))

    body += `'${text.substring(index)}' ) }`

    return new Function(slotProps, body).call(context, slotArgs)
  }
  return text
}

function propsToData(node, doc, slotProps, slotArgs) {
  const { tag, props } = node
  return Object.keys(props).reduce(
    function(data, key) {
      const k = key.replace(/.*:/, '')
      let obj = rootKeys.includes(k) ? data : data.attrs
      const value = props[key]
      const { attribute } = info.find(info.html, key)
      const native = nativeInputs.includes(tag)

      if (rxModel.test(key) && value in doc && !native) {
        const mods = key
          .replace(rxModel, '')
          .split('.')
          .filter(d => d)
          .reduce((d, k) => {
            d[k] = true
            return d
          }, {})

        // As of yet we don't resolve custom v-model field/event names from components
        const field = 'value'
        const event = mods.lazy ? 'change' : 'input'
        const processor = mods.number
          ? d => +d
          : mods.trim
          ? d => d.trim()
          : d => d

        obj[field] = evalInContext(value, doc, slotProps, slotArgs)
        data.on = data.on || {}
        data.on[event] = e => (doc[value] = processor(e))
      } else if (key === 'v-bind') {
        const val =
          value in doc
            ? doc[value]
            : evalInContext(value, doc, slotProps, slotArgs)
        obj = Object.assign(obj, val)
      } else if (rxOn.test(key)) {
        key = key.replace(rxOn, '')
        data.on = data.on || {}
        data.on[key] = evalInContext(value, doc)
      } else if (rxBind.test(key)) {
        key = key.replace(rxBind, '')
        obj[key] =
          value in doc
            ? doc[value]
            : evalInContext(value, doc, slotProps, slotArgs)
      } else if (Array.isArray(value)) {
        obj[attribute] = value.join(' ')
      } else {
        obj[attribute] = value
      }
      return data
    },
    { attrs: {} }
  )
}

/**
 * Create the scoped slots from `node` template children. Templates for default
 * slots are processed as regular children in `processNode`.
 */
function slotsToData(node, h, doc) {
  const data = {}
  const children = node.children || []

  children.forEach(child => {
    // Regular children and default templates are processed inside `processNode`.
    if (!isTemplate(child)) {
      return
    }

    const slotProps = getSlotProps(child)
    if (isDefaultTemplate(child) && !slotProps) {
      return
    }

    // Non-default templates are converted into slots.
    data.scopedSlots = data.scopedSlots || {}
    const template = child
    const name = getSlotName(template)
    data.scopedSlots[name] = function(slotArgs) {
      return template.content.map(tmplNode =>
        processNode(tmplNode, h, doc, slotProps, slotArgs)
      )
    }
  })

  return data
}

function processNode(node, h, doc, slotProps, slotArgs) {
  if (node.type === 'text') {
    return interpolateText(node.value, doc, slotProps, slotArgs)
  }

  const slotData = slotsToData(node || {}, h, doc)
  const propData = propsToData(node || {}, doc, slotProps, slotArgs)
  const data = Object.assign({}, slotData, propData)

  /**
   * Process child nodes, flat-mapping templates pointing to default slots.
   */
  const children = []
  for (const child of node.children) {
    let processQueue
    // Template nodes pointing to non-default slots are processed inside `slotsToData`.
    if (isTemplate(child)) {
      if (!isDefaultTemplate(child) || getSlotProps(child)) {
        continue
      }
      processQueue = child.content
    } else {
      processQueue = [child]
    }

    children.push(
      ...processQueue.map(node =>
        processNode(node, h, doc, slotProps, slotArgs)
      )
    )
  }

  return h(node.tag, data, children)
}

const DEFAULT_SLOT = 'default'

function isDefaultTemplate(node) {
  return isTemplate(node) && getSlotName(node) === DEFAULT_SLOT
}

function isTemplate(node) {
  return node.tag === 'template'
}

function getSlotProps(node) {
  for (const propName in node.props) {
    if (!propName.startsWith('#') && !propName.startsWith('v-slot:')) {
      continue
    }
    return node.props[propName]
  }
}

function getSlotName(node) {
  let name = ''
  for (const propName in node.props) {
    if (!propName.startsWith('#') && !propName.startsWith('v-slot:')) {
      continue
    }
    name = propName.split(/[:#]/, 2)[1]
    break
  }
  return name || DEFAULT_SLOT
}

export default {
  name: 'NuxtContent',
  functional: true,
  props: {
    document: {
      required: true
    }
  },
  render(h, { data, props }) {
    const { document } = props
    const { body } = document || {}
    if (!body || !body.children || !Array.isArray(body.children)) {
      return
    }
    let classes = []
    if (Array.isArray(data.class)) {
      classes = data.class
    } else if (typeof data.class === 'object') {
      const keys = Object.keys(data.class)
      classes = keys.filter(key => data.class[key])
    } else {
      classes = [data.class]
    }
    data.class = classes.concat('nuxt-content')
    data.props = Object.assign({ ...body.props }, data.props)
    return h(
      'div',
      data,
      body.children.map(child => processNode(child, h, document))
    )
  }
}

```
As a bonus, this version also supports slot props 😊. You'll have to add something like this to your `nuxt.config` to override the default implementation:
```javascript
build: {    
  templates: [
    {
      src: 'path to the new source file',
      dst: 'content/nuxt-content.js'
    }     
  ]
}
```

**Comment by ManasMadrecha** [comment]
@Atinux Is Templating possible in new Content 2? i.e., `{{some Yaml frontmatter key here}}` or `{{2+2}}` is this possible?

or The best way to do that will be to create a new component, and pass the text as prop? And then use that component in MDC format?
