### ISSUE TITLE
Property '$content' does not exist on type 'Context'

### ISSUE THREAD

**Issue by jairoblatt** [nuxt/content#830]
#### My tsconfig.json.

```javascript
"compilerOptions": {
..
  "types": ["@nuxt/types",  "@nuxt/content", "@types/node"]
} 
```

#### The problem 

![image](https://user-images.githubusercontent.com/45108346/111307349-109dce00-8638-11eb-821a-84e1d5dc1180.png)

**Comment by han-tyumi** [comment]
@danielroe I am also having this issue, but it does not appear to happen in CodeSandbox: https://codesandbox.io/s/eloquent-rgb-0dltv?file=/pages/index.vue. It may be a VSCode issue?

**Comment by iwgx** [comment]
I solved the issue by reordering the import (`@nuxt/content` before `@nuxt/types`), everything seems fine

![Screenshot 2021-03-29 041050](https://user-images.githubusercontent.com/20817629/112768164-cf98b700-9044-11eb-87f6-49d66bbd9496.png)

**Comment by Linus-Boehm** [comment]
@danielroe This seems just to happen with nuxt >2.15 https://codesandbox.io/s/competent-gates-9cp1o?file=/pages/index.vue

**Comment by dbarjs** [comment]
`@nuxt/content` and `@nuxt/axios` are not compatibles here. The solution of @han-tyumi resolve my types problems.
