### ISSUE TITLE
Is there a hook or event that's fired once markdown content has rendered?

### ISSUE THREAD

**Issue by cschweda** [nuxt/content#834]
Is there a way to tell when content has successfully rendered after using ```<nuxt-content>```?

I need to apply accessibility fixes to the content -- i.e., fill in a blank button, etc. etc. -- but I can't figure out how to (a) wait until the markdown has completely and then (b) grab the rendered elements from the DOM to (c) apply the fixes.

**Comment by cschweda** [comment]
BTW --

I tried using the following syntax on the ```nuxt-content``` component, but it doesn't seem to register a ```mounted``` lifecycle:

```
  <nuxt-content :document="doc" @hook:mounted="doSomething" />
```

Is there any other way with the existing hooks to tell that markdown is finished rendering?

**Comment by cschweda** [comment]
Any ideas here?

**Comment by ManasMadrecha** [comment]
Maybe you can check these out https://content.nuxtjs.org/advanced#hooks

**Comment by NozomuIkuta** [comment]
NuxtContent component is defined as a functional component, which by design doesn't have any lifecycle hook.
All it does is to receive props and to return virtual DOM nodes.

Why don't you use the parent's `mounted` hook? Did you try and have any problem?

**Comment by cschweda** [comment]
I ended up doing as you suggest -- checking for the rendered content in the mounted hook. However, I did the check within a ```this.$nextTick```. This seems to do the trick!
