### ISSUE TITLE
db.json is loaded client-side for static site that is not using $content within the client code

### ISSUE THREAD

**Issue by matthamil** [nuxt/content#837]
### Version
@nuxt/content: 1.12.0
nuxt: 2.14.12

### Reproduction Link

No minimal repro (yet)

### Steps to reproduce

We recently [rebuilt our documentation](https://docs.cypress.io) at [Cypress.io](https://cypress.io) to use nuxt and nuxt-content. We are building the site using `nuxt generate`. We have a page that is requesting the `db.json` file despite the site being generated with `nuxt generate` and none of the client code is using `$content` (this should only be called when building the static site). From what I've read, [the `db.json` should not be loaded](https://github.com/nuxt/content/issues/534#issuecomment-784902538) unless `$content` is used client-side. 

1. Go to `https://docs.cypress.io`

1. Click on "Plugins" in the top header

1. The page will not redirect immediately because the `db.json` file is being fetched.

### What is Expected?

The `/plugins` page does not fetch `db.json` since the `$content` API is not being used client-side in this statically generated site.

### What is actually happening?

The `/plugins` page requests the `db.json` on load, causing a noticeable delay before the user can land on `/plugins`.

**Comment by danielroe** [comment]
@matthamil Is it possible to see the code - perhaps an open repo? I notice that this is only loaded for `/plugins/*` unlike the other pages which suggests that there is something different about this section of the site.

**Comment by matthamil** [comment]
@danielroe My apologies, I had the code link on my clipboard but I'm dumb and didn't paste it into my original post.

[Here is the page that handles `/plugins/*`](https://github.com/cypress-io/cypress-documentation/blob/next-docs/pages/plugins/_.vue).

**Comment by matthamil** [comment]
Thanks a bunch @danielroe! This helped.

**Comment by danielroe** [comment]
@matthamil A pleasure 😊
