### ISSUE TITLE
How to use Nuxt Content with Composition API and TypeScript

### ISSUE THREAD

**Issue by ArthurDanjou** [nuxt/content#841]
Hello, I would like to use Nuxt/Content into my project with the Nuxt-composition-api module and Typescript.
I have test many methods to get a content from my directory.

Here is some examples : 

```typescript
setup() {
    const {$content} = useContext()
    const info = useAsync( () => {
      $content('infos').fetch<InfoData>()
    })

    return {
      info
    }
  }
```
---
```typescript
const info = await $content('infos').fetch<InfoData>()
```

Here is my InfoData object :
```typescript
interface InfoData {
  age: number
  hiring_status: string,
  hiring_color: string
}
```

I have errors like `"TypeError: Cannot read property 'value' of undefined"` or `"TypeError: Cannot read property 'age' of undefined"`

My infos.json file is : 
```json
{
  "age": 18,
  "hiring": {
    "status": "available",
    "color": "green"
  }
}
```

Do you have an example to use the Nuxt content module with the composition api ?

**Comment by ArthurDanjou** [comment]
I have added the v-if condition *(`v-if="info.value.age"`)* but I have the following error : `"TypeError: Cannot read property 'age' of undefined"`. Then I removed the `.age` in the condition and my div disappear.

I have created a debug method and my printed object contains the age variable. 
My problem is that my div does not reappear when the async method is terminated

**Comment by ArthurDanjou** [comment]
All is working well !

**Comment by danielroe** [comment]
@ArthurDanjou Glad to hear it 😊
