### ISSUE TITLE
How to fetch all content with sub directories?

### ISSUE THREAD

**Issue by kylemod** [nuxt/content#845]
So how can we fetch all  inside content with sub directories in one asyncData function? 

Example Directory :

```bash
- content
  - articles
    -subDir1
      -article.md
    -subDir2
      -article.md
    -subDir3
      -article.md
```

As i expected that in one async data function will result all articles data

**Comment by Hextar** [comment]
AFIK you can use add { deep: true }.

The only problem is that it won't create some kind of tree.

Instead of a result like:

```
articles: {
    children: [
        subDir1: {
            {...} // article
        },
        subDir2: {
            {...} // article
        },
        subDir3: {
            {...} // article
        },
    ],
}
```

you will instead get something similar to 

```
[
    {...}, // article of subDir1
    {...}, // article of subDir2
    {...} // article of subDir3
]
```

I don't know how you need the data to be nested but I'm looking into a way to have something like the first example

**Comment by kylemod** [comment]
Thanks! Now i can fetch all data with `deep:true`. 😁

**Comment by kissu** [comment]
I have a similar answer here: https://stackoverflow.com/a/73435204/8816585
