### ISSUE TITLE
Footnote References Not Working When Text

### ISSUE THREAD

**Issue by jhull** [nuxt/content#85]
While the footnotes now show up, they don't work with "relative" footnotes (`[^word]` instead of `[^1]`). The link to the footnote shows the actual word rather than a 1, or 2, etc.

**Comment by benjamincanac** [comment]
Hey @jhull, could you provide a reproduction link?

Thanks!

**Comment by jhull** [comment]
Looks like this is [an issue with the original plugin, `remark-footnotes`](https://github.com/remarkjs/remark-footnotes/issues/3).
