### ISSUE TITLE
Exclude folders while fetching content

### ISSUE THREAD

**Issue by kbrosseau** [nuxt/content#852]
Hi everyone,

In our Content folder, we have two folders that contain data (partners,  filters). They hasn't to be in our sitemap, so we need to find a way to exclude them like this : const files = await $content({ deep: true }).where({ slug: { $not: { $regex: /^.*partners.*$/ }

But regex doesn't work and we need to exclude multiple names.

Is there a way for that?

NB: We know that sitemap module has an exclude parameter but we need to use a hook with nuxt content to add hreflink to all content route (which is not integrated in nuxt i18n) like this: 

`    routes: async () => {
      const { $content } = require('@nuxt/content')
      const files = await $content({ deep: true }).where({ slug: { $not: { $regex: /^.*partners.*$/ } } }).only(['path', 'slug']).fetch()
      /*return files.map(file => file.path === '/index' ? '/' : file.path)*/

      return files.map((file) => ({
        url: file.path.split('/')[1] === 'en' ? file.slug : file.path,
        links: [
          { lang: 'en', url: `en/${file.slug}/` },
          { lang: 'en-ca', url: `en-ca/${file.slug}/` },
          { lang: 'en-gb', url: `en-ca/${file.slug}/` },
          { lang: 'en-ie', url: `en-ie/${file.slug}/` },
          { lang: 'en-us', url: `en-us/${file.slug}/` },
          { lang: 'fr-ca', url: `fr-ca/${file.slug}/` },
          { lang: 'fr-ch', url: `fr-ch/${file.slug}/` },
          /*{ lang: 'fr-fr', url: `fr-fr/${file.slug}/` },*/
          { lang: 'x-default', url: `${file.slug}/` }
        ]
      }))
    },`

Thanks,
Kevin

**Comment by kbrosseau** [comment]
Solution is .where({ dir: { $regex: /^((?!partners|filter).)*$/ } })

**Comment by ManasMadrecha** [comment]
@kbrosseau 
If you using `_.vue` dyanamic page, and I don't want some md files to have their links generated, I simply do not create parent md file named as parent folder. 

**Example**: Suppose, I have a Content folder structure like this

```
abc 📂
 - file-1.md
 - file-2.md
 - file-3.md
def 📂
 - file-1.md
 - file-2.md
 - file-3.md
xyz 📂
 - file-1.md
 - file-2.md
 - file-3.md
abc.md
xyz.md
```

Note I have not created `def.md` file, so none of the files inside `def folder 📂` will NOT have their links generated. 😃 
So, without changing my code of fetching, this way, I can add draft files inside some folder 📂 and not create that folder's same-file name. 

Hope this helps. 😊

**Comment by kbrosseau** [comment]
Hello,

Thanks for your answer, but for me it is not working, all page are generated ☺️

**Comment by ManasMadrecha** [comment]
Nuxt links are automatically generated if there's a nuxt-link anywhere in your app. 

As I use `_.vue` page, for me the depth of breadcrumbs is not an issue.
I simply display children md files of the current post in a sidebar. So if and only if my current post's link is there somewhere in the app, i.e. if and only if my current post is generated, its children will generated. Now, how you generate the current post depends on your code. 

So maybe you might be displaying some all index or all children or all parents based on content folder files somewhere in your website. If that's the case, it may not work.
