### ISSUE TITLE
It is possible to pass through a component via frontmatter?

### ISSUE THREAD

**Issue by 684efs3** [nuxt/content#856]
have a markdown file with YAML frontmatter. In the frontmatter, I want to refer to a component such as:

```
---
title: Hello world
component: <component-a></component-a>
---
Lorem ipsum...
```

I want to refer to this in a page file via {{page.component}}. Is there a way to have vue recognize this? Right now, it just spits out <component-a></component-a>, instead of the actual component.

**Comment by ManasMadrecha** [comment]
@684efs3 
Why did you close this? Did you find a way to do it? 🤷🏻‍♂️

**Comment by 684efs3** [comment]
I'm not trying to do this any more. I will reopen if others are interested!

**Comment by farnabaz** [comment]
I'm not sure that I understand the real purpose of `component` meta here, but as I get you point this goal can be achieved in V2.
You can pass `component: COMPONENE_NAME` inside front matter to wrap page inside your custom component.
Also with MDC syntax you can freely use your custom components within the markdown file.

But if you were loading for a way to import components as object, this is out of module's context.

Closing this issue, feel free to open new one if you have further questions.
