### ISSUE TITLE
tailwindcss/typography (prose) not working on docs theme

### ISSUE THREAD

**Issue by sindrepm** [nuxt/content#863]
### Version
@nuxt/content: 1.14.0
@nuxt/content-theme-docs:  0.10.2
nuxt: v2.15.4

### Steps to reproduce

Create a new nuxt content docs theme following the instructions:

```
yarn create nuxt-content-docs <project-name>
cd <project-name>
yarn dev
```

### What is Expected?

Articles to be nicely formatted with Tailwindcss Typography out of the box. 

### What is actually happening?

No text formatting at all. "prose" classes are added to the markup but the CSS is empty so I assume the `tailwindcss/typography` module is not being included properly.

![](https://i.imgur.com/yngK4Wh.png)

### Other comments

This bug seems to have been introduced with v0.10.2 of @nuxt/content-theme-docs. If I downgrade to v0.10.1 it works as expected. I suspect it has to do with tailwindcss version conflict. I noticed v0.10.2 installs @tailwindcss/typography@0.4.0 whereas previous versions install @tailwindcss/typography@0.2.0

**Comment by halilduygulu** [comment]
Thanks a lot, I was looking for a working lib version set after wasting 2 hours for searching why my pages looks bad. 

```
  "dependencies": {
    "@nuxt/content": "1.14.0",
    "@nuxt/content-theme-docs": "0.10.1",
    "nuxt": "2.15.4"
```

**Comment by NozomuIkuta** [comment]
@sindrepm @halilduygulu 

FYR: 

I found that this issue related to #826.
Please refer to [my comment](https://github.com/nuxt/content/issues/826#issuecomment-907811325) if you want to know the details.
