### ISSUE TITLE
Setup docs theme on particular directory

### ISSUE THREAD

**Issue by bagaskarala** [nuxt/content#868]
I confused that in documentation at `Manual Setup` it said `Let's say we're creating the documentation of an open-source project in the docs/ directory.`. But the result is i cant access the documentation in `/docs` route. this theme applied globally. i want to apply this theme in `/docs` only, how to do that?

reference: https://content.nuxtjs.org/themes/docs/
i use project from this sandbox https://codesandbox.io/s/nuxt-content-docs-theme-playground-inwxb?from-embed

**Comment by halilduygulu** [comment]
Hi @bagaskarala , I was just reading this https://github.com/nuxt/content/issues/669 
looks like not possible for now.

**Comment by bagaskarala** [comment]
Thank u sir,,

I hope this will be possible soon 👍
