### ISSUE TITLE
Can I load the markdown files from a server

### ISSUE THREAD

**Issue by andyfensham** [nuxt/content#87]
I would like to know if I can load the markdown from a server.  I am creating a content site but  admin users will be allowed to create their own content.  At the moment with the examples I see, you have to create the markdown in dev mode and then do a nuxt generate / nuxt build and then upload to production server.

**Comment by benjamincanac** [comment]
You might want to take a look at [Netlify CMS](https://www.netlifycms.org/) or [Forestry](https://forestry.io/) to work with @nuxt/content.
