### ISSUE TITLE
Conditional rendering with v-if statements

### ISSUE THREAD

**Issue by robert-moore** [nuxt/content#873]
Is it possible to use `v-if` statements in `.md` files? For instance, I have this snippet below which will appear despite the falsy statement. I'm using other Vue global components perfectly fine.

```
<div v-if="false">
This is showing up
</div>
```

**Comment by ManasMadrecha** [comment]
No, templating and vue features are not supported currently in md files. See #829 .
But as global vue components are supported, so, as a workaround, to at least support templating you may create a slot based component. Full code here 👉🏻 #829
