### ISSUE TITLE
Target Server with serverMiddleware which adds content

### ISSUE THREAD

**Issue by fabianwohlfart** [nuxt/content#883]
I have an api as a nuxt serverMiddleware which creates entries to the /content folder on post requests.
I expected that $content fetches all entries, also the newly created ones.
In dev it works, build & start does not work: it only shows the entries which are available at build time.

Is this intended?
Is there a way to make it working?

nuxt.config.js
``` 
target: 'server',
ssr: true,
```

pages/index.vue
``` 
async asyncData ({ $content }) {
    const tests = await $content('tests').fetch()
    return {
      tests
    }
  }
```

**Comment by ManasMadrecha** [comment]
Did you try adding `{deep: true}` option inside `$content()`? If it still doesn't work, then the issue is something else.

**Comment by fabianwohlfart** [comment]
> Did you try adding `{deep: true}` option inside `$content()`? If it still doesn't work, then the issue is something else.

still does not work. as i understand deep is for searching in subdirectories. my problem is that $content does not fetch all entries in production (build + start) mode if i dynamically add articles (through a servermiddleware).

**Comment by fabianwohlfart** [comment]
finally solved it.
digged through the source code and found that there is watch property.
watch property is **not** named in the docs.
why? is there a downside to it?
will open an enhancement for this.

```
  content: {
    watch: true
  },
```

**Comment by ManasMadrecha** [comment]
@fabianwohlfart 
So, you have created a website where you can write content by log-in? And then you save the content inside some database or Github? Anyway, what you have done seems like a great feature.
Is your repo public? 😊

**Comment by fabianwohlfart** [comment]
unfortunately no... it will be a more complex api with users, orders and products, and i am just testing out if it makes sense to use $content: probably no, because it will expose all data to the public under /_content/: the data is sensible and $content does not have a method for authentification – which is also not the job of $content.

**Comment by ManasMadrecha** [comment]
@fabianwohlfart May the future `@nuxt/data` module may help you. #872

**Comment by fabianwohlfart** [comment]
it works fine with custom server middleware for authentification. thanks!
