### ISSUE TITLE
Feature Request for Docs Theme: More leveling in navigation

### ISSUE THREAD

**Issue by derHodrig** [nuxt/content#892]
The current behaviour is, we can group by category. This is only one level.

The requested behaviour will allow multiple level (maybe 3 to 5)

So we got this structure

```
Category1
- page1
- page2
- Category1_2
-- page 3
-- page 4
-- Category1_3
--- page 5
page 7 // <<<< root level
```

I hope you get the idea...
Maybe its possible to adjust the groupBy function in fetchCategories() so it will group by Category and paths?

What do you think about it?

**Comment by derHodrig** [comment]
Bois, I got it to work with 2 level Navigation.
Before I show you the solution, I am sorry for the code style, there are definitely better ways. If you refactor it with a better solution, let me know

First to the output
![image](https://user-images.githubusercontent.com/53934248/125611975-3aabe7ab-1289-453b-9815-41b39de1280e.png)

As you see in the left Navigation, we got the SubCategories:
In front matter just give a category and the subcategory

```
---
title: 'Seiten Bearbeiten'
description: 'Hier lernst du, wie du einfach Seiten in dieser Dokumentation bearbeitest.'
position: 13310
category: 'QSD-Doku'
subCategory: "Guides"
---
```

now edit the action `fetchCategories`

```js
async fetchCategories({ commit, state }) {
    // Avoid re-fetching in production
    if (process.dev === false && state.categories) {
      return
    }
    const docs = await this.$content({ deep: true })
      .sortBy('position', 'asc')
      .sortBy('title', 'asc')
      .fetch()

    const categories = {}
    docs.forEach((doc) => {
      if (doc.category) {
        categories[doc.category] = categories[doc.category]
          ? categories[doc.category]
          : {}
        if (doc.subCategory) {
          categories[doc.category].subCategories = categories[doc.category]
            .subCategories
            ? categories[doc.category].subCategories
            : {}
          categories[doc.category].subCategories[doc.subCategory] = categories[
            doc.category
          ].subCategories[doc.subCategory]
            ? categories[doc.category].subCategories[doc.subCategory]
            : {}
          categories[doc.category].subCategories[doc.subCategory][doc.slug] =
            doc
        } else {
          categories[doc.category][doc.slug] = doc
        }
      } else {
        categories[doc.slug] = doc
      }
    })

    commit('SET_CATEGORIES', categories)
  },
```
(I know, shame on me, its quick and dirty, but it works)

> In my case, I removed the i18n selection

In the template there is something bad happening.

```vue
      <template v-for="(category, categoryIdx) in categories">
        <v-list-group
          v-if="categoryIdx !== 'undefined'"
          :key="categoryIdx"
          no-action
          :value="activatedRoute === categoryIdx"
          @contextmenu="show"
        >
          <template #activator>
            <v-list-item-title>{{ categoryIdx }}</v-list-item-title>
          </template>
          <template v-for="doc of category">
            <template v-if="doc.slug"> <<<<<<<<<<<<<<<<<<<<
              <v-list-item
                :key="doc.slug"
                nuxt
                :to="localePath(doc.path)"
                color="primary"
              >
                <v-list-item-title
                  v-text="doc.menuTitle || doc.title"
                ></v-list-item-title>
              </v-list-item>
            </template>
            <template v-else>
              <template v-for="(subCategory, subCategoryIdx) in doc"> <<<<<<<<<<<<<<<<<<<
                <v-list-group
                  v-if="subCategoryIdx !== 'undefined'"
                  :key="subCategoryIdx"
                  no-action
                  sub-group
                  :value="activatedRoute === subCategoryIdx"
                  @contextmenu="show"
                >
                  <template #activator>
                    <v-list-item-title>{{ subCategoryIdx }}</v-list-item-title>
                  </template>

                  <template v-for="doc of subCategory">
                    <v-list-item
                      :key="doc.slug"
                      nuxt
                      :to="localePath(doc.path)"
                      color="primary"
                    >
                      <v-list-item-title
                        v-text="doc.menuTitle || doc.title"
                      ></v-list-item-title>
                    </v-list-item>
                  </template>
                </v-list-group>
              </template>
            </template>
          </template>
        </v-list-group>
        ...
      </template>
```

We are iterating through all docs in categories by default. To figure out our subCategories, we have to ask "is there a slug?"(since every doc has a slug) if not, its our subcategory object.

**I do not like the solution and there must be rework.**

The day as we can create subcategories by the folder structure, I'm very happy!

**Comment by jsonUK** [comment]
Having more than 1 level for navigation is going to be a must for us some point in the near future.

The routing should really be informed from the folder structure. I also have issues with "position" giving inconsistent results, and if you have more than 10 pages, will be a nightmare to maintain when you need to re-order stuff.

Propose this is defined as a feature for a future version of Nuxt Content Docs Theme.

**Comment by wickstargazer** [comment]
hi guys, is this possible yet? Thankz

**Comment by Tahul** [comment]
Hey there!

This has been added into `docus` which will be the replacement of `@nuxt/content-theme-docs` for Nuxt3.

You will be able to configure the depth at which your navigation start on your pages via:

```ts
const themeConfig = {
   aside: {
      level: integer
   }
}
```

@nuxt/content v2 also includes a navigation feature that will help you build complex navigations out of your content with ease!

I'm closing this for now, but feel free to re-open with according PR targeted at `v1` branch as we won't be adding this as part of @nuxt/content roadmap.

**Comment by xarthurx** [comment]
> Hey there!
> 
> This has been added into `docus` which will be the replacement of `@nuxt/content-theme-docs` for Nuxt3.
> 
> You will be able to configure the depth at which your navigation start on your pages via:
> 
> const themeConfig = {
>    aside: {
>       level: integer
>    }
> }
> @nuxt/content v2 also includes a navigation feature that will help you build complex navigations out of your content with ease!
> 
> I'm closing this for now, but feel free to re-open with according PR targeted at `v1` branch as we won't be adding this as part of @nuxt/content roadmap.

In Docus `v4` and Nuxt Content `v3`, this feature doesn't work anymore.

https://github.com/nuxt-content/docus/issues/1185
