### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by savyjs** [nuxt/content#893]
Hi,
I want to use DOCS theme to build an RTL documentation site. 
is there any option to make theme right-to-left?

Thanks

**Comment by NozomuIkuta** [comment]
@savyjs 

Unfortunately, the current Theme Docs supports only LTR styles.
This is due to limitations of Tailwind CSS rather than Theme Docs itself.

It would be worth taking a look at conversation in #615.

**Comment by farnabaz** [comment]
Hey there 👋 

`@nuxt/content-theme-docs` is moving away and will not get any updates, very soon we will open-source Docus, a brand new theme based on Nuxt 3 and Content v2 with lots of improvements and new features. 

Closing this issue in favor of the new docs theme. Keep an eye on #726 for updates
