### ISSUE TITLE
Scoped slots in markdown doesn't receive props

### ISSUE THREAD

**Issue by NozomuIkuta** [nuxt/content#900]
### Version
@nuxt/content: v1.14.0
nuxt: v2.15.6

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/nuxt-content-900-reproduction-9nmp5)

### Steps to reproduce

If you modify `index.md` to use the scoped data, the app will break.

### What is Expected?

According to Vue 2.1.0+ spec, type of `vm.$scopedSlots` is `{ [name: string]: props => Array<VNode> | undefined }`.
So each property is a function that receives `props` from the context.

But, Nuxt Content compiles a scoped slot in markdown to a function without argument:

https://github.com/nuxt/content/blob/939caf36c547a6b4af6e303c52ed5989a5dea2f0/packages/content/templates/nuxt-content.js#L72-L76

This part should have been defined like the below:

```javascript
data.scopedSlots[name] = function (props) {
  return template.content.map(tmplNode => processNode(tmplNode, h, props))
}
```

Note that, if a property can't be resolved in `props`, then Nuxt Content will have to try to resolve it in `doc`, so the code above is not enough.

### What is actually happening?

Scoped slots in markdown are not compiled correctly.
They don't receive any argument from the context.

### References

I found this bug while I was looking into #899.
That and this issue seem to derive from the same part of Nuxt Content, so they may be fixed at once.

**Comment by gsjen** [comment]
This is a known limitation and is mentioned in the [docs](https://content.nuxtjs.org/writing#vue-components).

 With that said, as you point out it seems like slot props can fairly easily be supported. I'm using them in my project using a modified version of `nuxt-content`. I posted my version [here](https://github.com/nuxt/content/issues/829#issuecomment-847250807). The only issue with it is that props in the `doc` will take precedence over slot props, however there is an easy workaround by simply renaming the slot prop.

**Comment by NozomuIkuta** [comment]
@gsjen 

> This is a known limitation and is mentioned in the docs.

Oops, I missed the part. 🙏 

While it looks easy at glance, and your code seems to work, I doubt that things may get complicated in some cases (e.g. nested component in scoped slots).
Another point I'm worried about is the phrase "a couple of caveats from rehype-raw" in [documentation](https://content.nuxtjs.org/writing/#vue-components):

> Since @nuxt/content operates under the assumption all Markdown is provided by the author (and not via third-party user submission), sources are processed in full (tags included), with a couple of caveats from rehype-raw:

I guess authors tried to support it and finally abandoned for some reasons that we are missing. 🤔

**Comment by gsjen** [comment]
@NozomuIkuta Ok you piqued my curiosity. The PR to support slots is [here](https://github.com/nuxt/content/pull/121). It mentions slot props can't be supported due to "parser limitations". However even with the default rehype/remark plugins my slot props work, so there may have been an upstream change that "fixed" the parser. I think the caveats you quoted from the docs concerns processing potentially harmful HTML (XSS attack), but this risk exists regardless of the existence of slot props.

> I doubt that things may get complicated in some cases

I agree there are probably edge cases (indeed my code does not handle nested slot scopes), but slot props give so much power and flexibility that supporting them is worth dealing with the fallout IMO.

**Comment by NozomuIkuta** [comment]
This issue is about Nuxt Content v1 and has been stale.
