### ISSUE TITLE
`nuxt-image` integration

### ISSUE THREAD

**Issue by LukaHarambasic** [nuxt/content#911]
### Is your feature request related to a problem? Please describe.

I would like to use the default markdown image syntax (`![]()`), but still benefit from https://github.com/nuxt/image. 

### Describe the solution you'd like

Add a `nuxt-image` integration for markdown files and add a flag to enable it.

### Describe alternatives you've considered

Currently, I'm using `<nuxt-picture>` directly in my markdown files. It works but adds a dependency to nuxt, and I'm just a big fan of writing plain Markdown as much as possible ([example](https://github.com/LukaHarambasic/harambasic.de/commit/a8749fb1c7879652c80379d901b865dddbb4b86b#diff-b4c784f9c12032fd4fcd059df73eaf786f2d3029bccf743fcf5036f86b7cb2a8R57)).

### Additional context

If https://github.com/nuxt/content/issues/705 gets implemented, this would be easy to implement on my own, but I still think an in-house solution strengthening the nuxt eco-system would be preferable.

**Comment by ManasMadrecha** [comment]
@LukaHarambasic 
You can still do it using this https://github.com/nuxt/content/issues/106#issuecomment-778342600

Just add a custom rehype plugin. As `![]()` syntax is actually converted to `<img/>`, so in that plugin, you can convert all such `<img/>` tags to `<nuxt-img>` tags. The above link shows how to do this.

**Comment by LukaHarambasic** [comment]
@ManasMadrecha thanks a lot! That was exactly what I was looking for! 

> But, personally, using ![]() syntax is very less useful, as you can't even add anything other than alt in it like width or height. So, what you can do is add the above rehype plugin and use normal HTML <img> tag syntax. This way your docs will not be dependent on Nuxt, but at the same time, the images will be optimized with nuxt-img.

I'm quite happy with `![]()` and never set a width or height :)
