### ISSUE TITLE
How to import custom `data` into `.md` files?

### ISSUE THREAD

**Issue by ivodolenc** [nuxt/content#918]
Hi, is it possible to import custom `data` into `.md` files?

I have a lot of pages and want to generate html tables from custom `data` objects, so I believe the best solution is to create  `getData.js` file and later import a specific object from that util file to a page that will generate tables from the custom component.

I'm currently importing data into a component and then manipulating it using `props`, but as the data grows, it becomes more and more complicated and hard to maintain.

Something like this would be perfect:

```sh
# '.md' file

---
title: Title
description: Lorem ipsum...
position: 204
category: Category

# Data: Object
data: require('~/utils/getData.js')
---

## Title

# Table with data
<custom-component :set="data"></custom-component>

# ... 
```

I also tried to import the data into the `_slug.vue` (inside `data()`) template and into `publicRuntime` but can't access them in `.md` files (throws error or undefined).

Any advice is welcome.

**Comment by derHodrig** [comment]
https://content.nuxtjs.org/themes/docs#list

IDK if this could be a solution.

In docusaurus you can import the js direct in markdown. maybe try 
import data from ....
under the last  "---"

**Comment by ivodolenc** [comment]
@derHodrig thanks for reply, but this doesn't work as expected.

> import data from ....
> under the last "---"

```sh
---
title: Title
description: Lorem ipsum...
position: 204
category: Category
---

import data from '~/utils/getData.js'

```
Recognizes `import` line as plain text. 

> In docusaurus you can import the js direct in markdown. 

Yes, in `.mdx` format you can directly `import` in the md

**Comment by NozomuIkuta** [comment]
As @derHodrig said, you can define some data in [front matter of markdown files](https://content.nuxtjs.org/writing#front-matter).

If you want to extend _document_ objects further more, you can use [content:file:beforeInsert](https://content.nuxtjs.org/advanced#contentfilebeforeinsert) hook.

Nuxt's hook accepts async functions as well, so you can fetch data from somewhere.

**Comment by ivodolenc** [comment]
@NozomuIkuta Thanks for the tips, [`content:file:beforeInsert`](https://content.nuxtjs.org/advanced/#contentfilebeforeinsert) is exactly what I'm looking for. A much simpler and cleaner solution than manipulating component `props`.

I'll share my example:

**getData.js example**

```js
// ./utils/getData.js

export default {
  a: {
    1: 'one',
    2: 'two',
    3: 'three'
  },
  b: {
    1: 'one',
    2: 'two',
    3: 'three'
  },
  c: {
    1: 'one',
    2: 'two',
    3: 'three'
  }
  // ...
}
```

**content:file:beforeInsert**

```js
// nuxt.config.js

export default {
  modules: ['@nuxt/content'],

  hooks: {
    'content:file:beforeInsert': document => {
      if (document.extension === '.md') {
        const getData = require('./utils/getData').default

        document.$customData = getData
      }
    }
  }
}
```

**Page One (`.md`)**

Now I can access `$customData` in `.md` pages.

```sh
---
title: Page One
description: Lorem ipsum...
position: 1
category: Category
---

## Title

# Generates table from -> '$customData.a' object
<custom-component :set="$customData.a"></custom-component>

# Generates table from -> '$customData.b' object
<custom-component :set="$customData.b"></custom-component>

# etc ...

# other content and components ...
```

**Page Two (`.md`)**

```sh
# Page Two

---
title: Page Two
description: Lorem ipsum...
position: 10
category: Category
---

## Title

# Generates table from -> '$customData.b' object
<custom-component :set="$customData.b"></custom-component>

# Generates table from -> '$customData.c' object
<custom-component :set="$customData.c"></custom-component>

# etc ...

# other content and components ...
```
