### ISSUE TITLE
Rendering a Markdown string

### ISSUE THREAD

**Issue by remino** [nuxt/content#924]
Is there a way, like a Nuxt plugin or Vue component, @nuxt/content provides to let you reuse its instance of remark to render a single Markdown string?

**Comment by LukaHarambasic** [comment]
I also would be interested in a solution as I right now use marked: https://github.com/LukaHarambasic/harambasic.de/blob/main/nuxt.config.js#L199

**Comment by ChristianMurphy** [comment]
@LukaHarambasic offers a good work around, I would add that for consistency consider using https://github.com/micromark/micromark as the markdown parser/transformer.
Nuxt content uses remark/micromark
https://github.com/nuxt/content/blob/0b6a7be6f6287cde880b0d37c88e6461efa167ff/packages/content/package.json#L47
(and https://github.com/remarkjs/remark/releases/tag/13.0.0) to handle markdown.
Using the same parser/transformer for all content can guarantee the content will render the same way no matter where/how it is loaded on the page.

**Comment by LukaHarambasic** [comment]
> Using the same parser/transformer for all content can guarantee the content will render the same way no matter where/how it is loaded on the page.

How can it be guaranteed? I'm not sure what magic does nuxt/content, okay we could look it up, but then we still need a way to get the same instance or an instance with the same options. 
Not relevant for my use case at all, just thinking out loud :)

**Comment by ChristianMurphy** [comment]
npm/yarn modules are singletons.
if you don't install micromark at the top level, importing `micromark` will get the same instance of micromark that nuxt/content is using.
You're right that nuxt applies some plugins on top, which may change the content https://github.com/nuxt/content/blob/939caf36c547a6b4af6e303c52ed5989a5dea2f0/packages/content/lib/utils.js#L14-L26
You could go a level higher in abstraction and use remark and rehype with these same plugins.

However, even without the plugins `micromark` and `marked` have some differences in how they parse markdown.
Both aim to implement the CommonMark standard, but marked still has several unresolved commonmark bugs (https://github.com/markedjs/marked/issues?q=is%3Aissue+is%3Aopen+commonmark+label%3A%22parser%3A+CommonMark%22) which can cause content to be parsed different.

**Comment by CaptainFalcon92** [comment]
Hello.

I would like to add my own interest to this question.

I too would like to display markdown just like nuxt/content does, but loaded from an api call.
Obviously all i get from the api is a string - and not an object compatible with :
```
<NuxtContent :document="{ body: product.description }" />
```

This won't work because `product.description` is a markdown string.
That means i would first need to use the same markdown parser that nuxt/content uses.

Is there a way for us to use the power of the NuxtContent component while having markdown not fetched from the content directory ? (i.e. from api calls).

I can't use a different rendered because i wish to include components inside my markdown just like nuxt/content supports.

thanks !

**Comment by cingh-jasdeep** [comment]
Sat Sri Akal ji

Isn't this solved here?
https://content.nuxtjs.org/advanced#contentfilebeforeinsert

**Comment by rrrepos** [comment]
I too would be interested since the solution I am adopting is using  `@nuxtjs/markdownit'` module,

```
<div v-html="$md.render(blog.description)"></div>
```

However, this fails when the markdown string has a reference to an image that is stored within the blog content page directory

```
// markdown
...
<img src="images/img.png">

![blog image](images/img.png)

```

**Comment by abreumatheus** [comment]
> Hello :)
> 
> This should be solved by `<Markdown />` component provided by @nuxt/content v2.
> 
> I am closing this issue as there is no plan to provide this feature for v1 versions.
> 
> Feel free to reopen with a PR if you manage to add this in v1.
> 
> You can find documentation about this feature for v2 here: https://content-v2.nuxtjs.org/guide/syntax/mdc#markdown-rendering
@Tahul 

I don't understand how this would be solved using the `<Markdown />` component, as it seems to act as a substitute to a slot. Could you provide an example of how to render a string using the compoment? Also, the link you posted is broken.

**Comment by timgoeller** [comment]
I'd like to push this aswell, since the answer does indeed not solve the problem stated in the issue. There was a way to import and use the Markdown Parser in the old version of nuxt content, but the new version does not export it anymore.

**Comment by Lyokolux** [comment]
> Hello :)
> 
> This should be solved by `<Markdown />` component provided by @nuxt/content v2.
> 
> I am closing this issue as there is no plan to provide this feature for v1 versions.
> 
> Feel free to reopen with a PR if you manage to add this in v1.
> 
> You can find documentation about this feature for v2 here: https://content-v2.nuxtjs.org/guide/syntax/mdc#markdown-rendering

How can I solve it? I have a string as input, but I don't see how can I use it.

**Comment by yehuda-hybiz** [comment]
I also needed this, and figured it out by source diving 😇

Here is a minimal working example:
```js
import markdownParser from "@nuxt/content/transformers/markdown";

const markdownString = '<your-markdown-string>'

const parsedMarkdown = await markdownParser.parse(
    `<some-id>`,
    markdownString
);
```
Your `parsedMarkdown` AST can then be rendered like so:

```vue
<ContentRenderer :value="parsedMarkdown" />
```

**Comment by Yiddishe-Kop** [comment]
I also needed this, and figured it out by source diving 😇

Here is a minimal working example:
```js
import markdownParser from "@nuxt/content/transformers/markdown";

const markdownString = '<your-markdown-string>'

const parsedMarkdown = await markdownParser.parse(
    `<some-id>`,
    markdownString
);
```
Your `parsedMarkdown` AST can then be rendered like so:

```vue
<ContentRenderer :value="parsedMarkdown" />
```

**Comment by Flowko** [comment]
if you wanna use `ContentDoc` try `transformContent` instead,
its kinda the same as the above code, but i had issues related to code highlight, and `transformContent` seems to fix the issue

```vue
<template>
<ContentDoc v-slot="{ blogContent }" />
</template>

<script setup lang="ts">
import { transformContent } from "@nuxt/content/transformers/index";

const { data: blog, error } = await useFetch<Blog>(
  () => `/blog/blog-details/${slug}`,
  {
    baseURL: config.public.baseURL,
    initialCache: false,
  }
);

const blogContent = await transformContent(
  "blog-content",
  blog.value.content
);
</script>

```

**Comment by unguul** [comment]
I don't understand why this is closed. It's still not clear what is the *official* way of just rendering some markdown that does not come from a file.

**Comment by green-mike** [comment]
Need to parse string content by same parser and plugin in some condition. It would be useful if repo export parser or component.

**Comment by Mnigos** [comment]
> ```js
> import markdownParser from "@nuxt/content/transformers/markdown"
> ```

Cannot import from "@nuxt/content/transformers/markdown" - module not found

**Comment by fr-eed** [comment]
> > ```js
> > import markdownParser from "@nuxt/content/transformers/markdown"
> > ```
> 
> Cannot import from "@nuxt/content/transformers/markdown" - module not found
This worked for me 

```js
<template>
  <ContentRenderer :value="parsedMarkdown" />
</template>

<script>
import { defineComponent } from 'vue'

import markdownParser from '@nuxt/content/transformers/markdown'

export default defineComponent({
  components: {},

  // define props
  props: {
    md: {
      type: String,
      default: '',
    },
    cid: {
      type: String,
      default: '<some-id>',
    },
  },

  // init
  async setup(props) {
    return {
      parsedMarkdown: await markdownParser.parse(props.cid, props.md),
    }
  },
})
</script>


```

**Comment by Lyokolux** [comment]
> > ```js
> > import markdownParser from "@nuxt/content/transformers/markdown"
> > ```
> 
> Cannot import from "@nuxt/content/transformers/markdown" - module not found

Which version are you using?
and @fr-eed too

**Comment by fr-eed** [comment]
> > > ```js
> > > import markdownParser from "@nuxt/content/transformers/markdown"
> > > ```
> > 
> > 
> > Cannot import from "@nuxt/content/transformers/markdown" - module not found
> 
> Which version are you using? and @fr-eed too

"@nuxt/content": "2.3.0"

**Comment by garbit** [comment]
I'm also having the same issue on v2.3.0

**Comment by piscis** [comment]
I'm using `@nuxt/content` v2.4.3 and it still works. I noticed that if you're not registering @nuxt/content in your nuxt.config.ts then the parser does not work.

**Step one:**
Install @nuxt/content
```
pnpm i -D @nuxt/content
```

**Step two:**
Add nuxt content to your modules section
```typescript
export default defineNuxtConfig({
  modules: [
  ...
    '@nuxt/content',
  ],
...
```

**Step three:**
Implement a component that uses the markdown parser 
```vue
<script setup lang="ts">
// @ts-expect-error avoid lint error
import markdownParser from '@nuxt/content/transformers/markdown'

export interface MarkdownRenderProps {
  md?: string
  cid?: string
}
const props = withDefaults(defineProps<MarkdownRenderProps>(), { md: '', cid: '<some-id>' })
const parsedMarkdown = await markdownParser.parse(props.cid, props.md)
</script>

<template>
  <ContentRenderer :value="parsedMarkdown" v-bind="$attrs" />
</template>

```

**Comment by Elektronenhirn108** [comment]
Same problem for me: @nuxt/content/transformers/markdown does not exist.

**Comment by sevspo** [comment]
Same here: Same problem for me: @nuxt/content/transformers/markdown does not exist.

**Comment by ManUtopiK** [comment]
I'm wondering how to convert the `parsedMardown` to html ? I need to pass this html to a tiptap editor.
Or how you can programmatically use `ContentRender` to get the html output ?

**Comment by kwiat1990** [comment]
It seems like overwriting default prose components with `components/content/Prose<something>.vue` doesn't work for this solution. Did anybody also encounter such a problem?

**Comment by leminhluan4244** [comment]
Same here: Same problem for me: @nuxt/content/transformers/markdown does not exist.
This version: `"@nuxt/content": "^2.6.0"`
```typescript
import markdownParser from "@nuxt/content/transformers/markdown";

const markdownString = '<your-markdown-string>'

const parsedMarkdown = await markdownParser.parse(
    `<some-id>`,
    markdownString
);
```
Error message: Cannot find module '@nuxt/content/transformers/markdown' or its corresponding type declarations.ts(2307)

**Comment by piscis** [comment]
Maybe this helps to get thinks started:

[CodeSandbox Demo](https://codesandbox.io/p/github/piscis/nuxt3-markdown-renderer-codingsandbox/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clindmnfa000b3b6mcgwwd4q1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clindmnfa000d3b6m8azwer63%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clindmnfa000b3b6mcgwwd4q1%2522%253A%257B%2522id%2522%253A%2522clindmnfa000b3b6mcgwwd4q1%2522%252C%2522activeTabId%2522%253A%2522clinfn6k500hi3b6m1wup1v46%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clindmnfa000a3b6mkny3e00a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522cline32xp00443b6mngcmzd64%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fnuxt.config.ts%2522%252C%2522id%2522%253A%2522clinfn6k500hi3b6m1wup1v46%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clindmnfa000d3b6m8azwer63%2522%253A%257B%2522id%2522%253A%2522clindmnfa000d3b6m8azwer63%2522%252C%2522activeTabId%2522%253A%2522clinfjsdt00613b6m76cya7ha%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clinfjsdt00613b6m76cya7ha%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clinfjtrc00bl3b6ml5jf81i6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A4000%252C%2522id%2522%253A%2522clinfjva700e83b6m2pochdry%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

[Git Repo](https://github.com/piscis/nuxt3-markdown-renderer-codingsandbox)

**Comment by ManUtopiK** [comment]
> Maybe this helps to get thinks started

Thanks @piscis for your demo!

Personally, I tried this and it works perfectly!
But this is not I am looking for exactly.

I don't want to render the output in the page. I want the **HTML output** of the rendered markdown to pass this HTML to some libraries like tiptap editor.
`markdownParser.parse()` under the hood use remark to convert markdown to `mdast` (Markdown Abstract Syntax Tree), and a custom nuxt-content rehype plugin that convert this `mdast` to an `hast` (HTML Abstract Synt...).
This `hast` is used by the `ContentRendererMarkdown` component to output the html using Vue VNode.
Actually, there's no way to get the HTML output on the process. We should build our own parser with `rehypeStringify` for example.

**Comment by Rosinida** [comment]
Thanks @piscis for your demo.

Would it be possible to use this setup for in place rendering as well?
I would like to use something a textarea field for rendering Md in realtime.

**Comment by mimoo** [comment]
do you guys know how to use nice syntax highlighting when doing this?

**Comment by thaycacac** [comment]
It worked for me https://codesandbox.io/p/github/piscis/nuxt3-markdown-renderer-codingsandbox/main?file=/app.vue:12,1-12,74
with version 2.7.0

**Comment by tveimo** [comment]
It's now possible to use @nuxtjs/mdc instead, see details here; https://github.com/nuxt-modules/mdc, essentially you'll do
```
import { parseMarkdown } from '@nuxtjs/mdc/runtime'

async function main(mdc: string) {
  const ast = await parseMarkdown(mdc)

  // Do your magic with parsed AST tree

  return ast
}
```

**Comment by AleeeKoi** [comment]
> It's now (since nuxt/content v2.8.1 / @nuxtjs/mdc v0.1.3) possible to use @nuxtjs/mdc instead, see details here; https://github.com/nuxt-modules/mdc, essentially you'll do
> 
> ```
> import { parseMarkdown } from '@nuxtjs/mdc/runtime'
> 
> async function main(mdc: string) {
>   const ast = await parseMarkdown(mdc)
> 
>   // Do your magic with parsed AST tree
> 
>   return ast
> }
> ```

Hi @tveimo ! Cool, in my case I already switched to `vue-showdown` creating a custom component.

Are there any significant differences with `@nuxtjs/mdc` ?

**Comment by adamalfredsson** [comment]
With `@nuxt/content/transformers/markdown`, how does one use the remark/rehype plugins as defined in the `nuxt.config` file?

**Comment by marquaye** [comment]
> It's now (since nuxt/content v2.8.1 / @nuxtjs/mdc v0.1.3) possible to use @nuxtjs/mdc instead, see details here; https://github.com/nuxt-modules/mdc, essentially you'll do
> 
> ```
> import { parseMarkdown } from '@nuxtjs/mdc/runtime'
> 
> async function main(mdc: string) {
>   const ast = await parseMarkdown(mdc)
> 
>   // Do your magic with parsed AST tree
> 
>   return ast
> }
> ```

With v0.2.8 of @nuxtjs/mdc it is even simpler. Just use their ```<MDC />``` component

```
<script setup lang="ts">
const exampleMarkdownString = `##Hello MDC`
</script>

<template>
  <MDC :value="exampleMarkdownString" tag="article" />
</template>
```

**Comment by bbhxwl** [comment]
The following code can run normally, but there are warnings. How should I handle this?

<img width="813" alt="截屏2024-02-21 23 59 56" src="https://github.com/nuxt/content/assets/26525599/c6dea402-4c6e-4c24-93ca-2ff7ebdeee36">

**Comment by jeannen** [comment]
This works fine, but it seems like line breaks are not properly parsed. One line break = Ignored, 2 line break only works but for the first one
![image](https://github.com/nuxt/content/assets/4388849/880f7c90-2a3d-44c0-b5ec-791e00f67418)

**Comment by FabianMontoya** [comment]
> The following code can run normally, but there are warnings. How should I handle this?
> 
> <img alt="截屏2024-02-21 23 59 56" width="813" src="https://private-user-images.githubusercontent.com/26525599/306689631-c6dea402-4c6e-4c24-93ca-2ff7ebdeee36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNzIwMTgsIm5iZiI6MTcxODA3MTcxOCwicGF0aCI6Ii8yNjUyNTU5OS8zMDY2ODk2MzEtYzZkZWE0MDItNGM2ZS00YzI0LTkzY2EtMmZmN2ViZGVlZTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAyMDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MTI2MzkyZjgxMzYwYjE2NjhjNzFkYWM4YTgxODdkNmJjMmM2N2Q4YThmMGNmNDM0YWVmODJmM2FjYmMwZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UrQc3_cjmOKdpbZdH5bj90y8HJ80eO7sbdzWEbk_ezo">

I'm having the same issue:

![image](https://github.com/nuxt/content/assets/37662924/0c97cd1b-729c-4b0a-929b-acf2c5aa60f3)

**Comment by alex-eri** [comment]
Markdown support moved to https://nuxt.com/modules/mdc
