### ISSUE TITLE
conponent overridding issues 

### ISSUE THREAD

**Issue by vishnu-facilio** [nuxt/content#930]
Component overridding dosen't support inn npm run generate ........it's through error in npm run generate

**Comment by NozomuIkuta** [comment]
Would you provide a reproduction or a link to your repository?

**Comment by vishnu-facilio** [comment]
@NozomuIkuta https://github.com/facilio/facilio-script-docs

**Comment by NozomuIkuta** [comment]
I got a NOT FOUND error.
It is a private repository, isn't it?
