### ISSUE TITLE
How to Set-up Releases page in nuxt-content-docs 

### ISSUE THREAD

**Issue by AmolDerickSoans** [nuxt/content#931]
Hello ,Can someone tell me how to set up releases page in nuxt-content-docs  that shows content from CHANGELOG.md . Thanks!

**Comment by NozomuIkuta** [comment]
According to #367, the team says they will support it in the next version of Theme Docs.
If I'm correct, [they are now migrating Theme Docs to Nuxt v3](https://github.com/nuxt/content/issues/726#issuecomment-883511183), so your documentation would have to migrate as well.
