### ISSUE TITLE
Installing nuxt-content-docs with NPM is broken

### ISSUE THREAD

**Issue by jsonUK** [nuxt/content#935]
### Version
@nuxt/content-theme-docs: **v0.10.1**
nuxt: **v2.15.2**

FYI - Running
npm **v7.16.0**
node **v14.15.4**

### Steps to reproduce
Followed the install instructions for NPM - ended up with a test site https://localhost:3000 with no CSS theme.
On a fresh start, I did what was asked `npm init nuxt-content-docs` - set the installer as `npm` and then run `npm run dev`, and the theme was blank.

I replicated the same steps using `yarn` and got the expected theme output.

### What is Expected?
Not to be broken when building with `npm`.

### What is actually happening?
Setting up project from scratch with `npm` as the primary builder is broken.

**Comment by NozomuIkuta** [comment]
@jsonUK 

Did you get PostCSS errors in Terminal as described in #826?
If so, let us unify the issue to #826 by closing this issue.

**Comment by jsonUK** [comment]
Correct. Believe this issue is most likely the one and the same. Thanks 👍
