### ISSUE TITLE
Styling broken with docs theme 0.10.0+

### ISSUE THREAD

**Issue by deanpcmad** [nuxt/content#936]
The documentation styling is broken in 0.10.0 and above.

### Version
@nuxt/content-theme-docs:  0.10.0
@nuxt/content: 1.12.0
nuxt: 2.15.2

### Steps to reproduce
Create a new docs site using `yarn create nuxt-content-docs` and run

### What is actually happening?
Screenshot below:

![Screenshot from 2021-07-30 14-02-31](https://user-images.githubusercontent.com/425200/127657229-4cc08eb7-0f15-4bd7-a52c-e15a7996a9bc.png)

In 0.9.0 it works fine:

![Screenshot from 2021-07-30 14-08-54](https://user-images.githubusercontent.com/425200/127657476-3cf94141-ec67-493b-9a20-5a2ee9fbb912.png)

**Comment by pranavxc** [comment]
Downgrade `@tailwindcss/typography` to `0.2.0`

```
npm i @tailwindcss/typography@0.2.0
```

**Comment by NozomuIkuta** [comment]
@deanpcmad @pranavxc

FYI: you can fix it just by upgrading Theme Docs to v0.11.x because it came to depend on the compatible versions of Tailwind packages.
