### ISSUE TITLE
Invalid anchor links when router base is non-default

### ISSUE THREAD

**Issue by PeterPetrik** [nuxt/content#938]
### Version
@nuxt/content: v0.10.2
nuxt:  2.15.7

### Steps to reproduce

I want to serve the documentation in subfolder `/docs/` so I set the 

```
  router: {
    base: '/docs/'
  },
```
in nuxt.config.js

### What is Expected?

If I click on any anchor (`##` -> h2), it generates page `<domain>/<base>/<markdown_file>#<anchor_name>`

### What is actually happening?

if generates  `<domain>/<base>/#<anchor_name>`

**Comment by NozomuIkuta** [comment]
@PeterPetrik 

Please refer to #376, and reopen this issue if you think they are different.
