### ISSUE TITLE
Anyway to override translation for docs theme?

### ISSUE THREAD

**Issue by mauricioralcala** [nuxt/content#939]
I want to change some strings in the es-ES.js file but if I do it within the docs theme i18n folder, it wouldn't get committed to git and it would get overwritten if I update the module.

Anyway to override a language file in my projects root directory?

Ideally I'd like to create a i18n folder in my project's root and have my nuxt.config.js point to that directory.

**Comment by NozomuIkuta** [comment]
Neither Theme Docs nor [nuxt-i18n module](https://i18n.nuxtjs.org/) doesn't support overriding objects for now.

One way is to achieve that is to create a patch for Theme Docs package by [patch-package](https://www.npmjs.com/package/patch-package), for example.

Every time you `install`, `patch-package` will modify Theme Docs with the patch you have created.
