### ISSUE TITLE
Please update the unified 10.x 

### ISSUE THREAD

**Issue by yuriti** [nuxt/content#941]
Many "remarks" have applied ESM, but, unfortunately, their application becomes impossible, I hope it will be possible in the future.

**Comment by ChristianMurphy** [comment]
Unified, Remark, and Remark plugins are in the process of a major version update (update is nearly complete) unifiedjs/unified#121
The ecosystem is adding JSDoc based TypeScript types, using ESM packaging, and adopting more ES6 syntax.

Mixing plugins from before and after the major release, may work or may not work, for example https://github.com/nuxt/content/issues/771#issuecomment-894126676 does not

To update to the latest version, several packages would need to be updated together: all the `unified`, `remark-*`. `unist-*`, and `mdast-*` dependencies need to upgrade to the latest major together as a group.
https://github.com/nuxt/content/blob/0b6a7be6f6287cde880b0d37c88e6461efa167ff/packages/content/package.json#L40-L52
https://github.com/nuxt/content/blob/0b6a7be6f6287cde880b0d37c88e6461efa167ff/packages/content/package.json#L33

Once they are upgraded, downstream adopters should update any `remark-*` plugins they have added to the latest major as well.

---

In the meantime, adopters can continue using the current `unified` and `remark` versions by pinning plugins to the major release _before_ the current latest.
Releases that are a part of the next major unifiedjs/unified#121 can be identified by the note on ESM and JSDoc in their changelog, for example https://github.com/remarkjs/remark-directive/releases/tag/2.0.0

**Comment by ChristianMurphy** [comment]
This also may depend on the broader ESM work in-progress in nuxt https://github.com/nuxt/nuxt.js/issues/9302

**Comment by yuriti** [comment]
@ChristianMurphy thanks for the detailed answer

**Comment by yuriti** [comment]
in case someone needs to update now, in which case you can write your own Markdown parser, this helps as a workaround

**Comment by ChristianMurphy** [comment]
> in case someone needs to update now, in which case you can write your own Markdown parser

It would be a lot easier to pin a version of the plugin compatible with the current parser, as noted in https://github.com/nuxt/content/issues/771#issuecomment-894126676
Or if you need the latest version of `remark`, to use the work around in https://github.com/nuxt/content/issues/921#issuecomment-877698146

Writing your own parser can be a fun programming exercise, but is quite complex to implement correctly (markdown as a lot of edge cases which are difficult to wrangle https://spec.commonmark.org/0.30/) and writing a parser to be fast/performant can also be challenging.
I'd strongly recommend using an existing, well tested, CommonMark parser like `remark`, `markdown-it`, or `marked`.

---

It's also worth noting all of the above are workarounds, upgrading nuxt/content to the latest versions of remark and unified would be a good solution long term.

**Comment by farnabaz** [comment]
Content v2 uses latest version of `unified` and fully supports ESM, but Content v1 will not get this update.  
Checkout migration docs: https://content.nuxtjs.org/guide/migration/from-v1
