### ISSUE TITLE
[content-theme-docs] Render Error thrown on `yarn generate` with default docs theme components 

### ISSUE THREAD

**Issue by MattieBelt** [nuxt/content#948]
### Version
@nuxt/content-theme-docs: v0.10.1
nuxt: v2.15.2
yarn: v1.22.5
node: v14.16.0

### Steps to reproduce
1. 
```bash
yarn create nuxt-content-docs my-project
```
2. 
```bash
cd my-project
```
3.
```bash
yarn generate
```

### What is Expected?
The generation should happen without errors. The default theme [components](https://content.nuxtjs.org/themes/docs/#components) should be usable with the `generate` command.

### What is actually happening?
An render error is throw that the "function or template not defined in component". This happens with all the default components.
![image](https://user-images.githubusercontent.com/31662805/129479995-990b8949-a444-4385-b23f-b389af8f0597.png)
![image](https://user-images.githubusercontent.com/31662805/129479988-23fb2a0e-807a-42d8-912e-bdf7eb0e02fe.png)
 
 This only happens with the `generate` command, `yarn dev` renders the component correctly.

**Comment by MattieBelt** [comment]
These render errors also appear when running yarn generate on the @nuxt/content docs lmao.
https://github.com/nuxt/content/tree/main/docs

**Comment by PeterSchuhmann** [comment]
same here! right now i am not able to use any components inside a markdown file when running npm run generate. Using it in via npm run dev works without problems.

**Comment by PeterSchuhmann** [comment]
downgrading to "nuxt": "2.15.6" and  "@nuxt/components": "2.1.8" solved it for me. With yarn use: 
  "resolutions": {
    "nuxt": "2.15.6",
    "@nuxt/components": "2.1.8"
  }
in your package.json

**Comment by MattieBelt** [comment]
> downgrading to "nuxt": "2.15.6" and "@nuxt/components": "2.1.8" solved it for me. With yarn use:
> "resolutions": {
> "nuxt": "2.15.6",
> "@nuxt/components": "2.1.8"
> }
> in your package.json

Downgrading those packages also worked as a temporary solution for me. 👍🏼

**Comment by kkeisuke** [comment]
Updating `@nuxt/components` to v2.2.1 may help.
https://github.com/nuxt/components/issues/223
I've solved it.
