### ISSUE TITLE
Nuxt Content: Return Directory Structure

### ISSUE THREAD

**Issue by jcrawford** [nuxt/content#967]
I am looking to do what is attached as an image.

<img width="576" alt="question" src="https://user-images.githubusercontent.com/875341/134983637-dc7b530f-95e5-4ddf-9ec9-043ca4637f5f.png">

However, I have noticed that when my directory structure is like this

```
content/
    articles/
        javascript/
            nuxt/
                getting-startd-with-nuxt/
```
when I go to http://localhost:3000/_content/articles I only get an `[]` returned because there are no documents in the articles folder.  I was hoping that I would be able to get `javascript` as a value from that directory as I was hoping to dynamically generate my menu structure.

The addition of `deep: true` was nice which I found in #57 but it does not appear to return the directory names at all.

Is there a way to accomplish something like in the screen shot?

**Comment by rrrepos** [comment]
One relevance of this functionality is creating a drilled-down set of options for the user to reach the desired content. 

For example if the content can be navigated via: Courses >> Subjects >> Content of that subject, then the user can be presented by (a) List of courses to pick from, followed by (b) list of subjects of the selected course, and finally (c) list of content for that subject.

Something of that nature. 

To get around this,  I am creating a yaml file at each level which manually has a list of subdirectories in it and using that fetch to populate (a) and then (b). Not the most elegant way to do it

**Comment by Tahul** [comment]
Hey :)

This will be fully supported (and auto-generated from your content sources) in @nuxt/content v2!

We called this the `navigation` feature, which you can follow the documentation issue there: #1048

I am closing this as it'll be tracked in the issue linked above.
