### ISSUE TITLE
nuxt content with thousands of JSON data

### ISSUE THREAD

**Issue by ghost** [nuxt/content#978]
Hi guys.
I created a sample @nuxt/content static website with 10K movies data in JSON format. I want to deploy it to Netlify.
now when I go to the movie single, I open a developer console and look into the network tab. the website loads an 8MB payload.json file on every page that I use @nuxt/content data. on movies page and movie/_slug pages. what is this?
is this for search functionalities? there are also two .json files in "_nuxt/content" directory and one in "_nuxt\static\1634719196\movies" directory. what are these?

I have two problems with these files: one is the user must load these heavy files in the browser and also it takes a lot of resources to load and parse/process these files and two all of my website's data are compiled in a ready to crawl .json file. and a simple crawler could clone my website's data easily!

it is a sample project I want to expand to 500K movie files and more.

what can I do about that?
should I use @nuxt/content at all for this situation? or just move to a headless CMS?

**Comment by 684efs3** [comment]
Having the same problem. Would be great if content could fix this
