### ISSUE TITLE
Once i try to run the project after cloning it i get this error message, can anyone help? 

### ISSUE THREAD

**Issue by aws95** [nuxt/content#98]
FATAL  Both nuxt and nuxt-edge dependencies are installed! This is unsupported, please choose one and remove the other one from dependencies.                                          11:43:14  

  at Object.run (node_modules\@nuxt\cli-edge\dist\cli-index.js:3025:11)
  at Object.<anonymous> (node_modules\nuxt-edge\bin\nuxt.js:4:31)
  at Module._compile (internal/modules/cjs/loader.js:1138:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
  at Module.load (internal/modules/cjs/loader.js:986:32)
  at Function.Module._load (internal/modules/cjs/loader.js:879:14)
  at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
  at internal/main/run_main_module.js:17:47

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @nuxt/content@1.2.0 dev: `nuxt example`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @nuxt/content@1.2.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by thely** [comment]
What's your nuxt.config.js look like? How are you installing nuxt/content? It's best to install it via yarn/npm so it's in your package.json.

**Comment by aws95** [comment]
yes i installed it via npm, the project didn't come with a "nuxt.config.js" file plus this is how my package.json file looks like : 
![image](https://user-images.githubusercontent.com/49479997/83765511-8c1b2980-a67b-11ea-8a70-ac36d6a247cc.png)
![image](https://user-images.githubusercontent.com/49479997/83765562-9fc69000-a67b-11ea-9430-8bb91a4b5077.png)

**Comment by aws95** [comment]
my issue is that i wante dto clone this project : https://github.com/nuxt/content and run it, after i installed evrything with npm i ran : "npm run dev" and that error popped up,th eproject that already exists and that i cloned doesn't come with a nuxt.config file and this error keeps popping up : 
> @nuxt/content@1.2.0 dev C:\Users\ThinkPad\Desktop\Main\Job Trainer\nuxtContent\content
> nuxt example


 FATAL  Both nuxt and nuxt-edge dependencies are installed! This is unsupported, please choose one and remove the other one from dependencies.                                             15:53:49

  at Object.run (node_modules\@nuxt\cli-edge\dist\cli-index.js:3025:11)
  at Object.<anonymous> (node_modules\nuxt-edge\bin\nuxt.js:4:31)
  at Module._compile (internal/modules/cjs/loader.js:1138:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
  at Module.load (internal/modules/cjs/loader.js:986:32)
  at Function.Module._load (internal/modules/cjs/loader.js:879:14)
  at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
  at internal/main/run_main_module.js:17:47

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @nuxt/content@1.2.0 dev: `nuxt example`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @nuxt/content@1.2.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by benjamincanac** [comment]
@aws95 The project you cloned is the source code of the content module, you won't be able to use it this way. As mentioned @thely, you should try to create a Nuxt.js project and install the module following the [documentation](https://content.nuxtjs.org/installation).

Regarding the error you got, the content module uses `nuxt-edge` as a dev dependencies to run the example. You can't have `nuxt` and `nuxt-edge` installed at the same time. Did you ran a `npm install nuxt` beforehand?

**Comment by aws95** [comment]
yes i did, i installed everything using npm

**Comment by benjamincanac** [comment]
@aws95 If you installed `nuxt` locally, you have to deinstall it (`npm uninstall nuxt`) cause the library already installed `nuxt-edge` which is the preview version of `nuxt`.
