### ISSUE TITLE
There is a problem with the argument of $content in v1.3.0 TypeScript

### ISSUE THREAD

**Issue by naoki0719** [nuxt/content#99]
In Typescript, the argument of $content is `...args: String[]`.
Please allow String as well, since it is handled by Array.from(arguments).

**Comment by juliomrqz** [comment]
I'm getting this issue after upgrading to v1.3.0

![image](https://user-images.githubusercontent.com/1911993/83775531-6e3ecc00-a65d-11ea-8c40-16d2e4854c82.png)

**Comment by benjamincanac** [comment]
@juliomrqz Should be fixed in v1.3.1, let me know if it's still wrong!

**Comment by benjamincanac** [comment]
@naoki0719 What is your error? A rest parameter need to be of an array type.

**Comment by juliomrqz** [comment]
@benjamincanac. It's now fixed, thanks!

**Comment by naoki0719** [comment]
@benjamincanac We have confirmed that it works without any problems. thanks!
