### ISSUE TITLE
nuxt content in production doesn't render my data from content folder with fetch.

### ISSUE THREAD

**Issue by codemaoz90** [nuxt/content#994]
Hi all, I was using nuxt content to create a little blog for my page. But when I was developing in local it was running good, it fetchs and render my data that I create in content folder (JSON not MARKDOWN). However in production mode i cant fetch the data.

In localhost:
![image](https://user-images.githubusercontent.com/38266840/147156934-e4669c34-28d2-4b0b-ba52-53ef79605cd3.png)

In production: the console 
![image](https://user-images.githubusercontent.com/38266840/147157136-9d753b4d-2a07-453e-9b85-4e8f230b35ff.png)

I hope you can help me!! =D

**Comment by NozomuIkuta** [comment]
Community needs either of the following to answer to your question:

- Provide a link to repository with steps to reproduce
- Minimal reproduction that is a fork of https://codesandbox.io/s/nuxtcontent-demo-l164h
  - Update dependencies as needed

**Comment by codemaoz90** [comment]
Hi, @NozomuIkuta for not provide a link to my reposoritory, its because if private =(. For the next one, I will try to better reproduce the error I have. Thanks for your advice.
Well, I fixed this error changing ssr:true to false. It's a bit confusing because in the documentation it asks to be configured only by adding target:static.

Finally this solve my problem, i going to close the Issue. Thank you
