### ISSUE TITLE
where operator with date has a different behaviour in production

### ISSUE THREAD

**Issue by Tchoupinax** [nuxt/content#995]
Hello,

I met an unexpected behaviour with `where` operator and date. I read in the linked issue that I have to use `valueOf()` (on native Date object or on moment) to make working date comparaison.

Moreover, it works like a charm in development but not in production (when using `nuxt generate`). I was looking for a solution during a long time and I found my solution with the following comment : use `toJSON` instead of `valueOf` in production.

```js
.where({
  date: { $gte: moment().subtract(7, 'day').toJSON() }, // Works in production,
  date: { $gte: moment().subtract(7, 'day').valueOf() }, // Does not work in production
})
```

**Edit**: toJSON **does not** work in development, `valueOf` should be used.. ^^'

Why this happening ?

Thank you :)

`valueOf()` only worked for me in development. In production I had to switch to `toJSON()`.

_Originally posted by @gsjen in https://github.com/nuxt/content/issues/437#issuecomment-765695783_

@gsjen Thank you, you saved my day!

**Comment by Susccy** [comment]
Can confirm, same behavior for me.

**Comment by Tahul** [comment]
Hey!

I'm adding v1 tag as we are moving priority support towards @nuxt/content v2.

Could you maybe provide more informations about your environment and maybe a reproduction of the issue?

As we are waiting for the reproduction, I am closing this issue, feel free to re-open by providing one.

Thank you a lot!
