### ISSUE TITLE
Using variable with code highlighter

### ISSUE THREAD

**Issue by patrickgulas** [nuxt/content#997]
I have the following `.md` file:

```md
``html
<script>
  console.log(VARIABLE);
</script>
``
```

I wanted to pass `VARIABLE` into `<nuxt-content>`.

Is it possible to use variable inside code highlighter? 🤔

**Comment by NozomuIkuta** [comment]
@patrickgulas 

Currently, Nuxt Content doesn't support interpolation of variables as string on runtime.
All you can do is to modify raw markdown string on [`content:beforeParse`](https://content.nuxtjs.org/advanced#contentfilebeforeparse) on build time, although this is not what you want in this time.

FYR: Nuxt Content only resolves variable names set for component props, in the namespace of document (i.e. [properties of `document` prop](https://content.nuxtjs.org/writing) passed to `NuxtContent` component). You can also extend the `document` object just before passing it to `NuxtContent` component as described in https://github.com/nuxt/content/issues/877#issuecomment-833371194.
